// M02/M09 actual authenticated browser UI, scoped to a disposable Chrome profile.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 let raw='';for await(const chunk of process.stdin)raw+=chunk;const c=JSON.parse(raw),{chromium}=require(c.playwright);
 const browser=await chromium.launch({executablePath:c.browser,headless:true}),context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true}),page=await context.newPage(),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  const login=async person=>{await page.getByLabel('登录名',{exact:true}).fill(person.username);await page.getByLabel('密码',{exact:true}).fill(person.password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('heading',{name:'你的研究项目'}).waitFor();await page.getByRole('button',{name:/^显示与重建验证/}).click();};
  await page.goto(c.origin+'/server/');await login(c.people[0]);
  for(const file of c.uploads){await page.getByLabel('选择上传文件',{exact:true}).setInputFiles(file);const done=page.waitForResponse(r=>r.url().includes('/uploads/')&&r.url().endsWith('/finalize'));await page.getByRole('button',{name:'上传文件',exact:true}).click();assert.equal((await done).status(),200);await page.locator('.storage-files').getByText(path.basename(file),{exact:true}).waitFor();}
  await page.getByRole('button',{name:'进入研究工作台',exact:true}).click();await page.locator('.nav-item[title="参数显示"]').click();const m02=page.locator('.m02-page');
  await m02.getByRole('button',{name:'tone.wav',exact:true}).click();await page.locator('.empty-plot').waitFor();assert.equal(await page.locator('.m02-parameters input:checked').count(),0);await m02.getByRole('button',{name:'全选可见参数',exact:true}).click();await m02.getByRole('button',{name:'将 3 项分配到图窗',exact:true}).click();await m02.getByRole('button',{name:'清空勾选',exact:true}).click();await page.locator('.parameter-figure svg').waitFor();assert.equal(await page.locator('.parameter-figure').count(),1);assert.equal(await page.locator('.m02-parameters input').count(),4);
  assert((await page.locator('.parameter-figure svg').boundingBox()).height>=400);
  assert.equal(await page.locator('.shared-plot-area').count(),1);assert.equal(await page.locator('.parameter-curve').count(),3);assert.equal(await page.locator('.curve-legend').count(),3);assert(await page.locator('.m02-wave-annotations text').count()>0);
  const scales=await page.locator('.parameter-curve').evaluateAll(paths=>paths.map(p=>[p.dataset.axis,p.dataset.scaleMin,p.dataset.scaleMax]));assert(scales.every(s=>JSON.stringify(s)===JSON.stringify(scales[0])));checks.push('manual 2.2: three curves overlaid in one coordinate rectangle with shared scale and legend, annotations also on waveform');
  await page.locator('.parameter-figure').screenshot({path:path.join(c.output,'m02-default-overlay.png')});
  await m02.getByRole('button',{name:'新建图窗',exact:true}).click();assert((await page.locator('.empty-plot').boundingBox()).height>=280);await page.screenshot({path:path.join(c.output,'m02-empty-figure.png')});await page.locator('.m02-parameters input').nth(0).check();await page.locator('.m02-parameters input').nth(1).check();await m02.getByRole('button',{name:'将 2 项分配到图窗',exact:true}).click();assert.equal(await page.locator('.parameter-figure svg').count(),2);
  const sizes=await page.locator('.parameter-figure svg').evaluateAll(elements=>elements.map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,text:e.querySelector('text')?.getBoundingClientRect().height})));assert(sizes.every(s=>s.height>=290&&s.width>=340&&s.text>=14),JSON.stringify(sizes));await fs.writeFile(path.join(c.output,'m02-figure-dimensions.json'),JSON.stringify(sizes,null,2));checks.push('actual figure pixel heights and readable label size, including empty second figure');
  await m02.getByLabel('correction',{exact:true}).check();assert.equal(await page.locator('.m02-parameters input').count(),5);assert.equal(await page.locator('.m02-parameters input:checked').count(),2);checks.push('original XLSX, default one figure, bulk assignment, independent filter retains selection');
  await page.locator('.parameter-figure').nth(1).screenshot({path:path.join(c.output,'figure-2-readable.png')});
  const second=page.locator('.parameter-figure').nth(1);assert.equal(await second.locator('.shared-plot-area').count(),1);assert.equal(await second.locator('.parameter-curve').count(),2);const pair=await second.locator('.parameter-curve').evaluateAll(paths=>paths.map(p=>({name:p.dataset.parameter,axis:p.dataset.axis,min:p.dataset.scaleMin,max:p.dataset.scaleMax})));assert.equal(pair[0].min,pair[1].min);assert.equal(pair[0].max,pair[1].max);
  const chart=second.locator('svg');await chart.hover();await page.keyboard.down('Control');await page.mouse.wheel(0,-120);await page.keyboard.up('Control');await page.waitForTimeout(200);const startInput=m02.getByLabel('时间窗起点（秒）',{exact:true});const before=Number(await startInput.inputValue());const chartBox=await chart.boundingBox();await page.mouse.move(chartBox.x+chartBox.width*.6,chartBox.y+100);await page.mouse.down();await page.mouse.move(chartBox.x+chartBox.width*.45,chartBox.y+100,{steps:5});await page.mouse.up();assert(Number(await startInput.inputValue())>before);await chart.dblclick();assert.equal(Number(await startInput.inputValue()),0);checks.push('second graph also overlays its two curves; Ctrl-wheel zoom and left-drag pan, double-click reset');
  await m02.getByRole('button',{name:'新建图窗',exact:true}).click();await m02.getByRole('button',{name:'将 2 项分配到图窗',exact:true}).click();assert.equal(await page.locator('.parameter-figure').count(),3);assert.equal(await page.locator('.parameter-figure').nth(2).locator('svg').count(),1);
  await page.locator('.parameter-figure').nth(2).getByRole('button',{name:'合并回首图',exact:true}).click();assert.equal(await page.locator('.parameter-figure').count(),2);await m02.getByLabel('目标图窗',{exact:true}).selectOption('2');await m02.getByRole('button',{name:'将 2 项分配到图窗',exact:true}).click();checks.push('third figure bulk assignment, merge and redistribution without dropping curves');
  await m02.getByRole('button',{name:'保存绘图配置',exact:true}).click();
  await page.locator('.parameter-figure .image-format').first().selectOption('svg');const download=page.waitForEvent('download');await page.locator('.parameter-figure').first().getByRole('button',{name:'保存当前图',exact:true}).click();const svg=await download;await svg.saveAs(path.join(c.output,'parameters.svg'));assert((await fs.readFile(path.join(c.output,'parameters.svg'),'utf8')).includes('时间'));checks.push('real SVG export');
  await page.screenshot({path:path.join(c.output,'m02-light.png')});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:path.join(c.output,'m02-dark.png')});
  await page.locator('.nav-item[title="语谱图转音频"]').click();const m09=page.locator('.m09-page');await m09.getByLabel('语谱图图片',{exact:true}).selectOption({label:'spectrogram.png'});await page.locator('.image-frame img').waitFor();await page.waitForFunction(()=>document.querySelector('.image-frame img')?.naturalWidth>0);
  await m09.getByLabel('迭代次数',{exact:true}).fill('3');await m09.getByLabel('时间终点（s）',{exact:true}).fill('0.2');await m09.getByRole('button',{name:'选择四个角点',exact:true}).click();const image=page.locator('.image-frame svg'),box=await image.boundingBox();for(const [x,y] of [[.05,.05],[.95,.05],[.95,.95],[.05,.95]])await image.click({position:{x:box.width*x,y:box.height*y}});
  const submitted=page.waitForResponse(r=>r.url().endsWith('/jobs/spec2wav/create'));await m09.getByRole('button',{name:'开始重建',exact:true}).click();const response=await submitted;assert.equal(response.status(),201);const job=await response.json();await page.locator('.comparison img').first().waitFor({timeout:90000});assert.equal(await page.locator('.comparison img').count(),2);checks.push('real image four-point calibration, persistent job and reconstructed images/audio');
  await m09.getByLabel('窗长（ms）',{exact:true}).fill('12');await m09.getByText(/当前标定或角点已改变/).waitFor();checks.push('changed settings explicitly label the old immutable result');
  const complete=await(await context.request.get(c.origin+'/api/v1/jobs/'+job.id)).json(),downloads=[];
  for(const file of complete.result_manifest.files){const waiting=page.waitForEvent('download');await m09.getByRole('button',{name:'下载 '+file.name,exact:true}).click();const got=await waiting;await got.saveAs(path.join(c.output,file.name));downloads.push(file);}
  await fs.writeFile(path.join(c.output,'downloads.json'),JSON.stringify(downloads,null,2));checks.push('four authenticated downloads with hashes checked independently');
  await page.screenshot({path:path.join(c.output,'m09-dark.png')});await page.evaluate(()=>document.documentElement.dataset.theme='light');await page.screenshot({path:path.join(c.output,'m09-light.png')});
  for(const width of [1000,390]){await page.setViewportSize({width,height:800});await m09.getByRole('heading',{name:'重建对比',exact:true}).scrollIntoViewIfNeeded();const actual=await page.evaluate(()=>document.documentElement.scrollWidth);assert(actual<=width+1,`M09 overflow ${actual}/${width}`);await page.screenshot({path:path.join(c.output,`m09-${width}.png`)});await page.locator('.nav-item[title="参数显示"]').click();assert.equal(await page.locator('.parameter-figure').count(),2);assert(await page.evaluate(()=>document.documentElement.scrollWidth)<=width+1);await page.screenshot({path:path.join(c.output,`m02-${width}.png`)});await page.locator('.nav-item[title="语谱图转音频"]').click();}
  checks.push('1440, 1000 and 390 CSS px, themes, retained figure configuration across modules');await page.setViewportSize({width:1440,height:900});
  await page.reload();await page.getByRole('heading',{name:'你的研究项目'}).waitFor();await page.getByRole('button',{name:/^显示与重建验证/}).click();await page.getByRole('button',{name:'进入研究工作台',exact:true}).click();await page.locator('.nav-item[title="语谱图转音频"]').click();await page.locator('.job-row').getByRole('button',{name:new RegExp(job.id.slice(0,8))}).click();await page.locator('.comparison img').first().waitFor();checks.push('browser reload recovers persisted reconstruction and results');
  await page.getByRole('button',{name:/返回项目与文件管理/}).click();await page.getByRole('button',{name:'退出登录',exact:true}).click();await page.getByLabel('登录名',{exact:true}).waitFor();await login(c.people[1]);await page.getByRole('button',{name:'进入研究工作台',exact:true}).click();await page.locator('.nav-item[title="语谱图转音频"]').click();await page.getByText('尚无任务。关闭模块不会删除任务。',{exact:true}).waitFor();assert.equal((await context.request.get(c.origin+'/api/v1/jobs/'+job.id)).status(),404);assert.equal((await context.request.get(c.origin+'/api/v1/assets/'+downloads[0].id+'/content')).status(),404);checks.push('account switch clears UI and denies foreign job and result');
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(c.output,'web-report.json'),JSON.stringify({checks,errors,job_id:job.id},null,2));
 }catch(e){await page.screenshot({path:path.join(c.output,'web-failed.png')});throw e;}finally{await context.close();await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
