// M02-R2: owned headless Chrome, synthetic data, real browser pointer gestures and exports.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');const root=path.resolve(__dirname,'../..');
async function main(){
 const out=path.join(root,'output/validation/m02-r2','chrome-'+Date.now());await fs.mkdir(out,{recursive:true});
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},optimizeDeps:{entries:['tests/m02-r2.html']}});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--mute-audio']});
 const page=await browser.newPage({viewport:{width:1920,height:1080},acceptDownloads:true});const report={success:false,checks:[],layouts:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m02-r2.html');await page.getByRole('button',{name:'display.wav',exact:true}).click();await page.locator('.m02-parameters input').first().waitFor();
  const handle=page.getByRole('separator',{name:'图窗与导出宽度',exact:true});
  for(const [width,columns] of [[240,2],[400,3],[560,4]]){
   await handle.focus();await page.keyboard.press('Home');for(let i=240;i<width;i+=40)await page.keyboard.press('Shift+ArrowLeft');await page.waitForTimeout(200);
   const geometry=await page.locator('.m02-parameters').evaluate(el=>{const box=el.getBoundingClientRect(),labels=[...el.querySelectorAll('label')];return {columns:getComputedStyle(el).gridTemplateColumns.split(' ').length,height:box.height,scrollHeight:el.scrollHeight,width:box.width,overflow:el.scrollWidth>el.clientWidth,aligned:labels.every(e=>{const c=e.querySelector('input').getBoundingClientRect(),s=e.querySelector('span')?.getBoundingClientRect();return s&&Math.abs((s.top+s.bottom-c.top-c.bottom)/2)<2;}),gap:(()=>{const b=[...el.previousElementSibling.querySelectorAll('button')].map(e=>e.getBoundingClientRect());return b[1].top-b[0].bottom;})()};});
   assert.equal(geometry.columns,columns);assert(geometry.height<=280&&geometry.scrollHeight>geometry.height);assert(!geometry.overflow&&geometry.aligned);assert(geometry.gap>=0&&geometry.gap<=10);report.layouts.push({width,...geometry});
  }
  report.checks.push('2/3/4 fixed columns; checkbox/text baseline; bounded scroll; compact button gap');
  for(const name of ['F0 - REAPER','Intensity','TextGrid words','TextGrid phones'])await page.getByLabel(name,{exact:true}).check();await page.getByRole('button',{name:'将 4 项分配到图窗',exact:true}).click();
  await page.getByRole('button',{name:'新建图窗',exact:true}).click();await page.getByRole('button',{name:'清空勾选',exact:true}).click();for(const name of ['small','F0 - REAPER'])await page.getByLabel(name,{exact:true}).check();await page.getByRole('button',{name:'将 2 项分配到图窗',exact:true}).click();assert.equal(await page.locator('.parameter-figure').nth(1).locator('.right-tick').count(),5);await page.getByLabel('显示语谱图（Praat）',{exact:true}).check();await page.locator('.spectrogram-canvas canvas').waitFor();
  const inspect=()=>page.evaluate(()=>{const wave=document.querySelector('.wave-track>svg'),r=wave.getBoundingClientRect(),spec=document.querySelector('canvas').getBoundingClientRect(),text=wave.querySelector('.ipa-text'),m=text.getScreenCTM();return {wave:[r.left,r.right],spec:[spec.left,spec.right],figures:[...document.querySelectorAll('.parameter-chart')].map(e=>{const rect=e.getBoundingClientRect(),v=e.viewBox.baseVal,w=rect.width/v.width;return [rect.left+Number(e.dataset.plotLeft)*w,rect.left+Number(e.dataset.plotRight)*w];}),glyphScale:[Math.hypot(m.a,m.b),Math.hypot(m.c,m.d)]};});
  for(const mode of ['light','dark'])for(const size of [12,24]){
   await page.evaluate(async({mode,size})=>{document.documentElement.dataset.theme=mode;await window.qa.fonts(size);},{mode,size});await page.waitForTimeout(240);const g=await inspect();for(const pair of [g.spec,...g.figures])for(let i=0;i<2;i++)assert(Math.abs(g.wave[i]-pair[i])<1.5,JSON.stringify(g));assert(Math.abs(g.glyphScale[0]-g.glyphScale[1])<.01);report.layouts.push({mode,size,...g});
  }
  report.checks.push('time-axis boundaries match waveform/spectrogram/all groups at 12/24px in light/dark; glyph scales isotropic');
  for(const [width,size,zoom] of [[1440,24,1],[600,24,1],[390,12,1],[1920,12,1.5]]){
   await page.setViewportSize({width,height:1000});await page.evaluate(async({size,zoom})=>{document.documentElement.style.zoom=String(zoom);await window.qa.fonts(size);},{size,zoom});await page.waitForTimeout(250);await page.waitForFunction(()=>!!document.querySelector('.spectrogram-canvas canvas'));const g=await inspect();for(const pair of [g.spec,...g.figures])for(let i=0;i<2;i++)assert(Math.abs(g.wave[i]-pair[i])<1.5,JSON.stringify({width,size,zoom,...g}));assert(Math.abs(g.glyphScale[0]-g.glyphScale[1])<.01);const overflow=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert(overflow.scroll<=overflow.viewport+1,JSON.stringify({width,size,zoom,...overflow}));report.layouts.push({viewportWidth:width,size,zoom,...g});
  }
  report.checks.push('alignment and isotropic glyphs at 1440/600/390px, 24px text and 150% page zoom; shared horizontal overflow stays inside signal pane');
  await page.evaluate(()=>document.documentElement.style.zoom='1');await page.setViewportSize({width:1920,height:1080});await page.waitForTimeout(150);
  await page.evaluate(async()=>window.qa.fonts(12));await handle.focus();await page.keyboard.press('Home');await page.waitForTimeout(200);
  async function drag(locator,a,b){await locator.scrollIntoViewIfNeeded();const box=await locator.boundingBox();const bounds=await locator.evaluate(el=>el.classList.contains('parameter-chart')?[Number(el.dataset.plotLeft)/el.viewBox.baseVal.width,Number(el.dataset.plotRight)/el.viewBox.baseVal.width]:[0,1]);const x=f=>box.x+box.width*(bounds[0]+f*(bounds[1]-bounds[0]));await page.mouse.move(x(a),box.y+box.height*.45);await page.mouse.down();await page.mouse.move(x(b),box.y+box.height*.45,{steps:8});await page.mouse.up();const selected=await page.evaluate(()=>[window.qa.wave.start,window.qa.wave.end]);assert(Math.abs(selected[0]-Math.min(a,b)*4)<.015&&Math.abs(selected[1]-Math.max(a,b)*4)<.015,JSON.stringify(selected));}
  await drag(page.locator('.wave-track>svg'),.2,.4);await drag(page.locator('canvas'),.7,.3);for(const e of await page.locator('.parameter-chart').all())await drag(e,.25,.75);
  assert.equal(await page.locator('.spectrogram-selection').count(),1);report.checks.push('native pointer forward/reverse selections from waveform/spectrogram/two parameter groups share seconds');
  const chart=page.locator('.parameter-chart').first();await chart.scrollIntoViewIfNeeded();const cb=await chart.boundingBox();await page.mouse.move(cb.x+cb.width*.5,cb.y+cb.height*.5);await page.keyboard.down('Control');await page.mouse.wheel(0,-100);await page.keyboard.up('Control');await page.waitForTimeout(200);const z=await page.evaluate(()=>({zoom:window.qa.wave.zoom,offset:window.qa.wave.offset}));assert(z.zoom>1);
  await page.keyboard.down('Shift');await page.mouse.down();await page.mouse.move(cb.x+cb.width*.4,cb.y+cb.height*.5,{steps:5});await page.mouse.up();await page.keyboard.up('Shift');assert((await page.evaluate(()=>window.qa.wave.offset))>z.offset);await chart.dblclick();assert.equal(await page.evaluate(()=>window.qa.wave.zoom),1);report.checks.push('Ctrl wheel zoom; Shift drag pan; double click restores full duration');
  await page.waitForFunction(()=>document.querySelector('.spectrogram-canvas canvas')&&!document.querySelector('.spectrogram-view [role=status],[role=alert]'));
  const wait=page.waitForEvent('download');await page.locator('.parameter-figure').first().getByRole('button',{name:'保存整幅 PNG',exact:true}).click();const file=await wait;await file.saveAs(path.join(out,'whole.png'));assert((await fs.readFile(path.join(out,'whole.png'))).subarray(1,4).toString()==='PNG');report.checks.push('aligned annotated waveform/spectrogram/parameter figure whole PNG download');
  await page.screenshot({path:path.join(out,'dark.png'),fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='light');await page.screenshot({path:path.join(out,'light.png'),fullPage:true});
  await page.setViewportSize({width:600,height:800});await page.waitForTimeout(200);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=601));await page.screenshot({path:path.join(out,'narrow.png'),fullPage:true});assert.deepEqual(report.errors,[]);report.success=true;
 }catch(e){report.error=String(e);await page.screenshot({path:path.join(out,'failed.png'),fullPage:true});throw e;}
 finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(out);await browser.close();await server.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
