// Real owned backend/child + common AppShell, standalone headless Chrome.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','scripts/m03_ui_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:path.join(root,'backend/src')+';'+path.join(root,'desktop/src')}});
 const pending=new Map();let counter=0;let resolveReady,rejectReady;const ready=new Promise((resolve,reject)=>{resolveReady=resolve;rejectReady=reject;});
 createInterface({input:worker.stdout}).on('line',line=>{const v=JSON.parse(line);if(v.ready)resolveReady(v);else{const done=pending.get(v.id);pending.delete(v.id);done?.(v);}});worker.stderr.on('data',d=>process.stderr.write(d));worker.on('error',rejectReady);
 const {out}=await ready;const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},plugins:[{name:'owned-m03-rpc',configureServer(s){s.middlewares.use('/__m03',(req,res)=>{let body='';req.on('data',d=>body+=d);req.on('end',()=>{const data=JSON.parse(body),id=++counter;pending.set(id,v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v));});worker.stdin.write(JSON.stringify({...data,rpc_id:id})+'\n');});});}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=name=>page.getByRole('button',{name,exact:true}).first().click();const plotted=()=>page.waitForFunction(()=>document.querySelectorAll('.egg-four-plots .scientific-plot>svg').length===4,{},{timeout:60000});
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m03-live.html');await click('EGG 信号分析');await click('打开 WAV 目录');await page.getByLabel('EGG 音频文件').selectOption({label:'EGG ɑ̃˥.wav'});await page.waitForFunction(()=>!document.querySelector('.egg-source select').disabled);await click('更新分析');await plotted();
  const rows=()=>page.locator('.egg-history .task-row').count();const before=await rows();
  // Inject a missing export face to model browser/worker font availability divergence.
  // The actual authenticated endpoint and compatibility child remain unchanged.
  const setFont=name=>page.evaluate(async name=>{const f=await import('/src/state/fonts.ts');const p=f.fontPayload.value;f.fontPayload.value={...p,resolved:{...p.resolved,figureLatin:name}};},name);
  await setFont('PTB Missing Export 987654');await click('保存 CSV / 三图');await page.getByRole('alert').filter({hasText:'英文与数字 PTB Missing Export 987654'}).waitFor();assert.equal(await rows(),before);assert.equal(await page.locator('.egg-four-plots .scientific-plot>svg').count(),4);checks.push('missing worker font blocks single export without discarding analysis or creating job');
  await click('批量分析');const batch=page.getByRole('dialog',{name:'EGG 批量分析'});await batch.getByRole('checkbox',{name:/全选/}).uncheck();await batch.getByRole('checkbox',{name:'EGG ɑ̃˥.wav',exact:true}).check();await batch.getByRole('checkbox',{name:'同时导出三张图片'}).check();await click('提交所选文件');await batch.getByRole('alert').filter({hasText:'PTB Missing Export'}).waitFor();assert.equal(await rows(),before);assert(await batch.getByRole('checkbox',{name:'EGG ɑ̃˥.wav',exact:true}).isChecked());await batch.screenshot({path:path.join(out,'font-missing-batch.png')});
  await batch.getByRole('checkbox',{name:'同时导出三张图片'}).uncheck();await click('提交所选文件');await batch.waitFor({state:'detached'});await page.waitForFunction(n=>document.querySelectorAll('.egg-history .task-row').length===n,before+1);await page.waitForFunction(()=>![...document.querySelectorAll('.egg-history .task-row [role=status]')].some(e=>['排队中','运行中'].includes(e.textContent)),{},{timeout:60000});assert(!(await page.locator('.egg-history').innerText()).includes('失败'));checks.push('batch retains selection on font failure and data-only batch succeeds with same missing font');
  await setFont('Times New Roman');await click('保存 CSV / 三图');await page.locator('.egg-result-links button').filter({hasText:'CSV + 三张图'}).first().waitFor({timeout:60000});await page.locator('.egg-result-links button').filter({hasText:'CSV + 三张图'}).first().click();await page.waitForFunction(()=>document.querySelectorAll('dialog .egg-export-image').length===3);await page.locator('dialog summary').filter({hasText:'参数快照'}).click();assert((await page.locator('dialog pre').innerText()).includes('Times New Roman'));await page.screenshot({path:path.join(out,'font-export-success.png')});const rpc=body=>page.evaluate(async body=>{const r=await(await fetch('/__m03',{method:'POST',body:JSON.stringify(body)})).json();if(r.error)throw Error(r.error);return r.value;},body);
  const allJobs=await rpc({op:'egg_jobs'});const single=allJobs.find(j=>j.result_manifest?.kind==='managed_egg_files'&&j.result_manifest.files.some(f=>f.name==='egg_CQ_SQ.png'));
  const metadataFile=single.result_manifest.files.find(f=>f.name==='egg.ptb.json');const metadataResult=await rpc({op:'result',job:single.id,id:metadataFile.id});const metadata=JSON.parse(Buffer.from(metadataResult.base64,'base64').toString('utf8'));assert.equal(metadata.render_fonts.latin.family,'Times New Roman');assert.equal(metadata.render_fonts.ipa.family,'Doulos SIL');assert.equal(metadata.render_fonts.latin.sha256.length,64);
  checks.push('corrected font preflight and real CSV/three-PNG export succeed with matching render-family/hash evidence');
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'report.json'),JSON.stringify({success:true,checks,errors,schema_applied:[]},null,2));console.log(out);
 }catch(e){await page.screenshot({path:path.join(out,'failed.png')});await fs.writeFile(path.join(out,'report.json'),JSON.stringify({success:false,error:String(e),checks,errors},null,2));console.log(out);throw e;}
 finally{await browser.close();await server.close();worker.stdin.end(JSON.stringify({op:'shutdown'})+'\n');await new Promise(resolve=>worker.once('exit',resolve));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
