// Real owned backend/child + common AppShell, standalone headless Chrome.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','scripts/m03_ui_bridge.py','--long'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:path.join(root,'backend/src')+';'+path.join(root,'desktop/src')}});
 const pending=new Map();let counter=0;let resolveReady,rejectReady;const ready=new Promise((resolve,reject)=>{resolveReady=resolve;rejectReady=reject;});
 createInterface({input:worker.stdout}).on('line',line=>{const v=JSON.parse(line);if(v.ready)resolveReady(v);else{const done=pending.get(v.id);pending.delete(v.id);done?.(v);}});worker.stderr.on('data',d=>process.stderr.write(d));worker.on('error',rejectReady);
 const {out}=await ready;const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},plugins:[{name:'owned-m03-rpc',configureServer(s){s.middlewares.use('/__m03',(req,res)=>{let body='';req.on('data',d=>body+=d);req.on('end',()=>{const data=JSON.parse(body),id=++counter;pending.set(id,v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v));});worker.stdin.write(JSON.stringify({...data,rpc_id:id})+'\n');});});}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=name=>page.getByRole('button',{name,exact:true}).first().click();const plotted=()=>page.waitForFunction(()=>document.querySelectorAll('.egg-four-plots .scientific-plot>svg').length===4,{},{timeout:60000});
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m03-live.html');await click('EGG 信号分析');await click('打开 WAV 目录');await page.getByLabel('EGG 音频文件').selectOption({label:'long.wav'});await page.waitForFunction(()=>!document.querySelector('.egg-source select').disabled);
  await page.getByLabel('EGG 选区起点').fill('119.5');await page.getByLabel('EGG 选区起点').blur();await click('更新分析');await plotted();assert((await page.locator('.audio-pane small').textContent()).includes('119.7500'));await page.screenshot({path:path.join(out,'long-tail.png')});checks.push('120-second source tail preview computed with global preprocessing; center beyond old 60-second boundary');
  await page.getByLabel('EGG 选区起点').fill('0');await page.getByLabel('EGG 选区起点').blur();await page.getByLabel('EGG 选区时长').fill('120');await page.getByLabel('EGG 选区时长').blur();await click('更新分析');await plotted();assert.equal(await page.locator('.cq-pane .scientific-dots').count(),2);assert((await page.locator('.cq-pane circle').count())===0);const points=await page.locator('.cq-pane .scientific-dots').first().getAttribute('d');assert((points.match(/M/g)||[]).length>17000);await page.screenshot({path:path.join(out,'long-full.png')});checks.push('full 120-second preview preserves >17000 CQ points in bounded DOM paths');
  await click('保存 CSV / 三图');await page.waitForFunction(()=>[...document.querySelectorAll('.egg-result-links button')].some(e=>e.textContent.includes('CSV + 三张图')),{},{timeout:240000});await page.getByRole('button',{name:/CSV \+ 三张图/}).click();await page.waitForFunction(()=>document.querySelectorAll('.egg-export-image').length===3);assert.equal(await page.locator('.egg-export-image').count(),3);await click('选择目录保存完整结果');await page.getByRole('status').filter({hasText:'已保存 5'}).waitFor();checks.push('actual durable full-selection job saves CSV, three PNG and metadata via granted directory');
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'report.json'),JSON.stringify({success:true,checks,errors,schema_applied:[]},null,2));console.log(out);
 }catch(e){await page.screenshot({path:path.join(out,'failed.png')});await fs.writeFile(path.join(out,'report.json'),JSON.stringify({success:false,error:String(e),checks,errors},null,2));console.log(out);throw e;}
 finally{await browser.close();await server.close();worker.stdin.end(JSON.stringify({op:'shutdown'})+'\n');await new Promise(resolve=>worker.once('exit',resolve));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
