// Real owned backend/child + common AppShell, standalone headless Chrome.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','scripts/m03_ui_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:path.join(root,'backend/src')+';'+path.join(root,'desktop/src')}});
 const pending=new Map();let counter=0;let resolveReady,rejectReady;const ready=new Promise((resolve,reject)=>{resolveReady=resolve;rejectReady=reject;});
 createInterface({input:worker.stdout}).on('line',line=>{const v=JSON.parse(line);if(v.ready)resolveReady(v);else{const done=pending.get(v.id);pending.delete(v.id);done?.(v);}});worker.stderr.on('data',d=>process.stderr.write(d));worker.on('error',rejectReady);
 const {out}=await ready;const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},plugins:[{name:'owned-m03-rpc',configureServer(s){s.middlewares.use('/__m03',(req,res)=>{let body='';req.on('data',d=>body+=d);req.on('end',()=>{const data=JSON.parse(body),id=++counter;pending.set(id,v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v));});worker.stdin.write(JSON.stringify({...data,rpc_id:id})+'\n');});});}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=name=>page.getByRole('button',{name,exact:true}).first().click();const plotted=()=>page.waitForFunction(()=>document.querySelectorAll('.egg-four-plots .scientific-plot>svg').length===4,{},{timeout:60000});
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m03-live.html');await click('EGG 信号分析');await click('打开 WAV 目录');await page.getByLabel('EGG 音频文件').selectOption({label:'EGG ɑ̃˥.wav'});await page.waitForFunction(()=>!document.querySelector('.egg-source select').disabled);await click('更新分析');await plotted();checks.push('real backend and scientific child supply four interactive plots');
  await page.screenshot({path:path.join(out,'light-1440.png')});await page.locator('.egg-controls').screenshot({path:path.join(out,'controls-light.png')});console.log('Chrome real plots ready');
  assert.equal(await page.getByRole('checkbox',{name:'Praat F0',exact:true}).isChecked(),false);assert.equal(await page.getByRole('checkbox',{name:'GCI F0',exact:true}).isChecked(),false);
  await click('批量分析');const batch=page.getByRole('dialog',{name:'EGG 批量分析'});assert(await batch.getByRole('checkbox',{name:'Praat F0',exact:true}).isChecked());assert(await batch.getByRole('checkbox',{name:'GCI F0',exact:true}).isChecked());assert.equal(await batch.getByRole('checkbox',{name:'同时导出三张图片'}).isChecked(),false);await click('返回工作台');checks.push('single F0 display off and independent batch F0 defaults on');
  const mainPlot=page.locator('.cq-pane svg');await mainPlot.hover();await page.keyboard.down('Control');await page.mouse.wheel(0,-120);await page.keyboard.up('Control');await page.locator('.cq-pane .plot-empty').waitFor();await plotted();assert.ok(Math.abs(Number(await page.getByLabel('EGG 选区时长').inputValue())-.45)<.000001);
  const micro=page.locator('.egg-pane svg'),box=await micro.boundingBox();const before=Number((await page.locator('.audio-pane small').textContent()).split(' ')[0]);await page.mouse.move(box.x+box.width*.6,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.7,box.y+box.height*.5);await page.mouse.up();await page.locator('.egg-pane .plot-empty').waitFor();await plotted();const after=Number((await page.locator('.audio-pane small').textContent()).split(' ')[0]);assert(after<before);assert((await page.locator('.cq-pane svg title').allTextContents()).some(t=>t.startsWith('微观中心')));
  await mainPlot.focus();await page.keyboard.press('ArrowRight');await page.locator('.cq-pane .plot-empty').waitFor();await plotted();assert(Number(await page.getByLabel('EGG 选区起点').inputValue())>.025);checks.push('real main wheel zoom, micro pointer drag, keyboard pan and center marker');
  await page.getByLabel('EGG 选区时长').fill('.12');await page.getByLabel('EGG 选区时长').blur();await page.locator('.egg-four-plots .plot-empty').first().waitFor();assert(await page.getByRole('button',{name:'播放选区',exact:true}).isDisabled());await click('更新分析');await plotted();checks.push('ROI edits invalidate previous view and normalized playback');await click('更新分析');await click('取消分析');await page.getByRole('button',{name:'取消分析',exact:true}).waitFor({state:'detached',timeout:30000});await page.locator('.task-row').filter({hasText:'已取消'}).getByRole('button',{name:'重试此任务'}).click();await page.waitForFunction(()=>document.querySelector('.egg-history').innerText.includes('重试'),{},{timeout:30000});checks.push('actual preview cancellation and immutable retry via shared task panel');
  await click('设置');await page.getByRole('checkbox',{name:'图表与导出跟随全局字体'}).uncheck();await page.getByLabel('图表基础字号').fill('24');await click('应用字体');await page.getByRole('status').filter({hasText:'字体已应用'}).waitFor();await page.getByRole('button',{name:'关闭对话框',exact:true}).click();assert.equal(await page.locator('.scientific-plot text').first().evaluate(e=>getComputedStyle(e).fontSize),'24px');checks.push('shared figure font size propagates to live SVG without recomputation');
  for(const [width,height] of [[1920,1080],[1440,900],[1280,800],[1000,800],[390,900]]){await page.setViewportSize({width,height});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:path.join(out,`dark-${width}.png`)});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert(await page.locator('.egg-page').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert(await page.locator('.scientific-plot svg').first().evaluate(e=>{const boxes=[...e.querySelectorAll('text')].slice(-3,-1).map(t=>t.getBoundingClientRect());return boxes.length<2||boxes[0].right<=boxes[1].left;}));checks.push(`dark ${width} no horizontal clipping`);}
  const cdp=await context.newCDPSession(page);for(const scale of [1.25,1.5,2]){await cdp.send('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:scale,mobile:false});await page.screenshot({path:path.join(out,`dpi-${scale}.png`)});assert(await page.locator('.egg-page').evaluate(e=>e.scrollWidth<=e.clientWidth+1));checks.push(`Chrome emulated DPI ${scale}`);}await cdp.send('Emulation.clearDeviceMetricsOverride');await cdp.detach();await page.setViewportSize({width:1440,height:1000});await click('保存 CSV / 三图');await page.locator('.egg-result-links button').filter({hasText:'CSV + 三张图'}).first().waitFor({timeout:60000});await page.locator('.egg-result-links button').filter({hasText:'CSV + 三张图'}).first().click();await page.locator('.egg-export-image').nth(2).waitFor();await click('选择目录保存完整结果');await page.getByRole('status').filter({hasText:'已保存 5'}).waitFor();const firstNames=await fs.readdir(path.join(out,'saved'));assert(firstNames.some(n=>n.startsWith('EGG ɑ̃˥_')&&n.endsWith('_DATA.csv')));const csvName=firstNames.find(n=>n.endsWith('_DATA.csv'));const csv=await fs.readFile(path.join(out,'saved',csvName),'utf8');assert(csv.split('\n')[0].includes('F0_Praat (Hz)')&&csv.split('\n')[0].includes('F0_GCI (Hz)'));await click('选择目录保存完整结果');await page.getByRole('status').filter({hasText:'已保存 5'}).waitFor();assert.deepEqual(await fs.readdir(path.join(out,'saved')),firstNames);await page.screenshot({path:path.join(out,'named-save.png')});await click('返回分析');checks.push('real named single export retains both CSV F0 tracks, modal feedback and repeat save');
  await click('批量分析');await click('提交所选文件');await page.locator('.batch-files').waitFor({state:'detached'});await page.waitForFunction(()=>document.querySelector('.egg-history').innerText.includes('失败'),{},{timeout:60000});checks.push('mixed batch reports mono failure without dropping other tasks');await page.waitForFunction(()=>![...document.querySelectorAll('.egg-history .task-row [role=status]')].some(e=>['排队中','运行中','正在取消'].includes(e.textContent)),{},{timeout:60000});await page.getByRole('button',{name:/保存本次批量结果/}).click();await page.getByRole('status').filter({hasText:'已保存 2 个批次任务'}).waitFor();checks.push('one directory grant saves every successful batch result');
  await click('保存参数草稿');await page.getByRole('button',{name:'关闭 EGG 信号分析',exact:true}).click();await click('EGG 信号分析');await page.locator('.task-row').first().waitFor();checks.push('module reopen restores persisted jobs');
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'report.json'),JSON.stringify({success:true,checks,errors,schema_applied:[]},null,2));console.log(out);
 }catch(e){await page.screenshot({path:path.join(out,'failed.png')});await fs.writeFile(path.join(out,'report.json'),JSON.stringify({success:false,error:String(e),checks,errors},null,2));console.log(out);throw e;}
 finally{await browser.close();await server.close();worker.stdin.end(JSON.stringify({op:'shutdown'})+'\n');await new Promise(resolve=>worker.once('exit',resolve));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
