const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','tests/support/m05_host_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','packages/phonetic_core/src','desktop/src'].map(p=>path.join(root,p)).join(';')}});
 let readyResolve,readyReject,counter=0;const pending=new Map(),ready=new Promise((r,j)=>{readyResolve=r;readyReject=j});
 createInterface({input:worker.stdout}).on('line',line=>{const d=JSON.parse(line);if(d.ready)readyResolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id)}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>readyReject(Error('Host exited '+code)));
 const {out}=await ready;console.log(out);const operations=[];
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0,watch:null},optimizeDeps:{entries:['tests/m05-host.html']},plugins:[{name:'m05-r2-test-transport',configureServer(s){s.middlewares.use('/__m05_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter,request=JSON.parse(raw);operations.push(request.body.op);if(request.body.op==='choose'&&cancelNext){cancelNext=false;res.end(JSON.stringify({ok:true,value:null}));return;}pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))});worker.stdin.write(JSON.stringify({...request,id})+'\n')})})}}]});await server.listen();
 let cancelNext=false;
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1920,height:1080}}),report={success:false,physical_devices:false,checks:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));page.setDefaultTimeout(45000);
 const click=name=>page.getByRole('button',{name,exact:true}).click(),phase=p=>page.waitForFunction(p=>document.querySelector('.lip-state')?.dataset.phase===p,p),mode=m=>page.getByLabel('采集模式',{exact:true}).selectOption(m);
 const dirs=async()=> (await fs.readdir(path.join(out,'saved'))).filter(n=>n.startsWith('M05-recording-'));
 const save=async(video=true,animation=true)=>{await click('另存录制');await page.getByRole('dialog',{name:'另存录制',exact:true}).waitFor();await page.getByLabel('视频',{exact:true}).setChecked(video);await page.getByLabel('动画',{exact:true}).setChecked(animation);await click('选择目录并保存');await page.getByRole('dialog',{name:'另存录制',exact:true}).waitFor({state:'hidden'});};
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m05-host.html');await page.locator('nav').getByRole('button',{name:'唇形提取',exact:true}).click();
  await page.addScriptTag({path:path.join(root,'tests/support/m05_r2_capture.js')});
  const portrait=await fs.readFile(path.join(root,'output/validation/m05/inputs/astronaut.png'),'base64');await page.evaluate(p=>window.installM05R2Capture('data:image/png;base64,'+p),portrait);
  assert.deepEqual(await page.getByLabel('采集模式',{exact:true}).locator('option').allTextContents(),['实时预览','实时录制','高帧率先录后算']);
  await mode('preview');await click('打开预览');await phase('previewing');await page.waitForFunction(()=>Number(document.querySelector('.lip-state')?.textContent.match(/检出 (\d+)/)?.[1])>3);
  await click('结束录制');await phase('ready');assert.equal(await page.getByRole('button',{name:'另存录制',exact:true}).isDisabled(),true);assert.equal(await page.locator('#tab-M05 [aria-label="未保存"]').count(),0);report.checks.push('preview only clears frames and writes nothing');
  await mode('realtime');await click('开始录制');await phase('recording');
  const processed=()=>page.locator('.lip-state').innerText().then(t=>Number(t.match(/已推理 (\d+)/)[1]));const beforeCollapse=await processed();await click('收起视频与记录');await page.waitForTimeout(700);assert(await processed()>beforeCollapse,'collapsing video pane must not stop inference');await click('展开视频与记录');report.checks.push('collapsed video sidebar continues inference');
  await page.waitForFunction(()=>Number(document.querySelector('.lip-state')?.textContent.match(/检出 (\d+)/)?.[1])>12);await page.waitForTimeout(1100);await click('结束录制');await phase('ready');await page.waitForFunction(()=>document.querySelector('.lip-page')?.getAttribute('aria-busy')==='false');
  await click('检查偏移量');const dialog=page.getByRole('dialog',{name:'检查偏移量',exact:true});await dialog.waitFor();await page.waitForFunction(()=>!document.querySelector('.offset-editor')?.textContent.includes('正在读取'));
  const input=page.getByLabel('唇形偏移量 ms');await input.fill('120');await input.press('ArrowRight');assert.equal(await input.inputValue(),'121');await input.press('ArrowLeft');assert.equal(await input.inputValue(),'120');
  const editor=page.getByLabel('偏移量编辑区',{exact:true});await editor.focus();await page.keyboard.down('ArrowRight');for(let i=0;i<7;i++)await page.keyboard.press('ArrowRight');await page.keyboard.up('ArrowRight');assert.equal(await input.inputValue(),'128');
  await page.getByLabel('area',{exact:true}).check();assert.equal(await dialog.locator('.scientific-plot').nth(1).locator('.scientific-trace').count(),2);
  const axes=await dialog.locator('.scientific-plot svg[role=img]').evaluateAll(nodes=>nodes.map(n=>{const r=n.querySelector('clipPath rect');return {x:r.getAttribute('x'),width:r.getAttribute('width'),box:n.getBoundingClientRect().width}}));assert.deepEqual(axes[0],axes[1]);
  await page.screenshot({path:path.join(out,'offset.png'),fullPage:true});await click('应用偏移量');assert((await page.locator('.lip-curve-note').innerText()).includes('128 ms'));
  await click('检查偏移量');await input.fill('-200');await click('取消');assert((await page.locator('.lip-curve-note').innerText()).includes('128 ms'));report.checks.push('real decoded waveform, same-axis multi-parameter plot, input, repeated 1 ms keys, apply/cancel');
  const playback=page.getByLabel('视频与动画同步回放',{exact:true});await playback.evaluate(v=>{v.currentTime=.8});await page.waitForTimeout(200);const first=await page.getByLabel('回放帧',{exact:true}).inputValue();await playback.evaluate(v=>v.play());await page.waitForTimeout(400);await playback.evaluate(v=>v.pause());const second=await page.getByLabel('回放帧',{exact:true}).inputValue();assert(Number(second)>Number(first),first+' -> '+second);report.checks.push('recorded video drives central animation during seek/play/pause');
  const pixels=await page.locator('.lip-video canvas').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let top=c.height,bottom=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){let i=(y*c.width+x)*4;if(d[i+1]>180&&d[i]<80&&d[i+2]<80&&d[i+3]>0){top=Math.min(top,y);bottom=Math.max(bottom,y)}}return {top,bottom,height:c.height}});assert((pixels.bottom-pixels.top)/pixels.height>.86,JSON.stringify(pixels));report.checks.push({face:pixels});
  cancelNext=true;await click('另存录制');await click('选择目录并保存');await page.getByText('已取消保存，录制保留。',{exact:true}).waitFor();assert.equal((await dirs()).length,0);await page.getByRole('dialog',{name:'另存录制',exact:true}).getByRole('button',{name:'取消',exact:true}).click();
  for(const [video,animation] of [[true,true],[true,false],[false,true],[false,false]]){const previous=await dirs();await save(video,animation);const name=(await dirs()).find(n=>!previous.includes(n)),folder=path.join(out,'saved',name),files=await fs.readdir(folder),info=JSON.parse(await fs.readFile(path.join(folder,'recording-export.json'),'utf8'));assert.equal(files.includes('raw_recording.mp4'),video);assert.equal(files.includes('face_animation.mp4'),animation);assert(files.includes('audio_recording.wav')&&files.includes('audio_recording.lip.json'));const lip=JSON.parse(await fs.readFile(path.join(folder,'audio_recording.lip.json'),'utf8'));assert.equal(lip.data.metadata.lip_manual_offset,.128);report.checks.push({save_options:[video,animation],directory:folder,files});}
  assert.equal(operations.filter(op=>op==='m05_create').length,0);
  for(const [width,height,theme] of [[1920,1080,'light'],[1920,1080,'dark'],[1440,900,'dark'],[1280,800,'light']]){
   await page.setViewportSize({width,height});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.waitForTimeout(200);
   const layout=await page.locator('.lip-page').evaluate(el=>{const rect=s=>{const r=el.querySelector(s).getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};return {viewport:[innerWidth,innerHeight],face:rect('.lip-face-section'),params:rect('.lip-metrics'),media:rect('.lip-media-section'),center:rect('.workbench-center'),overflow:document.documentElement.scrollWidth>innerWidth}});assert.equal(layout.overflow,false);if(width===1920)assert(layout.params.bottom<height);report.checks.push({layout});await page.screenshot({path:path.join(out,`layout-${width}-${theme}.png`),fullPage:true});
  }
  await page.setViewportSize({width:1280,height:800});await page.evaluate(()=>{document.documentElement.style.setProperty('--control-size','22px');document.documentElement.style.setProperty('--figure-size','22px')});await page.waitForTimeout(200);await click('检查偏移量');await page.waitForTimeout(150);const modal=await page.getByRole('dialog',{name:'检查偏移量',exact:true}).evaluate(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom}});assert(modal.x>=0&&modal.y>=0&&modal.right<=1280&&modal.bottom<=800);await page.screenshot({path:path.join(out,'offset-large-font.png'),fullPage:true});await click('取消');
  const large=await page.locator('.lip-curves').evaluate(el=>{const r=el.getBoundingClientRect();return {bottom:r.bottom,height:innerHeight}});assert(large.bottom<large.height,JSON.stringify(large));report.checks.push({large_font_layout:large,modal});await page.evaluate(()=>{document.documentElement.style.removeProperty('--control-size');document.documentElement.style.removeProperty('--figure-size')});
  await page.setViewportSize({width:1920,height:1080});await mode('record_then_analyze');await click('开始录制');await phase('recording');await page.waitForTimeout(1300);await click('结束录制');await phase('ready');await page.waitForFunction(()=>document.querySelector('.lip-page')?.getAttribute('aria-busy')==='false');const old=await dirs();await click('另存录制');await page.waitForFunction(()=>document.querySelector('.lip-page')?.getAttribute('aria-busy')==='false');const high=(await dirs()).find(n=>!old.includes(n));assert.deepEqual((await fs.readdir(path.join(out,'saved',high))).sort(),['audio_recording.wav','raw_recording.mp4','recording-export.json']);report.checks.push('high-frame-rate capture saves only video/audio plus receipt');
  const savedVideo=report.checks.find(x=>x.save_options?.[0]&&x.save_options?.[1]).directory;
  await page.getByLabel('选择离线视频',{exact:true}).setInputFiles(path.join(savedVideo,'raw_recording.mp4'));await click('分析所选 1 个视频');await page.getByText('已完成 1 个文件，结果等待保存。',{exact:true}).waitFor();
  await click('检查偏移量');await page.waitForFunction(()=>document.querySelectorAll('.offset-editor .scientific-plot')[0]?.querySelector('path')?.getAttribute('d')?.length>10);await page.getByLabel('唇形偏移量 ms').fill('-75');await click('应用偏移量');await click('同步回放');await page.waitForTimeout(350);await click('暂停回放');assert(Number(await page.getByLabel('回放帧',{exact:true}).inputValue())>0);await click('应用偏移并保存');await page.getByText('完整结果与偏移写入完成。',{exact:true}).waitFor();report.checks.push('actual legacy offline task, native saved audio waveform, negative offset and synchronized replay/save');
  const tracks=await page.evaluate(()=>({created:window.m05R2.created,ended:window.m05R2.ended}));assert.equal(tracks.created,tracks.ended);assert.deepEqual(report.errors,[]);report.success=true;
 }finally{const retained=await page.getByLabel('视频与动画同步回放',{exact:true}).evaluate(async v=>{const b=new Uint8Array(await (await fetch(v.src)).arrayBuffer());let x='';for(let i=0;i<b.length;i+=8192)x+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(x)}).catch(()=>null);if(retained)await fs.writeFile(path.join(out,'retained-recording.webm'),Buffer.from(retained,'base64'));await page.screenshot({path:path.join(out,'m05-r3-final.png'),fullPage:true}).catch(()=>{});report.final_text=await page.locator('body').innerText().catch(()=>'');await fs.writeFile(path.join(out,'m05-r3-report.json'),JSON.stringify(report,null,2));await browser.close();await server.close();worker.stdin.end();}
 console.log(JSON.stringify({out,success:report.success,checks:report.checks},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1});
