const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','tests/support/m06_host_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','packages/phonetic_core/src','desktop/src','scripts'].map(p=>path.join(root,p)).join(';')}});
 let readyResolve,readyReject,counter=0;const pending=new Map(),ready=new Promise((r,j)=>{readyResolve=r;readyReject=j});
 createInterface({input:worker.stdout}).on('line',line=>{const d=JSON.parse(line);if(d.ready)readyResolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id)}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>readyReject(Error('Host exited '+code)));
 const {out}=await ready;console.log(out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:5196},optimizeDeps:{entries:['tests/m06-host.html']},plugins:[{name:'m06-host-transport-test',configureServer(s){s.middlewares.use('/__m06_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter;pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))});worker.stdin.write(JSON.stringify({...JSON.parse(raw),id})+'\n')})})}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(45000);
 const click=name=>page.getByRole('button',{name,exact:true}).click(),open=()=>page.locator('nav').getByRole('button',{name:'语音合成',exact:true}).click(),idle=()=>page.waitForFunction(()=>document.querySelector('[aria-label="语音合成工作区"]')?.getAttribute('aria-busy')==='false');
 const scope=page.getByLabel('语音合成工作区',{exact:true}),dialog=()=>page.getByRole('dialog');
 let success=false;
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m06-host.html');await open();await scope.waitFor();

  assert(await scope.getByRole('button',{name:'播放选区',exact:true}).isDisabled());
  assert(await scope.getByRole('button',{name:'导出音频',exact:true}).isDisabled());
  await scope.getByLabel('IPA 元音序列',{exact:true}).fill('a?i');await click('生成元音');await scope.getByText('IPA 第 2 个字符无效：?').waitFor();
  await scope.getByLabel('总时长',{exact:true}).fill('0');await click('应用时长');assert((await scope.innerText()).includes('0.1–100'));
  await scope.getByLabel('总时长',{exact:true}).fill('0.6');await click('应用时长');await scope.getByLabel('IPA 元音序列',{exact:true}).fill('a i');await click('生成元音');await idle();assert((await scope.innerText()).includes('元音曲线已生成'));assert(await scope.getByRole('button',{name:'播放选区',exact:true}).isDisabled());checks.push('F01 invalid IPA/duration; valid duration and vowel generation remain separate from audio');
  await scope.getByLabel('Override curve',{exact:true}).fill('140');await click('应用覆盖');await click('合成');await idle();assert((await scope.innerText()).includes('合成完成'));
  await click('播放选区');await click('停止');await click('语谱图');await scope.getByLabel('语谱窗长').selectOption('5');await page.screenshot({path:path.join(out,'spectrum.png'),fullPage:true});await click('重置范围');await click('波形');
  await click('导出音频');await page.waitForFunction(()=>document.body.textContent.includes('已导出合成结果'));assert((await fs.readdir(path.join(out,'saved'))).includes('synthesis.wav'));checks.push('F03/F04 actual production synthesis, common player, spectrum/window/range, WAV+actual snapshot save');
  await scope.getByLabel('Override curve',{exact:true}).fill('160');await click('应用覆盖');assert((await scope.innerText()).includes('参数已修改'));
  const dl=page.waitForEvent('download');await click('导出实际合成参数');const download=await dl;await download.saveAs(path.join(out,'actual.csv'));assert((await fs.readFile(path.join(out,'actual.csv'),'utf8')).includes('140'));await click('清除覆盖');const graph=scope.getByRole('img',{name:'F0 参数曲线',exact:true});const box=await graph.boundingBox();const beforePath=await graph.locator('path.curve').getAttribute('d');await page.keyboard.down('Shift');await page.mouse.move(box.x+box.width*.3,box.y+box.height*.4);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.6,{steps:5});await page.mouse.up();await page.keyboard.up('Shift');assert.notEqual(await graph.locator('path.curve').getAttribute('d'),beforePath);await page.keyboard.down('Control');await graph.hover();await page.mouse.wheel(0,-150);await page.keyboard.up('Control');await click('重置范围');await scope.getByLabel('Override curve',{exact:true}).fill('100,150;200');await click('应用覆盖');checks.push('F02 scalar lock and segmented curve; stale result export uses original snapshot');
  await scope.getByLabel('发声类型预设').selectOption('气声');await click('应用预设');await dialog().getByRole('button',{name:'取消',exact:true}).click();await click('应用预设');await click('应用并覆盖');await click('清空参数');await dialog().getByRole('button',{name:'取消',exact:true}).click();
  await click('元音规则');assert((await dialog().innerText()).includes('1.1'));await dialog().getByRole('button',{name:'关闭对话框',exact:true}).click();await click('辅音规则');assert((await dialog().innerText()).includes('已移除'));await dialog().getByRole('button',{name:'关闭对话框',exact:true}).click();
  await click('打开音频目录');await scope.getByLabel('源音频',{exact:true}).selectOption({label:'source.wav'});await click('应用并覆盖');await idle();assert((await scope.innerText()).includes('参数提取完成'));await click('合成');await idle();assert((await scope.innerText()).includes('合成完成'));checks.push('F05 preset cancel/confirm, vowel/consonant rules and source extraction then synthesis through resource references');
  const saved=page.waitForEvent('download');await click('导出参数');await(await saved).saveAs(path.join(out,'roundtrip.csv'));await scope.locator('input[accept=".csv,.json"]').setInputFiles(path.join(out,'roundtrip.csv'));await click('应用并覆盖');
  await scope.locator('input[accept=".csv,.json"]').setInputFiles(path.join(out,'saved/m06.ptb.json'));await click('应用并覆盖');await scope.locator('input[accept=".csv,.json"]').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('bad')});assert((await scope.innerText()).includes('CSV 表头无效'));await click('帮助');assert((await dialog().innerText()).includes('Shimmer'));await dialog().getByRole('button',{name:'关闭对话框',exact:true}).click();checks.push('F06 actual full CSV roundtrip, malformed import preserves configuration, help');
  await scope.getByLabel('总时长',{exact:true}).fill('10');await click('应用时长');await click('合成');await scope.getByLabel('IPA 元音序列',{exact:true}).fill('a');await idle();assert((await scope.innerText()).includes('迟到结果未应用'));checks.push('late real synthesis cannot replace changed configuration');
  await click('合成');await click('取消任务');await idle();assert((await scope.innerText()).includes('取消'));checks.push('real task cancellation preserves previous published result');
  await page.getByLabel('关闭 语音合成',{exact:true}).click();await click('取消关闭');await page.evaluate(()=>{window.__set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.includes('m06.'))throw Error('controlled storage failure');return window.__set.call(this,k,v)}});await page.getByLabel('关闭 语音合成',{exact:true}).click();await click('保存草稿并关闭');await dialog().getByRole('alert').waitFor();await page.evaluate(()=>Storage.prototype.setItem=window.__set);await click('保存草稿并关闭');await scope.waitFor({state:'detached'});await open();await scope.waitFor();checks.push('AppShell close protection, failed save then successful save/reopen');
  await scope.locator('input[aria-label=总时长]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'light.png'),fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.waitForTimeout(250);assert.equal(await page.locator('.curve-editor text').first().evaluate(e=>getComputedStyle(e).fill),'rgb(233, 240, 249)');await page.screenshot({path:path.join(out,'dark.png'),fullPage:true});await page.setViewportSize({width:900,height:700});await page.screenshot({path:path.join(out,'compact.png'),fullPage:true});
  assert.deepEqual(errors,[]);success=true;
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}
 finally{await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify({success,checks,errors,scope:'Windows Chrome, production desktop adapter and real host; QWebChannel transport substituted'},null,2));console.log(JSON.stringify({success,checks}));await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1});
