// M07-R3: actual production host on isolated synthetic files, muted WebAudio.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-B','-X','utf8','tests/support/m07_host_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','packages/phonetic_core/src','desktop/src','scripts'].map(p=>path.join(root,p)).join(';')}});
 let readyResolve,readyReject,counter=0;const pending=new Map(),ready=new Promise((r,j)=>{readyResolve=r;readyReject=j;});
 createInterface({input:worker.stdout}).on('line',line=>{const d=JSON.parse(line);if(d.ready)readyResolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id);}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>readyReject(Error('Host exited '+code)));
 const {out}=await ready;console.log(out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0,watch:null},optimizeDeps:{entries:['tests/m07-host.html']},plugins:[{name:'m07-r3-host',configureServer(s){s.middlewares.use('/__m07_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter;pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));});worker.stdin.write(JSON.stringify({...JSON.parse(raw),id})+'\n');});});}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--mute-audio']}),page=await browser.newPage({viewport:{width:1920,height:1080}}),checks=[],layouts=[],errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(60000);
 await page.addInitScript(()=>{window.audioStarts=[];const create=AudioContext.prototype.createBufferSource;AudioContext.prototype.createBufferSource=function(){const node=create.call(this),start=node.start;node.start=function(when,offset,duration){window.audioStarts.push({offset,duration,frames:this.buffer.length,sample:this.buffer.getChannelData(0)[10]});return start.call(this,when,offset,duration);};return node;};});
 const scope=page.getByLabel('发声类型连续统工作区',{exact:true});const click=name=>scope.getByRole('button',{name,exact:true}).click();
 const idle=()=>page.waitForFunction(()=>document.querySelector('.m07-page')?.getAttribute('aria-busy')==='false');
 const curves=n=>page.waitForFunction(n=>document.querySelectorAll('.f0-plot path[data-curve=synthesis]').length===n,n);
 const playing=()=>page.evaluate(async()=>{const {playback}=await import('/src/state/audio.ts');return playback.playing;});

 let success=false,exports=[],playbackChecks=[];
 const active=()=>scope.locator('.f0-plot').getAttribute('data-active-step');
 const waitActive=name=>page.waitForFunction(name=>document.querySelector('.f0-plot').dataset.activeStep===name,name);
 const axis=async(min,max)=>{await scope.getByLabel('F0 图窗纵轴下限',{exact:true}).fill(String(min));await scope.getByLabel('F0 图窗纵轴上限',{exact:true}).fill(String(max));};
 const captureExport=async(name,min,max,steps)=>{
  await page.evaluate(()=>{window.exportScene='';const serialize=XMLSerializer.prototype.serializeToString;if(!window.exportCapture){window.exportCapture=true;XMLSerializer.prototype.serializeToString=function(node){const raw=serialize.call(this,node);if(node.querySelector?.('[data-y-min]')&&node.querySelector('text'))window.exportScene=raw;return raw;};}});
  const download=page.waitForEvent('download');await scope.getByRole('button',{name:'导出图片',exact:true}).click();const file=await download;await file.saveAs(path.join(out,name+'.png'));
  const scene=await page.evaluate(()=>{const doc=new DOMParser().parseFromString(window.exportScene,'image/svg+xml'),plot=doc.querySelector('[data-y-min]');return {raw:window.exportScene,min:Number(plot.dataset.yMin),max:Number(plot.dataset.yMax),texts:[...doc.querySelectorAll('text')].map(e=>e.textContent),width:Number(doc.documentElement.getAttribute('width')),height:Number(doc.documentElement.getAttribute('height')),lines:[...plot.querySelectorAll('[data-curve]')].map(e=>({name:e.dataset.name,opacity:e.style.opacity,width:e.style.strokeWidth}))};});
  assert.equal(scene.min,min);assert.equal(scene.max,max);assert(scene.texts.includes(String(min))&&scene.texts.includes(String(max)));assert.equal(scene.texts.filter(s=>/^step\d+$/.test(s)).length,steps);assert(scene.lines.every(e=>e.opacity==='1'&&e.width==='2'));await fs.writeFile(path.join(out,name+'.svg'),scene.raw);exports.push({...scene,raw:undefined,name});
 };
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m07-host.html');await page.locator('nav').getByRole('button',{name:'发声类型合成',exact:true}).click();await scope.waitFor();
  assert.equal(await scope.getByRole('button',{name:'导出图片',exact:true}).isDisabled(),true);
  const frames=await scope.evaluate(e=>{const f=e.querySelector('.plot-frame'),w=e.querySelector('.waveform-placeholder svg');return {fFill:getComputedStyle(f).fill,wFill:getComputedStyle(w).backgroundColor,fStroke:getComputedStyle(f).stroke,border:getComputedStyle(w).borderTopColor};});assert.equal(frames.fFill,frames.wFill);assert.equal(frames.fStroke,frames.border);await page.screenshot({path:path.join(out,'r3-empty.png')});
  const footer=scope.locator('.attribution-line');assert.equal(await footer.innerText(),'经许可改写自陆尧、梁昌维、孔江平团队发布的 MATLAB 重合成代码。感谢三位老师及北京大学语言学实验室的支持与授权。（2026-09-10 作者邮件许可）');
  await scope.getByRole('button',{name:'改写说明',exact:true}).click();const dialog=page.getByRole('dialog',{name:'发声类型合成改写说明',exact:true});const explanation=await dialog.innerText();assert(explanation.includes('REAPER 算法作为 PhoneticToolbox 新增')&&explanation.includes('用于嘎裂声基频的提取')&&explanation.includes('很可能与 PhoneticToolbox 本次改写'));assert(explanation.includes('（2026-09-10）作者邮件许可，允许相关 MATLAB 代码改写为 Python，集成至 PhoneticToolbox v3 免费开源发布，并按约定引用、署名致谢和说明改写。'));assert((await dialog.getByRole('link',{name:'尝试作者团队的官方开源代码'}).getAttribute('href')).startsWith('https://github.com/Luyao2025/'));await dialog.locator('.dialog-header button').click();
  checks.push('exact footer and permission wording, REAPER creaky F0 adaptation attribution, humble limitation with upstream action; framed empty plot matches waveform colors');
  await click('打开音频目录');await scope.getByRole('combobox',{name:'源音频',exact:true}).selectOption({label:'input0.wav'});await scope.getByRole('combobox',{name:'目标音频',exact:true}).selectOption({label:'input1.wav'});await click('提取 F0');await idle();await click('生成当前');await idle();await curves(9);
  await page.evaluate(async()=>{const {states}=await import('/src/state/workspace.ts');window.m07wave=Object.entries(states).find(([key])=>key==='M07'||key.endsWith(':M07'))[1];window.m07source=Object.entries(states).find(([key])=>key==='M07.source'||key.endsWith(':M07.source'))[1];window.audioApi=await import('/src/state/audio.ts');});
  assert.equal(await active(),'');assert(!(await scope.innerText()).includes('已载入本组完整音频'));assert(!(await scope.getByLabel('F0 图例',{exact:true}).innerText()).includes('合成 F0'));assert.equal(await scope.locator('.result-audios button').count(),10);
  await scope.locator('.result-audios').getByRole('button',{name:'整组试听',exact:true}).click();await waitActive('step01');
  const framesPerStep=await page.evaluate(()=>m07wave.asset.frames/9);assert.equal(framesPerStep,await page.evaluate(()=>audioStarts.at(-1).frames/9));
  await page.evaluate(()=>{window.highlightLog=[];window.highlightObserver=new MutationObserver(()=>{const step=document.querySelector('.f0-plot').dataset.activeStep;if(step&&highlightLog.at(-1)!==step)highlightLog.push(step);});highlightObserver.observe(document.querySelector('.f0-plot'),{attributes:true,attributeFilter:['data-active-step']});});
  await waitActive('step02');await waitActive('step05');await waitActive('step09');await page.waitForFunction(()=>!audioApi.playback.playing);assert.equal(await active(),'');const progress=await page.evaluate(()=>{highlightObserver.disconnect();return highlightLog;});assert.deepEqual(progress,Array.from({length:8},(_,i)=>'step'+String(i+2).padStart(2,'0')));playbackChecks.push({natural:progress,framesPerStep});
  // Production seek and pause APIs exercise exact sample boundaries and selection offsets.
  for(const frame of [framesPerStep-1,framesPerStep,framesPerStep*8]){
   const expected='step'+String(Math.floor(frame/framesPerStep)+1).padStart(2,'0');
   const initial=await page.evaluate(async frame=>{const w=m07wave;await audioApi.play(w.asset,frame/w.asset.sampleRate,w.asset.duration,w.channel);await Promise.resolve();const step=document.querySelector('.f0-plot').dataset.activeStep;audioApi.pause();return step;},frame);
   assert.equal(initial,expected);await waitActive('');playbackChecks.push({frame,expected});
  }
  await page.evaluate(async()=>{const w=m07wave;await audioApi.play(w.asset,w.asset.duration*.47,w.asset.duration*.7,w.channel);});await waitActive('step05');await page.evaluate(async()=>{const w=m07source;await audioApi.play(w.asset,0,w.asset.duration,w.channel);});await waitActive('');
  await scope.locator('.result-audios').getByRole('button',{name:'step09',exact:true}).click();await curves(1);await waitActive('step09');await page.evaluate(()=>audioApi.stop());await waitActive('');checks.push('natural nine-step playback highlights all sequential curves; frame boundary seek, offset selection, single step, pause/end/stop and source audio takeover clear correctly');
  await axis(70,120);assert.equal(await scope.locator('.f0-plot').getAttribute('data-y-min'),'70');assert.equal(await scope.locator('.f0-plot').getAttribute('data-y-max'),'120');
  assert.equal(await scope.getByRole('button',{name:'生成当前',exact:true}).isEnabled(),true);assert.equal(await scope.locator('.f0-line[data-name=step09]').getAttribute('clip-path'),null);assert(await scope.locator('.f0-plot g[clip-path]').count());
  await captureExport('r3-single-70-120',70,120,1);
  await scope.getByLabel('F0 图窗纵轴上限',{exact:true}).fill('60');await scope.getByRole('alert').filter({hasText:'上限须大于下限'}).waitFor();assert.equal(await scope.locator('.f0-plot').getAttribute('data-y-max'),'120');await scope.getByLabel('F0 图窗纵轴上限',{exact:true}).fill('120');
  await scope.locator('.result-audios').getByRole('button',{name:'整组试听',exact:true}).click();await curves(9);await waitActive('step01');await page.evaluate(()=>audioApi.pause());await captureExport('r3-whole-70-120',70,120,9);
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');await axis(20,200);await captureExport('r3-dark-20-200',20,200,9);
  await click('自动范围');assert.equal(await scope.locator('.f0-plot').getAttribute('data-y-min'),'0');assert.equal(await scope.getByLabel('F0 图窗纵轴上限',{exact:true}).inputValue(),'');checks.push('manual and automatic axes apply without invalidating generation; invalid range retains last good plot; actual 300dpi single/whole/dark downloads keep visible range and every legend');
  await axis(40,180);await page.reload();await page.locator('nav').getByRole('button',{name:'发声类型合成',exact:true}).click();await scope.waitFor();assert.equal(await scope.getByLabel('F0 图窗纵轴下限',{exact:true}).inputValue(),'40');assert.equal(await scope.getByLabel('F0 图窗纵轴上限',{exact:true}).inputValue(),'180');await click('刷新任务历史');await curves(9);assert.equal(await scope.locator('.f0-plot').getAttribute('data-y-max'),'180');checks.push('independent display range persists after real reload and recovered task selection');
  for(const [width,height,rightWidth] of [[1920,1080,300],[1920,1080,460],[1440,900,300],[1440,900,460],[1280,800,300],[960,720,300]])for(const theme of ['light','dark']){
   await page.setViewportSize({width,height});await page.waitForTimeout(200);await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);if(width>=1440){const separator=scope.getByRole('separator',{name:'连续统与任务宽度',exact:true});for(let attempt=0;attempt<60;attempt++){const current=Number(await separator.getAttribute('aria-valuenow'));if(current===rightWidth)break;await separator.press(current<rightWidth?'ArrowLeft':'ArrowRight');}assert.equal(Number(await separator.getAttribute('aria-valuenow')),rightWidth);}await page.waitForTimeout(1000);
   const geo=await scope.evaluate(e=>{const box=n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,bottom:r.bottom,height:r.height};},right=e.querySelector('.workbench-right-body'),buttons=[...e.querySelectorAll('.generate-actions>.primary')];return {right:box(right),scroll:right.scrollHeight,client:right.clientHeight,actions:buttons.map(box),group:box(e.querySelector('.result-audios')),save:box(e.querySelector('.result-row>.primary')),history:box(e.querySelector('.task-history')),footer:box(e.querySelector('.m07-attribution')),plot:box(e.querySelector('.main-f0')),columns:getComputedStyle(e.querySelector('.generate-actions')).gridTemplateColumns};});
   if(width>=1440){assert(geo.group.bottom<=geo.right.bottom+1&&geo.save.bottom<=geo.right.bottom+1,JSON.stringify(geo));assert(geo.plot.bottom<=geo.footer.y+1);}
   if(rightWidth===460&&width>=1440)assert(Math.abs(geo.actions[0].y-geo.actions[1].y)<1);assert(geo.history.height<=113);assert(geo.footer.bottom<=height+1);await page.screenshot({path:path.join(out,`r3-${width}-${rightWidth}-${theme}.png`)});layouts.push({width,height,rightWidth,theme,...geo});
  }
  checks.push('12 shallow/deep desktop and narrow layouts; wide sidebar has two-column actions; desktop selected-group and save stay in view without outer right scrolling');assert.deepEqual(errors,[]);success=true;
 }catch(e){await fs.writeFile(path.join(out,'r3-failure.txt'),await scope.innerText());await page.screenshot({path:path.join(out,'r3-failure.png'),fullPage:true});throw e;}
 finally{await fs.writeFile(path.join(out,'r3-report.json'),JSON.stringify({success,checks,layouts,exports,playbackChecks,errors,scope:'Windows Chrome actual production desktop adapter and isolated host; real synthetic PCM and muted WebAudio; no physical audio/DPI'},null,2));console.log(JSON.stringify({out,success,checks}));await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
