const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','tests/support/m07_host_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','packages/phonetic_core/src','desktop/src','scripts'].map(p=>path.join(root,p)).join(';')}});
 let readyResolve,readyReject,counter=0;const pending=new Map(),ready=new Promise((r,j)=>{readyResolve=r;readyReject=j});
 createInterface({input:worker.stdout}).on('line',line=>{const d=JSON.parse(line);if(d.ready)readyResolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id)}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>readyReject(Error('Host exited '+code)));
 const {out}=await ready;console.log(out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},optimizeDeps:{entries:['tests/m07-host.html']},plugins:[{name:'m07-host-transport-test',configureServer(s){s.middlewares.use('/__m07_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter;pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))});worker.stdin.write(JSON.stringify({...JSON.parse(raw),id})+'\n')})})}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(45000);
 const click=name=>page.getByRole('button',{name,exact:true}).click(),open=()=>page.locator('nav').getByRole('button',{name:'发声类型合成',exact:true}).click(),idle=()=>page.waitForFunction(()=>document.querySelector('[aria-label="发声类型连续统工作区"]')?.getAttribute('aria-busy')==='false');
 const scope=page.getByLabel('发声类型连续统工作区',{exact:true}),dialog=()=>page.getByRole('dialog');
 let success=false;
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m07-host.html');await open();await scope.waitFor();

  await click('打开音频目录');await scope.getByRole('combobox',{name:'源音频',exact:true}).selectOption({label:'input0.wav'});await scope.getByRole('combobox',{name:'目标音频',exact:true}).selectOption({label:'input1.wav'});
  await click('提取 F0');await idle();await scope.getByText('分析完成，控制点尚未修改',{exact:true}).waitFor();assert((await scope.locator('.f0-plot').boundingBox()).height>=200);await page.screenshot({path:path.join(out,'analyzed.png')});checks.push('source/target roles, real file reads, production analysis and F0 table');
  await scope.getByLabel('源 F0 第 4 点',{exact:true}).fill('NaN');assert(await scope.getByRole('button',{name:'生成当前',exact:true}).isDisabled());await click('应用编辑');await scope.getByText(/每份 F0 至少需要一个有效点/).waitFor();
  await scope.getByLabel('源 F0 第 4 点',{exact:true}).fill('130');await click('应用编辑');await idle();await scope.getByText('F0 编辑已应用，LPC、残差和脉冲继续复用',{exact:true}).waitFor();
  const csvPromise=page.waitForEvent('download');await click('保存 F0 CSV');await(await csvPromise).saveAs(path.join(out,'edited_f0.csv'));assert((await fs.readFile(path.join(out,'edited_f0.csv'),'utf8')).startsWith('time_ms,source_f0,target_f0'));checks.push('invalid control rejection, explicit apply, real full-grid CSV download');
  await scope.getByLabel('F0 对齐',{exact:true}).selectOption('onset');await click('应用编辑');await idle();await scope.getByLabel('连续统步数',{exact:true}).fill('3');await click('生成全部六组');await idle();assert.equal(await scope.locator('.result-row').count(),1);assert((await scope.locator('.history-heading').innerText()).includes('6 组'));checks.push('onset alignment and six real atomic groups');
  const row=scope.locator('.result-row').first();await row.getByRole('button',{name:'step01',exact:true}).click();await scope.getByText(/当前试听：/).waitFor();await scope.getByRole('button',{name:'播放选区',exact:true}).last().click();await scope.getByRole('button',{name:'停止',exact:true}).last().click();
  await click('输出位置');await row.getByRole('button',{name:'保存完整组',exact:true}).click();await scope.getByText('已保存本组完整文件和参数清单',{exact:true}).waitFor();const folders=await fs.readdir(path.join(out,'saved'));assert.equal(folders.length,1);assert((await fs.readdir(path.join(out,'saved',folders[0]))).includes('combined_steps.wav'));const protectedFile=path.join(out,'saved',folders[0],'step01.wav');await fs.writeFile(protectedFile,'existing-result-sentinel');const savedAgain=page.waitForResponse(async r=>r.url().includes('/__m07_host')&&r.request().postData()?.includes('m07_save'));await row.getByRole('button',{name:'保存完整组',exact:true}).click();await savedAgain;await page.waitForFunction(()=>document.querySelector('[aria-label="发声类型连续统工作区"]').innerText.includes('已保存本组完整文件和参数清单'));assert.equal(await fs.readFile(protectedFile,'utf8'),'existing-result-sentinel');checks.push('result ownership, common playback and actual native complete-group save');
  await scope.getByLabel('源 F0 第 4 点',{exact:true}).fill('141');await click('保存参数草稿');await page.getByLabel('关闭 发声类型合成',{exact:true}).click();await scope.waitFor({state:'detached'});await open();await scope.waitFor();await click('打开音频目录');await scope.getByRole('combobox',{name:'源音频',exact:true}).selectOption({label:'input0.wav'});await scope.getByRole('combobox',{name:'目标音频',exact:true}).selectOption({label:'input1.wav'});await click('提取 F0');await idle();assert.equal(await scope.getByLabel('源 F0 第 4 点',{exact:true}).inputValue(),'141');assert(await scope.getByRole('button',{name:'生成当前',exact:true}).isDisabled());await click('应用编辑');await idle();await click('刷新任务历史');await page.waitForFunction(()=>document.querySelectorAll('.result-row').length===1&&document.querySelector('.history-heading').innerText.includes('6 组'));checks.push('unapplied draft points survive close, matching reanalysis and explicit application');
  await scope.getByLabel('最低 F0 (Hz)',{exact:true}).fill('60');assert(await scope.getByRole('button',{name:'生成当前',exact:true}).isDisabled());await scope.getByText(/原分析失效/).waitFor();await scope.getByLabel('最低 F0 (Hz)',{exact:true}).fill('50');await click('生成当前');await click('取消任务');await idle();assert.equal(await scope.locator('.result-row').count(),1);assert((await scope.locator('.history-heading').innerText()).includes('6 组'));checks.push('analysis parameter invalidation and cancellation preserve published groups');
  await scope.getByLabel('F0 后端',{exact:true}).selectOption('reaper');await click('提取 F0');await idle();await fs.writeFile(path.join(out,'reaper-ui.txt'),await scope.innerText());await scope.getByLabel('F0 后端',{exact:true}).selectOption('parselmouth');
  await click('提取 F0');await scope.getByRole('combobox',{name:'目标音频',exact:true}).selectOption({label:'input0.wav'});await page.waitForTimeout(1000);assert(await scope.getByRole('button',{name:'生成当前',exact:true}).isDisabled());checks.push('input switching during real analysis cannot apply late callback');
  await click('参数帮助');assert((await dialog().innerText()).includes('知觉等距'));await dialog().getByRole('button',{name:'关闭对话框',exact:true}).click();
  await page.getByLabel('关闭 发声类型合成',{exact:true}).click();await click('取消关闭');await page.getByLabel('关闭 发声类型合成',{exact:true}).click();await click('保存草稿并关闭');await scope.waitFor({state:'detached'});await open();await scope.waitFor();await click('刷新任务历史');await page.waitForFunction(()=>document.querySelectorAll('.result-row').length===1&&document.querySelector('.history-heading').innerText.includes('6 组'));checks.push('public close guard, saved draft and persistent history reopen');
  await scope.getByRole('button',{name:'打开音频目录',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'light.png'),fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:path.join(out,'dark.png'),fullPage:true});await page.setViewportSize({width:900,height:700});await page.screenshot({path:path.join(out,'compact.png'),fullPage:true});checks.push('light/dark/compact screenshots and help IPA');
  assert.deepEqual(errors,[]);success=true;
 }catch(e){await fs.writeFile(path.join(out,'failure.txt'),await scope.innerText());await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}
 finally{await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify({success,checks,errors,scope:'Windows Chrome, actual desktop adapter and production host; only QWebChannel transport substituted'},null,2));console.log(JSON.stringify({success,checks}));await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1});

