const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{let raw='';for await(const c of process.stdin)raw+=c;const config=JSON.parse(raw),{chromium}=require(config.playwright),browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1000}}),page=await context.newPage(),checks=[];page.setDefaultTimeout(60000);let manifest=[];
const click=name=>page.getByRole('button',{name,exact:true}).first().click(),scope=page.getByLabel('发声类型连续统工作区',{exact:true}),idle=()=>page.waitForFunction(()=>document.querySelector('[aria-label="发声类型连续统工作区"]')?.getAttribute('aria-busy')==='false');
try{
await page.goto(config.origin+'/server/');await page.getByLabel('登录名',{exact:true}).fill(config.people[0].username);await page.getByLabel('密码',{exact:true}).fill(config.people[0].password);await click('登录');await page.getByRole('button',{name:/^M07 网页验证/}).click();
for(const file of config.uploads){await page.getByLabel('选择上传文件',{exact:true}).setInputFiles(file);const response=page.waitForResponse(r=>r.url().includes('/uploads/')&&r.url().endsWith('/finalize'));await click('上传文件');assert.equal((await response).status(),200);}
await click('进入研究工作台');await page.locator('nav').getByRole('button',{name:'发声类型合成',exact:true}).click();await scope.getByRole('combobox',{name:'源音频',exact:true}).selectOption({label:'input0.wav'});await scope.getByRole('combobox',{name:'目标音频',exact:true}).selectOption({label:'input1.wav'});await click('提取 F0');await idle();await scope.getByText('分析完成，控制点尚未修改',{exact:true}).waitFor();await scope.getByLabel('连续统步数',{exact:true}).fill('3');const created=page.waitForResponse(r=>r.url().endsWith('/jobs/m07/create'));await click('生成当前');const jobId=(await(await created).json()).id;await idle();await scope.locator('.result-row').waitFor();const job=await(await context.request.get(config.origin+'/api/v1/jobs/'+jobId)).json();assert.equal(job.state,'succeeded');manifest=job.result_manifest.files;checks.push('authenticated uploads, real PG/worker analysis and generation');
const download=page.waitForEvent('download');await click('下载完整组');await(await download).saveAs(path.join(config.output,'complete.zip'));checks.push('single full-group browser ZIP download');
const other=await browser.newContext(),foreign=await other.newPage();await foreign.goto(config.origin+'/server/');await foreign.getByLabel('登录名',{exact:true}).fill(config.people[1].username);await foreign.getByLabel('密码',{exact:true}).fill(config.people[1].password);await foreign.getByRole('button',{name:'登录',exact:true}).click();await foreign.getByRole('heading',{name:'你的研究项目'}).waitFor();assert.equal((await other.request.get(config.origin+'/api/v1/jobs/'+jobId)).status(),404);assert.equal((await other.request.get(config.origin+'/api/v1/assets/'+manifest[0].id+'/content')).status(),404);await other.close();checks.push('second authenticated account cannot read task or result');await page.screenshot({path:path.join(config.output,'web.png')});await fs.writeFile(path.join(config.output,'web-report.json'),JSON.stringify({success:true,checks,manifest},null,2));
}catch(e){await fs.writeFile(path.join(config.output,'failure.txt'),await page.locator('body').innerText());throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
