// Real Chrome + real Praat via a test-only stdio adapter on the existing Vite runner.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','tests/support/m08_browser_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:path.join(root,'backend/src')+';'+path.join(root,'packages/phonetic_core/src')}});
 const pending=new Map();let counter=0,readyResolve,readyReject;const ready=new Promise((r,j)=>{readyResolve=r;readyReject=j;});
 createInterface({input:worker.stdout}).on('line',line=>{const d=JSON.parse(line);if(d.ready)readyResolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id);}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>readyReject(Error('fixture exited '+code)));
 const {out}=await ready;console.log('M08 evidence '+out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:5188},optimizeDeps:{entries:['tests/m08-live.html']},plugins:[{name:'owned-m08-test-rpc',configureServer(s){s.middlewares.use('/__m08_test',(req,res)=>{let body='';req.on('data',d=>{body+=d});req.on('end',()=>{const id=++counter;pending.set(id,d=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(d));});worker.stdin.write(JSON.stringify({...JSON.parse(body),rpc_id:id})+'\n');});});}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const click=name=>page.getByRole('button',{name,exact:true}).click();const idle=()=>page.waitForFunction(()=>document.querySelector('.m08-page')?.getAttribute('aria-busy')==='false');
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m08-live.html');await page.getByLabel('M08 音频').selectOption('0');await page.locator('.m08-curve').waitFor();await idle();
  assert.equal(await page.getByLabel('语速倍率').inputValue(),'1');assert.equal(await page.getByLabel('F0 下限').inputValue(),'50');checks.push('actual WAV/Praat F0 and original defaults');
  const curve=page.locator('.m08-curve'),before=await curve.locator('.modified').getAttribute('d'),box=await curve.boundingBox();
  await page.keyboard.down('Shift');await page.mouse.move(box.x+box.width*.3,box.y+box.height*.3);await page.mouse.down();await page.mouse.move(box.x+box.width*.7,box.y+box.height*.4,{steps:12});await page.mouse.up();await page.keyboard.up('Shift');assert.notEqual(await curve.locator('.modified').getAttribute('d'),before);checks.push('Shift drawing actual F0');
  await click('导入基频序列');await page.getByLabel('基频序列',{exact:true}).fill('0 180\n1 210');await click('导入序列');await page.getByLabel('语速倍率').fill('0.8');await click('合成当前视野');await idle();await page.locator('.m08-page').getByText('输出 1.250 s',{exact:false}).waitFor();checks.push('import interpolation and actual speed 0.8 output duration');
  await click('保存并编号');await idle();await page.locator('.history li').first().waitFor();await click('保存并编号');await idle();assert.equal(await page.locator('.history li').count(),2);const names=await fs.readdir(path.join(out,'saved'));assert(names.some(n=>n.endsWith('_1.wav'))&&names.some(n=>n.endsWith('_2.wav')));checks.push('real PCM16 save, numbering, re-extracted history');
  await page.screenshot({path:path.join(out,'light.png'),fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'dark.png'),fullPage:true});
  const download=page.waitForEvent('download');await click('保存对比图');const item=await download;await item.saveAs(path.join(out,'comparison.png'));assert((await fs.stat(path.join(out,'comparison.png'))).size>1000);checks.push('actual PNG export and light/dark screenshots');
  await click('批量重命名');await page.getByLabel('新的共同前缀').fill('../escape');await click('确认重命名');await page.getByRole('alert').filter({hasText:'无效文件名'}).last().waitFor();await page.getByLabel('新的共同前缀').fill('renamed_');await click('确认重命名');await idle();assert((await fs.readdir(path.join(out,'saved'))).every(n=>n.startsWith('renamed_')));checks.push('path escape refused and real owned-result rename');
  await click('删除本批次音频');await click('确认删除所选音频');await idle();assert.equal((await fs.readdir(path.join(out,'saved'))).length,0);assert((await fs.stat(path.join(out,'public ɑ̃˥.wav'))).size>1000);checks.push('explicit current-batch delete leaves synthetic source intact');
  await page.getByLabel('放大波形',{exact:true}).first().click();await click('合成当前视野');await idle();await page.getByText('源区间 0.000–0.500 s',{exact:false}).waitFor();await click('合成整段');await idle();await page.getByText('源区间 0.000–1.000 s',{exact:false}).waitFor();await page.getByRole('button',{name:'适合窗口',exact:true}).first().click();checks.push('zoomed current-view synthesis differs from explicit whole-file synthesis');
  await click('当前视野原音');await click('播放选区');await page.getByRole('button',{name:'暂停',exact:true}).waitFor();await click('停止');checks.push('real browser AudioContext playback and stop');
  await click('编辑拐点表');await page.getByLabel('频率 0',{exact:true}).fill('120,180');await page.getByLabel('频率 1',{exact:true}).fill('140,200');await page.getByLabel('连接 0',{exact:true}).selectOption('full');await page.getByLabel('连接 1',{exact:true}).selectOption('reverse');await click('添加行');await page.getByLabel('时间 1',{exact:true}).fill('0.5');await page.getByLabel('频率 1',{exact:true}).fill('160,190');assert(await page.getByLabel('选择拐点 0',{exact:true}).isDisabled());assert(await page.getByLabel('选择拐点 2',{exact:true}).isDisabled());await click('保存更改');await click('批量生成并保存');await idle();assert.equal((await fs.readdir(path.join(out,'saved'))).length,4);checks.push('knot table, endpoint protection, full/order/reverse real four-output batch');
  await click('批量变速变调');await click('全选音频');await page.getByLabel('音高倍率').fill('1.1');await page.getByLabel('音高偏移 Hz').fill('20');await click('开始批量处理');await idle();assert.equal(await page.locator('.task-row').filter({hasText:'已完成'}).count(),6);assert.equal(await page.locator('.task-row').filter({hasText:'失败'}).count(),1);checks.push('broken input reported individually; folder-style multi-file speed/ratio/Hertz processing and per-file tasks');
  await click('单文件与基频');await click('保存编辑草稿');await page.getByLabel('语速倍率').fill('1.2');await page.getByLabel('M08 音频').selectOption('1');await page.getByRole('dialog').filter({hasText:'保留当前编辑'}).waitFor();await click('取消');assert.equal(await page.getByLabel('M08 音频').inputValue(),'0');checks.push('dirty source-switch cancellation');
  await click('保存编辑草稿');await page.reload();await page.getByLabel('M08 音频').selectOption('0');await curve.waitFor();await idle();assert.equal(await page.getByLabel('语速倍率').inputValue(),'1.2');checks.push('saved F0/config draft restored by source hash');
  for(const width of [1000,800,390]){await page.setViewportSize({width,height:850});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.waitForTimeout(300);await page.screenshot({path:path.join(out,`dark-${width}.png`),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}checks.push('responsive 1000/800/390 no page horizontal overflow');
  await page.goto(server.resolvedUrls.local[0]+'tests/m08-live.html?unwired');await page.getByLabel('M08 音频').selectOption('0');await idle();await page.getByText('当前入口尚未接入 M08',{exact:false}).waitFor();assert(await page.getByRole('button',{name:'合成当前视野',exact:true}).isDisabled());assert.equal(await page.locator('.m08-curve').count(),0);checks.push('missing production port clearly unavailable, no fabricated F0 or success');
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'checks.json'),JSON.stringify({checks,errors,scope:'isolated module, real Praat, test-only adapter; public host wiring unverified'},null,2));console.log(JSON.stringify({checks:checks.length,out}));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});await fs.writeFile(path.join(out,'failure.json'),JSON.stringify({checks,errors,error:String(e)},null,2));throw e;}
 finally{await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});

