const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
async function main(){
 const root=process.cwd(),pending=new Map();let counter=0;
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-B','-X','utf8','scripts/verify_m09_r1.py','--serve'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','packages/phonetic_core/src','desktop/src'].map(x=>path.join(root,x)).join(';')}});
 let resolve,reject;const ready=new Promise((a,b)=>{resolve=a;reject=b});createInterface({input:worker.stdout}).on('line',line=>{try{const d=JSON.parse(line);if(d.ready)resolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id)}}catch(e){reject(e)}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>reject(Error('Host exit '+code)));
 const info=await ready,out=info.out;console.log(out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},optimizeDeps:{entries:['tests/m08-host.html']},plugins:[{name:'m09-real-host',configureServer(s){s.middlewares.use('/__m08_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter;pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))});worker.stdin.write(JSON.stringify({...JSON.parse(raw),id})+'\n')})})}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1920,height:1080}}),report={success:false,checks:[],layouts:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));page.setDefaultTimeout(90000);
 const click=label=>page.getByRole('button',{name:label,exact:true}).filter({visible:true}).click();const idle=()=>page.waitForFunction(()=>!document.querySelector('.m09-page[aria-busy="true"]'));
 async function shot(name){await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});const g=await page.locator('.m09-page').evaluate(e=>({scroll:e.scrollWidth,client:e.clientWidth}));assert(g.scroll<=g.client+1,JSON.stringify(g));report.layouts.push(name);}
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m08-host.html');await page.locator('nav').getByRole('button',{name:'语谱图转音频',exact:true}).click();
  assert.deepEqual(await page.locator('.m09-page .mode-switch button').allTextContents(),['图片重建','图片涂鸦重建','音频藏信息']);
  assert.equal(await page.getByText('原图与四点校正',{exact:true}).count(),1);assert(await page.locator('.original-card').evaluate(e=>e.open));
  await click('选择图片目录');await page.getByLabel('语谱图图片',{exact:true}).selectOption({label:'skewed.png'});await page.waitForFunction(()=>document.querySelector('.image-frame img')?.naturalWidth===121);
  await page.getByLabel('时间终点（s）',{exact:true}).fill('.2');await page.getByLabel('迭代次数',{exact:true}).fill('2');await click('选择四个角点');
  const svg=page.locator('.image-frame svg'),b=await svg.boundingBox();for(const [x,y] of [[10/120,5/100],[110/120,25/100],[90/120,90/100],[20/120,80/100]])await svg.click({position:{x:x*b.width,y:y*b.height}});
  await click('开始重建');await page.getByRole('button',{name:'保存重建结果',exact:true}).waitFor();
  const meta=await page.locator('.m09-card pre').textContent();assert.equal(JSON.parse(meta).corners.length,4);const size=await page.locator('.comparison img').first().evaluate(e=>({width:e.naturalWidth,height:e.naturalHeight}));assert(size.width!==121||size.height!==101,JSON.stringify(size));assert(!(await page.locator('.original-card').evaluate(e=>e.open)));await shot('image-corrected');report.checks.push('single title; empty expanded; native browser four-corner clicks flow into real warp; result auto collapses');
  await click('图片涂鸦重建');await click('应用校正并绘图');await page.locator('canvas[aria-label="可缩放频谱画布"]').waitFor();
  async function draw(){const c=page.locator('canvas[aria-label="可缩放频谱画布"]');await c.scrollIntoViewIfNeeded();const b=await c.boundingBox();await page.mouse.move(b.x+b.width*.3,b.y+b.height*.45);await page.mouse.down();await page.mouse.move(b.x+b.width*.6,b.y+b.height*.55,{steps:8});await page.mouse.up();}
  await draw();await page.getByText('1 笔',{exact:true}).waitFor();await click('撤销笔迹');await page.getByText('0 笔',{exact:true}).waitFor();await click('重做笔迹');await page.getByText('1 笔',{exact:true}).waitFor();await click('生成涂鸦音频');await page.getByRole('button',{name:'保存重建结果',exact:true}).waitFor();await click('保存重建结果');await page.getByText(/已保存 4 个结果文件/).waitFor();await shot('image-drawing');report.checks.push('calibration-first picture canvas; actual pointer stroke; undo/redo; Griffin-Lim job and real four-artifact save');
  await click('音频藏信息');assert.equal(await page.locator('.m09-page .workbench-left').count(),0);await click('选择音频目录');await page.locator('canvas[aria-label="可缩放频谱画布"]').waitFor();await click('白色画笔');await page.getByLabel('画笔不透明度').evaluate(e=>{e.value='40';e.dispatchEvent(new Event('input',{bubbles:true}))});await draw();await page.getByText('1 笔',{exact:true}).waitFor();
  const c=page.locator('canvas[aria-label="可缩放频谱画布"]');await c.hover();await page.keyboard.down('Control');await page.mouse.wheel(0,-120);await page.keyboard.up('Control');await page.getByText('125%',{exact:true}).waitFor();await click('适合窗口');await click('生成藏信息音频');await page.getByRole('button',{name:'保存重建结果',exact:true}).waitFor();await click('保存重建结果');await page.getByText(/已保存 4 个结果文件/).waitFor();await shot('audio-drawing');report.checks.push('audio mode hides calibration; real stereo preview; white 40% brush; Ctrl wheel zoom; original-phase job and save');
  for(const [w,h]of [[1920,1080],[1366,768],[1100,800]])for(const theme of ['light','dark']){await page.setViewportSize({width:w,height:h});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await shot(`audio-${w}-${theme}`);}
  await click('图片涂鸦重建');await page.getByText('1 笔',{exact:true}).waitFor();report.checks.push('switching modes preserves independent drawings');
  await draw();await page.getByText('2 笔',{exact:true}).waitFor();await page.getByRole('button',{name:'关闭 语谱图转音频',exact:true}).click();
  await page.getByRole('dialog',{name:'笔迹尚未生成音频'}).waitFor();await click('返回绘图');await page.getByText('2 笔',{exact:true}).waitFor();report.checks.push('requested mode order; unsubmitted strokes prompt on close and return without loss');
  assert.deepEqual(report.errors,[]);report.success=true;
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}finally{await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify(report,null,2));await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1});
