module.exports=async({page,click,loaded,out,rpc,checks})=>{
 const assert=require('node:assert/strict'),path=require('node:path');
 const setup=(await rpc({op:'r1_setup'})).value;
 await click('语音标注对齐');await click('选择语料文件夹');
 const choose=async name=>{await page.locator('.annotation-file-list button').filter({hasText:name}).click();await loaded();};
 const create=async()=>{await click('创建标注层');await page.getByLabel('新建音节层名').fill('words');await page.getByLabel('新建音素层名').fill('phones');await click('创建层');};
 const save=async()=>{await page.getByRole('button',{name:/^保存 TextGrid/,exact:false}).first().click();await page.waitForFunction(()=>document.querySelector('.notice')?.textContent.includes('已保存：')&&document.querySelector('.annotation-page')?.getAttribute('aria-busy')==='false');const result=await rpc({op:'r1_inspect'});assert(!result.error,result.error);return result.value;};
 const timed=async(time,{ctrl=false,grid=false}={})=>{const target=page.locator(grid?'.annotation-grid':'.annotation-plots .wave-track svg').first();await target.scrollIntoViewIfNeeded();const b=await target.boundingBox();if(ctrl)await page.keyboard.down('Control');await page.mouse.dblclick(b.x+b.width*time/2,b.y+b.height*(grid?.22:.5),{delay:60});if(ctrl)await page.keyboard.up('Control');};
 const move=async(a,b)=>{const target=page.locator('.annotation-grid');await target.scrollIntoViewIfNeeded();const r=await target.boundingBox();await page.mouse.move(r.x+r.width*a/2,r.y+r.height*.22);await page.mouse.down();await page.mouse.move(r.x+r.width*b/2,r.y+r.height*.22,{steps:12});await page.mouse.up();};
 const doc=data=>data.grids['r1_无标注_自动保存.TextGrid'];const nonempty=(d,tier)=>d.tiers.find(t=>t.name===tier).intervals.filter(i=>i.text);
 await choose('r1_无标注.wav');assert.equal(await page.getByRole('alert').count(),0);await create();await click('粘贴词表');
 await page.getByLabel('拼音词表',{exact:true}).fill('zhe4 shi4 shang4 yi1 ding4 cun2 zai4 zhe5 mou3 xie1 mei3 hao3 de5 shi4 wu4 zhi2 de2 wo3 men5 fen4 zhan4 dao4 di3');await click('应用词表');
 await page.getByRole('checkbox',{name:'自动生成音节和音素'}).check();
 await timed(.2);await page.getByRole('status').filter({hasText:'起点'}).waitFor();await timed(.7);
 let data=await save(),d=doc(data),w=nonempty(d,'words');assert.equal(w[0].text,'zhe4');assert.deepEqual(nonempty(d,'phones'),w);assert(Math.abs(w[0].xmin-.2)<.004&&Math.abs(w[0].xmax-.7)<.004);checks.push('no TextGrid WAV opens, pasted full user list, two actual waveform double clicks create aligned syllable and phone');
 await timed(.35);await timed(1.1,{ctrl:true});await timed(1.35);await timed(1.8);await timed(1.5,{grid:true});
 data=await save();d=doc(data);w=nonempty(d,'words');assert.deepEqual(w.map(i=>i.text),['zhe4','shi4','shang4']);assert.equal(w[1].xmin,w[0].xmax);assert(w[2].xmin>w[1].xmax);assert.deepEqual(nonempty(d,'phones').map(i=>i.text),['zh','e4','shi4','sh','ang4']);assert.equal(await page.getByLabel('下一音节').inputValue(),'3');checks.push('clicked onset/rime splits, Ctrl previous-end continuation, ordinary new start preserves pause and consumes exactly one label');
 await page.locator('.annotation-grid').focus();await page.keyboard.press('Control+z');assert.equal(await page.getByLabel('下一音节').inputValue(),'3');await timed(1.5,{grid:true});
 await timed(.05);await page.locator('.annotation-grid').focus();await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'取消起点（Esc）'}).count(),0);checks.push('undo split keeps list cursor; Escape cancels pending start');
 await click('框选标注');await move(.1,1.2);await page.getByText('已选 2 段',{exact:true}).waitFor();
 const before=doc(await save());await page.locator('.annotation-grid').focus();await page.keyboard.press('ArrowRight');
 const one=doc(await save());for(const tier of ['words','phones']){const a=nonempty(before,tier),b=nonempty(one,tier);a.forEach((p,i)=>{const delta=p.xmax<=1.2?.001:0;assert(Math.abs(b[i].xmin-p.xmin-delta)<1.1e-6);assert(Math.abs(b[i].xmax-p.xmax-delta)<1.1e-6);});}
 await page.getByLabel('标注微调步长毫秒').fill('2.5');await page.locator('.annotation-grid').focus();await page.keyboard.press('ArrowLeft');const fine=doc(await save());assert(Math.abs(nonempty(fine,'words')[0].xmin-nonempty(one,'words')[0].xmin+.0025)<1.1e-6);
 await move(.45,.55);const dragged=doc(await save());const delta=nonempty(dragged,'words')[0].xmin-nonempty(fine,'words')[0].xmin;assert(delta>.095&&delta<.105);assert(Math.abs(nonempty(dragged,'words')[1].xmin-nonempty(fine,'words')[1].xmin-delta)<1.1e-6);
 await page.getByLabel('标注微调步长毫秒').fill('1000');await page.locator('.annotation-grid').focus();await page.keyboard.press('ArrowRight');await page.getByRole('alert').filter({hasText:/重叠|范围/}).waitFor();assert.deepEqual(doc(await save()),dragged);checks.push('left-button box selection, exact default 1ms and custom 2.5ms keyboard nudge, whole group drag, collision rejected without changing any interval');
 await page.getByLabel('标注微调步长毫秒').fill('0');await page.locator('.annotation-grid').focus();await page.keyboard.press('ArrowLeft');await page.getByRole('alert').filter({hasText:'步长'}).waitFor();await page.getByLabel('标注微调步长毫秒').fill('1');await save();
 await page.getByLabel('配色主题').selectOption('light');await page.locator('.annotation-grid').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'r1-sequence-light.png'),fullPage:true});await page.getByLabel('配色主题').selectOption('dark');await page.screenshot({path:path.join(out,'r1-sequence-dark.png'),fullPage:true});
 for(const name of ['r1_空白','r1_零层']){await choose(name+'.wav');assert.equal(await page.getByRole('alert').count(),0);await create();const value=await save();assert.equal(value.grids[name+'_自动保存.TextGrid'].tiers.length,2);}
 await page.locator('.annotation-file-list button').filter({hasText:'r1_损坏.wav'}).click();await page.getByRole('alert').waitFor();assert(!(await page.locator('.notice').innerText()).includes('正在读取'));checks.push('blank and valid zero-tier originals initialize and save, malformed nonempty file still fails with loading cleared');
 if(setup.long){const began=Date.now();await choose(setup.long);await page.waitForFunction(()=>document.querySelector('.notice')?.textContent.includes('_初始定位.TextGrid'));checks.push('actual Chinese 312.572154s FLOAT recording and recovery TextGrid loaded in '+((Date.now()-began)/1000).toFixed(2)+'s');
  const slider=page.getByLabel('平移波形时间窗');await slider.evaluate(e=>{e.value=e.max;e.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('.annotation-grid').scrollIntoViewIfNeeded();assert((await page.locator('.annotation-plots .time-axis').first().innerText()).includes('312.572'));await page.screenshot({path:path.join(out,'r1-long-tail.png'),fullPage:true});
  const value=await save(),long=value.grids[setup.long.replace(/\.wav$/i,'_自动保存.TextGrid')];assert.equal(long.tiers.length,4);assert.equal(long.tiers.find(t=>t.name==='words').intervals.length,1147);assert.equal(long.tiers.find(t=>t.name==='phones').intervals.length,2236);assert(Math.abs(long.xmax-312.572154195011)<1e-6);checks.push('long recording tail visible, full four-tier output saved and reread without truncation');
 }
 assert.equal((await rpc({op:'r1_inspect'})).value.sources_unchanged,true);checks.push('all original synthetic and user-provided recording/TextGrid sources remain byte-identical');
 await page.setViewportSize({width:800,height:720});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'r1-small.png'),fullPage:true});
};
