module.exports=async({page,click,loaded,out,rpc,checks})=>{
 const assert=require('node:assert/strict'),path=require('node:path');
 await rpc({op:'r3_setup'});
 await click('设置');await page.getByLabel('放大页面',{exact:true}).click();assert.equal(await page.getByLabel('页面缩放比例').innerText(),'110%');await page.getByRole('dialog').getByRole('button',{name:'关闭对话框'}).click();
 const global=()=>page.evaluate(()=>({scale:document.documentElement.style.zoom,ratio:devicePixelRatio,width:innerWidth,overflow:document.documentElement.scrollHeight>innerHeight+1}));const scale=await global();
 await page.locator('.welcome').hover();await page.keyboard.down('Control');await page.mouse.wheel(0,-500);await page.keyboard.up('Control');await page.clock.runFor(50);assert.deepEqual(await global(),scale);assert.equal(scale.overflow,false);
 await page.reload();assert.equal((await global()).scale,'1.1');checks.push('global settings button changes page to 110%, persists across reload, Ctrl-wheel outside plots leaves page unchanged');
 await page.evaluate(()=>{const f=document.createElement('iframe');f.id='r3-owned-frame';f.style.cssText='position:fixed;left:0;top:0;width:400px;height:150px;z-index:99999';f.srcdoc='<body>Owned embedded module wheel verification</body>';f.onload=()=>f.contentWindow.addEventListener('wheel',e=>{window.__r3FrameWheel={prevented:e.defaultPrevented,ctrl:e.ctrlKey};});document.body.append(f);});await page.frameLocator('#r3-owned-frame').locator('body').hover();await page.keyboard.down('Control');await page.mouse.wheel(0,-120);await page.keyboard.up('Control');await page.waitForFunction(()=>window.__r3FrameWheel?.ctrl&&window.__r3FrameWheel?.prevented);await page.locator('#r3-owned-frame').evaluate(e=>e.remove());checks.push('Ctrl-wheel inside an owned same-origin embedded document is cancelled while its own wheel handler still receives the event');
 await click('语音标注对齐');await click('选择语料文件夹');
 const choose=async name=>{await page.locator('.annotation-file-list button').filter({hasText:name}).click();await loaded();};
 await choose('密集.wav');assert.equal(await page.getByRole('button',{name:'清空文本',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'删除边界',exact:true}).count(),0);
 const state=()=>page.getByLabel('标注可视时长').inputValue();
 const setView=async span=>{await page.getByLabel('标注可视时长').fill(String(span));await page.getByLabel('标注可视时长').press('Tab');};
 const position=async(time,row=0,wav=false)=>{const p=page.locator(wav?'.annotation-plots .wave-track svg':'.annotation-grid').first();await p.scrollIntoViewIfNeeded();const r=await p.boundingBox(),span=Number(await state()),offset=await page.getByLabel('平移波形时间窗').count()?Number(await page.getByLabel('平移波形时间窗').inputValue()):0;return {x:r.x+r.width*(time-offset)/span,y:r.y+r.height*(wav?.5:row===0?.22:.73)};};
 const double=async(time,row=0,wav=false)=>{const p=await position(time,row,wav);await page.mouse.dblclick(p.x,p.y,{delay:60});};
 const drag=async(from,to,row=0)=>{const a=await position(from,row),b=await position(to,row);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();};
 const save=async()=>{await page.locator('.annotation-grid').focus();await page.keyboard.press('Control+s');await loaded();await page.getByRole('status').filter({hasText:'已保存：'}).waitFor();return (await rpc({op:'inspect'})).value;};
 await setView(.08);await page.getByLabel('平移波形时间窗').evaluate(e=>{e.value='.45';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.clock.runFor(40);await drag(.5,.5018);
 let d=(await save()).grids['密集_自动保存.TextGrid'];for(const t of d.tiers){const tiny=t.intervals.find(i=>i.text==='b');assert(tiny.xmax-tiny.xmin>0&&tiny.xmax-tiny.xmin<.001);}
 await page.keyboard.press('Alt+Backspace');d=(await save()).grids['密集_自动保存.TextGrid'];assert.equal(d.tiers[0].intervals.length,2,'dragged boundary remains the keyboard deletion target');await page.keyboard.press('Control+z');d=(await save()).grids['密集_自动保存.TextGrid'];assert.equal(d.tiers[0].intervals.length,3);
 await double(.5019,1);d=(await save()).grids['密集_自动保存.TextGrid'];assert.equal(d.tiers[1].intervals.length,4);const split=d.tiers[1].intervals[1].xmax;
 const p=await position(split,1);await page.mouse.click(p.x,p.y);await page.keyboard.press('Alt+Backspace');d=(await save()).grids['密集_自动保存.TextGrid'];assert.equal(d.tiers[1].intervals.length,3);assert.equal(d.tiers[1].intervals[1].xmax,.502);checks.push('110% page scale: real drag creates <1ms syllable/phone, close phone double-click inserts boundary, keyboard merges only that boundary');
 await setView(2);await double(.8,0,true);await double(1.1,0,true);await page.getByLabel('编辑选中标注文本').fill('新标注');await page.getByLabel('编辑选中标注文本').press('Enter');d=(await save()).grids['密集_自动保存.TextGrid'];assert(d.tiers[0].intervals.some(i=>i.text==='新标注'&&i.xmin>.79&&i.xmax<1.11));
 await page.keyboard.press('Backspace');d=(await save()).grids['密集_自动保存.TextGrid'];assert(!d.tiers[0].intervals.some(i=>i.text==='新标注'));await page.keyboard.press('Control+z');d=(await save()).grids['密集_自动保存.TextGrid'];assert(d.tiers[0].intervals.some(i=>i.text==='新标注'));
 await double(1.3);await double(1.5);await page.getByLabel('编辑选中标注文本').fill('层内新增');await page.getByLabel('编辑选中标注文本').press('Enter');d=(await save()).grids['密集_自动保存.TextGrid'];assert(d.tiers[0].intervals.some(i=>i.text==='层内新增'));checks.push('loaded TextGrid without a word list accepts two endpoint double-clicks in wave and blank syllable row; keyboard clear and undo preserve document');
 await page.getByLabel('编辑选中标注文本').fill('定时自动保存');await page.getByLabel('编辑选中标注文本').press('Enter');await page.clock.fastForward(61000);await loaded();let files=(await rpc({op:'inspect'})).value;assert(files.grids['密集_自动保存.TextGrid'].tiers[0].intervals.some(i=>i.text==='定时自动保存'));assert(!files.files.includes('密集_webedit.TextGrid'));
 await choose('legacy.wav');assert((await page.getByRole('status').innerText()).includes('legacy_webedit.TextGrid'));await double(1.3,0,true);await double(1.6,0,true);await page.getByLabel('编辑选中标注文本').fill('兼容旧版');await page.getByLabel('编辑选中标注文本').press('Enter');await choose('密集.wav');files=(await rpc({op:'inspect'})).value;assert(files.files.includes('legacy_自动保存.TextGrid')&&files.files.includes('legacy_webedit.TextGrid'));await choose('legacy.wav');assert((await page.getByRole('status').innerText()).includes('legacy_自动保存.TextGrid'));checks.push('timer and file-switch autosaves use Chinese suffix, legacy webedit is retained, reopening prefers new autosave');
 const wave=page.locator('.wave-track svg').first();await wave.hover();const before=Number(await state()),globalBefore=await global();await page.keyboard.down('Control');await page.mouse.wheel(0,-120);await page.keyboard.up('Control');await page.waitForFunction(n=>Number(document.querySelector('[aria-label="标注可视时长"]').value)<n,before);assert.equal((await global()).scale,globalBefore.scale);assert.equal((await global()).ratio,globalBefore.ratio);checks.push('Ctrl-wheel still zooms waveform time axis without changing page scale');
 await setView(.08);
 for(const span of [.08,.04,.01]){
  while(Number(await state())>span)await page.getByLabel('放大波形',{exact:true}).click();await page.getByLabel('平移波形时间窗').evaluate(e=>{e.value='.84';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.clock.runFor(30);
  const actual=await wave.evaluate(e=>({start:Number(e.dataset.start),end:Number(e.dataset.end),mode:e.querySelector('.wave-line').dataset.mode,path:e.querySelector('.wave-line').getAttribute('d'),limit:Number(e.parentElement.querySelector('.amplitude-axis').dataset.limit)}));assert.equal(actual.mode,'samples');assert.equal((actual.path.match(/M/g)||[]).length,1);assert(!actual.path.includes('V'));
  assert(Math.abs(actual.end-actual.start-span)<1e-10);const points=actual.path.slice(1).split(' L').map(p=>p.split(',').map(Number));assert(points.length>10);for(const [x,y] of points){const frame=Math.round((actual.start+x/1000*(actual.end-actual.start))*16000),sample=Math.fround(.4*Math.sin(2*Math.PI*180*frame/16000));assert(Math.abs(y-(45-sample/actual.limit*37))<1e-5,'path uses real original sample and timestamp');}
 }
 const waveBox=await wave.boundingBox(),specBox=await page.getByLabel('标注语谱图与唇形曲线').boundingBox();assert(Math.abs(waveBox.height-specBox.height)<1);await wave.screenshot({path:path.join(out,'r3-wave-detail.png')});checks.push('wave and spectrum heights match; 10/40/80ms detailed views form one connected path matching original signed samples and times');
 const startTime=async()=>Number(await wave.getAttribute('data-start'));const pan=async(locator,delta)=>{await locator.hover();const old=await startTime();await page.keyboard.down('Shift');await page.mouse.wheel(0,delta);await page.keyboard.up('Shift');await page.waitForFunction(([old,delta])=>{const e=document.querySelector('.wave-track svg');return Math.abs(Number(e.dataset.start)-old-delta*.01*.0015)<1e-8;},[old,delta]);assert.equal(await wave.getAttribute('data-start'),await page.locator('.annotation-tracks').getAttribute('data-start'));assert.equal(await wave.getAttribute('data-end'),await page.locator('.annotation-tracks').getAttribute('data-end'));};
 await pan(wave,120);await pan(page.getByLabel('标注语谱图与唇形曲线'),120);await pan(page.locator('.annotation-grid'),-120);assert.equal((await global()).scale,globalBefore.scale);assert.equal(await page.getByRole('button',{name:'保存 TextGrid *',exact:true}).count(),0);await page.locator('.annotation-plots').screenshot({path:path.join(out,'r3-wave-linked.png')});checks.push('real Shift-wheel in waveform, spectrum and TextGrid pans the shared window by identical amounts without changing page scale or annotations');
 const modalFits=async()=>assert(await page.getByRole('dialog').evaluate(e=>{const r=e.getBoundingClientRect(),h=e.querySelector('.dialog-header').getBoundingClientRect(),f=e.querySelector('.dialog-actions')?.getBoundingClientRect();return r.top>=0&&r.left>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1&&h.top>=0&&(!f||f.bottom<=innerHeight+1);}),'dialog header, close and footer remain inside scaled viewport');
 await click('设置');for(let i=0;i<4;i++)await page.getByLabel('放大页面',{exact:true}).click();assert.equal(await page.getByLabel('页面缩放比例').innerText(),'150%');assert.equal((await global()).overflow,false);await modalFits();await page.screenshot({path:path.join(out,'r3-settings-150.png'),fullPage:true});
 await page.setViewportSize({width:800,height:700});await modalFits();await page.screenshot({path:path.join(out,'r3-settings-small.png'),fullPage:true});for(let i=0;i<8;i++)await page.getByLabel('缩小页面',{exact:true}).click();assert.equal(await page.getByLabel('页面缩放比例').innerText(),'70%');await modalFits();await click('恢复 100%');await page.getByRole('dialog').getByRole('button',{name:'关闭对话框'}).click();await page.setViewportSize({width:1600,height:1100});await page.locator('.annotation-grid').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'r3-editing.png'),fullPage:true});checks.push('settings 70/150% and reset, including 800px window, keep header/close/footer visible; editing survives scale change');
 await choose('split.wav');await setView(2);assert.equal(await page.getByLabel('音素首个切分点').inputValue(),'cursor');await double(.35,1);d=(await save()).grids['split_自动保存.TextGrid'];let inside=d.tiers[1].intervals.filter(i=>i.xmin>=.2&&i.xmax<=.8);assert.equal(inside.length,2);assert(Math.abs(inside[0].xmax-.35)<.004);const first=inside[0].xmax;
 await page.getByLabel('音素首个切分点').selectOption('equal');await double(1.,1);d=(await save()).grids['split_自动保存.TextGrid'];inside=d.tiers[1].intervals.filter(i=>i.xmin>=.8&&i.xmax<=1.4);assert.equal(inside.length,2);assert.equal(inside[0].xmax,1.1);await double(.25,1);d=(await save()).grids['split_自动保存.TextGrid'];assert(d.tiers[1].intervals.some(i=>i.xmax===first));assert(d.tiers[1].intervals.some(i=>Math.abs(i.xmax-.25)<.004));await page.keyboard.press('Control+z');await save();checks.push('phone double-click first boundary follows cursor or equal choice; already split phone adds only clicked boundary, preserving old edges; undo saves correctly');
 const spectrogram=page.getByLabel('标注语谱图与唇形曲线');await spectrogram.scrollIntoViewIfNeeded();const sr=await spectrogram.boundingBox();const specDrag=async(a,b)=>{await page.mouse.move(sr.x+sr.width*a/2,sr.y+sr.height*.5);await page.mouse.down();await page.mouse.move(sr.x+sr.width*b/2,sr.y+sr.height*.5,{steps:10});await page.mouse.up();return page.getByLabel('语谱图选区').evaluate(e=>[Number(e.dataset.start),Number(e.dataset.end)]);};
 const range=await specDrag(.25,.6);assert(Math.abs(range[0]-.25)<.004&&Math.abs(range[1]-.6)<.004);assert.deepEqual(await page.getByLabel('标注层选区').evaluate(e=>[Number(e.dataset.start),Number(e.dataset.end)]),range);assert.equal(await page.getByLabel('编辑选中标注文本').isDisabled(),true);assert.deepEqual(await specDrag(.6,.25),range);
 const rectangle=await wave.locator('.wave-selection').evaluate(e=>[Number(e.getAttribute('x')),Number(e.getAttribute('width'))]);assert(Math.abs(rectangle[0]-range[0]/2*1000)<1e-8&&Math.abs(rectangle[1]-(range[1]-range[0])/2*1000)<1e-8);
 await page.evaluate(()=>{const original=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){window.__r3Play=args;return original.apply(this,args);};});await page.keyboard.press('Space');await page.waitForFunction(()=>!!window.__r3Play);const played=await page.evaluate(()=>window.__r3Play);assert.equal(played[1],range[0]);assert.equal(played[2],range[1]-range[0]);await page.keyboard.press('Space');assert.equal(await page.getByRole('button',{name:'保存 TextGrid *',exact:true}).count(),0);await page.locator('.annotation-plots').screenshot({path:path.join(out,'r3-spectrum-selection.png')});checks.push('spectrogram forward/reverse pointer selection links all three tracks, clears stale interval selection, and Space starts real WebAudio at the selected range');
 await page.reload();await click('语音标注对齐');await click('选择语料文件夹');await choose('split.wav');assert.equal(await page.getByLabel('音素首个切分点').inputValue(),'equal');checks.push('first phone split choice persists across page reload');
 await click('粘贴词表');await page.getByLabel('拼音词表',{exact:true}).fill('ba1 ba2 ba3');await click('应用词表');await page.locator('.sequence-toggle input').check();await double(1.6,1);await double(1.8,1);d=(await save()).grids['split_自动保存.TextGrid'];const third=d.tiers[0].intervals.find(i=>i.text==='ba3');assert(third);assert(d.tiers[1].intervals.some(i=>i.text==='ba3'&&i.xmin===third.xmin&&i.xmax===third.xmax));await double(1.65,1);d=(await save()).grids['split_自动保存.TextGrid'];assert(d.tiers[1].intervals.some(i=>i.text==='b'&&i.xmax===Number(((third.xmin+third.xmax)/2).toFixed(6))));checks.push('sequence mode retains phone-row endpoint creation and applies the selected first-boundary mode for its initial internal split');
};
