// M13: local conversion, bundled font and browser PNG export. No server task or user upload.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const out=path.join(root,'output/validation/m13-browser',String(Date.now()));await fs.mkdir(out,{recursive:true});
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},optimizeDeps:{entries:['tests/m13-live.html']}});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});const page=await context.newPage();
 const errors=[],external=[],checks=[];const observe=target=>{target.on('pageerror',error=>errors.push(error.message));target.on('request',request=>{const url=new URL(request.url());if(!['127.0.0.1','localhost'].includes(url.hostname)&&!['data:','blob:'].includes(url.protocol))external.push(request.url());});};observe(page);
 const input=()=>page.getByLabel('待转换汉字文本'),standard=()=>page.getByLabel('转换标准');
 const screenshot=async name=>page.screenshot({path:path.join(out,name+'.png'),fullPage:true,animations:'disabled'});
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m13-live.html');await page.locator('.mandarin-ipa-page').waitFor();await page.waitForFunction(()=>[...document.fonts].some(face=>face.family==='PTB-Doulos'&&face.status==='loaded'));
  assert.equal(await page.locator('.mandarin-ipa-page h1').count(),0);assert.equal(await page.getByRole('button',{name:'关闭模块',exact:true}).count(),0);checks.push('public module frame without duplicate heading or close button');
  await input().fill('妈行 A1，\n花');
  const standards=['Standard Chinese (Beijing)','Standard Chinese (Beijing)严','胡裕树《现代汉语》','黄伯荣、廖序东《现代汉语》','钱乃荣《现代汉语》','吴宗济','赵元任《汉语口语语法》','《汉语方音字汇》','UntPhesoca宽','UntPhesoca严','汉语拼音'];
  const expected=['ma˥','ma̠˥','mᴀ˥','mᴀ˥','mᴀ˥','mᴀ˥','mᴀ˥','mᴀ˥','ma˥','mä˥','mā'];const observed=[];
  for(let i=0;i<standards.length;i++){await standard().selectOption(standards[i]);observed.push(await page.locator('.m13-mapped[data-index="0"]').getAttribute('data-value'));}
  assert.deepEqual(observed,expected);assert.equal((await standard().locator('option').allTextContents()).length,11);checks.push('all 11 reviewed legacy standards render expected text');
  await input().fill('银行花');await standard().selectOption('汉语拼音');const aligned=await page.locator('.m13-mapped').evaluateAll(tokens=>({ipa:tokens.map(token=>token.querySelector('.m13-ipa').getBoundingClientRect().top),hanzi:tokens.map(token=>token.querySelector('.m13-hanzi').getBoundingClientRect().top)}));assert(Math.max(...aligned.ipa)-Math.min(...aligned.ipa)<.5);assert(Math.max(...aligned.hanzi)-Math.min(...aligned.hanzi)<.5);await screenshot('aligned-pinyin-light-1440x900');checks.push('ordinary and ambiguous tokens share exact IPA and Hanzi row coordinates');
  await input().fill('妈行 A1，\n花');
  await standard().selectOption('Standard Chinese (Beijing)严');await page.locator('button.m13-ambiguous[data-index="1"]').click();const dialog=page.getByRole('dialog',{name:'选择 行 的读音'});assert.equal(await dialog.locator('> button').count(),4);await dialog.getByRole('button',{name:/hang2.*xa/}).click();assert.equal(await page.locator('.m13-mapped[data-index="1"]').getAttribute('data-value'),'xa̝ŋ˧˥');checks.push('ambiguity remains explicit and selected per text position');
  await page.getByLabel('汉字字号').evaluate((element)=>{element.value='42';element.dispatchEvent(new Event('input',{bubbles:true}));});await page.getByLabel('音标字号').evaluate((element)=>{element.value='27';element.dispatchEvent(new Event('input',{bubbles:true}));});await page.getByLabel('字音间距').evaluate((element)=>{element.value='-6';element.dispatchEvent(new Event('input',{bubbles:true}));});await page.getByLabel('行距').evaluate((element)=>{element.value='24';element.dispatchEvent(new Event('input',{bubbles:true}));});
  for(const name of ['B 粗体','I 斜体','U 下划线'])await page.getByRole('button',{name,exact:true}).click();await screenshot('paired-light-1440x900');
  await page.getByLabel('仅音标').check();await page.getByLabel('上下排布').check();assert.equal(await page.locator('.m13-mapped .m13-hanzi').count(),0);assert(await page.locator('.m13-ipa-only-literal').count()>0);await page.evaluate(()=>document.documentElement.dataset.theme='dark');await screenshot('ipa-only-stacked-dark-1440x900');checks.push('independent sizes, gap, line height, Hanzi styles and both display/layout modes');
  const longText='妈行花。\n'.repeat(400);await input().fill(longText);assert.equal(await page.locator('.m13-mapped').count(),1200);await page.setViewportSize({width:1280,height:800});await screenshot('long-dark-1280x800');checks.push('long text renders all 1200 mapped characters without truncating state');
  await input().fill('妈行花 a̠');await page.getByLabel('字音同显').check();await page.getByLabel('左右排布').check();await page.evaluate(()=>{window.__m13Paint=[];window.__m13FillText=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...args){window.__m13Paint.push({text,font:this.font});return window.__m13FillText.call(this,text,...args);};});
  await context.setOffline(true);const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'保存为 PNG',exact:true}).click();const download=await downloadPromise,file=path.join(out,'m13-offline.png');await download.saveAs(file);await context.setOffline(false);
  const paint=await page.evaluate(()=>window.__m13Paint);assert(paint.some(item=>item.font.includes('PTB-Doulos')&&item.text.includes('ma')));assert(paint.some(item=>item.text==='行'));assert.equal(await page.locator('[role=alert]').count(),0);
  const bytes=await fs.readFile(file);assert.equal(bytes.subarray(1,4).toString(),'PNG');const visual=await page.evaluate(async base64=>{const image=new Image();image.src='data:image/png;base64,'+base64;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d');context.drawImage(image,0,0);const data=context.getImageData(0,0,image.width,image.height).data;let nonWhite=0,blue=0;for(let i=0;i<data.length;i+=4){if(data[i]<245||data[i+1]<245||data[i+2]<245)nonWhite++;if(data[i+2]>data[i]+20)blue++;}return {width:image.width,height:image.height,nonWhite,blue};},bytes.toString('base64'));assert(visual.width>1000&&visual.height>300&&visual.nonWhite>1000&&visual.blue>100);checks.push('offline PNG contains rasterized Hanzi/IPA and actual PTB-Doulos canvas calls');
  await page.evaluate(()=>{document.fonts.__m13Load=document.fonts.load.bind(document.fonts);document.fonts.load=()=>Promise.reject(Error('test font failure'));});await page.getByRole('button',{name:'保存为 PNG',exact:true}).click();await page.getByRole('alert').filter({hasText:'Doulos SIL 字体加载失败'}).waitFor();await page.getByRole('button',{name:'收起提示'}).click();await page.evaluate(()=>{document.fonts.load=document.fonts.__m13Load;HTMLCanvasElement.prototype.__m13ToBlob=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(callback){callback(null);};});
  await page.getByRole('button',{name:'保存为 PNG',exact:true}).click();await page.getByRole('alert').filter({hasText:'PNG 编码失败'}).waitFor();checks.push('font and PNG encoder failures remain recoverable without clearing text');
  await input().fill('');assert(await page.getByText('输入文本后，这里会实时显示转换结果。').isVisible());assert(await page.getByRole('button',{name:'保存为 PNG',exact:true}).isDisabled());checks.push('empty input is explicit and cannot export a fake result');
  const appPage=await context.newPage();observe(appPage);await appPage.goto(server.resolvedUrls.local[0]);await appPage.locator('.nav-item').filter({hasText:'普通话转 IPA'}).click();await appPage.locator('.mandarin-ipa-page').waitFor();await appPage.getByLabel('待转换汉字文本').fill('银行');
  assert(await appPage.getByText('普通话转 IPA · 本地逐字映射与离线导出').isVisible());assert.equal(await appPage.locator('.global-transport:visible').count(),0);assert.equal(await appPage.locator('.mandarin-ipa-page h1').count(),0);
  await appPage.getByRole('button',{name:'关闭 普通话转 IPA',exact:true}).click();assert(await appPage.getByRole('heading',{name:'保存转换草稿？'}).isVisible());await appPage.getByRole('button',{name:'保存草稿并关闭',exact:true}).click();await appPage.locator('.mandarin-ipa-page').waitFor({state:'detached'});
  await appPage.locator('.nav-item').filter({hasText:'普通话转 IPA'}).click();await appPage.locator('.mandarin-ipa-page').waitFor();assert.equal(await appPage.getByLabel('待转换汉字文本').inputValue(),'银行');await appPage.screenshot({path:path.join(out,'appshell-m13-light-1440x900.png'),fullPage:true,animations:'disabled'});checks.push('actual AppShell lazy-loads M13, tracks dirty state, saves on protected close and restores the local draft');await appPage.close();
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  await fs.writeFile(path.join(out,'report.json'),JSON.stringify({checks,observed,paint:paint.slice(0,30),visual,external,errors,platform:process.platform,browser:'Google Chrome',offline_export:true},null,2));console.log(out);
 }catch(error){await screenshot('failure');await fs.writeFile(path.join(out,'failure.txt'),String(error)+'\n'+await page.locator('body').innerText());throw error;}
 finally{await browser.close();await server.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
