const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn,spawnSync}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const python=path.join(root,'.venv/m14/Scripts/python.exe'),worker=spawn(python,['-B','-X','utf8','tests/support/m14_host_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','packages/phonetic_core/src','desktop/src','scripts'].map(p=>path.join(root,p)).join(';')}});
 let readyResolve,readyReject,counter=0;const pending=new Map(),ready=new Promise((r,j)=>{readyResolve=r;readyReject=j});
 createInterface({input:worker.stdout}).on('line',line=>{const d=JSON.parse(line);if(d.ready)readyResolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id)}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>readyReject(Error('Host exited '+code)));
 const {out}=await ready;console.log(out);const inputs=path.join(out,'r1-inputs');assert.equal(spawnSync(python,['-B','scripts/m14_r1_inputs.py',inputs],{cwd:root,windowsHide:true}).status,0);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:5199,strictPort:true},optimizeDeps:{entries:['tests/m14-host.html']},plugins:[{name:'m14-owned-transport',configureServer(s){s.middlewares.use('/__m14_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter;pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))});worker.stdin.write(JSON.stringify({...JSON.parse(raw),id})+'\n')})})}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1920,height:1080}}),checks=[],errors=[],formats=[],layouts=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(60000);
 const scope=page.getByLabel('音系归纳工作区',{exact:true}),click=name=>scope.getByRole('button',{name,exact:true}).click(),idle=()=>page.waitForFunction(()=>document.querySelector('[aria-label="音系归纳工作区"]')?.getAttribute('aria-busy')==='false');
 const upload=async p=>{await scope.locator('input[type=file]').setInputFiles(p);await idle();};
 const reviewAbsent=async()=>assert.equal(await scope.getByText('导入与归并审阅',{exact:false}).count(),0);
 let success=false;
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m14-host.html');await page.locator('nav').getByRole('button',{name:'音系归纳',exact:true}).click();await scope.waitFor();
  for(const ext of ['xlsx','xls','csv','txt','tsv']){await upload(path.join(root,'tests/fixtures/m14','public.'+ext));await scope.getByRole('table',{name:'原始表格样例'}).waitFor();await reviewAbsent();await click('确认导入并继续');await idle();assert((await scope.innerText()).includes('已读取'));await reviewAbsent();formats.push({ext,message:await scope.locator('[role=status]').allTextContents()});await click('1 · 导入');}
  checks.push('five existing formats through inspect and confirmed import, production desktop adapter and real durable child');
  await upload(path.join(inputs,'table.docx'));await scope.getByLabel('工作表 / 表格').selectOption('1');await idle();await scope.getByLabel('备注列',{exact:true}).selectOption('2');await scope.getByLabel('字头列',{exact:true}).selectOption('4');await scope.getByLabel('IPA 列',{exact:true}).selectOption('3');await click('确认导入并继续');await idle();assert((await scope.innerText()).includes('已读取 5 条记录'));await reviewAbsent();checks.push('DOCX second table and arbitrary columns');
  await click('1 · 导入');await upload(path.join(inputs,'large.xlsx'));await scope.getByLabel('工作表 / 表格').selectOption('1');await idle();assert.equal(await scope.getByRole('table',{name:'原始表格样例'}).locator('thead th').count(),5);await click('取消此次选择');checks.push('second-sheet inspection remains available after prior column choices temporarily overlap on a narrow first sheet');
  await click('1 · 导入');await scope.getByLabel('文本编码').selectOption('gb18030');await scope.getByLabel('分隔符',{exact:true}).selectOption('semicolon');await upload(path.join(inputs,'gbk.txt'));await scope.getByLabel('字头列',{exact:true}).selectOption('1');await scope.getByLabel('IPA 列',{exact:true}).selectOption('2');await scope.getByLabel('备注列',{exact:true}).selectOption('3');await click('确认导入并继续');await idle();assert((await scope.innerText()).includes('已读取 2 条记录'));checks.push('GB18030 text decoded using selected encoding and delimiter');
  await click('1 · 导入');await upload(path.join(inputs,'large.xlsx'));await scope.getByLabel('工作表 / 表格').selectOption('1');await idle();await scope.getByLabel('备注列',{exact:true}).selectOption('2');await scope.getByLabel('字头列',{exact:true}).selectOption('4');await scope.getByLabel('IPA 列',{exact:true}).selectOption('3');await scope.getByLabel('数据开始行',{exact:true}).fill('3');await scope.getByLabel('数据开始行',{exact:true}).press('Tab');await idle();await click('确认导入并继续');await idle();assert((await scope.innerText()).includes('已读取 360 条记录'));
  assert.equal(await page.getByRole('dialog').count(),0);await scope.getByLabel('调类 35',{exact:true}).fill('阳');await scope.getByLabel('调类 55',{exact:true}).fill('阴');await click('上移调值 55');await click('还原本次编辑');assert.equal(await scope.getByLabel('调类 55',{exact:true}).inputValue(),'55');await scope.getByLabel('调类 35',{exact:true}).fill('阳');await scope.getByLabel('调类 55',{exact:true}).fill('阴');await click('保存调类设置并继续');await reviewAbsent();
  const initials=scope.getByRole('listbox',{name:'声母列表'}),finals=scope.getByRole('listbox',{name:'韵母列表'});
  await initials.getByRole('option',{name:'m',exact:true}).click();await initials.getByRole('option',{name:'ts',exact:true}).click({modifiers:['Control']});await initials.getByRole('option',{name:'m',exact:true}).dragTo(initials.getByRole('option',{name:'Ø',exact:true}));assert.deepEqual(await initials.getByRole('option').allTextContents(),['m','ts','Ø']);await click('还原本次编辑');
  await finals.getByRole('option',{name:'ã',exact:true}).click();await finals.getByRole('option',{name:'t͡s',exact:true}).click({modifiers:['Shift']});await finals.getByRole('option',{name:'ã',exact:true}).dragTo(finals.getByRole('option',{name:'a',exact:true}));assert.deepEqual(await finals.getByRole('option').allTextContents(),['ã','t͡s','a']);await initials.getByRole('option',{name:'Ø',exact:true}).dragTo(finals.getByRole('option',{name:'a',exact:true}));assert.deepEqual(await finals.getByRole('option').allTextContents(),['ã','t͡s','a']);await click('还原本次编辑');checks.push('real Ctrl/Shift multi-selection and group dragging in both lists, cross-list drag rejected');
  await initials.getByRole('option',{name:'ts',exact:true}).click();await click('归并声母');await scope.getByLabel('归并目标',{exact:true}).selectOption('m');await click('确认归并');await scope.getByRole('button',{name:'撤销归并 ts',exact:true}).click();assert.equal(await initials.getByRole('option',{name:'ts',exact:true}).count(),1);await initials.getByRole('option',{name:'ts',exact:true}).click();await click('归并声母');await scope.getByLabel('归并目标',{exact:true}).selectOption('m');await click('确认归并');
  await finals.getByRole('option',{name:'ã',exact:true}).click();await click('归并韵母');await scope.getByLabel('归并目标',{exact:true}).selectOption('a');await click('确认归并');assert.equal(await page.getByRole('dialog').count(),0);await click('保存声韵设置并继续');checks.push('360 rows with selected fourth/third/second columns and start row 3; inline tones and symbols, merge undo and saved mapping');
  await scope.getByRole('button',{name:'声母 → 韵母',exact:false}).waitFor();await scope.getByLabel('搜索字头或 IPA',{exact:true}).fill('罕');await scope.locator('.result-sheet .preview-entry.focused').waitFor();assert((await scope.locator('.result-sheet .preview-entry.focused').innerText()).includes('罕'));assert((await scope.locator('.word-sheet .pagination').innerText()).includes('第 4 / 4 页'));await scope.getByLabel('搜索字头或 IPA',{exact:true}).fill('罕 ');await scope.locator('.result-sheet .preview-entry.focused').waitFor();assert((await scope.locator('.word-sheet .pagination').innerText()).includes('第 4 / 4 页'));
  await scope.getByRole('button',{name:'韵母 → 声母',exact:false}).click();assert((await scope.locator('.result-sheet .preview-entry.focused').innerText()).includes('罕'));await scope.getByRole('button',{name:'二维声韵表',exact:false}).click();await scope.locator('.matrix-sheet .preview-entry.focused').waitFor();assert((await scope.locator('.matrix-sheet .preview-entry.focused').innerText()).includes('罕'));assert.equal(await scope.locator('.matrix-sheet .preview-entry').count()<360,true);
  await scope.getByLabel('搜索字头或 IPA',{exact:true}).fill('ã');assert((await scope.locator('.result-sheet .preview-entry.focused').innerText()).includes('鼻'));await scope.getByLabel('搜索字头或 IPA',{exact:true}).fill('没有此字');assert((await scope.innerText()).includes('没有匹配记录'));await click('清空');checks.push('all three complete preview modes; search beyond row 200, canonical IPA match, paged matrix-cell positioning and empty-search state');
  await click('生成三份结果');await idle();assert((await scope.innerText()).includes('三份结果已完整生成'));await click('选择目录保存三份结果');await idle();const files=await fs.readdir(path.join(out,'saved'));assert.equal(files.length,3);await click('选择目录保存三份结果');await idle();assert((await scope.innerText()).includes('同名结果'));assert.deepEqual(await fs.readdir(path.join(out,'saved')),files);checks.push('real 360-record generation, exactly three native saved files and collision preservation');
  await click('2 · 调类与调值');await scope.getByLabel('调类 55',{exact:true}).fill('阴改');await click('4 · 结果');assert((await scope.innerText()).includes('设置已修改，需重新生成'));assert(await scope.getByRole('button',{name:'生成三份结果',exact:true}).isDisabled());assert(!(await scope.locator('.result-sheet').innerText()).includes('[阴改]'));await click('2 · 调类与调值');await click('保存调类设置并继续');await click('4 · 结果');assert(!(await scope.getByRole('button',{name:'生成三份结果',exact:true}).isDisabled()));checks.push('generated preview snapshot retains old labels; edits mark old output and require saved settings');
  for(const [width,height] of [[1366,768],[1920,1080],[2560,1440],[3840,2160]])for(const theme of ['light','dark']){await page.setViewportSize({width,height});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(let s=0;s<4;s++){await click((s+1)+' · '+['导入','调类与调值','声韵排序归并','结果'][s]);if(s<3)await reviewAbsent();await page.screenshot({path:path.join(out,`r1-${width}-${theme}-step${s+1}.png`),fullPage:true});const g=await scope.evaluate(e=>({scroll:e.scrollWidth,width:e.clientWidth}));assert(g.scroll<=g.width+1,JSON.stringify({width,theme,s,g}));layouts.push({width,height,theme,step:s+1,...g});}}
  await page.setViewportSize({width:1920,height:1080});await click('4 · 结果');await scope.locator('.review>summary').click();assert(await scope.getByRole('table',{name:'导入与归并审阅表',exact:true}).isVisible());await scope.getByLabel('搜索字头或 IPA',{exact:true}).fill('罕');assert((await scope.getByRole('table',{name:'导入与归并审阅表',exact:true}).innerText()).includes('322'));checks.push('32 layouts in four sizes/two themes; review exists only in result step and includes actual source row 322');
  await click('1 · 导入');await scope.getByLabel('文本编码').selectOption('auto');await scope.getByLabel('分隔符',{exact:true}).selectOption('auto');await upload(path.join(inputs,'missing.tsv'));await scope.getByLabel('数据开始行',{exact:true}).fill('2');await scope.getByLabel('数据开始行',{exact:true}).press('Tab');await idle();await scope.getByLabel('字头列',{exact:true}).selectOption('1');await scope.getByLabel('IPA 列',{exact:true}).selectOption('2');await scope.getByLabel('备注列',{exact:true}).selectOption('3');await click('确认导入并继续');await idle();assert((await scope.innerText()).includes('没有有效记录'));await click('取消此次选择');await click('4 · 结果');assert((await scope.locator('.preview-caption').innerText()).includes('360 条记录'));checks.push('empty mapped input fails without replacing current data or generated result');
  await click('保存草稿');await page.getByLabel('关闭 音系归纳',{exact:true}).click();await scope.waitFor({state:'detached'});await page.locator('nav').getByRole('button',{name:'音系归纳',exact:true}).click();await scope.waitFor();assert((await scope.innerText()).includes('已恢复本机草稿'));assert.equal(await scope.getByLabel('调类 55',{exact:true}).inputValue(),'阴改');checks.push('top save and AppShell reopen retain current inline edits');
  assert.deepEqual(errors,[]);success=true;
 }catch(e){await page.screenshot({path:path.join(out,'r1-failure.png'),fullPage:true});throw e;}
 finally{await fs.writeFile(path.join(out,'r1-browser-report.json'),JSON.stringify({success,checks,formats,layouts,errors,scope:'Windows actual Chrome, production desktop adapter/host/child; synthetic files and substituted QWebChannel transport only'},null,2));console.log(JSON.stringify({success,checks,layouts:layouts.length}));await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1});
