const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m14/Scripts/python.exe'),['-X','utf8','tests/support/m14_host_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','packages/phonetic_core/src','desktop/src','scripts'].map(p=>path.join(root,p)).join(';')}});
 let readyResolve,readyReject,counter=0;const pending=new Map(),ready=new Promise((r,j)=>{readyResolve=r;readyReject=j});
 createInterface({input:worker.stdout}).on('line',line=>{const d=JSON.parse(line);if(d.ready)readyResolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id)}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>readyReject(Error('Host exited '+code)));
 const {out}=await ready;console.log(out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:5189},optimizeDeps:{entries:['tests/m14-host.html']},plugins:[{name:'m14-host-transport-test',configureServer(s){s.middlewares.use('/__m14_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter;pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))});worker.stdin.write(JSON.stringify({...JSON.parse(raw),id})+'\n')})})}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(45000);
 const click=name=>page.getByRole('button',{name,exact:true}).click(),open=()=>page.locator('nav').getByRole('button',{name:'音系归纳',exact:true}).click(),idle=()=>page.waitForFunction(()=>document.querySelector('[aria-label="音系归纳工作区"]')?.getAttribute('aria-busy')==='false');
 const scope=page.getByLabel('音系归纳工作区',{exact:true}),dialog=()=>page.getByRole('dialog');
 const upload=async name=>{await scope.locator('input[type=file]').setInputFiles(path.join(root,'tests/fixtures/m14',name));await idle();};
 let success=false;
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m14-host.html');await open();await scope.waitFor();
  for(const ext of ['xlsx','xls','csv','txt','tsv']){await upload('public.'+ext);assert((await scope.innerText()).includes(ext==='txt'||ext==='tsv'?'18 条记录':'16 条记录'));}
  checks.push('five formats through production desktop adapter, TaskBridge, local HTTP and persistent child');
  await upload('public.xlsx');await click('编辑调值顺序与调类');const tone35=dialog().getByLabel('调类 35');await tone35.fill('临时');await dialog().getByRole('button',{name:'取消',exact:true}).click();await click('编辑调值顺序与调类');assert.notEqual(await dialog().getByLabel('调类 35').inputValue(),'临时');
  const toneRows=dialog().locator('tbody tr'),before=await toneRows.locator('td:first-child').allTextContents();await toneRows.first().dragTo(toneRows.last());const after=await toneRows.locator('td:first-child').allTextContents();assert.equal(after.at(-1),before[0]);assert.equal(after[0],before.at(-1));
  await dialog().getByLabel('调类 35').fill('合调');await dialog().getByLabel('调类 55').fill('合调');await click('确认调类');checks.push('tone drag swaps two rows; names and same-label mapping; cancel/confirm');
  await click('3 · 声韵排序归并');await click('编辑声韵顺序与归并');const initials=dialog().getByRole('listbox',{name:'声母列表'}),finals=dialog().getByRole('listbox',{name:'韵母列表'});let opts=initials.getByRole('option');
  await opts.nth(0).click();await opts.nth(2).click({modifiers:['Control']});assert.equal(await initials.locator('[aria-selected=true]').count(),2);await opts.nth(4).click({modifiers:['Shift']});assert.equal(await initials.locator('[aria-selected=true]').count(),3);
  const chosen=await initials.locator('[aria-selected=true]').allTextContents();await initials.locator('[aria-selected=true]').first().dragTo(opts.first());assert.deepEqual((await opts.allTextContents()).slice(0,3),chosen);
  await finals.getByRole('option').nth(0).click();await finals.getByRole('option').nth(2).click({modifiers:['Control']});assert.equal(await finals.locator('[aria-selected=true]').count(),2);await finals.getByRole('option').nth(4).click({modifiers:['Shift']});assert.equal(await finals.locator('[aria-selected=true]').count(),3);const chosenFinals=await finals.locator('[aria-selected=true]').allTextContents();await finals.locator('[aria-selected=true]').first().dragTo(finals.getByRole('option').first());assert.deepEqual((await finals.getByRole('option').allTextContents()).slice(0,3),chosenFinals);await page.screenshot({path:path.join(out,'selection.png'),fullPage:true});
  await initials.getByRole('option',{name:'pʰ',exact:true}).click();await click('归并声母');await click('取消本次归并');assert(await initials.getByRole('option',{name:'pʰ',exact:true}).count());
  await click('归并声母');await initials.getByRole('option',{name:'p',exact:true}).click();await dialog().getByRole('button',{name:'取消',exact:true}).click();await click('编辑声韵顺序与归并');assert(await initials.getByRole('option',{name:'pʰ',exact:true}).count());
  await initials.getByRole('option',{name:'pʰ',exact:true}).click();await click('归并声母');await initials.getByRole('option',{name:'p',exact:true}).click();await initials.getByRole('option',{name:'p',exact:true}).click();await click('归并声母');await initials.getByRole('option',{name:'m',exact:true}).click();
  await finals.getByRole('option',{name:'ã',exact:true}).click();await click('归并韵母');await finals.getByRole('option',{name:'a',exact:true}).click();await click('确认声韵设置');assert((await scope.getByLabel('已确认归并映射').innerText()).includes('pʰ → p → m'));checks.push('Ctrl/Shift initial/final selection, group drag, source/target/cancel, chained merges preserve input');
  await click('4 · 结果');await click('生成三份结果');await idle();await click('选择目录保存三份结果');await idle();let names=await fs.readdir(path.join(out,'saved'));assert.equal(names.length,3);await click('选择目录保存三份结果');await idle();assert((await scope.innerText()).includes('同名结果'));assert.deepEqual(await fs.readdir(path.join(out,'saved')),names);checks.push('three actual outputs, save, collision refusal keeps all files');
  const dl=page.waitForEvent('download');await scope.getByRole('listitem').filter({hasText:'同音字表_韵母到声母.docx'}).getByRole('button',{name:'下载',exact:true}).click();await(await dl).saveAs(path.join(out,'download.docx'));await idle();assert((await fs.stat(path.join(out,'download.docx'))).size>1000);
  await upload('broken.xlsx');assert((await scope.innerText()).includes('无法解析'));assert.equal(await scope.getByRole('button',{name:'下载',exact:true}).count(),3);await upload('missing.tsv');assert((await scope.innerText()).includes('没有有效记录'));await upload('empty.txt');assert((await scope.innerText()).includes('文件为空'));await upload('public.xlsx');checks.push('bad/empty/missing input recovery preserves earlier results until successful import');
  await click('1 · 导入');await page.getByLabel('单辅音策略').selectOption('false');await page.getByLabel('跳过首行（表头）').uncheck();await upload('public.xlsx');await click('3 · 声韵排序归并');await click('编辑声韵顺序与归并');await finals.getByRole('option',{name:'空韵',exact:true}).click();await click('归并韵母');await finals.getByRole('option',{name:'a',exact:true}).click();await click('确认声韵设置');checks.push('skip-first off and consonant-as-initial strategy; empty-final merge is usable');
  await page.getByLabel('关闭 音系归纳',{exact:true}).click();await click('取消关闭');await page.evaluate(()=>{window.__set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.includes('m14:'))throw Error('controlled storage failure');return window.__set.call(this,k,v)}});await page.getByLabel('关闭 音系归纳',{exact:true}).click();await click('保存草稿并关闭');await dialog().getByRole('alert').waitFor();await page.evaluate(()=>Storage.prototype.setItem=window.__set);await click('保存草稿并关闭');await scope.waitFor({state:'detached'});await open();await scope.waitFor();assert((await scope.innerText()).includes('恢复本机草稿'));checks.push('formal AppShell close guard, failed draft save, reopen retains confirmed settings');
  await page.screenshot({path:path.join(out,'light.png'),fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.waitForTimeout(250);await page.screenshot({path:path.join(out,'dark.png'),fullPage:true});await page.setViewportSize({width:900,height:700});await page.screenshot({path:path.join(out,'compact.png'),fullPage:true});
  assert.deepEqual(errors,[]);success=true;
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}
 finally{await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify({success,checks,errors,scope:'Windows Chrome, production desktop adapter and real host; QWebChannel transport substituted'},null,2));console.log(JSON.stringify({success,checks}));await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1});
