const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','tests/support/m16_host_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['packages/phonetic_core/src','desktop/src','scripts'].map(p=>path.join(root,p)).join(';')}});
 let resolveReady,rejectReady,counter=0;const pending=new Map(),ready=new Promise((r,j)=>{resolveReady=r;rejectReady=j;});
 createInterface({input:worker.stdout}).on('line',line=>{try{const d=JSON.parse(line);if(d.ready)resolveReady(d);else{pending.get(d.id)?.(d);pending.delete(d.id);}}catch(e){rejectReady(e);}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>rejectReady(Error('M16 worker exited '+code)));
 const {out}=await ready;console.log(out);const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0,watch:null},optimizeDeps:{entries:['tests/m16-host.html']},plugins:[{name:'m16-test-transport',configureServer(s){s.middlewares.use('/__m16_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter;pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));});worker.stdin.write(JSON.stringify({...JSON.parse(raw),id})+'\n');});});}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[],checks=[],network=[],previews=[],layouts=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:')&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))network.push(r.url());});page.on('response',async r=>{if(r.url().includes('/__m16_host')){try{const b=r.request().postDataJSON();if(b.body?.op==='preview')previews.push({request:b.body,value:(await r.json()).value});}catch{}}});page.setDefaultTimeout(30000);
 const scope=page.locator('.recording-page'),click=text=>scope.getByRole('button',{name:text,exact:true}).click(),idle=()=>page.waitForFunction(()=>document.querySelector('.recording-page')?.getAttribute('aria-busy')==='false');let success=false;
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m16-host.html');await scope.waitFor();await click('新建工程');await scope.getByText('本地录音工程已建立',{exact:true}).waitFor();await click('设备与录前检测');const input=scope.getByLabel('输入设备',{exact:true});const device=await input.locator('option').nth(1).getAttribute('value');await input.selectOption(device);assert.equal(await scope.getByLabel('同声卡输入通道数',{exact:true}).inputValue(),'2');assert.equal(await scope.getByLabel('物理输入 2 角色',{exact:true}).inputValue(),'microphone');checks.push('default two audio channels; EGG is opt-in');await scope.getByLabel('扬声器 / 耳机',{exact:true}).selectOption(device);await scope.getByLabel('同声卡输入通道数',{exact:true}).fill('2');await scope.getByLabel('物理输入 2 角色',{exact:true}).selectOption('egg');
  await click('开始录前检测（不保存音频）');await scope.getByText('录前检测中，音频不会保存为 take',{exact:true}).waitFor();await page.waitForTimeout(350);await scope.getByLabel('检测数字增益预览（dB）',{exact:true}).fill('24');await page.waitForTimeout(350);await click('停止检测');await idle();assert.equal((JSON.parse(await fs.readFile(path.join(out,'project/project.json'),'utf8'))).takes.length,0);await scope.locator('.devices-panel').getByRole('button',{name:'收起',exact:true}).click();assert.equal(await scope.locator('.wave-lane').count(),0);checks.push('preflight live raw/digital meter, no take side effect, and cleared unsaved detection preview');
  assert.equal(await scope.getByRole('button',{name:'任务清单',exact:true}).count(),0);
  await click('导入表格');const help=page.getByRole('dialog',{name:'录音任务表格格式'});await help.waitFor();assert((await help.innerText()).includes('每行是一条录音任务'));const downloaded=page.waitForEvent('download');await click('下载 CSV 示例');const sample=await downloaded;await sample.saveAs(path.join(out,'录音任务表格示例.csv'));assert((await fs.readFile(path.join(out,'录音任务表格示例.csv'),'utf8')).includes('录音内容'));await page.screenshot({path:path.join(out,'import-help.png'),fullPage:true});await click('关闭');checks.push('Import explains purpose, formats, required fields and downloadable Chinese CSV example; no task-list toggle');
  await scope.locator('input[type=file]').setInputFiles({name:'task.csv',mimeType:'text/csv',buffer:Buffer.from('task_id,prompt,filename_stem,repeat_count\nT01,合成验证 ɑ̃,test,2\nT02,可跳过,skip,1')});await page.getByRole('dialog',{name:'任务表格导入预览'}).waitFor();assert((await scope.innerText()).includes('展开后 3 条'));await click('确认导入');await click('保存清单');await idle();checks.push('CSV mapping preview, repeats and saved task list');
  await click('编辑');await scope.getByLabel('任务编号',{exact:true}).fill('CUSTOM');await click('完成编辑');await scope.getByLabel('录音任务与版本').getByRole('button',{name:'复制',exact:true}).click();await page.getByRole('dialog',{name:'编辑录音任务'}).waitFor();await click('完成编辑');await click('保存清单');await idle();assert((await scope.innerText()).includes('CUSTOM-copy'));checks.push('task id edits stay selected and Vue reactive task copying succeeds');
  await click('● 开始录音');await page.waitForTimeout(4500);await page.keyboard.press('Space');assert((await scope.innerText()).includes('正在录音'));await click('■ 停止录音');await scope.getByText('已存入本地工程，尚未导出',{exact:true}).waitFor();await idle();let p=JSON.parse(await fs.readFile(path.join(out,'project/project.json'),'utf8'));assert.equal(p.takes.length,1);assert.equal(p.takes[0].task_snapshot.id,'CUSTOM-copy');checks.push('Space during capture never stops recording; raw task identity correct');
  const full=previews.at(-1).value;assert(full.window_frames>48000*10);assert.equal(full.spectrum_window_frames,full.window_frames);assert.equal(full.spectrum.time_edges.at(-1),full.window_frames/48000);assert(Math.max(...full.spectrum.frequencies)<=5000);
  const pixels=await scope.locator('.m16-spectrum canvas').evaluate(c=>{const g=c.getContext('2d'),w=c.width,h=c.height;return [.01,.5,.99].map(x=>g.getImageData(Math.floor(w*x),Math.floor(h*.6),1,1).data[3]);});assert.deepEqual(pixels,[255,255,255]);
  const lane=await scope.locator('.m16-wave-lanes').boundingBox(),spectrogram=await scope.locator('.m16-spectrum').boundingBox();assert(Math.abs(lane.x-spectrogram.x)<1);assert(Math.abs(lane.width-spectrogram.width)<1);checks.push('Over 10 seconds spectrum covers complete waveform time, pixels at both ends, 0–5000 Hz');
  await page.mouse.move(spectrogram.x+spectrogram.width*.7,spectrogram.y+spectrogram.height*.6);await page.mouse.down();await page.mouse.move(spectrogram.x+spectrogram.width*.85,spectrogram.y+spectrogram.height*.6);await page.mouse.up();await click('放大选区');await page.waitForTimeout(500);const z=previews.at(-1);assert(z.value.start_frame>full.window_frames*.65);assert.equal(z.value.window_frames,z.request.end-z.request.start);assert.equal(await scope.locator('.selection').count(),2);await click('整段总览');await page.waitForTimeout(300);checks.push('Spectrogram pointer selection and waveform highlight share nonzero zoom range');
  await scope.getByLabel('起点（帧）',{exact:true}).fill('10');await scope.getByLabel('终点（帧）',{exact:true}).fill('20');await scope.getByLabel('终点（帧）',{exact:true}).blur();await click('删除选区');await idle();p=JSON.parse(await fs.readFile(path.join(out,'project/project.json'),'utf8'));assert.equal(p.takes[0].versions.length,2);await click('撤销');await idle();await click('恢复原始');await idle();checks.push('sample-exact edit, undo and raw restoration through production service');
  await click('▶ 播放');await scope.getByRole('button',{name:'■ 停止播放',exact:true}).waitFor();await scope.locator('.m16-wave').focus();await page.keyboard.press('Space');await scope.getByRole('button',{name:'▶ 播放',exact:true}).waitFor();await click('编辑');await scope.getByLabel('录音内容',{exact:true}).focus();await page.keyboard.press('Space');assert.equal(await scope.getByRole('button',{name:'■ 停止播放',exact:true}).count(),0);await click('完成编辑');checks.push('Space output stop and text-field focus guard');
  await scope.getByLabel('起点（帧）',{exact:true}).fill('0');await scope.getByLabel('终点（帧）',{exact:true}).fill('10000');await scope.getByLabel('终点（帧）',{exact:true}).blur();await click('将选区设为噪声样本');await idle();await click('整段降噪');await scope.getByText('后台处理已结束',{exact:true}).waitFor({timeout:90000});await idle();checks.push('real isolated-process denoise publishes validated derived version');
  await click('保存 / 批量导出');await click('选择目录并导出');await scope.getByText('已导出 1 / 1 条，详见导出清单',{exact:true}).waitFor();checks.push('real WAV output plus JSON/CSV manifest without upload');
  const controls=await scope.locator('.prompt-card .recording-controls button').allTextContents();assert.deepEqual(controls.map(s=>s.trim()),['● 重新录音','■ 停止录音','▶ 播放','下一条','跳过此条']);assert.equal(await scope.locator('.selection-toolbar .edit-toolbar').count(),1);
  const sizes=await scope.locator('.processing-channels input').evaluateAll(es=>es.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert(sizes.every(s=>s.w<=16&&s.h<=16));checks.push('Prominent ordered prompt-card controls, compact channel checks, edits follow selection controls');
  // Delay only delivery of a real job status to observe the progress UI.
  let held=false,release;const gate=new Promise(r=>release=r);const delay=async route=>{const b=route.request().postDataJSON();if(b.body?.op==='status'&&!held){held=true;const response=await route.fetch();await gate;await route.fulfill({response});}else await route.continue();};
  await page.route('**/__m16_host',delay);await click('应用增益');await scope.locator('.job-progress').waitFor();assert.equal(await scope.locator('.job-progress').innerText(),'×');assert((await scope.locator('.job-progress progress').boundingBox()).height<=5);await page.screenshot({path:path.join(out,'thin-progress.png'),fullPage:true});release();await scope.getByText('后台处理已结束',{exact:true}).waitFor({timeout:90000});await page.unroute('**/__m16_host',delay);checks.push('Real gain job has a four-pixel progress line with accessible cancellation and no status text');
  await click('● 重新录音');await page.waitForTimeout(350);await page.locator('nav').getByRole('button',{name:'国际音标表Plus',exact:true}).click();await page.waitForTimeout(150);await page.getByRole('button',{name:'录音',exact:true}).first().click();await scope.waitFor();assert((await scope.innerText()).includes('正在录音'));await click('■ 停止录音');await idle();p=JSON.parse(await fs.readFile(path.join(out,'project/project.json'),'utf8'));assert.equal(p.takes.length,2);checks.push('module navigation preserves ongoing capture and rerecord appends take');
  for(const [width,height,theme,zoom] of [[1920,1080,'light',1],[1440,900,'dark',1],[900,700,'light',1],[2560,1440,'dark',1],[1920,1080,'dark',1.35],[1280,800,'light',1.25]]){
   await page.setViewportSize({width,height});await page.evaluate(({theme,zoom})=>{document.documentElement.dataset.theme=theme;document.querySelector('.app-shell').style.zoom=zoom;},{theme,zoom});await page.waitForTimeout(200);
   const measured=await scope.evaluate(e=>{const main=e.querySelector('.recording-main'),bar=e.querySelector('.recording-controls'),buttons=[...bar.querySelectorAll('button')].map(b=>b.getBoundingClientRect().toJSON());return {main:{w:main.clientWidth,scroll:main.scrollWidth},buttons,chart:e.querySelector('.recording-chart').getBoundingClientRect().toJSON(),layoutBottom:e.querySelector('.recording-layout').getBoundingClientRect().bottom,statusBottom:e.querySelector('.recording-status').getBoundingClientRect().bottom,exportTop:e.querySelector('.export-results')?.getBoundingClientRect().top,checkboxes:[...e.querySelectorAll('.processing-channels input')].map(c=>c.getBoundingClientRect().toJSON())};});assert(measured.main.scroll<=measured.main.w+2);assert(measured.chart.height>=280);assert(measured.statusBottom<=measured.layoutBottom+1);if(measured.exportTop)assert(measured.layoutBottom<=measured.exportTop);
   for(let i=0;i<measured.buttons.length;i++)for(let j=i+1;j<measured.buttons.length;j++){const a=measured.buttons[i],b=measured.buttons[j];assert(!(a.left<b.right-1&&a.right>b.left+1&&a.top<b.bottom-1&&a.bottom>b.top+1));}
   layouts.push({width,height,theme,zoom,...measured});await page.screenshot({path:path.join(out,`${width}-${theme}-${zoom}.png`),fullPage:true});
   if(width===900){await scope.getByRole('button',{name:'应用增益',exact:true}).scrollIntoViewIfNeeded();const b=await scope.getByRole('button',{name:'应用增益',exact:true}).boundingBox();assert(b.y>=0&&b.y+b.height<=height);await page.screenshot({path:path.join(out,'900-scrolled-tools.png')});await scope.locator('.prompt-card').scrollIntoViewIfNeeded();}
  }checks.push('Six light/dark viewport and enlarged UI layouts without main overflow or overlapping primary controls');
  await page.evaluate(()=>document.querySelector('.app-shell').style.zoom=1);await page.setViewportSize({width:1920,height:1080});
  const old=JSON.parse(await fs.readFile(path.join(out,'project/project.json'),'utf8')),oldId=old.takes[0].task_snapshot.id;
  // Refused persistence must leave the visible task and recording untouched.
  const fail=async route=>{const b=route.request().postDataJSON();if(b.body?.op==='tasks')await route.fulfill({json:{ok:false,error:'M16-R3 injected save failure'}});else await route.continue();};await page.route('**/__m16_host',fail);await click('删除任务');await scope.getByText('M16-R3 injected save failure',{exact:true}).waitFor();assert(await scope.locator('.task-row').filter({hasText:oldId}).count());await page.unroute('**/__m16_host',fail);await click('删除任务');await idle();
  const deleted=JSON.parse(await fs.readFile(path.join(out,'project/project.json'),'utf8'));assert(!deleted.tasks.some(t=>t.id===oldId));assert.deepEqual(deleted.takes,old.takes);await page.reload();await scope.waitFor();await page.waitForTimeout(800);assert.equal(await scope.locator('.task-row').filter({hasText:oldId}).count(),0);assert.equal(await scope.locator('.take-select option').count(),old.takes.length+1);checks.push('Task deletion persists across reload, saves atomically, retains all takes, and failed persistence retains task');
  await click('＋ 新任务');await page.getByRole('dialog',{name:'编辑录音任务'}).waitFor();await scope.getByLabel('录音内容',{exact:true}).fill('新建任务不应显示上一条录音');await click('完成编辑');assert.equal(await scope.locator('.wave-lane').count(),0);assert.equal(await scope.getByRole('button',{name:'● 开始录音',exact:true}).count(),1);await click('删除任务');await idle();assert.equal(JSON.parse(await fs.readFile(path.join(out,'project/project.json'),'utf8')).tasks.length,deleted.tasks.length);checks.push('New task clears prior recording view, and deleting the unsaved new task persists the remaining list');
  assert.deepEqual(errors,[]);assert.deepEqual(network,[]);success=true;
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}
 finally{await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify({success,checks,errors,network,layouts,scope:'Real Chrome + production desktop adapter/service; QWebChannel substituted; synthetic PortAudio only'},null,2));console.log(JSON.stringify({success,checks}));await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
