// P17 real-only current-source Chrome integration. Owned processes and ports.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m14/Scripts/python.exe'),['-X','utf8','scripts/p17_m01_m05_bridge.py'],{cwd:root,windowsHide:true});
 const pending=new Map();let counter=0,resolveReady,rejectReady;const ready=new Promise((r,j)=>{resolveReady=r;rejectReady=j;});
 createInterface({input:worker.stdout}).on('line',line=>{try{const v=JSON.parse(line);if(v.ready)resolveReady(v);else{pending.get(v.id)?.(v);pending.delete(v.id);}}catch(e){console.error(line);}});worker.stderr.on('data',d=>process.stderr.write(d));worker.on('error',rejectReady);worker.once('exit',code=>rejectReady(Error('bridge exited '+code)));
 const info=await ready,{out,short}=info;console.log(out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),cacheDir:path.join(out,'vite-cache'),server:{host:'127.0.0.1',port:0,hmr:false},optimizeDeps:{entries:['tests/p17-m01-m05.html']},plugins:[{name:'p17a',configureServer(s){s.middlewares.use('/__p17a',(req,res)=>{let body='';req.on('data',d=>body+=d);req.on('end',()=>{const id=++counter;pending.set(id,v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v));});worker.stdin.write(JSON.stringify({...JSON.parse(body),rpc_id:id})+'\n');});});}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1920,height:1000}}),page=await context.newPage();const report={out,short,checks:[],timings:[],layouts:[],errors:[],warnings:[]};
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='warning')report.warnings.push(m.text().slice(0,250));});
 const click=name=>page.getByRole('button',{name,exact:true}).first().click();
 const timing=async(name,action,condition)=>{const start=performance.now();await action();await condition();const ms=performance.now()-start;report.timings.push({name,ms});console.log(name,ms.toFixed(1));};
 const geometry=async(mid,state)=>{await page.locator({M01:'.m01-page',M02:'.m02-page',M03:'.egg-page',M04:'.lpc-page',M05:'.lip-page'}[mid]).waitFor();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const data=await page.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio,plots:[...document.querySelectorAll('.scientific-plot > svg,.parameter-chart,.wave-track svg,.lip-video')].filter(e=>e.getBoundingClientRect().width).map(e=>({class:e.getAttribute('class'),height:e.getBoundingClientRect().height,internal:e.querySelector('clipPath rect')?.getAttribute('height')})),panels:[...document.querySelectorAll('.module-frame,.module-workbench,.workbench-left,.workbench-center,.workbench-right-body,.signal-panel,.egg-four-plots')].filter(e=>e.getBoundingClientRect().width).map(e=>({class:e.className,height:e.clientHeight,scroll:e.scrollHeight,top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom}))}));report.layouts.push({mid,state,...data});await page.screenshot({path:path.join(out,mid+'-'+state+'.png'),fullPage:true});};
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/p17-m01-m05.html');
  if(process.env.P17_REMAINING_ONLY==='1'){await require('./p17-m01-m05-remaining.cjs')({page,click,report,short,out});return;}
  for(const [mid,name] of [['M01','参数估计'],['M02','参数显示'],['M03','EGG 信号分析'],['M04','LPC 谱图'],['M05','唇形提取']]){await click(name);await geometry(mid,'empty');}
  await click('参数估计');await click('选择音频目录');await page.locator('.m01-file-entry').first().waitFor();
  await timing('M01 short wave',()=>page.locator('.m01-file-list .file-row').filter({hasText:short}).click(),()=>page.locator('.m01-page .wave-track').first().waitFor());
  await page.waitForFunction(()=>document.querySelectorAll('.m01-tiers option').length>0);await geometry('M01','data');report.checks.push('M01 real WAV and UTF16 TextGrid load');
  await click('编辑14项设置');assert.equal(await page.locator('.m01-settings input').count(),10);await page.getByLabel('帧移',{exact:true}).fill('0');await click('应用设置');await page.getByRole('alert').waitFor();await page.getByLabel('帧移',{exact:true}).fill('10');await click('REAPER设置 · 4');assert.equal(await page.locator('.m01-settings input').count(),4);await click('应用设置');await click('保存草稿');report.checks.push('M01 14 settings, invalid frame step rejection and saved draft');
  await click('选择输出参数');await click('全不选');assert(await page.getByRole('button',{name:'应用到草稿',exact:true}).isDisabled());await click('全选');await click('应用到草稿');
  if(!process.env.P17_UI_ONLY){
  await page.getByLabel('结果与WAV同目录',{exact:true}).uncheck();await click('选择结果目录');
  await timing('M01 first successful analysis in 3-file batch',()=>click('开始全列表分析'),()=>page.getByText('1 / 3 已完成',{exact:true}).waitFor({timeout:120000}));await page.getByText(/已保存/).first().waitFor({timeout:90000});report.checks.push('M01 one real recording analyzed; two long EGG recordings rejected by sample budget; completed output saved');
  await page.locator('.m01-file-list .file-row').filter({hasText:short}).click();await page.waitForFunction(()=>document.querySelectorAll('.m01-tiers option').length>0);await page.getByLabel('同时切分参数结果',{exact:true}).check();await timing('M01 real segmentation with parameter parent',()=>click('保存当前层切分音频'),()=>page.getByText('1 / 1 已完成',{exact:true}).waitFor({timeout:120000}));await page.getByText(/已保存/).first().waitFor({timeout:90000});report.checks.push('M01 real TextGrid segmentation with source-matched parameter results');
  }
  await click('参数显示');await click('选择音频目录');await timing('M02 short wave and table',()=>page.locator('.m02-files button').filter({hasText:short}).click(),()=>page.locator('.m02-page .wave-track').first().waitFor());await page.waitForFunction(()=>!document.querySelector('.m02-page > p[role=status]'));
  await page.locator('.m02-parameters input').first().waitFor();assert.equal(await page.locator('.parameter-curve').count(),0);await page.locator('.m02-parameters input').first().check();await click('将 1 项分配到图窗');await page.locator('.parameter-curve').waitFor();await geometry('M02','data');
  await click('新建图窗');await click('将 1 项分配到图窗');assert.equal(await page.locator('.parameter-curve').count(),1);await click('清空选定图窗');assert.equal(await page.locator('.parameter-curve').count(),0);await click('删除选定图窗');assert.equal(await page.locator('.parameter-figure').count(),1);await click('将 1 项分配到图窗');await click('保存绘图配置');
  for(const label of ['保存当前图','保存整幅 PNG']){const downloaded=page.waitForEvent('download');await click(label);const d=await downloaded;await d.saveAs(path.join(out,'M02-'+d.suggestedFilename()));}report.checks.push('M02 first empty figure, explicit assignment, create/clear/delete and two actual PNG exports');
  await click('EGG 信号分析');await click('打开 WAV 目录');
  const idle=()=>page.waitForFunction(()=>document.querySelector('.egg-live-status')?.textContent==='实时预览',{},{timeout:90000});
  await timing('M03 EGG first display',()=>page.getByLabel('EGG 音频文件').selectOption({label:'EGG-real.wav'}),idle);await geometry('M03','data');
  const fill=async(label,value)=>{await page.getByLabel(label).fill(String(value));await page.getByLabel(label).press('Tab');};
  await fill('EGG 选区起点',40);await fill('EGG 选区时长',.5);await idle();
  for(let i=0;i<20;i++)await timing('M03 micro '+i,()=>fill('EGG 微观窗口',i%2?50:100),idle);
  report.checks.push('M03 20 real micro recalculations');
  for(const area of ['cq','spec','audio','egg']){const svg=page.locator('.'+area+'-pane svg');const b=await svg.boundingBox();await page.mouse.move(b.x+b.width*.5,b.y+b.height*.5);await page.mouse.wheel(0,-120);await idle();await page.mouse.down();await page.mouse.move(b.x+b.width*.6,b.y+b.height*.5,{steps:4});await page.mouse.up();await idle();await svg.focus();await page.keyboard.press('ArrowRight');await idle();}report.checks.push('M03 all four plots wheel drag and keyboard');
  await fill('EGG 选区起点',40);await fill('EGG 选区时长',.5);await idle();await click('逆滤波 IF');await page.locator('.inverse-grid svg').first().waitFor({timeout:90000});assert.equal(await page.locator('.inverse-grid svg').count(),4);await click('选择目录保存完整结果');await page.locator('dialog').getByText(/已保存/).waitFor();const png=page.waitForEvent('download');await click('保存四图 PNG');await (await png).saveAs(path.join(out,'M03-inverse-four.png'));for(let n=0;n<4;n++){const p=page.waitForEvent('download');await page.getByRole('button',{name:'保存此图 PNG',exact:true}).nth(n).click();await(await p).saveAs(path.join(out,'M03-inverse-'+n+'.png'));}await page.locator('dialog summary').first().click();await page.locator('dialog summary').first().click();await click('返回分析');report.checks.push('M03 real IF four charts, ORIG/IF and PNG export');
  await click('保存 CSV / 三图');if(!await page.locator('.egg-history').evaluate(e=>e.open))await page.locator('.egg-history summary').click();await page.waitForFunction(()=>document.querySelectorAll('.egg-result-links button').length>=2,{},{timeout:90000});await page.locator('.egg-result-links button').first().click();await page.locator('dialog .egg-export-image').first().waitFor();await click('选择目录保存完整结果');await page.locator('dialog').getByText(/已保存/).waitFor();await click('返回分析');report.checks.push('M03 real CSV and three-image task, history and save');
  await click('LPC 谱图');await click('打开 WAV 目录');await timing('M04 short wave',()=>page.getByLabel('LPC 音频文件').selectOption({label:short}),()=>page.locator('.lpc-page .wave-track').first().waitFor());await geometry('M04','data');
  await page.waitForFunction(()=>document.querySelector('select[aria-label="LPC 标注层"]').value!=='');await page.getByLabel('LPC 选区起点').fill('.2');await page.getByLabel('LPC 选区终点').fill('.4');
  await timing('M04 analysis',()=>click('开始分析'),()=>page.locator('.lpc-spectrum:visible svg').waitFor({timeout:90000}));await geometry('M04','result');await click('选择目录保存完整结果');await page.getByText(/已保存 3 个结果文件/).waitFor();report.checks.push('M04 real LPC calculation and 3-file native save');
  await require('./p17-m01-m05-extra.cjs')({page,click,report,out,geometry,short});
  for(const [mid,name] of [['M01','参数估计'],['M02','参数显示'],['M03','EGG 信号分析'],['M04','LPC 谱图'],['M05','唇形提取']]){await click(name);await page.setViewportSize({width:1280,height:720});await geometry(mid,'small');await page.setViewportSize({width:1920,height:1000});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await geometry(mid,'dark');await page.evaluate(()=>document.documentElement.dataset.theme='light');for(const [width,height] of [[2560,1360],[3840,2080]]){await page.setViewportSize({width,height});await geometry(mid,'large-'+width);}await page.setViewportSize({width:1920,height:1000});}
  await require('./p17-m01-m05-tail.cjs')({page,click,report});
  await require('./p17-m01-m05-extra.cjs').closeDrafts({page,click,report});
 }catch(e){report.failure=String(e.stack);await page.screenshot({path:path.join(out,'failed.png'),fullPage:true});console.error(await page.locator('main').innerText().catch(()=>page.locator('body').innerText()));throw e;}
 finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({out,checks:report.checks,errors:report.errors,failure:report.failure},null,2));await browser.close();await server.close();worker.stdin.write(JSON.stringify({op:'shutdown',rpc_id:++counter})+'\n');await new Promise(resolve=>worker.once('exit',resolve));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
