// P17: real recording supplied by P17_AUDIO; UI checkbox simulation does not verify hearing or physical audio timing.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){const out=path.join(root,'output/validation/p17/M15',String(Date.now()));await fs.mkdir(out,{recursive:true});
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0}});await server.listen();const base=server.resolvedUrls.local[0];const source=process.env.P17_AUDIO;if(!source)throw Error('P17_AUDIO real recording required');const real=await fs.readFile(source);
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1920,height:1000},acceptDownloads:true});let page=await context.newPage();const checks=[],errors=[],external=[],exports=[];function observe(p){p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(base))external.push(r.url());});p.on('dialog',d=>d.accept());}observe(page);
 const waitPhase=async p=>page.locator(`.m15-run[data-phase="${p}"]`).waitFor({timeout:20000});
 async function open(){await page.goto(base);await page.locator('.nav-item').filter({hasText:'感知实验'}).click();await page.locator('.perception-page').waitFor();}
 async function prepare(paradigm='X',files){await open();await page.getByLabel('实验范式',{exact:true}).selectOption(paradigm);const rs={X:['X'],AX:['A','X'],ABX:['A','B','X'],AXB:['A','X','B']}[paradigm];for(const [i,r] of rs.entries()){await page.getByLabel('导入刺激 '+r,{exact:true}).setInputFiles(files??[{name:r+'.wav',mimeType:'audio/wav',buffer:real}]);await page.getByRole('button',{name:'预检与试音',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('.perception-page').getAttribute('aria-busy')==='false');}
 await page.getByRole('tab',{name:'参数',exact:true}).click();await page.getByLabel('ISI 毫秒',{exact:true}).fill('0');await page.getByLabel('试次间隔毫秒',{exact:true}).fill('0');await page.getByLabel('提示音',{exact:true}).uncheck();await page.getByRole('button',{name:'预检与试音',exact:true}).click();await page.getByText(/预检通过/).waitFor();await page.getByLabel('已听见试音，设备正确').check();await page.getByLabel('已暂停其他录制、播放及重型任务').check();}
 async function questionnaire(){await page.getByRole('button',{name:'填写被试信息',exact:true}).click();await page.getByLabel('姓名/编号',{exact:true}).fill('P17 自动化会话 IPA a̠');await page.getByLabel('女',{exact:true}).check();await page.getByRole('button',{name:'建立独立会话',exact:true}).click();await waitPhase('intro');}
 async function readDownload(button,name){const waiting=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const d=await waiting;const file=path.join(out,name);await d.saveAs(file);return file;}
 try{
 for(const paradigm of ['X','AX','ABX','AXB']){await prepare(paradigm);await questionnaire();await context.setOffline(true);await page.getByRole('button',{name:'开始实验',exact:true}).click();await waitPhase('playing');await page.keyboard.press('f');await waitPhase('responding');await page.keyboard.press('j');await waitPhase('completed');const file=await readDownload('完整溯源 JSON',paradigm+'.json'),s=JSON.parse(await fs.readFile(file,'utf8'));exports.push(s);assert.equal(s.attempts.length,1);const a=s.attempts[0];assert.equal(a.status,'completed');assert.deepEqual(a.order,{X:['X'],AX:['A','X'],ABX:['A','B','X'],AXB:['A','X','B']}[paradigm]);assert.deepEqual(a.timing.planned.map(x=>x.role),a.order);assert.equal(a.key,'j');assert(a.rtMs>=0);assert(a.timing.responseOpenPerfMs>=a.timing.endDetectedPerfMs);assert(a.roles.X.originalSampleRate>0);assert(a.roles.X.channels>0);for(let i=1;i<a.timing.planned.length;i++)assert.equal(a.timing.planned[i].startAudioSeconds,a.timing.planned[i-1].endAudioSeconds);assert.equal(s.answers.q1,'P17 自动化会话 IPA a̠');assert.equal(s.finalTrialOrder.length,1);checks.push(paradigm+' official AppShell offline playback, zero ISI, no early answer, full-role export');
 if(paradigm==='AXB'){await readDownload('兼容 XLSX','results.xlsx');await readDownload('兼容 CSV','results.csv');const {read,utils}=await import(pathToFileURL(path.join(root,'frontend/src/modules/perception/vendor/xlsx.mjs')));const wb=read(await fs.readFile(path.join(out,'results.xlsx')));assert.equal(utils.sheet_to_json(wb.Sheets.Results)[0].Paradigm,'AXB');checks.push('actual downloaded XLSX and CSV reread');}
 await page.getByRole('button',{name:'确认导出文件已保存',exact:true}).click();await page.getByText('已记录用户确认保存文件').waitFor();await context.setOffline(false);await page.close();page=await context.newPage();observe(page);
 }
 await prepare('X',[{name:'字.txt',mimeType:'text/plain',buffer:Buffer.from('汉语 a̠ ŋ ɹ')}]);await questionnaire();await context.setOffline(true);await page.getByRole('button',{name:'开始实验',exact:true}).click();await waitPhase('responding');assert.equal(await page.locator('.m15-presentation pre').innerText(),'汉语 a̠ ŋ ɹ');await page.screenshot({path:path.join(out,'focus-text-light.png')});await page.keyboard.down('j');await page.keyboard.down('j');await page.keyboard.up('j');await waitPhase('completed');const text=JSON.parse(await fs.readFile(await readDownload('完整溯源 JSON','text.json'),'utf8'));assert.equal(text.attempts.length,1);assert(text.attempts[0].timing.visualFramePerfMs<=text.attempts[0].timing.responseOpenPerfMs);checks.push('text decoded before two-frame response gate, repeat does not double-answer');await context.setOffline(false);await page.close();page=await context.newPage();observe(page);
 await prepare();await questionnaire();await page.getByRole('button',{name:'开始实验',exact:true}).click();await waitPhase('responding');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await waitPhase('paused');const partial=JSON.parse(await fs.readFile(await readDownload('完整溯源 JSON','partial.json'),'utf8'));assert.equal(partial.attempts[0].status,'interrupted');assert.equal(partial.attempts[0].rtMs,null);await page.getByRole('button',{name:'明确继续 / 重新呈现',exact:true}).click();await waitPhase('responding');await page.keyboard.press('f');await waitPhase('completed');const retried=JSON.parse(await fs.readFile(await readDownload('完整溯源 JSON','retried.json'),'utf8'));assert.deepEqual(retried.attempts.map(a=>a.status),['interrupted','completed']);assert.equal(retried.attempts[1].attempt,2);checks.push('blur marks interrupted and explicit replay retains both attempts');
 await page.getByRole('button',{name:'返回设计器',exact:true}).click();await page.getByRole('tab',{name:'资源与恢复',exact:true}).click();await page.getByRole('button',{name:'刷新本机记录',exact:true}).click();assert(await page.getByRole('button',{name:'恢复 / 导出会话',exact:true}).count()>=6);await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:path.join(out,'design-dark.png'),fullPage:true});await page.setViewportSize({width:900,height:700});await page.evaluate(()=>document.documentElement.style.zoom='1.5');await page.screenshot({path:path.join(out,'design-dark-150.png'),fullPage:true});checks.push('dark theme, 150 percent small-window layout and recoverable session inventory');
 await page.setViewportSize({width:1920,height:1000});await page.evaluate(()=>document.documentElement.style.zoom='1');await require('./p17-m15-extra.cjs')({page,prepare,questionnaire,waitPhase,readDownload,checks});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await fs.writeFile(path.join(out,'report.json'),JSON.stringify({checks,errors,external,browser:await browser.version(),physicalTimingMeasured:false},null,2));console.log(out);
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});await fs.writeFile(path.join(out,'failure.txt'),String(e)+'\n'+await page.locator('body').innerText());throw e;}finally{await browser.close();await server.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
