// P17 real-only current-source Chrome integration. Owned processes and ports.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m14/Scripts/python.exe'),['-X','utf8','scripts/p17_m04_r2_bridge.py'],{cwd:root,windowsHide:true});
 const pending=new Map();let counter=0,resolveReady,rejectReady;const ready=new Promise((r,j)=>{resolveReady=r;rejectReady=j;});
 createInterface({input:worker.stdout}).on('line',line=>{try{const v=JSON.parse(line);if(v.ready)resolveReady(v);else{pending.get(v.id)?.(v);pending.delete(v.id);}}catch(e){console.error(line);}});worker.stderr.on('data',d=>process.stderr.write(d));worker.on('error',rejectReady);worker.once('exit',code=>rejectReady(Error('bridge exited '+code)));
 const info=await ready,{out,short}=info;console.log(out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),cacheDir:path.join(out,'vite-cache'),server:{host:'127.0.0.1',port:0,hmr:false},optimizeDeps:{entries:['tests/p17-m01-m05.html']},plugins:[{name:'p17a',configureServer(s){s.middlewares.use('/__p17a',(req,res)=>{let body='';req.on('data',d=>body+=d);req.on('end',()=>{const id=++counter;pending.set(id,v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v));});worker.stdin.write(JSON.stringify({...JSON.parse(body),rpc_id:id})+'\n');});});}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1920,height:1000}}),page=await context.newPage();const report={out,short,checks:[],timings:[],layouts:[],errors:[],warnings:[]};
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='warning')report.warnings.push(m.text().slice(0,250));});
 const click=name=>page.getByRole('button',{name,exact:true}).first().click();
 const timing=async(name,action,condition)=>{const start=performance.now();await action();await condition();const ms=performance.now()-start;report.timings.push({name,ms});console.log(name,ms.toFixed(1));};
 const geometry=async(mid,state)=>{await page.locator({M01:'.m01-page',M02:'.m02-page',M03:'.egg-page',M04:'.lpc-page',M05:'.lip-page'}[mid]).waitFor();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const data=await page.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio,plots:[...document.querySelectorAll('.scientific-plot > svg,.parameter-chart,.wave-track svg,.lip-video')].filter(e=>e.getBoundingClientRect().width).map(e=>({class:e.getAttribute('class'),height:e.getBoundingClientRect().height,internal:e.querySelector('clipPath rect')?.getAttribute('height')})),panels:[...document.querySelectorAll('.module-frame,.module-workbench,.workbench-left,.workbench-center,.workbench-right-body,.signal-panel,.egg-four-plots')].filter(e=>e.getBoundingClientRect().width).map(e=>({class:e.className,height:e.clientHeight,scroll:e.scrollHeight,top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom}))}));report.layouts.push({mid,state,...data});await page.screenshot({path:path.join(out,mid+'-'+state+'.png'),fullPage:true});};
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/p17-m01-m05.html');await click('LPC 谱图');await click('打开 WAV 目录');await page.getByLabel('LPC 音频文件').selectOption({label:short});await page.locator('.lpc-page .wave-track svg').waitFor();await page.waitForFunction(()=>document.querySelector('select[aria-label="LPC 标注层"]').value!=='');
  assert.equal(await page.locator('.workbench-left input[aria-label="LPC 选区起点"]').count(),0);assert.equal(await page.locator('.workbench-right .lpc-analysis-settings input[aria-label="LPC 选区起点"]').count(),1);
  await page.getByLabel('LPC 选区起点').fill('.2');await page.getByLabel('LPC 选区终点').fill('.4');
  await require('./p17-m04-alignment.cjs')({page,report,out});
  for(const [width,height] of [[1920,1000],[2560,1360],[3840,2080]]){await page.setViewportSize({width,height});await geometry('M04','wave-'+width);await page.getByLabel('显示语谱图（Praat）').check();await page.locator('.spectrogram-canvas canvas').waitFor();await page.waitForTimeout(180);await geometry('M04','spectrogram-'+width);await page.getByLabel('显示语谱图（Praat）').uncheck();}
  await page.setViewportSize({width:1920,height:1000});await timing('LPC real task',()=>click('开始分析'),()=>page.locator('.lpc-spectrum:visible svg').waitFor({timeout:90000}));
  for(const [width,height] of [[1920,1000],[2560,1360],[3840,2080]]){await page.setViewportSize({width,height});await geometry('M04','result-'+width);}
  await page.setViewportSize({width:1920,height:1000});const dl=page.waitForEvent('download');await click('保存 PNG 图片');const image=await dl;await image.saveAs(path.join(out,'direct-'+image.suggestedFilename()));report.checks.push('R2 direct actual task PNG browser download');
  const fail=async route=>{const body=route.request().postDataJSON();if(body.op==='result')await route.fulfill({json:{error:'P17 controlled PNG read failure'}});else await route.continue();};await page.route('**/__p17a',fail);await click('保存 PNG 图片');await page.locator('.lpc-page [role=alert]').waitFor();await page.unroute('**/__p17a',fail);const again=page.waitForEvent('download');await click('保存 PNG 图片');await(await again).saveAs(path.join(out,'recovered.png'));assert.equal(await page.locator('.lpc-page [role=alert]').count(),0);report.checks.push('R2 PNG read failure feedback and successful real-byte retry');
  await click('选择目录保存完整结果');await page.getByText(/已保存 3 个结果文件/).waitFor();report.checks.push('R2 complete native result directory remains available');
  const {createHash}=require('node:crypto');const hash=async p=>createHash('sha256').update(await fs.readFile(p)).digest('hex');const walk=async d=>(await Promise.all((await fs.readdir(d,{withFileTypes:true})).map(e=>e.isDirectory()?walk(path.join(d,e.name)):Promise.resolve([path.join(d,e.name)])))).flat();const png=(await walk(path.join(out,'saved'))).find(p=>p.endsWith('.png'));assert(png);assert.equal(await hash(png),await hash(path.join(out,'direct-'+image.suggestedFilename())));assert.equal(await hash(png),await hash(path.join(out,'recovered.png')));report.checks.push('R2 PNG direct/full/retry SHA256 identical');
  await click('波形');await page.setViewportSize({width:1280,height:720});await geometry('M04','small');
 }catch(e){report.failure=String(e.stack);await page.screenshot({path:path.join(out,'failed.png'),fullPage:true});throw e;}
 finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({out,checks:report.checks,errors:report.errors,failure:report.failure},null,2));await browser.close();await server.close();worker.stdin.write(JSON.stringify({op:'shutdown',rpc_id:++counter})+'\n');await new Promise(resolve=>worker.once('exit',resolve));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
