const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn,execFileSync}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const baseline=process.argv.includes('--baseline'),stamp=new Date().toISOString().replace(/[:.]/g,'-'),out=path.join(root,'output/validation/p17/M08',(baseline?'baseline-':'browser-')+stamp);
 const inputs=JSON.parse(await fs.readFile(process.argv[2],'utf8'));
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','scripts/p17_m06_m09_host.py','--out',out,'--inputs',...inputs],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','packages/phonetic_core/src','desktop/src','scripts'].map(p=>path.join(root,p)).join(';')}});
 let readyResolve,readyReject,counter=0;const pending=new Map(),ready=new Promise((r,j)=>{readyResolve=r;readyReject=j});
 createInterface({input:worker.stdout}).on('line',line=>{try{const d=JSON.parse(line);if(d.ready)readyResolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id)}}catch(e){readyReject(e)}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>readyReject(Error('Host exited '+code)));
 const info=await ready;console.log(out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const plugins=[{name:'p17-real-host',enforce:'pre',load(id){if(baseline&&id.replaceAll('\\','/').endsWith('/modules/pitch-manipulation/PitchManipulationPage.vue'))return execFileSync('git',['show','0779bee:frontend/src/modules/pitch-manipulation/PitchManipulationPage.vue'],{cwd:root,encoding:'utf8'})},transform(code,id){if(id.replaceAll('\\','/').endsWith('/platform/decode.ts'))return code.replace('return new Promise((resolve,reject)=>{','const p17Started=performance.now();return new Promise((resolve,reject)=>{').replace('worker.onmessage=event=>{cleanup();','worker.onmessage=event=>{((globalThis as any).__p17DecodeStages??=[]).push({name,ms:performance.now()-p17Started});cleanup();');},configureServer(s){s.middlewares.use('/__m08_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter;pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))});worker.stdin.write(JSON.stringify({...JSON.parse(raw),id})+'\n')})})}}];
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},optimizeDeps:{entries:['tests/m08-host.html']},plugins});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1920,height:1000}}),checks=[],errors=[],timings=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(90000);
 let success=false,active='M08';const reports={};for(const m of ['M06','M07','M08','M09']){const dir=m==='M08'?out:path.join(root,'output/validation/p17',m,'browser-'+stamp);await fs.mkdir(dir,{recursive:true});reports[m]={dir,checks:[],geometry:[]};}
 const click=name=>page.getByRole('button',{name,exact:true}).filter({visible:true}).click(),open=async(name,m)=>{await page.locator('nav').getByRole('button',{name,exact:true}).click();active=m;},idle=()=>page.waitForFunction(()=>[...document.querySelectorAll('.module-frame')].filter(x=>x.offsetParent).every(x=>x.getAttribute('aria-busy')!=='true'));
 async function evidence(name){await page.waitForTimeout(150);const g=await page.evaluate(()=>{const e=[...document.querySelectorAll('.module-frame')].find(x=>x.offsetParent),r=e.getBoundingClientRect(),anc=[];for(let p=e.parentElement;p;p=p.parentElement)anc.push({class:p.className,scroll:p.scrollHeight,client:p.clientHeight,top:p.scrollTop});return{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,rect:{top:r.top,bottom:r.bottom,height:r.height},scroll:e.scrollHeight,client:e.clientHeight,anc}});reports[active].geometry.push({name,...g});await page.screenshot({path:path.join(reports[active].dir,name+'.png'),fullPage:true});}
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m08-host.html');await open('变速变调','M08');await evidence('empty');await click('打开音频目录');const select=page.getByLabel('M08 音频');
  const options=await select.locator('option').evaluateAll(a=>a.filter(x=>x.value).map(x=>({value:x.value,name:x.textContent})));
  for(const idx of (process.argv.includes('--long-first')?[2,0,2,1]:[0,1,0,2])){
   const decodeBefore=await page.evaluate(()=>(globalThis.__p17DecodeStages??[]).length);const t=Date.now();await select.selectOption(options[idx].value);await page.locator('.m08-page .wave-track svg').first().waitFor({timeout:60000}).catch(async()=>await page.locator('.m08-page .wave-track svg').first().waitFor());const waveMs=Date.now()-t;
   await page.locator('.m08-curve').waitFor();await idle();timings.push({source:idx,phase:timings.length?'warm':'cold',wave_ms:waveMs,f0_and_history_ms:Date.now()-t,decode_stages:await page.evaluate(n=>(globalThis.__p17DecodeStages??[]).slice(n),decodeBefore)});console.log(timings.at(-1));
  }
  await evidence('loaded-long');if(baseline||process.argv.includes('--loading-only')){success=true;return;}
  await select.selectOption(options[0].value);await page.locator('.m08-curve').waitFor();await idle();
  await page.getByLabel('F0 下限',{exact:true}).fill('400');await click('应用范围');await page.getByRole('alert').filter({visible:true}).waitFor();await page.getByLabel('F0 下限',{exact:true}).fill('50');await click('应用范围');
  await page.getByLabel('参考线 Hz',{exact:true}).fill('200');await click('添加参考线');await click('清除参考线');
  const dragMs=[];const svg=page.locator('svg.m08-curve');for(let i=0;i<20;i++){const b=await svg.boundingBox();const t=Date.now();await page.keyboard.down('Shift');await page.mouse.move(b.x+b.width*.25,b.y+b.height*.5);await page.mouse.down();await page.mouse.move(b.x+b.width*.65,b.y+b.height*.4,{steps:4});await page.mouse.up();await page.keyboard.up('Shift');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));dragMs.push(Date.now()-t)}reports.M08.drag_ms=dragMs;
  await click('合成当前视野');await page.getByText(/源区间 .*输出 /).waitFor();await idle();await click('保存并编号');await idle();await evidence('result');reports.M08.checks.push('real preview cold/warm short/long','F0 invalid axis recovery','reference add/clear','20 Shift gestures','real synthesis and native numbered save');
  await page.locator('summary').filter({hasText:'本批次与历史文件'}).click();await page.locator('.history li').first().waitFor();const down=page.waitForEvent('download');await click('下载合成音');await(await down).saveAs(path.join(out,'download.wav'));await page.locator('summary').filter({hasText:'本批次与历史文件'}).click();
  await click('保存编辑草稿');
  await open('语音合成','M06');await evidence('empty');await page.getByLabel('总时长',{exact:true}).fill('0.6');await click('应用时长');await page.getByLabel('IPA 元音序列',{exact:true}).fill('a i');await click('生成元音');await page.getByText('元音曲线已生成，请点击合成生成音频',{exact:true}).waitFor();await click('合成音频');await page.getByText('合成完成，试听与导出绑定本次参数快照',{exact:true}).waitFor();await click('导出音频');await evidence('result');reports.M06.checks.push('product vowel generation and real Klatt synthesis','native WAV snapshot export');
  await click('打开音频目录');await page.locator('select[aria-label="源音频"]').filter({visible:true}).selectOption({label:'真实录音1.wav'});await click('应用并覆盖');await page.getByText('参数提取完成。复制合成效果有限，请检查曲线后合成',{exact:true}).waitFor();await evidence('real-source-extracted');reports.M06.checks.push('real recording parameter extraction');await click('保存参数草稿');
  await open('发声类型合成','M07');await evidence('empty');await click('打开音频目录');await page.locator('select[aria-label="源音频"]').filter({visible:true}).selectOption({label:'真实录音1.wav'});await page.locator('select[aria-label="目标音频"]').filter({visible:true}).selectOption({label:'真实录音2.wav'});await page.getByRole('button',{name:'提取 F0',exact:true}).waitFor();await click('提取 F0');await page.getByText('分析完成，控制点尚未修改',{exact:true}).waitFor();await evidence('analyzed');await page.getByLabel('连续统步数',{exact:true}).fill('3');await click('生成全部六组');await page.getByText('生成完成，试听和保存绑定各组已应用快照',{exact:true}).waitFor({timeout:180000});await evidence('six-groups');reports.M07.checks.push('real source and target decode','Praat/LPC real analysis','six directions/types generated with three steps each');
  await page.locator('summary').filter({hasText:'任务与结果'}).click();await page.getByRole('button',{name:'保存完整组',exact:true}).first().click();await page.getByText('已保存本组完整文件和参数清单',{exact:true}).waitFor();reports.M07.checks.push('complete native group export');await page.locator('summary').filter({hasText:'任务与结果'}).click();await click('保存参数草稿');
  await open('语谱图转音频','M09');await evidence('empty');await click('选择图片目录');await page.getByLabel('语谱图图片').selectOption({label:'真实录音语谱图.png'});await page.locator('img[alt="待校正语谱图"]').waitFor();await page.getByLabel('时间终点（s）').fill(String(info.manifest[0].duration));await page.getByLabel('频率终点（Hz）').fill(String(info.manifest[0].rate/2));await click('开始重建');await page.getByRole('button',{name:'保存重建结果',exact:true}).waitFor();await click('保存重建结果');await page.getByText(/已保存 4 个结果文件/).waitFor();await evidence('result');reports.M09.checks.push('spectrogram derived from authorized real recording','32 iteration reconstruction','four artifact native save');
  if(process.argv.includes('--extended'))await require('./p17-m06-m09-controls.cjs')({page,open,click,idle,reports,evidence});
  if(process.argv.includes('--recovery'))await require('./p17-m06-m09-recovery.cjs')({page,open,click,idle,reports,evidence});
  for(const [label,m] of [['变速变调','M08'],['语音合成','M06'],['发声类型合成','M07'],['语谱图转音频','M09']]){await open(label,m);await page.evaluate(()=>document.documentElement.dataset.theme='dark');await evidence('dark');await page.evaluate(()=>document.documentElement.dataset.theme='light');await page.setViewportSize({width:1366,height:768});await evidence('1366');await page.setViewportSize({width:1280,height:720});await evidence('small');await page.setViewportSize({width:1920,height:1000});await evidence('three-column');const frame=page.locator('.module-frame').filter({visible:true});const before=await frame.evaluate(e=>({top:e.scrollTop,scroll:e.scrollHeight,client:e.clientHeight}));await page.mouse.move(900,500);await page.mouse.wheel(0,400);await page.waitForTimeout(200);const after=await frame.evaluate(e=>e.scrollTop);assert.equal(after,before.top);reports[m].checks.push('ordinary wheel leaves module page fixed at 1920x1000');for(const v of [{width:2560,height:1360},{width:3840,height:2080}]){await page.setViewportSize(v);await evidence('large-'+v.width);}await page.setViewportSize({width:1920,height:1000});}
  if(process.argv.includes('--recovery')){await open('语音合成','M06');await click('保存参数草稿');const duration=await page.getByLabel('总时长',{exact:true}).inputValue(),ipa=await page.getByLabel('IPA 元音序列',{exact:true}).inputValue();await page.getByRole('button',{name:'关闭 语音合成',exact:true}).click();await open('语音合成','M06');assert.equal(await page.getByLabel('总时长',{exact:true}).inputValue(),duration);assert.equal(await page.getByLabel('IPA 元音序列',{exact:true}).inputValue(),ipa);reports.M06.checks.push('actual module close/reopen restores saved duration and IPA draft');}
  assert.deepEqual(errors,[]);success=true;
 }catch(e){await evidence('failure').catch(()=>{});throw e;}
 finally{for(const [m,r]of Object.entries(reports))await fs.writeFile(path.join(r.dir,'browser-report.json'),JSON.stringify({...r,success,timings:m==='M08'?timings:undefined,errors,baseline,scope:'Windows Chrome production adapters via substituted QWebChannel, real inputs and local jobs'},null,2));await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1});
