const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m14/Scripts/python.exe'),['-X','utf8','scripts/p17_m11_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','packages/phonetic_core/src','desktop/src','scripts'].map(p=>path.join(root,p)).join(';')}});
 let readyResolve,readyReject,counter=0;const pending=new Map(),ready=new Promise((r,j)=>{readyResolve=r;readyReject=j});
 createInterface({input:worker.stdout}).on('line',line=>{const d=JSON.parse(line);if(d.ready)readyResolve(d);else{pending.get(d.id)?.(d);pending.delete(d.id)}});worker.stderr.on('data',d=>process.stderr.write(d));worker.once('exit',code=>readyReject(Error('Host exited '+code)));
 const {out}=await ready;console.log(out);
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},optimizeDeps:{entries:['tests/m14-host.html']},plugins:[{name:'m14-host-transport-test',configureServer(s){s.middlewares.use('/__m14_host',(req,res)=>{let raw='';req.on('data',d=>raw+=d);req.on('end',()=>{const id=++counter;pending.set(id,data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data))});worker.stdin.write(JSON.stringify({...JSON.parse(raw),id})+'\n')})})}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),page=await browser.newPage({viewport:{width:1920,height:1000}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(45000);
 const click=name=>page.getByRole('button',{name,exact:true}).click(),idle=()=>page.waitForFunction(()=>document.querySelector('[aria-label="MFA 自动标注工作区"]')?.getAttribute('aria-busy')==='false');
 const scope=page.getByLabel('MFA 自动标注工作区',{exact:true});
 let success=false;
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/m14-host.html');await page.locator('.nav-item').filter({hasText:'MFA 自动标注'}).click();await scope.waitFor();await idle();
  if(!process.env.P17_REUSE_M11){await click('帮助');await page.getByRole('dialog').waitFor();assert((await page.getByRole('dialog').innerText()).includes('Beam 默认 10'));await page.keyboard.press('Escape');
  await scope.getByLabel('Beam',{exact:true}).fill('20');await scope.getByLabel('Beam',{exact:true}).press('Tab');assert.equal(await scope.getByLabel('Retry beam',{exact:true}).inputValue(),'80');await scope.getByLabel('Retry beam',{exact:true}).fill('20');await click('保存参数草稿');await page.getByText(/参数草稿已保存/).waitFor();
  await scope.getByLabel('Beam',{exact:true}).fill('0');await scope.getByLabel('Beam',{exact:true}).press('Tab');assert(await scope.getByRole('alert').count());await scope.getByLabel('Beam',{exact:true}).fill('10');await scope.getByLabel('Beam',{exact:true}).press('Tab');await scope.getByLabel('Retry beam',{exact:true}).fill('40');await click('保存参数草稿');await click('刷新任务');checks.push('Beam linkage, invalid Beam feedback, normalized draft save and refresh');
  const lab=process.env.P17_LAB;assert(lab);await scope.locator('input[type=file][multiple]').setInputFiles([lab,lab.replace(/\.lab$/i,'.wav')]);await idle();assert((await scope.innerText()).includes('已选择 1 组'));checks.push('natural WAV and exact existing LAB imported through production M11 adapter');
  await scope.locator('input[type=file][accept=".dict,.txt"]').setInputFiles({name:'one.dict',mimeType:'text/plain',buffer:Buffer.from('dai1 d ai1\n')});await idle();await click('使用登记词典');checks.push('custom dictionary import and revert to registered dictionary');
  await click('组件安装与环境检查');await scope.locator('input[maxlength="64"]').fill('invalid');assert(await scope.getByRole('button',{name:'校验并导入离线组件',exact:true}).isDisabled());await click('收起组件管理');
  await page.screenshot({path:path.join(out,'M11-real-light.png')});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.waitForTimeout(250);await page.screenshot({path:path.join(out,'M11-real-dark.png')});checks.push('component controls gated without verified inputs; no installation or synthetic component probe');
  await scope.locator('input[type=file][accept=".dict,.txt"]').setInputFiles('C:/Users/13680/Documents/MFA/pretrained_models/dictionary/mandarin_pinyin_tab.dict');await idle();
  await click('开始对齐');await idle();await page.getByRole('button',{name:'取消任务',exact:true}).waitFor();await click('取消任务');await page.waitForFunction(()=>document.querySelector('.job-state')?.textContent.includes('已取消'),{},{timeout:120000});
  await click('开始对齐');await idle();await page.waitForFunction(()=>document.querySelector('.job-state')?.textContent.includes('失败'),{},{timeout:420000});
  }
  const history=scope.locator('label').filter({hasText:'任务记录'}).locator('select');await history.locator('option').nth(2).waitFor({state:'attached'});assert.equal(await history.locator('option').count(),3);await history.selectOption({index:2});await page.waitForFunction(()=>document.querySelector('.job-state')?.textContent.includes('已取消')&&document.querySelectorAll('.event-log li').length>0);await history.selectOption({index:1});const summary=page.getByText('查看脱敏 MFA 日志',{exact:true});await summary.waitFor();await summary.click();assert((await scope.locator('.native-log').innerText()).length>0);assert(await scope.locator('.event-log li').count()>0);await fs.writeFile(path.join(out,'failed-task-ui.txt'),await scope.innerText());checks.push('registered existing components, actual isolated task cancel, actual failed task, history selection and redacted log UI');
  await click('选择语料目录');await idle();assert((await scope.innerText()).includes('已选择 1 组'));await click('选择输出目录');await idle();const chooser=page.waitForEvent('filechooser');await click('导入音频与转写');await(await chooser).setFiles([path.join(out,'input','00141低_梯_题.lab'),path.join(out,'input','00141低_梯_题.wav')]);await idle();const detail=scope.locator('.component-details');await detail.locator('summary').click();assert(await detail.getAttribute('open')!==null);await detail.locator('summary').click();await click('组件安装与环境检查');for(const label of ['已有环境 / auto_alignment','声学模型 ZIP','配套词典']){await scope.locator('.resource-line').filter({hasText:label}).getByRole('button',{name:'选择',exact:true}).click();await idle();}assert(await scope.getByRole('button',{name:'检查已有环境与模型',exact:true}).isEnabled());await click('收起组件管理');checks.push('actual corpus-directory capability, output-directory selection, upload button file chooser, component details, existing runtime/model/dictionary grants; component self-test intentionally not started');
  const timing=[];for(let i=0;i<20;i++){const begin=Date.now();await scope.getByLabel('Beam',{exact:true}).fill(String(i%2?10:20));await scope.getByLabel('Beam',{exact:true}).press('Tab');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));timing.push(Date.now()-begin);}await fs.writeFile(path.join(out,'interaction-timing.json'),JSON.stringify({scope:'20 Beam edits to two frames, includes automation; not MFA execution or cold start',samples:timing},null,2));
  assert.deepEqual(errors,[]);success=true;
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}
 finally{await fs.writeFile(path.join(out,process.env.P17_REUSE_M11?'history-report.json':'browser-report.json'),JSON.stringify({success,checks,errors,scope:'M11 natural input/UI gates; actual successful alignment blocked by available model/dictionary mismatch'},null,2));console.log(JSON.stringify({success,checks}));await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1});
