// M12: project-owned isolated Chrome with real file capabilities, no EXE/DDL.
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{createInterface}=require('node:readline'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
async function main(){
 const worker=spawn(path.join(root,'.venv/m09-ui/Scripts/python.exe'),['-X','utf8','scripts/p17_m12_bridge.py'],{cwd:root,windowsHide:true,env:{...process.env,PYTHONPATH:['backend/src','desktop/src','packages/phonetic_core/src'].map(p=>path.join(root,p)).join(';')}});
 const pending=new Map();let counter=0,readyResolve,readyReject;
 const ready=new Promise((r,j)=>{readyResolve=r;readyReject=j;});
 createInterface({input:worker.stdout}).on('line',line=>{const v=JSON.parse(line);if(v.ready)readyResolve(v);else{pending.get(v.id)?.(v);pending.delete(v.id);}});worker.stderr.on('data',d=>process.stderr.write(d));worker.on('error',readyReject);worker.once('exit',code=>readyReject(Error('RPC exited '+code)));
 const {out,audio,document:doc}=await ready;const rpc=data=>new Promise(resolve=>{const id=++counter;pending.set(id,resolve);worker.stdin.write(JSON.stringify({...data,rpc_id:id})+'\n');});
 const {createServer}=await import(pathToFileURL(path.join(root,'frontend/node_modules/vite/dist/node/index.js')));
 const server=await createServer({root:path.join(root,'frontend'),server:{host:'127.0.0.1',port:0},optimizeDeps:{entries:['tests/p17-m12-live.html']},plugins:[{name:'m12-owned-rpc',configureServer(s){s.middlewares.use('/__m12',(req,res)=>{let body='';req.on('data',d=>body+=d);req.on('end',async()=>{const value=await rpc(JSON.parse(body));res.setHeader('Content-Type','application/json');res.end(JSON.stringify(value));});});}}]});await server.listen();
 const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--mute-audio']}),context=await browser.newContext({viewport:{width:1920,height:1000},acceptDownloads:true}),page=await context.newPage(),checks=[],errors=[];

 page.on('pageerror',e=>errors.push(e.message));
 const click=name=>page.getByRole('button',{name,exact:true}).first().click();
 const loaded=()=>page.waitForFunction(()=>document.querySelector('.annotation-page')?.getAttribute('aria-busy')==='false'&&document.querySelector('.annotation-grid'));
 const gridClick=async(time,row=0)=>{const box=await page.locator('.annotation-grid').boundingBox();await page.mouse.click(box.x+box.width*time/2,box.y+box.height*(row===0?.22:.73));};
 try{
  await page.goto(server.resolvedUrls.local[0]+'tests/p17-m12-live.html');await click('TextGrid标注');await page.screenshot({path:path.join(out,'empty.png')});await click('选择语料文件夹');await page.locator('.annotation-file-list button').first().waitFor();
  const t0=Date.now();await page.locator('.annotation-file-list button').filter({hasText:audio}).click();await loaded();const loadMs=Date.now()-t0;
  const tiers=doc.tiers.filter(t=>t.intervals);await page.getByLabel('词层名',{exact:true}).selectOption(tiers[0].name);await page.getByLabel('音素层名',{exact:true}).selectOption(tiers[1].name);
  await page.screenshot({path:path.join(out,'loaded-light.png')});checks.push('real 10.26 s recording and original TextGrid loaded, manual tier selection');
  const samples=[];for(let i=0;i<20;i++){const begin=Date.now();await page.getByLabel('标注可视时长').fill(String(i%2?3.2:1.6));await page.getByLabel('标注可视时长').press('Tab');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));samples.push(Date.now()-begin);}
  const interval=tiers[0].intervals.find(i=>(i.xmin+i.xmax)/2<3.2);const box=await page.locator('.annotation-grid').boundingBox();await page.mouse.click(box.x+box.width*((interval.xmin+interval.xmax)/2)/3.2,box.y+box.height*.22);
  await page.getByLabel('编辑选中标注文本').fill('P17 井井 æ');await page.getByLabel('编辑选中标注文本').press('Enter');await page.keyboard.press('Control+s');await page.getByText(/已保存：.*自动保存/).waitFor();await loaded();
  let data=(await rpc({op:'inspect'})).value;assert(data.originals_unchanged);assert(Object.entries(data.grids).some(([name,g])=>name.includes('自动保存')&&g.tiers[0].intervals.some(i=>i.text==='P17 井井 æ')));checks.push('Ctrl+S real edit, independent TextGrid parse readback, originals unchanged');
  await page.getByLabel('搜索词层文本').fill('P17');await page.getByLabel('替换文本').fill('P17 替换');await click('全部替换');await click('替换全部');await page.locator('.annotation-grid').focus();await page.keyboard.press('Control+z');await page.keyboard.press('Control+s');await page.getByRole('button',{name:'保存 TextGrid',exact:true}).waitFor();data=(await rpc({op:'inspect'})).value;assert(Object.entries(data.grids).some(([name,g])=>name.includes('自动保存')&&g.tiers[0].intervals.some(i=>i.text==='P17 井井 æ')));checks.push('search/replace confirmation and keyboard undo');

  for(const ms of ['5','10','20','50','100','0']){await page.getByLabel('语谱窗长',{exact:true}).selectOption(ms);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}checks.push('all six actual spectrogram window settings');
  await page.getByLabel('标注可视时长').fill('0');await page.getByLabel('标注可视时长').press('Tab');assert(await page.getByRole('alert').count());await page.getByLabel('标注可视时长').fill('3.2');await page.getByLabel('标注可视时长').press('Tab');
  await click('后一窗');const later=await page.locator('.annotation-tracks').getAttribute('data-start');assert(Number(later)>0);await click('前一窗');assert.equal(Number(await page.locator('.annotation-tracks').getAttribute('data-start')),0);checks.push('invalid duration feedback and previous/next view without modifying audio');
  await page.locator('input[type=file][accept=".TextGrid,.textgrid"]').setInputFiles(path.join(out,'inputs',audio.replace(/\.wav$/i,'.TextGrid')));
  for(const mode of ['inside','outside','before','after']){await page.getByLabel('参考复用模式').selectOption(mode);await page.getByLabel('参考起点').fill('.5');if(['inside','outside'].includes(mode))await page.getByLabel('参考终点').fill('1.5');await click('复用参考标注');await page.locator('.annotation-grid').focus();await page.keyboard.press('Control+z');}await click('清除参考');checks.push('all four reference splice modes then undo, original reference read only');
  await page.getByLabel('TextGrid 保存后缀').fill('');await page.getByRole('button',{name:/^保存 TextGrid/}).click();await page.getByRole('dialog').waitFor();await click('取消');await page.getByLabel('TextGrid 保存后缀').fill('_自动保存');checks.push('empty suffix requires overwrite confirmation; cancel preserves original copy');
  await click('粘贴词表');await page.getByLabel('拼音词表',{exact:true}).fill('ba1 ba2');await click('应用词表');await page.getByLabel('音素首个切分点').selectOption('equal');await page.getByLabel('音素首个切分点').selectOption('cursor');await click('清除词表');checks.push('word-list paste, two split settings, clear word list');
  await page.getByRole('button',{name:'文件列表',exact:true}).click();await page.getByRole('button',{name:'文件列表',exact:true}).click();
  await require('./p17-m12-controls.cjs')({page,click,audio,out,checks});
  await require('./p17-m12-gestures.cjs')({page,click,rpc,audio,checks});
  await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'loaded-dark.png')});
  const geometry=await page.locator('.annotation-page').evaluate(e=>({client:e.clientHeight,scroll:e.scrollHeight,panes:[...e.querySelectorAll('.annotation-files,.annotation-settings,.annotation-editor')].map(p=>({class:p.className,client:p.clientHeight,scroll:p.scrollHeight}))}));
  const largeGeometry=[];for(const size of [{width:1920,height:1000},{width:2560,height:1360},{width:3840,height:2080}]){await page.setViewportSize(size);await page.waitForTimeout(250);largeGeometry.push({size,plot:await page.locator('.wave-track svg').first().boundingBox(),root:await page.locator('.annotation-page').boundingBox()});await page.screenshot({path:path.join(out,'loaded-'+size.width+'.png')});}assert(largeGeometry[2].plot.height>largeGeometry[0].plot.height);await fs.writeFile(path.join(out,'large-layout.json'),JSON.stringify(largeGeometry,null,2));
  await page.setViewportSize({width:1280,height:720});await page.screenshot({path:path.join(out,'small.png'),fullPage:true});await page.getByRole('button',{name:'复用参考标注',exact:true}).scrollIntoViewIfNeeded();assert(await page.getByRole('button',{name:'复用参考标注',exact:true}).isVisible());checks.push('small viewport last settings reachable');
  await page.setViewportSize({width:1920,height:1000});await require('./p17-m12-file-cases.cjs')({page,click,audio,out,rpc,checks});
  await page.goto(server.resolvedUrls.local[0]);await page.locator('.nav-item').filter({hasText:'TextGrid标注'}).click();const browserPicker=page.waitForEvent('filechooser');await click('打开语料文件');await(await browserPicker).setFiles([path.join(out,'inputs',audio),path.join(out,'inputs',audio.replace(/\.wav$/i,'.TextGrid'))]);await page.locator('.annotation-file-list button').filter({hasText:audio}).click();await loaded();assert(await page.locator('.annotation-grid').isVisible());checks.push('browser preview Open corpus files button and file input load byte-identical real WAV/TextGrid; no server account claim');
  await page.getByLabel('词层名',{exact:true}).selectOption(tiers[0].name);await page.getByLabel('音素层名',{exact:true}).selectOption(tiers[1].name);await page.getByLabel('标注可视时长').fill('3.2');await page.getByLabel('标注可视时长').press('Tab');
  const browserBox=await page.locator('.annotation-grid').boundingBox();await page.mouse.click(browserBox.x+browserBox.width*((interval.xmin+interval.xmax)/2)/3.2,browserBox.y+browserBox.height*.22);await page.getByLabel('编辑选中标注文本').fill('P17 浏览器保存 æ');await page.getByLabel('编辑选中标注文本').press('Enter');await page.getByLabel('TextGrid 保存后缀').fill('_自动保存');
  const browserDownloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:/^保存 TextGrid/}).click();const browserDownload=await browserDownloadEvent;assert.equal(browserDownload.suggestedFilename(),audio.replace(/\.wav$/i,'_自动保存.TextGrid'));await browserDownload.saveAs(path.join(out,'inputs','P17-browser-export.TextGrid'));data=(await rpc({op:'inspect'})).value;assert(data.originals_unchanged);assert(data.grids['P17-browser-export.TextGrid'].tiers[0].intervals.some(i=>i.text==='P17 浏览器保存 æ'));assert.equal(data.grids['P17-browser-export.TextGrid'].tiers.length,doc.tiers.length);await fs.writeFile(path.join(out,'browser-save-readback.json'),JSON.stringify({suggestedFilename:browserDownload.suggestedFilename(),savedPath:path.join(out,'inputs','P17-browser-export.TextGrid'),document:data.grids['P17-browser-export.TextGrid'],originals_unchanged:data.originals_unchanged},null,2));checks.push('browser preview actual edit and Save TextGrid download: automatic suffix filename, independent core parse and original source hashes; no remote upload claim');
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'report.json'),JSON.stringify({checks,errors,loadMs,samples,geometry,sourceAudio:audio},null,2));console.log(JSON.stringify({out,checks,loadMs,geometry},null,2));
 }catch(error){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});await fs.writeFile(path.join(out,'failure.txt'),String(error)+'\n'+await page.locator('body').innerText()+'\nErrors:'+JSON.stringify(errors));console.error('M12 evidence:',out);throw error;}
 finally{await browser.close();await server.close();worker.stdin.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
