<script setup lang="ts">
import {computed,ref,reactive,watch,onMounted,onUnmounted,markRaw} from 'vue';
import type {ResearchContext,ResearchFile,JobView} from '../../platform/research.ts';
import {workspace,host} from '../../state/workspace.ts';import {stop} from '../../state/audio.ts';import {decodeWav} from '../../platform/decode.ts';
import ModuleFrame from '../../components/ModuleFrame.vue';import ModuleToolbar from '../../components/ModuleToolbar.vue';import ModuleSection from '../../components/ModuleSection.vue';import ModuleStatus from '../../components/ModuleStatus.vue';import ModalDialog from '../../components/ModalDialog.vue';import WaveformViewport from '../../components/WaveformViewport.vue';import AudioTransport from '../../components/AudioTransport.vue';import TaskPanel from '../../components/TaskPanel.vue';
import CurveEditor from './CurveEditor.vue';import SynthesisSpectrum from './SynthesisSpectrum.vue';
import {defaults,parameters,vowels,presets,clone,valid,number,ipa,override,resize,f0Range,preset,exportParams,importParams,isCurrent,type Config} from './state.ts';
import type {Action,Result,Raster} from './port.ts';import {downloadBytes} from '../../platform/m06.ts';
const props=defineProps<{context:ResearchContext;stateKey:string;active:boolean}>();const emit=defineEmits<{references:[]}>();
const wave=workspace(props.stateKey),config=reactive(defaults()),name=ref('F0'),overrideText=ref(''),durationText=ref('2'),low=ref('50'),high=ref('500');
const error=ref(''),notice=ref(''),busy=ref(false),revision=ref(0),resultRevision=ref(-1),result=ref<Result>(),job=ref<JobView>();
const help=ref(false),rules=ref(false),consonants=ref(false),pending=ref<(()=>void)|null>(null),pendingLabel=ref(''),selectedPreset=ref('常态浊声');
const files=ref<ResearchFile[]>([]),source=ref<ResearchFile>(),directory=ref(''),audioPicker=ref<HTMLInputElement>(),paramPicker=ref<HTMLInputElement>();
const view=ref('wave'),windowMs=ref(20),rangeStart=ref(0),rangeEnd=ref(2);let epoch=0,disposed=false,abort:AbortController|undefined;
const sourceWave=workspace(props.stateKey+'.m06-source'),previewTarget=ref('result'),sourceSpectra=ref<Record<string,Raster>>({});
const previewWave=computed(()=>previewTarget.value==='source'?sourceWave:wave),spectra=computed(()=>previewTarget.value==='source'?sourceSpectra.value:result.value?.metadata.spectrograms);
const port=computed(()=>props.context.files.m06),stale=computed(()=>!!result.value&&resultRevision.value!==revision.value);
const activeRange=computed(()=>previewWave.value.asset?[previewWave.value.offset,previewWave.value.offset+previewWave.value.asset.duration/previewWave.value.zoom]:[rangeStart.value,rangeEnd.value]);
const tasks=computed(()=>job.value?[{id:job.value.id,title:'语音合成 · '+job.value.id.slice(0,8),status:job.value.state,progress:job.value.progress,error:job.value.error_code??undefined,canCancel:true}]:[]);
watch(config,()=>{revision.value++;wave.dirty=true;stop();},{deep:true,flush:'sync'});
watch(()=>props.active,v=>{if(!v)stop();});
watch(name,()=>syncInputs());
function editPending(){revision.value++;wave.dirty=true;stop();}
function requireApplied(){if(Number(durationText.value)!==config.duration||Number(low.value)!==config.f0_range[0]||Number(high.value)!==config.f0_range[1])throw Error('请先应用时长或 F0 范围');const v=config.curves[name.value].override;const expected=v===null?'':String(v*(name.value==='Shimmer'?100:1));if(overrideText.value!==expected)throw Error('请先应用 Override curve');}
function copySymbol(s:string){void attempt(()=>navigator.clipboard.writeText(s));}
function syncInputs(){const v=config.curves[name.value].override;overrideText.value=v===null?'':String(v*(name.value==='Shimmer'?100:1));durationText.value=String(config.duration);low.value=String(config.f0_range[0]);high.value=String(config.f0_range[1]);}
function attempt(work:()=>void|Promise<void>){error.value='';return Promise.resolve().then(work).catch(e=>{if(!disposed)error.value=e instanceof Error?e.message:String(e);});}
function replace(c:Config){Object.assign(config,valid(c));syncInputs();resetRange();}
function resetRange(){rangeStart.value=0;rangeEnd.value=config.duration;wave.zoom=1;wave.offset=0;sourceWave.zoom=1;sourceWave.offset=0;}
function setRange(a:number,b:number){if(b<=a)return;rangeStart.value=a;rangeEnd.value=b;const p=previewWave.value;if(p.asset){p.zoom=p.asset.duration/(b-a);p.offset=a;}}
function applyOverride(){return attempt(()=>{override(config,name.value,overrideText.value);syncInputs();});}
function applyDuration(){return attempt(()=>{resize(config,number(durationText.value,'时长'));resetRange();});}
function applyRange(){return attempt(()=>{f0Range(config,number(low.value,'F0 下限'),number(high.value,'F0 上限'));syncInputs();});}
function confirm(label:string,work:()=>void){pendingLabel.value=label;pending.value=work;}
function commitPending(){const work=pending.value;pending.value=null;if(work)void attempt(work);}
function clear(){confirm('恢复全部 23 项参数，清除曲线覆盖与静音区间',()=>{const c=defaults();resize(c,config.duration);c.sample_rate=config.sample_rate;c.sequence=config.sequence;c.fade_in=config.fade_in;c.fade_out=config.fade_out;c.smooth=config.smooth;replace(c);});}
function applyPreset(){confirm('用“'+selectedPreset.value+'”覆盖其关联参数，其他参数保留',()=>{preset(config,selectedPreset.value);syncInputs();});}
function save(){try{valid(config);if(durationText.value!==String(config.duration)||low.value!==String(config.f0_range[0])||high.value!==String(config.f0_range[1]))throw Error('请先应用时长或 F0 范围');const c=clone(config);override(c,name.value,overrideText.value);valid(c);if(!host.projects.write('m06.draft.'+props.stateKey,c))throw Error('草稿保存失败');if(JSON.stringify(c)!==JSON.stringify(config))replace(c);wave.dirty=false;notice.value='完整参数草稿已保存';return true;}catch(e){error.value=String(e);return false;}}
defineExpose({save});
async function refresh(){files.value=(await props.context.files.list(directory.value||undefined)).filter(f=>/\.wav$/i.test(f.name));}
async function choose(){await attempt(async()=>{const grant=await props.context.files.choose?.('input');if(grant){directory.value=grant.id;await refresh();}});}
async function addAudio(event:Event){await attempt(async()=>{const target=event.target as HTMLInputElement;props.context.files.add?.([...target.files??[]]);target.value='';await refresh();});}
function loadSource(event:Event){const id=(event.target as HTMLSelectElement).value;const f=files.value.find(f=>f.id===id);if(!f)return;confirm('加载音频并提取参数将覆盖当前曲线',()=>{source.value=f;void run('extract');});}
async function run(action:Action){await attempt(async()=>{
 if(!port.value)throw Error('当前宿主尚未提供 M06 科学任务能力');if(busy.value)throw Error('请等待当前任务完成或取消');
 requireApplied();const submitted=clone(valid(config));if(action==='generate')ipa(submitted.sequence);if(action==='extract'&&!source.value)throw Error('请先加载 WAV 音频');
 if(submitted.duration>10||submitted.duration*submitted.sample_rate>480000)throw Error('当前已验证任务预算为 10 秒且 480,000 样本，请缩短输入');
 const input=source.value;const rev=revision.value,ticket=++epoch;abort=new AbortController();busy.value=true;notice.value='';
 try{const completed=await port.value.run(action,submitted,input,abort.signal,j=>{if(!disposed&&ticket===epoch)job.value=j;});
  if(disposed||!isCurrent(rev,revision.value,ticket,epoch)){notice.value='任务完成期间配置已改变，迟到结果未应用。原结果保留。';return;}
  if(action==='synthesize'){
   const asset=await decodeWav(completed.wav!,'合成结果.wav');if(disposed||!isCurrent(rev,revision.value,ticket,epoch))return;
   previewTarget.value='result';result.value=completed;resultRevision.value=rev;wave.asset=markRaw(asset);wave.start=0;wave.end=asset.duration;wave.channel=0;resetRange();notice.value='合成完成，试听与导出绑定本次参数快照';
  }else{if(action==='extract'&&input){const raw=await props.context.files.read(input,abort.signal);if(raw.sha256!==completed.metadata.input_sha256)throw Error('源音频在提取后已变化，未应用参数');const asset=await decodeWav(raw.buffer,input.name);if(disposed||!isCurrent(rev,revision.value,ticket,epoch))return;sourceWave.asset=markRaw(asset);sourceWave.start=0;sourceWave.end=asset.duration;sourceWave.channel=0;sourceSpectra.value=completed.metadata.spectrograms;previewTarget.value='source';}replace(completed.metadata.config);notice.value=action==='generate'?'元音曲线已生成，请点击合成生成音频':'参数提取完成。复制合成效果有限，请检查曲线后合成';}
 }finally{if(ticket===epoch)busy.value=false;}
 });}
async function cancel(){abort?.abort();if(job.value&&port.value)await attempt(async()=>{await port.value!.cancel(job.value!.id);});}
async function exportAudio(){await attempt(async()=>{if(!result.value)throw Error('暂无合成结果');await port.value!.download(result.value,'synthesis.wav');notice.value=stale.value?'已导出旧结果及其实际合成快照':'已导出合成结果';});}
async function exportActual(){await attempt(async()=>{if(!result.value)throw Error('暂无合成结果');await port.value!.download(result.value,'parameters.csv');});}
async function importFile(event:Event){await attempt(async()=>{const target=event.target as HTMLInputElement,file=target.files?.[0];target.value='';if(!file)return;if(file.size>8_000_000)throw Error('参数文件超过 8 MB');const c=importParams(await file.text());confirm('导入参数将覆盖当前完整配置',()=>replace(c));});}
onMounted(()=>{const draft=host.projects.read<Config|null>('m06.draft.'+props.stateKey,null);if(draft){try{replace(draft);wave.dirty=false;}catch{error.value='旧草稿无效，已保留存储内容并使用默认参数';}}void attempt(refresh);});
onUnmounted(()=>{sourceWave.asset=null;disposed=true;epoch++;abort?.abort();stop();});
</script>
<template><ModuleFrame label="语音合成工作区" :aria-busy="busy">
<template #toolbar><ModuleToolbar><button v-if="context.files.choose" @click="choose">打开音频目录</button><button v-else @click="audioPicker?.click()">加载音频</button><input ref="audioPicker" hidden type="file" accept=".wav" @change="addAudio"/><select aria-label="源音频" :value="source?.id??''" @change="loadSource"><option value="">选择 WAV 后加载并提取</option><option v-for="f in files" :key="f.id" :value="f.id">{{f.name}}</option></select><button :disabled="busy||!source" @click="run('extract')">提取参数</button><button @click="paramPicker?.click()">导入参数</button><input ref="paramPicker" hidden type="file" accept=".csv,.json" @change="importFile"/><button @click="attempt(()=>downloadBytes(exportParams(config),'语音合成参数.csv'))">导出参数</button><template #actions><button @click="help=true">帮助</button><button @click="emit('references')">方法与来源</button></template></ModuleToolbar></template>
<template #status><ModuleStatus v-if="error" kind="error" :message="error"/><ModuleStatus v-if="stale" kind="info" message="参数已修改，需重新合成。合成结果预览与音频导出仍对应旧结果。"/><ModuleStatus v-if="notice" kind="info" :message="notice"/><ModuleStatus v-if="!port" kind="info" message="当前为参数编辑模式。M06 正式任务需要可用的 Windows 宿主；未通过 Linux 门时保持关闭。"/></template>
<ModuleSection label="合成基础设置"><div class="controls"><label>总时长 (s)<input v-model="durationText" aria-label="总时长" @input="editPending"/></label><button @click="applyDuration">应用时长</button><label class="ipa-input">IPA 元音序列<input v-model="config.sequence" class="ipa-text" aria-label="IPA 元音序列" placeholder="a-i/- ///u+/e++o/-"/></label><label>淡入 (ms)<input v-model.number="config.fade_in" type="number" min="0" max="1000"/></label><label>淡出 (ms)<input v-model.number="config.fade_out" type="number" min="0" max="1000"/></label><label>平滑点数<input v-model.number="config.smooth" type="number" min="1" max="50"/></label></div><div class="controls"><label>F0 下限 (Hz)<input v-model="low" aria-label="F0 下限" @input="editPending"/></label><label>F0 上限 (Hz)<input v-model="high" aria-label="F0 上限" @input="editPending"/></label><button @click="applyRange">应用 F0 范围</button><span>{{config.sample_rate}} Hz 输出 · Klatt 内部 10 kHz</span><button @click="rules=true">元音规则</button><button @click="consonants=true">辅音规则</button><select v-model="selectedPreset" aria-label="发声类型预设"><option v-for="p in Object.keys(presets)" :key="p">{{p}}</option></select><button @click="applyPreset">应用预设</button></div></ModuleSection>
<div class="editor-layout"><ModuleSection label="参数列表"><div class="parameter-list"><button v-for="(definition,key) in parameters" :key="key" :aria-pressed="name===key" @click="name=key">{{key}} <small>{{definition[3]}}</small></button></div></ModuleSection><div class="plots"><ModuleSection label="参数曲线"><div class="controls"><label>Override curve<input v-model="overrideText" aria-label="Override curve" placeholder="常数，或 100,150;200" @input="editPending" @change="applyOverride"/></label><button @click="applyOverride">应用覆盖</button><button @click="overrideText='';applyOverride()">清除覆盖</button><button @click="resetRange">重置范围</button><button @click="clear">清空参数</button><button @click="save">保存参数草稿</button></div><CurveEditor :config="config" :name="name" :start="activeRange[0]" :end="activeRange[1]" @range="setRange" @error="error=$event"/></ModuleSection>
<ModuleSection label="音频预览"><div class="controls"><button :aria-pressed="previewTarget==='result'" @click="previewTarget='result';stop()">合成结果</button><button v-if="sourceWave.asset" :aria-pressed="previewTarget==='source'" @click="previewTarget='source';stop()">源音频</button><span>{{previewTarget==='source'?'源音频试听，音频导出仍保存合成结果':'本次合成结果'}}</span><button :aria-pressed="view==='wave'" @click="view='wave'">波形</button><button :aria-pressed="view==='spectrum'" @click="view='spectrum'">语谱图</button><label>窗长<select v-model.number="windowMs" aria-label="语谱窗长"><option v-for="ms in [5,10,20,40]" :key="ms" :value="ms">{{ms}} ms</option></select></label></div><WaveformViewport v-if="previewWave.asset&&view==='wave'" :state="previewWave" auto-amplitude continuous-detail/><SynthesisSpectrum v-else-if="spectra?.[String(windowMs)]&&view==='spectrum'" :data="spectra[String(windowMs)]" :start="activeRange[0]" :end="activeRange[1]" :window-ms="windowMs"/><ModuleStatus v-else kind="empty" message="暂无合成音频。生成元音只更新参数曲线，合成后可试听和导出。"/><AudioTransport :state="previewWave" :active="active"/></ModuleSection></div></div>
<ModuleSection label="合成操作"><div class="controls"><button :disabled="busy||!port" @click="run('generate')">生成元音</button><button class="primary" :disabled="busy||!port" @click="run('synthesize')">合成</button><button :disabled="!result" @click="exportAudio">导出音频</button><button :disabled="!result" @click="exportActual">导出实际合成参数</button><button v-if="busy" @click="cancel">取消任务</button><span v-if="result">结果 {{result.job.slice(0,8)}} · 随机种子 {{result.metadata.seed}}</span></div><TaskPanel :tasks="tasks" empty-title="尚未提交合成任务" empty-text="参数编辑不会自动触发音频合成" @cancel="cancel"/></ModuleSection>
<ModalDialog v-if="pending" title="覆盖参数确认" @close="pending=null"><p>{{pendingLabel}}。现有合成音频保留并标记为旧结果。</p><template #footer><button @click="pending=null">取消</button><button @click="commitPending">应用并覆盖</button></template></ModalDialog>
<ModalDialog v-if="rules" title="元音规则" @close="rules=false"><table><thead><tr><th>IPA</th><th>F1 Hz</th><th>F2 Hz</th><th>F3 Hz</th></tr></thead><tbody><tr v-for="(f,s) in vowels" :key="s"><td><button class="ipa-text" @click="copySymbol(s)">{{s}}</button></td><td v-for="(v,i) in f" :key="i">{{v}}</td></tr></tbody></table><p>点击音标复制。空格为静音段。+、-、*、/ 依次将相对时长乘以 1.1、0.9、2、0.5，再按总时长归一。生成元音只更新共振峰与 AV 曲线。</p></ModalDialog>
<ModalDialog v-if="consonants" title="辅音规则" @close="consonants=false"><p>V2 已移除辅音合成，当前保留元音合成。此入口保留原说明语义。</p></ModalDialog>
<ModalDialog v-if="help" title="语音合成帮助" @close="help=false"><p>设置时长和 IPA → 生成元音曲线 → 编辑参数 → 合成 → 公共播放器试听或导出 WAV。生成、合成、试听和导出分别执行。</p><p>Shift 拖动绘制，Ctrl 拖动恢复默认值，Ctrl 滚轮缩放。Override 常数冻结曲线，清空输入恢复原曲线；逗号线性插值，分号等长分段。Shimmer 显示百分数，文件保留小数。</p><p>加载 WAV 后提取参数。源录音采样率保留。复制合成与五类发声预设效果有限，输入参数不保证等于重新分析得到的测量值。</p><p>导出参数保存当前编辑，导出实际合成参数保存所听结果的配置与完整曲线。修改后旧音频仍可导出，并明确标为旧结果。完整 CSV 保留采样率、淡入淡出、静音、Override 下的原曲线。</p><p>目前任务上限为 10 秒且 480,000 样本。新计算结果与复制产物期限由公共平台区分处理，下载不续期。云端/实验室调度由公共平台管理。</p></ModalDialog>
</ModuleFrame></template>
<style scoped>.controls{display:flex;align-items:end;gap:var(--control-gap);flex-wrap:wrap;margin-bottom:8px}.controls label{display:grid;gap:4px}.controls input{width:100px}.controls .ipa-input{flex:1;min-width:200px}.ipa-input input{width:100%}.editor-layout{display:grid;grid-template-columns:180px minmax(0,1fr);gap:12px}.parameter-list{display:grid;grid-template-columns:1fr 1fr;gap:4px}.parameter-list button{min-width:0;text-align:left}.parameter-list button[aria-pressed=true]{color:var(--accent);background:var(--selected)}.parameter-list small{display:block}.plots{display:grid;gap:12px;min-width:0}table{width:100%;border-collapse:collapse}td,th{padding:6px;border-bottom:1px solid var(--border)}@container module (max-width:850px){.editor-layout{grid-template-columns:1fr}.parameter-list{grid-template-columns:repeat(auto-fit,minmax(70px,1fr))}}.ipa-text{font-family:var(--font-ipa)}</style>
