import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { fileURLToPath,pathToFileURL } from 'node:url';
import { gunzipSync } from 'node:zlib';
import { withArtifacts } from './artifacts.mjs';
import { ProjectStore,sha } from '../server/project-store.mjs';
import { startServer } from '../server/http-server.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
await withArtifacts(root, async ({ out, scratch }) => {
const runtime=process.env.PTB_PLAYWRIGHT ?? path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const {chromium}=await import(pathToFileURL(runtime)),store=new ProjectStore();
const directory=path.join(scratch,'作者工程 中文 空格'),seed=await store.create(directory,'可迁移压力样章');
const paragraph=text=>({type:'paragraph',content:[{type:'text',text}]}),chapter={schemaVersion:'ptb-manual-chapter/1',id:'stress',title:'富文本、媒体与引用',moduleId:'M08',body:{type:'doc',content:[
{type:'heading',attrs:{id:'stress-start',level:2},content:[{type:'text',text:'编辑往返压力样章'}]},
{type:'paragraph',content:[{type:'text',text:'中文、IPA ãː、组合 t͡ɕʰ 与 Unicode 完整保存。',marks:[{type:'bold'},{type:'italic'},{type:'underline'}]}]},
{type:'paragraph',attrs:{textAlign:'justify',lineHeight:'1.8',marginTop:'0.5em',marginBottom:'0.8em',indent:1},content:[{type:'text',text:'字号、字色与背景强调',marks:[{type:'textStyle',attrs:{color:'#256147',colorDark:'#ace8c7',fontSize:'18px',fontFamily:'SimSun',backgroundColor:'#e8f3dd',backgroundColorDark:'#2d473b'}},{type:'highlight',attrs:{color:'#e8f3dd',colorDark:'#2d473b'}}]},{type:'text',text:'H',marks:[]},{type:'text',text:'2',marks:[{type:'subscript'}]},{type:'text',text:'O / x'},{type:'text',text:'2',marks:[{type:'superscript'}]}]},
{type:'table',attrs:{id:'stress-table',caption:'表：合并与宽度',note:'本表仅验证作者编辑器'},content:[{type:'tableRow',content:[{type:'tableHeader',attrs:{colspan:2,rowspan:1,colwidth:[180,180]},content:[paragraph('合并表头')]}]},{type:'tableRow',content:[{type:'tableCell',attrs:{colspan:1,rowspan:1,colwidth:[180]},content:[paragraph('输入')]},{type:'tableCell',attrs:{colspan:1,rowspan:1,colwidth:[180]},content:[paragraph('结果')]}]}]},
{type:'formula',attrs:{id:'stress-formula',latex:'f_0 = \\frac{1}{T}',display:true,caption:'公式以 LaTeX 源文保留'}},
{type:'codeBlock',attrs:{id:'stress-code',language:'python'},content:[{type:'text',text:'print("声学与编辑分离")\nvalue = 1 / 0.005'}]},
{type:'columns',attrs:{id:'stress-columns'},content:[{type:'column',content:[paragraph('左栏：原音说明')]},{type:'column',content:[paragraph('右栏：结果说明')]}]},
{type:'admonition',attrs:{id:'stress-tip',kind:'limitation'},content:[paragraph('本样章使用合成测试文件，不作为自然录音或科研结果。')]},
{type:'footnote',attrs:{id:'stress-note',label:'1'},content:[paragraph('脚注、跨章引用和来源字段保持可编辑。')]},
{type:'paragraph',content:[{type:'crossReference',attrs:{chapterId:'stress',targetId:'stress-start',label:'返回本节'}},{type:'text',text:' / '},{type:'citation',attrs:{referenceId:'tiptap-doc',label:'Tiptap 官方文档'}}]},paragraph('这段文字会通过真实按键修改并保存。')
]}};
seed.project.chapters.push({id:'stress',title:chapter.title,moduleId:'M08',path:'chapters/stress.json',status:'draft'});seed.project.references.push({id:'tiptap-doc',label:'Tiptap 官方文档',url:'https://tiptap.dev/docs'});seed.chapters.push(chapter);await store.save({...seed,baseRevision:seed.revision});await store.release();
const instance=await startServer({studioRoot:root,projectRoot:directory}),browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:false,args:['--start-maximized','--no-first-run'],});
const context=await browser.newContext({viewport:null,acceptDownloads:true}),page=await context.newPage(),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async dialog=>{if(dialog.type()==='confirm')await dialog.accept();else if(dialog.type()==='prompt')await dialog.accept(path.join(scratch,'导入工程 新位置'));else await dialog.accept();});
try {
  await page.goto(instance.url);const cdp=await context.newCDPSession(page),windowInfo=await cdp.send('Browser.getWindowForTarget');await cdp.send('Browser.setWindowBounds',{windowId:windowInfo.windowId,bounds:{windowState:'maximized'}});
  await page.locator('.tiptap').waitFor();await page.getByRole('button',{name:'排版、素材与文献',exact:true}).click();const bounds=await cdp.send('Browser.getWindowBounds',{windowId:windowInfo.windowId});assert.equal(bounds.bounds.windowState,'maximized');checks.push({name:'actual Chrome window maximized',bounds:bounds.bounds,dimensions:await page.evaluate(()=>({innerWidth,innerHeight,outerWidth,outerHeight,screen:screen.availWidth+'×'+screen.availHeight}))});
  await page.getByRole('button',{name:'收起预览',exact:true}).click();await page.locator('.tiptap > p').last().click();await page.keyboard.press('Control+End');await page.keyboard.type(' 作者实改成功，保存到磁盘。');await page.getByRole('button',{name:'保存 Ctrl+S',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.save-state')?.textContent?.startsWith('已保存到磁盘'));let saved=JSON.parse(await fs.readFile(path.join(directory,'chapters/stress.json'),'utf8'));assert.ok(JSON.stringify(saved).includes('作者实改成功'));checks.push({name:'native editor typing and disk save'});
  await page.keyboard.press('Control+End');await page.keyboard.type('撤销测试');await page.getByRole('button',{name:'撤销',exact:true}).click();assert.ok(!(await page.locator('.tiptap').innerText()).includes('撤销测试'));await page.getByRole('button',{name:'重做',exact:true}).click();assert.ok((await page.locator('.tiptap').innerText()).includes('撤销测试'));await page.getByRole('button',{name:'撤销',exact:true}).click();checks.push({name:'undo and redo'});
  const table=page.locator('.tiptap table');await table.locator('td').first().click();await page.getByRole('button',{name:'后加行',exact:true}).click();assert.equal(await table.locator('tr').count(),3);await table.locator('tr').last().locator('td').first().click();await page.getByRole('button',{name:'删行',exact:true}).click();assert.equal(await table.locator('tr').count(),2);await table.locator('th').first().click();await page.getByRole('button',{name:'拆分格',exact:true}).click();assert.equal(await table.locator('th').count(),2);checks.push({name:'merged table split, row add/delete'});
  await page.locator('.tiptap > p').last().click();await page.keyboard.press('Control+End');await page.getByRole('button',{name:'公式',exact:true}).click();await page.locator('.formula-editor').last().click();const formulaInput=page.getByLabel('LaTeX 公式');await formulaInput.fill('F_1 = 500 \\; Hz');await page.getByRole('button',{name:'双栏',exact:true}).click();assert.equal(await page.locator('.columns-editor').count(),2);checks.push({name:'formula editing and two-column insertion'});
  const pngBase64=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=480;canvas.height=220;const ctx=canvas.getContext('2d');ctx.fillStyle='#e5eee7';ctx.fillRect(0,0,480,220);ctx.fillStyle='#315d48';ctx.font='26px sans-serif';ctx.fillText('Manual Studio · TEST FIXTURE',20,50);ctx.strokeStyle='#315d48';ctx.beginPath();for(let x=20;x<460;x++){const y=135+35*Math.sin(x/18);if(x===20)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();return canvas.toDataURL('image/png').split(',')[1];});
  await page.locator('.tiptap > p').last().click();await page.keyboard.press('Control+End');await page.locator('input[type=file]').first().setInputFiles({name:'编辑器测试图片.png',mimeType:'image/png',buffer:Buffer.from(pngBase64,'base64')});await page.locator('.tiptap .editable-media img').waitFor();await page.locator('.tiptap .editable-media img').last().click();await page.getByRole('button',{name:'排版',exact:true}).click();await page.getByLabel('标题 / 图注').fill('图：真实导入的测试图片');await page.getByRole('button',{name:'保存 Ctrl+S',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.save-state')?.textContent?.startsWith('已保存到磁盘'));checks.push({name:'image file import and editable caption'});
  const rate=16000,frames=3200,wav=Buffer.alloc(44+frames*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(rate,24);wav.writeUInt32LE(rate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(frames*2,40);for(let i=0;i<frames;i++)wav.writeInt16LE(Math.round(2500*Math.sin(2*Math.PI*220*i/rate)),44+i*2);
  await page.locator('.tiptap > p').last().click();await page.keyboard.press('Control+End');await page.locator('input[type=file]').first().setInputFiles({name:'合成验证音频.wav',mimeType:'audio/wav',buffer:wav});await page.locator('.tiptap audio').waitFor();await page.locator('.tiptap audio').last().click();await page.getByRole('button',{name:'排版',exact:true}).click();await page.getByLabel('标题 / 图注').fill('音频：仅用于解码验证的合成测试');await page.getByRole('button',{name:'保存 Ctrl+S',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.save-state')?.textContent?.startsWith('已保存到磁盘'));await page.getByRole('button',{name:'正式预览',exact:true}).click();const media=page.locator('.reading-preview audio');await media.waitFor();await media.evaluate(a=>{a.muted=true;a.load();});await page.waitForFunction(()=>document.querySelector('.reading-preview audio')?.readyState>=1);assert.ok(await media.evaluate(a=>Math.abs(a.duration-.2)<.001));checks.push({name:'actual WAV decode in shared reading component',duration:await media.evaluate(a=>a.duration)});
  await page.getByRole('button',{name:'生成阅读资源',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.save-state')?.textContent?.startsWith('阅读资源已生成'));assert.equal(await page.getByLabel('预览内容版本').inputValue(),'generated');assert.equal(await page.locator('.reading-preview .katex').count(),2);assert.equal(await page.locator('.reading-preview math').count(),2);checks.push({name:'offline mathematical rendering and accessible MathML'});assert.ok((await page.locator('.reading-preview').innerText()).includes('作者实改成功'));assert.ok(JSON.parse(await fs.readFile(path.join(directory,'.studio/reading/project.json'),'utf8')).searchIndex.length);checks.push({name:'compiler and generated reading preview'});
  const title='压力样章已重命名';await page.getByLabel('章节标题').fill(title);await page.getByRole('button',{name:'保存 Ctrl+S',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.save-state')?.textContent?.startsWith('已保存到磁盘'));await page.reload();await page.locator('.tiptap').waitFor();assert.equal(await page.getByLabel('章节标题').inputValue(),title);assert.ok((await page.locator('.tiptap').innerText()).includes('作者实改成功'));checks.push({name:'save, reload and stable anchors'});
  await page.getByRole('button',{name:'复制',exact:true}).click();await page.getByRole('button',{name:'上移',exact:true}).click();await page.getByRole('button',{name:'保存 Ctrl+S',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.save-state')?.textContent?.startsWith('已保存到磁盘'));assert.equal((await instance.store.load()).project.chapters.length,2);checks.push({name:'chapter duplicate and reorder'});
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出完整工程',exact:true}).click();const download=await downloadPromise,bundleFile=path.join(scratch,'完整工程.ptbmanual.gz');await download.saveAs(bundleFile);const packed=JSON.parse(gunzipSync(await fs.readFile(bundleFile)));for(const f of packed.files)assert.equal(sha(Buffer.from(f.data,'base64')),f.sha256);const destination=path.join(scratch,'移交工程 中文 空格'),imported=new ProjectStore(),state=await imported.importBundle(destination,await fs.readFile(bundleFile));assert.equal(state.project.chapters.length,2);assert.equal(state.project.assets.length,2);assert.ok(JSON.stringify(state.chapters).includes('f_0 ='));assert.ok(JSON.stringify(state.chapters).includes('F_1 ='));assert.ok(JSON.stringify(state.chapters).includes('真实导入的测试图片'));assert.ok(state.project.assets.some(a=>a.duration===.2 && a.channels===1 && a.sampleRate===16000));await imported.release();checks.push({name:'complete engineering export, new-directory import and media hash parity'});
  await page.getByRole('button',{name:'深色',exact:true}).click();await page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:path.join(out,'studio-dark-maximized.png')});await page.getByRole('button',{name:'浅色',exact:true}).click();await page.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:path.join(out,'studio-light-maximized.png')});checks.push({name:'light/dark actual maximized screenshots'});
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'report.json'),JSON.stringify({checks,errors,artifacts:{directory,bundleFile,destination}},null,2));console.log(JSON.stringify({passed:checks.length,report:path.join(out,'report.json'),screenshots:[path.join(out,'studio-light-maximized.png'),path.join(out,'studio-dark-maximized.png')]}));
}catch(e){await page.screenshot({path:path.join(out,'failure-maximized.png')});await fs.writeFile(path.join(out,'failure.json'),JSON.stringify({error:e.stack,errors,checks},null,2));throw e;}finally{try{await browser.close();}finally{await instance.close();}}

});
