import test, { after } from 'node:test';
import { createArtifacts } from './artifacts.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { gzipSync,gunzipSync } from 'node:zlib';
import { ProjectStore, sha,relativePath,validateProject,validateChapter } from '../server/project-store.mjs';
import { startServer } from '../server/http-server.mjs';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execute=promisify(execFile),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),artifacts=await createArtifacts(root,'store'),output=artifacts.scratch;
after(()=>artifacts.finish());
const chapter=(text='中文及 IPA [t͡ɕʰa˥]')=>({schemaVersion:'ptb-manual-chapter/1',id:'chapter-one',title:'测试章节',moduleId:'M08',body:{type:'doc',content:[{type:'heading',attrs:{id:'section-one',level:2},content:[{type:'text',text:'第一节'}]},{type:'paragraph',content:[{type:'text',text,marks:[{type:'bold'},{type:'textStyle',attrs:{color:'#336644',fontSize:'18px'}}]}]}]}});
async function fixture(t){const directory=path.join(output,'工程 空格-'+randomUUID()),store=new ProjectStore();const state=await store.create(directory,'测试工程');const c=chapter();state.project.chapters.push({id:c.id,title:c.title,path:'chapters/chapter-one.json',status:'draft'});state.chapters.push(c);await store.save({...state,baseRevision:state.revision});t.after(()=>store.release());return {store,directory};}
const payload=s=>({project:s.project,chapters:s.chapters,baseRevision:s.revision});
test('actual edit, atomic save and reopen retain Chinese/IPA without historical copies',async t=>{const {store,directory}=await fixture(t),s=await store.load();s.chapters[0].body.content[1].content[0].text='已修改：ãː、声调 35';await store.save(payload(s));await store.release();await store.open(directory);assert.equal((await store.load()).chapters[0].body.content[1].content[0].text,'已修改：ãː、声调 35');assert.equal((await fs.readdir(path.join(directory,'.studio/history'))).length,0);assert.equal((await fs.readdir(path.join(directory,'.studio/transactions'))).length,0);assert.equal((await store.recoveries()).length,1);});
test('external modification rejects stale save and preserves exact recovery',async t=>{const {store,directory}=await fixture(t),s=await store.load();s.chapters[0].title='作者当前稿';s.project.chapters[0].title=s.chapters[0].title;const file=path.join(directory,'chapters/chapter-one.json'),external=chapter('外部较新文字');await fs.writeFile(file,JSON.stringify(external));await assert.rejects(()=>store.save(payload(s)),e=>e.status===409&&!!e.extra.recoveryId);assert.equal(JSON.parse(await fs.readFile(file,'utf8')).body.content[1].content[0].text,'外部较新文字');const recovery=await store.readRecovery((await store.recoveries())[0].id);assert.equal(recovery.chapters[0].title,'作者当前稿');});
test('duplicate writer is locked, normal release permits reopen',async t=>{const {store,directory}=await fixture(t),second=new ProjectStore();await assert.rejects(()=>second.open(directory),e=>e.status===423);await store.release();await second.open(directory);await second.release();});
test('interrupted stale reservation and dead lock can be reopened without deleting',async t=>{const {store,directory}=await fixture(t);await store.release();await fs.writeFile(path.join(directory,'.studio/lock.json'),JSON.stringify({pid:2147483647,id:'dead',released:false}));await fs.mkdir(path.join(directory,'.studio/reservation'));await fs.writeFile(path.join(directory,'.studio/reservation/owner.json'),JSON.stringify({pid:2147483647}));await store.open(directory);assert.ok((await fs.readdir(path.join(directory,'.studio'))).some(n=>n.startsWith('reservation-interrupted-')));});
test('soft chapter removal preserves the old chapter and unreferenced media',async t=>{const {store,directory}=await fixture(t),s=await store.load();await fs.writeFile(path.join(directory,'assets/unreferenced.txt'),'旧素材');s.project.chapters=[];s.chapters=[];await store.save(payload(s));assert.ok(await fs.readFile(path.join(directory,'chapters/chapter-one.json')));assert.equal(await fs.readFile(path.join(directory,'assets/unreferenced.txt'),'utf8'),'旧素材');});
test('blocked chapter write leaves manifest and recovery intact',async t=>{const {store,directory}=await fixture(t),s=await store.load();s.project.chapters[0].path='chapters/blocked.json';await fs.mkdir(path.join(directory,'chapters/blocked.json'));await assert.rejects(()=>store.save(payload(s)));assert.equal(JSON.parse(await fs.readFile(path.join(directory,'project.json'),'utf8')).chapters[0].path,'chapters/chapter-one.json');assert.ok((await store.recoveries()).length);});
test('repeated saves retain only the latest exact recovery and no committed journals',async t=>{
  const {store,directory}=await fixture(t);
  for(let i=0;i<6;i++){const s=await store.load();s.chapters[0].body.content[1].content[0].text='最新稿 '+i;await store.save(payload(s));}
  const list=await store.recoveries();assert.equal(list.length,1);
  assert.equal((await store.readRecovery(list[0].id)).chapters[0].body.content[1].content[0].text,'最新稿 5');
  assert.equal((await fs.readdir(path.join(directory,'.studio/history'))).length,0);
  assert.equal((await fs.readdir(path.join(directory,'.studio/transactions'))).length,0);
});
test('queued recovery writes preserve the last submitted payload',async t=>{
  const {store}=await fixture(t),s=await store.load();
  const requests=Array.from({length:5},(_,i)=>{const copy=structuredClone(s);copy.chapters[0].body.content[1].content[0].text='草稿 '+i;return store.recovery(payload(copy));});
  const ids=await Promise.all(requests),list=await store.recoveries();assert.equal(list.length,1);assert.equal(list[0].id,ids.at(-1));
  assert.equal((await store.readRecovery(ids.at(-1))).chapters[0].body.content[1].content[0].text,'草稿 4');
});
test('failed atomic draft publish preserves the previous recovery and removes its temporary file',async t=>{
  const {store,directory}=await fixture(t),old=(await store.recoveries())[0],bytes=await fs.readFile(path.join(directory,'.studio/recovery',old.id+'.json'));
  const rename=fs.rename.bind(fs);
  t.mock.method(fs,'rename',async(from,to)=>{if(to.includes(path.join('.studio','recovery')))throw new Error('simulated publish failure');return rename(from,to);});
  await assert.rejects(async()=>store.recovery(payload(await store.load())),/simulated publish failure/);
  assert.deepEqual(await fs.readFile(path.join(directory,'.studio/recovery',old.id+'.json')),bytes);
  assert.deepEqual(await fs.readdir(path.join(directory,'.studio/recovery')),[old.id+'.json']);
});
test('retention refuses a linked snapshot and leaves its target intact',async t=>{
  const {store,directory}=await fixture(t),outside=path.join(output,'retention-outside-'+randomUUID());await fs.mkdir(outside);await fs.writeFile(path.join(outside,'original.txt'),'preserve');
  const link=path.join(directory,'.studio/history/2000-01-01T00-00-00-000Z-12345678');await fs.symlink(outside,link,'junction');t.after(()=>fs.unlink(link));
  await store.save(payload(await store.load()));
  assert.equal(await fs.readFile(path.join(outside,'original.txt'),'utf8'),'preserve');
  const report=JSON.parse(await fs.readFile(path.join(directory,'.studio/retention-report.json'),'utf8'));
  assert.ok(report.retained.some(item=>item.path.endsWith('12345678')));
});
test('media is content addressed, copied and survives removal of source location',async t=>{const {store,directory}=await fixture(t),bytes=Buffer.from('RIFF-synthetic-fixture');const {asset}=await store.addAsset({name:'作者录音.wav',data:bytes.toString('base64'),kind:'audio',distribution:'software-only',sourceType:'合成测试'});assert.equal(asset.git,false);assert.equal(asset.sha256,sha(bytes));assert.deepEqual(await fs.readFile(path.join(directory,asset.path)),bytes);assert.equal((await store.addAsset({name:'另一个名字.wav',data:bytes.toString('base64'),kind:'audio'})).asset.id,asset.id);});
test('media import refuses an external change and cannot adopt a new revision over stale chapters',async t=>{const {store,directory}=await fixture(t),s=await store.load(),file=path.join(directory,'chapters/chapter-one.json');await fs.writeFile(file,JSON.stringify(chapter('外部编辑仍须保留')));await assert.rejects(()=>store.addAsset({name:'new.wav',kind:'audio',data:Buffer.from('test').toString('base64'),baseRevision:s.revision}),e=>e.status===409);assert.equal((await store.load()).project.assets.length,0);assert.ok((await fs.readFile(file,'utf8')).includes('外部编辑仍须保留'));});
test('full bundle moves to a new Chinese directory, retaining orphan chapters/media and hashes',async t=>{const {store,directory}=await fixture(t);await fs.writeFile(path.join(directory,'assets/old.txt'),'旧未引用素材');const bytes=Buffer.from('sample media');await store.addAsset({name:'sample.wav',kind:'audio',data:bytes.toString('base64')});const {bytes:bundle}=await store.exportBundle();const target=path.join(output,'迁移工程 '+randomUUID()),imported=new ProjectStore();t.after(()=>imported.release());const state=await imported.importBundle(target,bundle);assert.equal(state.project.chapters[0].id,'chapter-one');assert.equal(await fs.readFile(path.join(target,'assets/old.txt'),'utf8'),'旧未引用素材');assert.equal(sha(await fs.readFile(path.join(target,state.project.assets[0].path))),sha(bytes));});
test('public bundle filters private media and orphan files, software bundle includes authorized bytes',async t=>{const {store,directory}=await fixture(t);await store.addAsset({name:'private.wav',kind:'audio',data:Buffer.from('private').toString('base64'),distribution:'software-only'});await store.addAsset({name:'public.png',kind:'image',data:Buffer.from('public').toString('base64'),distribution:'public'});await fs.writeFile(path.join(directory,'assets/private-orphan.txt'),'private');const publicResult=await store.exportBundle('public'),decoded=JSON.parse(gunzipSync(publicResult.bytes));assert.equal(publicResult.skipped.length,1);assert.ok(!decoded.files.some(f=>f.path.endsWith('.wav')||f.path.includes('orphan')));assert.equal(JSON.parse(Buffer.from(decoded.files.find(f=>f.path==='project.json').data,'base64')).assets.length,1);});
test('invalid bundle traversal, hash corruption and existing destination are refused',async t=>{const {store,directory}=await fixture(t),{bytes}=await store.exportBundle();const bad=JSON.parse(gunzipSync(bytes));bad.files.push({path:'../outside.txt',data:'eA==',sha256:sha('x')});await assert.rejects(()=>store.importBundle(path.join(output,randomUUID()),gzipSync(JSON.stringify(bad))));const corrupt=JSON.parse(gunzipSync(bytes));corrupt.files[0].sha256='0'.repeat(64);await assert.rejects(()=>store.importBundle(path.join(output,randomUUID()),gzipSync(JSON.stringify(corrupt))));await assert.rejects(()=>store.importBundle(directory,bytes),/空目录/);});
test('path and private source rejection includes encoded traversal and nested source objects',()=>{for(const p of ['../a','a/../b','C:/x','assets/%2e%2e/x','assets/a?x','assets/a\\b'])assert.throws(()=>relativePath(p));const p={schemaVersion:'ptb-manual/1',id:'p',title:'工程',chapters:[],references:[],assets:[{id:'a',path:'assets/a.wav',kind:'audio',distribution:'software-only',git:false,source:{path:'C:\\Users\\private.wav'}}]};assert.throws(()=>validateProject(p),/私有绝对/);});
test('unsafe script attrs and links are rejected, unknown nodes retained and reported',()=>{const c=chapter();c.body.content.push({type:'newFutureNode',attrs:{id:'future'},content:[]});assert.deepEqual(validateChapter(c,c.id),['newFutureNode']);c.body.content[1].content[0].marks=[{type:'link',attrs:{href:'javascript:alert(1)'}}];assert.throws(()=>validateChapter(c,c.id),/链接/);c.body.content[1].content[0].marks=[];c.body.content[0].attrs.onclick='run()';assert.throws(()=>validateChapter(c,c.id),/脚本/);});
test('symlink media cannot read outside the opened project',async t=>{const {store,directory}=await fixture(t),outside=path.join(output,'outside-'+randomUUID());await fs.mkdir(outside);await fs.symlink(outside,path.join(directory,'assets/linked'),'junction');t.after(()=>fs.unlink(path.join(directory,'assets/linked')));const s=await store.load();s.project.assets.push({id:'external',path:'assets/linked/file.wav',kind:'audio',distribution:'public'});await store.save(payload(s));await assert.rejects(()=>store.exportBundle(),/符号链接/);});
test('HTTP capabilities and same-origin checks block unauthorized writes; media range is bounded',async t=>{const {store,directory}=await fixture(t);const asset=(await store.addAsset({name:'test.wav',kind:'audio',data:Buffer.from('abcdefghij').toString('base64')})).asset;await store.release();const instance=await startServer({studioRoot:root,projectRoot:directory});t.after(()=>instance.close());const headers={Authorization:'Bearer '+instance.capability,'Content-Type':'application/json'};assert.equal((await fetch(instance.origin+'/api/session')).status,401);assert.equal((await fetch(instance.origin+'/api/open',{method:'POST',headers:{...headers,Origin:'https://evil.example'},body:JSON.stringify({path:directory})})).status,403);const allowed=await fetch(instance.origin+'/api/session',{headers});assert.equal(allowed.status,200);const range=await fetch(instance.origin+'/media/'+asset.path+'?session='+instance.capability,{headers:{Range:'bytes=2-5'}});assert.equal(range.status,206);assert.equal(await range.text(),'cdef');assert.equal((await fetch(instance.origin+'/media/'+asset.path)).status,403);});
test('software/public compiler is deterministic and public output cannot retain stale private files',async t=>{const {store,directory}=await fixture(t);await store.addAsset({name:'private.wav',kind:'audio',data:Buffer.from('test').toString('base64')});const script=path.resolve(root,'../../scripts/manual/build.py'),publicOut=path.join(output,'public-'+randomUUID()),softwareOut=path.join(output,'software-'+randomUUID());await execute('python',[script,'--project',directory,'--output',publicOut,'--distribution','public']);const first=await fs.readFile(path.join(publicOut,'project.json'));await execute('python',[script,'--project',directory,'--output',publicOut,'--distribution','public']);assert.deepEqual(await fs.readFile(path.join(publicOut,'project.json')),first);await execute('python',[script,'--project',directory,'--output',softwareOut,'--distribution','software']);assert.equal(JSON.parse(await fs.readFile(path.join(softwareOut,'project.json'),'utf8')).assets.length,1);await assert.rejects(()=>execute('python',[script,'--project',directory,'--output',softwareOut,'--distribution','public']),/新的独立目录/);});
