<script setup lang="ts">
import {computed,ref,toRaw,onMounted,onBeforeUnmount,watch} from 'vue';
import ModuleFrame from '../../components/ModuleFrame.vue';
import ModuleToolbar from '../../components/ModuleToolbar.vue';
import ModuleStatus from '../../components/ModuleStatus.vue';
import RecordingWave from './RecordingWave.vue';
import {getRecordingPort,type RecordingCapabilities} from '../../platform/recording.ts';
import {claimCapture,releaseCapture} from '../../platform/capture-lease.ts';
import {stop as stopGlobalPlayback} from '../../state/audio.ts';
import {newTask,nextTask,setSelectionEndpoint,currentFrames,formatTime,taskName,channelName} from './state.ts';
import {shortcut} from './shortcuts.ts';
import {recordingDefaults,bindInput} from './defaults.ts';
import {readTable,autoMapping,importRows,fields,fieldLabels,exampleCSV,type Table,type Field} from './task-import.ts';
import type {Device,Project,Take,Task,Config,Preview,RecordingStatus,JobStatus,Role} from './types.ts';
const props=defineProps<{active:boolean;stateKey:string;context?:unknown}>();
const emit=defineEmits<{dirty:[value:boolean];references:[];recording:[value:boolean]}>();
const port=getRecordingPort(),project=ref<Project|null>(null),devices=ref<Device[]>([]),error=ref(''),notice=ref(''),busy=ref(false),capture=ref(false),probing=ref(false),playing=ref(false),job=ref<JobStatus|null>(null),lastJob=ref<JobStatus|null>(null),status=ref<RecordingStatus|null>(null);
const playbackVariant=ref<'current'|'raw'|'residual'>('current');const processingChannels=ref<number[]>([0,1]);
const config=ref<Config>(recordingDefaults()),outputDevice=ref(''),playChannel=ref(0),playVolume=ref(.7),showDevices=ref(false),showSpectrum=ref(true),showImportHelp=ref(false),search=ref(''),taskId=ref(''),takeId=ref(''),tasksDraft=ref<Task[]>([]),tasksDirty=ref(false),taskEditor=ref<Task|null>(null),preview=ref<Preview|null>(null),selection=ref<[number,number]>([0,0]),zoom=ref<[number,number]|null>(null),displayScale=ref(1),canvasFocused=ref(false),noise=ref<{take_id:string;version_id:string;start:number;end:number;channel:number;warning:string}|null>(null),strength=ref(1),gainDb=ref(0),subtype=ref('FLOAT'),rawExport=ref(false),exportMode=ref('current'),showExport=ref(false),table=ref<Table|null>(null),sheetIndex=ref(0),mapping=ref<Record<Field,number>>(autoMapping([])),fileInput=ref<HTMLInputElement>(),leftWidth=ref(300);
let timer:ReturnType<typeof setTimeout>|undefined,polling=false,disposed=false,sequence=0,loadingPreview=0,closingPending=false;
const currentTask=computed(()=>tasksDraft.value.find(t=>t.id===taskId.value)??null),take=computed(()=>project.value?.takes.find(t=>t.id===takeId.value)??null),frames=computed(()=>currentFrames(take.value)),sampleRate=computed(()=>take.value?.config.sample_rate??config.value.sample_rate),roles=computed(()=>capture.value||probing.value?config.value.roles:take.value?.config.roles??config.value.roles),capturing=computed(()=>capture.value||probing.value),locked=computed(()=>busy.value||capturing.value||!!job.value),selectedDevice=computed(()=>devices.value.find(d=>d.id===config.value.device)),visibleTasks=computed(()=>tasksDraft.value.filter(t=>`${t.id} ${t.title} ${t.prompt}`.toLowerCase().includes(search.value.toLowerCase()))),visibleTakes=computed(()=>project.value?.takes??[]),importPreview=computed(()=>table.value?(table.value.template?{tasks:table.value.template,errors:[]}:importRows(table.value.sheets[sheetIndex.value]?.rows??[],mapping.value)):{tasks:[],errors:[]}),finishedTasks=computed(()=>tasksDraft.value.filter(t=>!!project.value?.selected[t.id]).length);
function setProject(p:Project|null){project.value=p;if(!tasksDirty.value)tasksDraft.value=p?structuredClone(toRaw(p.tasks)):[];if(p&&!p.takes.some(t=>t.id===takeId.value)){const last=p.takes.at(-1);takeId.value=last?.id??'';if(last)taskId.value=last.task_snapshot?.id&&p.tasks.some(t=>t.id===last.task_snapshot!.id)?last.task_snapshot.id:'';else if(!p.tasks.some(t=>t.id===taskId.value))taskId.value='';}}
function message(exc:unknown){error.value=exc instanceof Error?exc.message:String(exc);}
async function request<T>(body:Record<string,unknown>){if(!port)throw Error('此能力需要 Windows 桌面宿主，普通浏览器尚未开放录音工程');return port.request<T>(body);}
async function action(work:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await work();}catch(exc){message(exc);}finally{busy.value=false;}}
async function initialize(){if(!port)return;await action(async()=>{const cap=await request<RecordingCapabilities>({op:'capabilities'});devices.value=cap.devices;setProject(cap.project);if(cap.device_error)error.value=cap.device_error;});}
async function openProject(create:boolean){await action(async()=>{const choice=await port?.choose(create?'new':'open');if(!choice)return;if(tasksDirty.value)await saveTasks();const opened=await request<Project>({op:'open',grant:choice.grant,create});tasksDirty.value=false;taskId.value='';takeId.value='';setProject(opened);emit('dirty',false);noise.value=null;selection.value=[0,0];zoom.value=null;notice.value=create?'本地录音工程已建立':'本地工程已打开';await loadPreview();});}
async function saveTasks(){setProject(await request<Project>({op:'tasks',tasks:tasksDraft.value}));tasksDirty.value=false;emit('dirty',capturing.value);notice.value='任务清单已存入本地工程';}
async function save(){if(busy.value){error.value='录音操作正在完成，请等待后再关闭';return false;}try{await stopPlay();if(capturing.value)await stopCapture();if(tasksDirty.value)await saveTasks();if(project.value)setProject(await request<Project>({op:'save'}));emit('dirty',false);return true;}catch(exc){message(exc);return false;}}
async function beforeClose(){
 if(busy.value||closingPending){error.value='录音请求正在完成，请稍后再关闭';return false;}
 if(job.value){error.value='请先等待或取消后台处理，再关闭录音页';return false;}
 closingPending=true;clearTimeout(timer);
 try{
  const deadline=Date.now()+5000;
  while(polling||loadingPreview){if(Date.now()>=deadline){error.value='录音请求仍在完成，请稍后重试关闭';return false;}await new Promise(resolve=>setTimeout(resolve,25));}
  return await save();
 }finally{closingPending=false;schedule();}
}
defineExpose({save,beforeClose,isRecording:()=>capturing.value});
function changed(){tasksDirty.value=true;emit('dirty',true);}
async function addTask(){await action(async()=>{const n=tasksDraft.value.length+1;const task=newTask(n);while(tasksDraft.value.some(t=>t.id===task.id)||project.value?.takes.some(t=>t.task_snapshot?.id===task.id)){task.id+='A';task.filename_stem+='A';}tasksDraft.value.push(task);changed();await selectTask(task.id);taskEditor.value=tasksDraft.value.at(-1)!;});}
function moveTask(direction:number){const i=tasksDraft.value.findIndex(t=>t.id===taskId.value),j=i+direction;if(i<0||j<0||j>=tasksDraft.value.length)return;[tasksDraft.value[i],tasksDraft.value[j]]=[tasksDraft.value[j],tasksDraft.value[i]];changed();}
async function cloneTask(){if(!currentTask.value)return;await action(async()=>{const value=structuredClone(toRaw(currentTask.value!));value.id+='-copy';value.filename_stem+='-copy';while(tasksDraft.value.some(t=>t.id===value.id)||project.value?.takes.some(t=>t.task_snapshot?.id===value.id)){value.id+='A';value.filename_stem+='A';}value.skipped=false;tasksDraft.value.push(value);changed();await selectTask(value.id);taskEditor.value=tasksDraft.value.at(-1)!;});}
function skipTask(){if(currentTask.value){currentTask.value.skipped=!currentTask.value.skipped;changed();}}
async function deleteTask(){
 if(!currentTask.value||locked.value)return;
 const index=tasksDraft.value.findIndex(t=>t.id===taskId.value),remaining=tasksDraft.value.filter(t=>t.id!==taskId.value);
 await action(async()=>{
  const saved=await request<Project>({op:'tasks',tasks:remaining});
  tasksDirty.value=false;setProject(saved);taskEditor.value=null;emit('dirty',false);
  await selectTask(remaining[Math.min(index,remaining.length-1)]?.id??'');
  notice.value='任务已删除并保存，已有录音保留在录音历史中';
 });
}
async function selectTask(id:string){await stopPlay();taskId.value=id;const candidates=project.value?.takes.filter(t=>id?t.task_snapshot?.id===id:!t.task_snapshot)??[];takeId.value=project.value?.selected[id||'__free__']??candidates.at(-1)?.id??'';selection.value=[0,0];zoom.value=null;await loadPreview();}
async function selectTake(){await stopPlay();taskId.value=take.value?.task_snapshot?.id&&tasksDraft.value.some(t=>t.id===take.value?.task_snapshot?.id)?take.value.task_snapshot.id:'';selection.value=[0,0];zoom.value=null;await loadPreview();}
async function loadPreview(){const id=takeId.value,requestId=++sequence;if(!id||!take.value){preview.value=null;return;}const version=take.value.head;loadingPreview++;try{const [start,end]=zoom.value??[0,frames.value];if(!end){preview.value=null;return;}const value=await request<Preview>({op:'preview',id,version,start,end,width:900,spectrum:showSpectrum.value,channel:Math.min(playChannel.value,take.value.config.channels-1)});if(requestId===sequence&&!disposed)preview.value=value;}catch(exc){if(requestId===sequence)message(exc);}finally{loadingPreview--;}}
async function refreshDevices(){await action(async()=>{devices.value=await request<Device[]>({op:'devices'});notice.value='设备列表已刷新，请确认物理输入与角色';});}
function channelsChanged(){config.value.roles=Array.from({length:config.value.channels},(_,i)=>config.value.roles[i]??'microphone');}
async function startCapture(probe=false){await action(async()=>{if(tasksDirty.value)await saveTasks();claimCapture('M16');stopGlobalPlayback();try{await stopPlay();await request({op:probe?'probe_start':'start',config:config.value,task_id:taskId.value||null});capture.value=!probe;probing.value=probe;preview.value=null;selection.value=[0,0];zoom.value=null;emit('recording',true);emit('dirty',true);notice.value=probe?'录前检测中，音频不会保存为 take':'录音中，原始采样正在存入本地工程';}catch(exc){try{const s=await request<RecordingStatus>({op:'status'});if(s.capture_active){capture.value=!probe;probing.value=probe;emit('recording',true);emit('dirty',true);}else releaseCapture('M16');}catch{capture.value=!probe;probing.value=probe;emit('recording',true);emit('dirty',true);}throw exc;}});}
async function stopCapture(){const result=await request<{project:Project|null;error:string;probe:boolean;quality:unknown}>({op:'stop'});capture.value=false;probing.value=false;releaseCapture('M16');emit('recording',false);setProject(result.project);if(!result.probe)takeId.value=project.value?.takes.at(-1)?.id??'';await loadPreview();emit('dirty',tasksDirty.value);if(result.error){error.value=result.error;notice.value='录音不完整，已落盘部分保留在工程';}else notice.value=result.probe?'录前检测已停止':'已存入本地工程，尚未导出';}
async function poll(){if(disposed||closingPending||polling||busy.value||!project.value){schedule();return;}polling=true;try{const value=await request<RecordingStatus>({op:'status',spectrum:capturing.value&&showSpectrum.value,channel:Math.min(playChannel.value,config.value.channels-1),gain_preview_db:config.value.gain_db});if(disposed)return;status.value=value;playing.value=value.playback.playing;if(value.playback.error)error.value=value.playback.error;if(value.capture_active&&value.wave){preview.value=value as Preview;if(value.error){error.value=value.error;await stopCapture();}}
 if(value.job){if(['complete','failed','cancelled'].includes(value.job.state)){lastJob.value=value.job;job.value=null;if(value.job.project){setProject(value.job.project);await loadPreview();}if(value.job.error)error.value=value.job.error;else notice.value=value.job.success_count!==undefined?`已导出 ${value.job.success_count} / ${value.job.total} 条，详见导出清单`:'后台处理已结束';}else job.value=value.job;}
 }catch(exc){if(!disposed)message(exc);}finally{polling=false;schedule();}}
function schedule(){if(!disposed&&!closingPending)timer=setTimeout(poll,capturing.value?180:600);}
async function stopPlay(){if(playing.value){await request({op:'play_stop'});playing.value=false;}}
async function play(){if(!take.value||capturing.value||busy.value||job.value)return;await action(async()=>{if(playing.value){await stopPlay();return;}stopGlobalPlayback();const range=selection.value[1]>selection.value[0]?selection.value:[0,frames.value];await request({op:'play',id:takeId.value,start:range[0],end:range[1],device:outputDevice.value,channel:playChannel.value,volume:playVolume.value,variant:playbackVariant.value});playing.value=true;});}
async function edit(kind:string){if(!take.value||locked.value)return;await action(async()=>{const navigation=['undo','redo','restore'].includes(kind);const p=await request<Project>({op:navigation?kind:'edit',id:takeId.value,action:kind,start:selection.value[0],end:selection.value[1]});setProject(p);selection.value=[0,0];zoom.value=null;await loadPreview();notice.value=kind==='copy'?'片段引用已复制到模块音频剪贴板':'编辑已存入工程，原始录音保留';});}
async function changeVersion(event:Event){await action(async()=>{setProject(await request<Project>({op:'version',id:takeId.value,index:Number((event.target as HTMLSelectElement).value)}));selection.value=[0,0];zoom.value=null;await loadPreview();});}
async function setNoise(){await action(async()=>{noise.value=await request({op:'noise',id:takeId.value,start:selection.value[0],end:selection.value[1],channel:playChannel.value});notice.value=noise.value?.warning||'噪声样本已设置，一键降噪会处理当前完整编辑版本';});}
async function process(kind:'denoise'|'gain'){await action(async()=>{job.value=await request({op:'process_start',id:takeId.value,kind,strength:strength.value,gain_db:gainDb.value,channels:processingChannels.value});lastJob.value=null;notice.value=kind==='denoise'?'正在处理当前完整编辑版本，仅音频通道参与降噪':'正在生成可恢复的数字增益版本，EGG 保持不变';});}
async function cancelJob(){await action(async()=>{await request({op:'job_cancel'});notice.value='已请求取消，等待后台确认';});}
async function exportRecording(){await action(async()=>{const choice=await port?.choose('export');if(!choice)return;job.value=await request({op:'export_start',grant:choice.grant,id:takeId.value,mode:exportMode.value,raw:rawExport.value,subtype:subtype.value,start:selection.value[0],end:selection.value[1]});showExport.value=false;lastJob.value=null;});}
async function importFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;await action(async()=>{table.value=await readTable(file);showImportHelp.value=false;sheetIndex.value=0;mapping.value=autoMapping(table.value.sheets[0]?.rows[0]??[]);});(event.target as HTMLInputElement).value='';}
function downloadExample(){const url=URL.createObjectURL(new Blob([exampleCSV],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='录音任务表格示例.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function commitImport(){if(importPreview.value.errors.length)return;tasksDraft.value=structuredClone(toRaw(importPreview.value.tasks));taskId.value=tasksDraft.value[0]?.id??'';table.value=null;changed();}
function downloadTemplate(){const blob=new Blob([JSON.stringify({schema_version:'ptb-recording-tasks/1',tasks:tasksDraft.value},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='录音任务清单.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function keydown(event:KeyboardEvent){const command=shortcut(event,props.active,capturing.value,canvasFocused.value);if(!command)return;event.preventDefault();if(command==='play')void play();else if(command==='all')selection.value=[0,frames.value];else void edit(command);}
function resizeSidebar(event:PointerEvent){const origin=event.clientX,width=leftWidth.value;const move=(e:PointerEvent)=>leftWidth.value=Math.min(480,Math.max(200,width+e.clientX-origin));const end=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);localStorage.setItem('ptb-m16-sidebar',String(leftWidth.value));};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end,{once:true});}
watch(()=>config.value.device,id=>{const device=devices.value.find(d=>d.id===id);if(device&&!capturing.value){const bound=bindInput(config.value,device);config.value=bound.config;notice.value=bound.message;}});
watch(()=>roles.value.join(','),()=>{processingChannels.value=roles.value.flatMap((role,i)=>role==='microphone'?[i]:[]);playChannel.value=Math.min(playChannel.value,Math.max(0,roles.value.length-1));},{immediate:true});
watch(showSpectrum,()=>{if(!capturing.value)void loadPreview();});watch(sheetIndex,()=>mapping.value=autoMapping(table.value?.sheets[sheetIndex.value]?.rows[0]??[]));watch(()=>config.value.channels,channelsChanged);watch(()=>props.active,active=>{if(!active&&playing.value)void stopPlay();});watch(playChannel,()=>{if(!capturing.value)void loadPreview();});watch(outputDevice,()=>void stopPlay());
onMounted(()=>{try{leftWidth.value=Math.min(480,Math.max(200,Number(localStorage.getItem('ptb-m16-sidebar'))||300));}catch{}window.addEventListener('keydown',keydown);void initialize();schedule();});
onBeforeUnmount(()=>{disposed=true;sequence++;clearTimeout(timer);window.removeEventListener('keydown',keydown);if(!capturing.value)releaseCapture('M16');if(playing.value)void request({op:'play_stop'});});
</script>
<template>
 <ModuleFrame unified label="本地录音工作区" class="recording-page" :aria-busy="busy">
  <template #toolbar><ModuleToolbar label="录音工程操作">
   <button class="primary" :disabled="!port||locked" @click="openProject(true)">新建工程</button><button class="primary" :disabled="!port||locked" @click="openProject(false)">打开工程</button>
   <button :disabled="!project||locked" @click="showImportHelp=true">导入表格</button><button :disabled="!project||!tasksDraft.length" @click="downloadTemplate">保存清单模板</button>
   <button :disabled="!project||busy||capture" @click="showDevices=!showDevices">设备与录前检测</button><button class="primary" :disabled="!take||locked" @click="showExport=true">保存 / 批量导出</button>
   <template #actions><span class="local-badge">本机 · 离线工程</span><button @click="emit('references')">方法与引用</button></template>
  </ModuleToolbar></template>
  <template #status><ModuleStatus v-if="!port" kind="info" message="完整录音能力需要 Windows 桌面宿主。浏览器版尚未开放本地采集工程，不会上传音频作为回退。"/><ModuleStatus v-if="error" kind="error" :message="error"><button @click="error=''">收起</button></ModuleStatus><ModuleStatus v-else-if="notice" kind="info" :message="notice"/></template>
  <input ref="fileInput" type="file" accept=".csv,.tsv,.xlsx,.json" hidden @change="importFile"/>
  <div v-if="project?.recoveries.length" class="recovery-list"><strong>发现可恢复录音</strong><span v-for="r in project.recoveries" :key="r.id">{{r.frames}} 帧 · {{r.error}} <button :disabled="locked" @click="action(async()=>{setProject(await request({op:'recover',id:r.id}));notice='已恢复已落盘片段';})">恢复</button></span></div>
  <div class="recording-layout" :style="{'--recording-sidebar':leftWidth+'px'}">
   <aside class="recording-sidebar" aria-label="录音任务与版本">
    <div class="task-heading"><strong>{{project?.label||'本地工程'}}</strong><span>{{finishedTasks}} / {{tasksDraft.length}}</span></div>
    <button class="free-recording" :class="{selected:!taskId}" :disabled="locked" @click="selectTask('')">自由录音 <span>不需要任务清单</span></button>
    <input v-model="search" type="search" placeholder="搜索任务文本" aria-label="搜索任务"/>
    <div class="task-buttons"><button :disabled="!project||locked" @click="addTask">＋ 新任务</button><button :disabled="!currentTask||locked" @click="taskEditor=currentTask">编辑</button><button :disabled="!currentTask||locked" @click="cloneTask">复制</button><button class="delete-task" :disabled="!currentTask||locked" title="从任务清单删除，已有录音继续保留在历史中" @click="deleteTask">删除任务</button></div>
    <div class="task-list"><button v-for="task in visibleTasks" :key="task.id" class="task-row" :class="{selected:task.id===taskId,muted:!task.enabled||task.skipped}" :disabled="locked" @click="selectTask(task.id)"><span>{{task.id}} · {{taskName(task)}}</span><small>{{!task.enabled?'未启用':task.skipped?'已跳过':project?.selected[task.id]?'已有选用录音':'待录'}}</small></button><p v-if="!tasksDraft.length" class="muted">可以直接录音，或逐条新增、导入清单。</p></div>
    <div class="task-buttons task-order"><button :disabled="!currentTask||locked" @click="moveTask(-1)">上移</button><button :disabled="!currentTask||locked" @click="moveTask(1)">下移</button><button :disabled="!tasksDirty||locked" @click="action(saveTasks)">保存清单</button></div>
    <label class="take-select">录音历史（{{visibleTakes.length}} take）<select v-model="takeId" :disabled="locked" @change="selectTake"><option value="">暂无选中录音</option><option v-for="(item,index) in visibleTakes" :key="item.id" :value="item.id">Take {{index+1}} · {{item.task_snapshot?.id||'自由'}} · {{item.started_at.slice(11,19)}} {{item.error?'· 不完整':''}}</option></select></label>
    <button v-if="take" :disabled="locked" @click="action(async()=>{setProject(await request({op:'select_take',id:takeId}));notice='已标记为批量导出的选用 take';})">{{project?.selected[taskId||'__free__']===takeId?'✓ 当前选用 take':'标记为选用 take'}}</button>
   </aside>
   <div class="sidebar-resizer" role="separator" aria-label="调整任务栏宽度" aria-orientation="vertical" @pointerdown="resizeSidebar"/>
   <section class="recording-main" aria-label="录音和编辑">
    <div class="prompt-card">
     <div class="prompt-text"><span class="muted">{{currentTask?currentTask.id:'自由录音'}} <span v-if="capture" class="recording-indicator">● 正在录音</span><span v-if="probing" class="recording-indicator">● 录前检测</span></span><p class="ipa-text">{{currentTask?.prompt||currentTask?.title||'准备好后开始录音，每次停止都会自动保存。'}}</p><small v-if="take?.task_snapshot" class="muted">录制时的提示：{{take.task_snapshot.prompt||take.task_snapshot.title||take.task_snapshot.id}}</small></div>
     <div class="recording-controls" aria-label="录制与播放">
      <button class="primary record-button" :disabled="!project||locked||!config.device" :title="!config.device?'先在设备与录前检测中选择输入设备':'录制后自动保存，重录保留旧录音'" @click="startCapture(false)">● {{take?'重新录音':'开始录音'}}</button>
      <button class="stop-button primary" :disabled="!capturing||busy" @click="action(stopCapture)">■ {{probing?'停止检测':'停止录音'}}</button>
      <button class="play-button" :disabled="!take||locked||!outputDevice" :title="!outputDevice?'先在设备与录前检测中选择扬声器或耳机':'有选区时播放选区，否则播放整段；空格可播放或停止'" @click="play">{{playing?'■ 停止播放':'▶ 播放'}}</button>
      <button v-if="currentTask" :disabled="locked" @click="selectTask(nextTask(tasksDraft,taskId))">下一条</button>
      <button v-if="currentTask" class="skip-button" :disabled="locked" @click="skipTask">{{currentTask.skipped?'恢复待录':'跳过此条'}}</button>
     </div>
    </div>
    <div class="plot-toolbar"><label><input v-model="showSpectrum" type="checkbox"/> 显示语谱图</label><label>显示倍率 <select v-model.number="displayScale"><option :value="1">1×</option><option :value="2">2×</option><option :value="4">4×</option><option :value="10">10×</option></select></label><button :disabled="locked||selection[0]===selection[1]" @click="zoom=[...selection];loadPreview()">放大选区</button><button :disabled="locked||!take" @click="zoom=null;loadPreview()">整段总览</button><span v-if="take" class="version-control">版本 <select :value="take.head" :disabled="locked" @change="changeVersion"><option v-for="(v,i) in take.versions" :key="v.id" :value="i">{{i+1}} · {{v.kind==='raw'?'原始':v.kind==='denoised'?'降噪':v.kind==='gain'?'数字增益':v.kind==='restored_raw'?'恢复原始':'编辑'}} · {{formatTime(v.frames,sampleRate)}}</option></select></span></div>
    <div class="recording-chart"><RecordingWave :preview="preview" :selection="selection" :roles="roles" :spectrum="showSpectrum" :disabled="locked" :scale="displayScale" :channel="playChannel" @selection="selection=$event" @focus="canvasFocused=$event"/></div>
    <div class="selection-toolbar" aria-label="选区与剪辑">
     <label>起点（帧）<input :value="selection[0]" type="number" min="0" :max="frames" :disabled="locked||!take" @change="selection=setSelectionEndpoint(selection,0,Number(($event.target as HTMLInputElement).value),frames)"/></label><label>终点（帧）<input :value="selection[1]" type="number" min="0" :max="frames" :disabled="locked||!take" @change="selection=setSelectionEndpoint(selection,1,Number(($event.target as HTMLInputElement).value),frames)"/></label><span>{{formatTime(selection[1]-selection[0],sampleRate)}}</span><button :disabled="locked||!take" @click="selection=[0,frames]">全选</button><button :disabled="locked||!take" @click="selection=[0,0]">清空选区</button>
     <div class="edit-toolbar"><button v-for="[command,label] in [['cut','剪切'],['copy','复制'],['paste','粘贴'],['delete','删除选区'],['keep','保留选区'],['undo','撤销'],['redo','重做'],['restore','恢复原始']]" :key="command" :disabled="locked||!take||(['cut','copy','delete','keep'].includes(command)&&selection[0]===selection[1])" @click="edit(command)">{{label}}</button></div>
    </div>
    <div class="processing-toolbar" aria-label="降噪与音量调整">
     <div class="processing-channels"><span class="group-label">应用到</span><label v-for="(role,i) in roles" :key="i"><input v-model="processingChannels" type="checkbox" :value="i" :disabled="locked||role!=='microphone'"/>{{channelName(i,roles)}}{{role!=='microphone'?'（保留）':''}}</label></div>
     <div class="processing-group"><button :disabled="locked||!take||selection[1]===selection[0]||roles[playChannel]!=='microphone'" :title="`从${channelName(playChannel,roles)}选取一段只有背景噪声的片段`" @click="setNoise">将选区设为噪声样本</button><label>降噪强度 <input v-model.number="strength" type="number" min="0.1" max="2" step="0.1" :disabled="locked"/></label><button :disabled="locked||!take||!noise||!processingChannels.length" title="使用噪声样本处理完整录音，保留原始版本" @click="process('denoise')">整段降噪</button></div>
     <div class="processing-group"><label>音量增益 <input v-model.number="gainDb" type="number" min="-60" max="24" :disabled="locked"/> dB</label><button :disabled="locked||!take||!processingChannels.length" title="应用数字增益并保存为新版本，原始录音保留" @click="process('gain')">应用增益</button></div>
     <p class="processing-help">先选一段背景噪声并设为样本，再对勾选声道整段降噪。降噪和增益均保存为新版本。</p>
    </div>
    <div class="preview-controls"><label>试听与语谱声道 <select v-model.number="playChannel" :disabled="locked||playing"><option v-for="(_,i) in roles" :key="i" :value="i">{{channelName(i,roles)}}</option></select></label><label>试听版本 <select v-model="playbackVariant" :disabled="locked||playing"><option value="current">当前版本</option><option value="raw">原始录音</option><option value="residual">处理前后差分</option></select></label><span class="muted">拖动波形或语谱选择片段 · 空格试听</span><span class="duration">{{formatTime(capturing?(status?.frames??0):frames,capturing?config.sample_rate:sampleRate)}}</span></div>
    <p v-if="noise" class="noise-note">噪声样本：take {{noise.take_id.slice(0,6)}} / 版本 {{noise.version_id.slice(0,6)}} / {{channelName(noise.channel,roles)}} / {{noise.start}}–{{noise.end}} 帧。EGG 保持不变，降噪可能改变擦音、气声及声学参数。</p>
    <div class="recording-status"><span>{{sampleRate}} Hz · {{roles.length}} 通道 · 原始 float32</span><span v-if="status?.disk_free">磁盘剩余 {{(status.disk_free/1e9).toFixed(2)}} GB</span><span v-if="capturing">已确认 {{status?.confirmed_frames??0}} 帧 · 队列 {{status?.queue_blocks??0}} 块</span><span v-if="take?.error" class="warning">{{take.error}}</span></div>
   </section>
  </div>
  <section v-if="showDevices" class="devices-panel" aria-label="设备与录前检测">
   <div class="device-heading"><strong>设备与录前检测</strong><button :disabled="capturing||busy" @click="refreshDevices">刷新设备</button><button @click="showDevices=false">收起</button></div>
   <div class="device-grid"><label>输入设备<select aria-label="输入设备" v-model="config.device" :disabled="capturing"><option value="">请选择输入设备</option><option v-for="d in devices.filter(d=>d.inputs>0)" :key="d.id" :value="d.id">{{d.name}} · {{d.hostapi}} · {{d.inputs}} 输入</option></select></label><label>扬声器 / 耳机<select aria-label="扬声器 / 耳机" v-model="outputDevice" :disabled="capturing"><option value="">请选择输出设备</option><option v-for="d in devices.filter(d=>d.outputs>0)" :key="d.id" :value="d.id">{{d.name}} · {{d.hostapi}}</option></select></label><label>采样率<select aria-label="采样率" v-model.number="config.sample_rate" :disabled="capturing"><option v-for="r in [16000,22050,32000,44100,48000,88200,96000]" :key="r" :value="r">{{r}} Hz</option></select></label><label>同声卡输入通道数<input v-model.number="config.channels" type="number" min="1" :max="Math.min(8,selectedDevice?.inputs??1)" :disabled="capturing"/></label><label v-for="(_,i) in config.roles" :key="i">物理输入 {{i+1}} 角色<select :aria-label="`物理输入 ${i+1} 角色`" v-model="config.roles[i]" :disabled="capturing"><option value="microphone">音频（麦克风 / 线路）</option><option value="egg">EGG</option><option value="other">其他</option></select></label><label>试听通道<select aria-label="试听通道" v-model.number="playChannel"><option v-for="(role,i) in roles" :key="i" :value="i">{{channelName(i,roles)}}</option></select></label><label>播放音量<input v-model.number="playVolume" type="range" min="0" max="1" step="0.05"/></label><label>检测数字增益预览（dB）<input v-model.number="config.gain_db" type="number" min="-60" max="24"/></label></div>
   <div class="meter-row" v-for="(role,i) in roles" :key="i"><span>输入 {{i+1}} · {{role}}</span><meter min="0" max="1" :value="status?.meter?.peak[i]??0"/><span>峰值 {{(20*Math.log10(Math.max(status?.meter?.peak[i]??0,1e-9))).toFixed(1)}} dBFS / RMS {{(20*Math.log10(Math.max(status?.meter?.rms[i]??0,1e-9))).toFixed(1)}} dBFS</span><strong v-if="status?.meter?.raw_clip[i]" class="warning">原始满幅</strong><strong v-if="status?.meter?.digital_clip[i]" class="warning">数字增益后超幅</strong><span v-if="(status?.meter?.rms[i]??1)<0.00001">极低电平</span><span v-if="Math.abs(status?.meter?.dc[i]??0)>.05">明显 DC 偏置</span></div>
   <p class="muted">硬件增益请调声卡旋钮。数字增益预览、显示倍率与播放音量均不改变原始采样。系统音效 / AGC 状态未知，需确认声卡设置。默认不实时外放。</p><p v-if="Math.abs(status?.meter?.correlation??0)>.995" class="warning">两通道高度相似，请核对接线或 Loopback；此提示不能单独认定硬件故障。</p>
   <button class="primary" :disabled="!project||locked||!config.device" @click="startCapture(true)">开始录前检测（不保存音频）</button><button class="primary" :disabled="!probing||busy" @click="action(stopCapture)">停止检测</button>
  </section>
  <div v-if="job" class="job-progress"><progress aria-label="本机后台处理进度" :value="job.progress??0" max="1"/><button aria-label="取消处理" title="取消处理" :disabled="busy||job.state==='cancelling'" @click="cancelJob">×</button></div>
  <div v-if="lastJob?.items" class="export-results"><strong>导出结果 · {{lastJob.directory_name}}</strong><p v-for="item in lastJob.items" :key="item.take_id">{{item.take_id.slice(0,6)}} · {{item.status==='exported'?'已导出':item.status==='cancelled'?'未完成':'失败'}} {{item.error}} <span v-for="file in item.files" :key="file.name">{{file.name}} </span></p></div>
  <div v-if="taskEditor" class="m16-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="编辑录音任务" class="m16-dialog"><h3>录音任务</h3><label>任务编号<input v-model="taskEditor.id" @input="changed"/></label><label>任务名称<input v-model="taskEditor.title" @input="changed"/></label><label>录音内容<textarea v-model="taskEditor.prompt" rows="4" class="ipa-text" @input="changed"/></label><label>导出文件名<input v-model="taskEditor.filename_stem" @input="changed"/></label><label>分组<input v-model="taskEditor.group" @input="changed"/></label><label>备注<input v-model="taskEditor.note" @input="changed"/></label><label><input v-model="taskEditor.enabled" type="checkbox" @change="changed"/> 启用此任务</label><p class="muted">修改不会追溯改变已有 take 的任务快照。</p><button class="primary" @click="taskId=taskEditor.id;taskEditor=null">完成编辑</button></section></div>
  <div v-if="showImportHelp" class="m16-modal-backdrop" @click.self="showImportHelp=false"><section role="dialog" aria-modal="true" aria-label="录音任务表格格式" class="m16-dialog import-dialog">
   <h3>导入要逐条朗读的录音任务</h3>
   <p>每行是一条录音任务，第一行是列名。可用 Excel 工作簿（.xlsx）、UTF-8 CSV 或 TSV；也可导入本模块保存的 JSON 清单模板。</p>
   <div class="import-example"><table><thead><tr><th>任务编号</th><th>录音内容</th><th>文件名</th><th>次数</th></tr></thead><tbody><tr><td>T001</td><td>请读：春天来了</td><td>example-001</td><td>1</td></tr><tr><td>T002</td><td>请读：今天是晴天</td><td>example-002</td><td>2</td></tr></tbody></table></div>
   <p><strong>至少填写录音内容或任务名称一列。</strong>任务编号和文件名可留空，由程序生成。次数默认为 1，可填 1–100；分组、备注和启用均为可选列。</p>
   <p class="muted">任务编号和文件名须唯一，文件名不含扩展名及路径符号。XLSX 中的公式请先转为文字；需要保留前导零的编号请设为文本。选择文件后可映射不同列名并预览，确认后替换任务清单，已有录音保留。</p>
   <div class="dialog-actions"><button @click="downloadExample">下载 CSV 示例</button><button class="primary" @click="fileInput?.click()">选择表格文件</button><button @click="showImportHelp=false">关闭</button></div>
  </section></div>
  <div v-if="table" class="m16-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="任务表格导入预览" class="m16-dialog import-dialog"><h3>录音任务表格 · 导入预览</h3><p class="muted">核对列的对应关系和下方任务内容后，再确认导入。</p><label>工作表<select v-model.number="sheetIndex"><option v-for="(sheet,i) in table.sheets" :key="sheet.name" :value="i">{{sheet.name}}</option></select></label><div v-if="!table.template" class="mapping-grid"><label v-for="field in fields" :key="field">{{fieldLabels[field]}}<select v-model.number="mapping[field]"><option :value="-1">不导入此列</option><option v-for="(header,i) in table.sheets[sheetIndex]?.rows[0]" :key="i" :value="i">{{header||`第${i+1}列`}}</option></select></label></div><p>展开后 {{importPreview.tasks.length}} 条任务。确认后替换当前清单，已录 take 和任务快照继续保留。</p><ul v-if="importPreview.errors.length" class="warning"><li v-for="e in importPreview.errors.slice(0,30)" :key="e">{{e}}</li></ul><div class="import-rows"><p v-for="task in importPreview.tasks.slice(0,30)" :key="task.id">{{task.id}} · {{taskName(task)}} · {{task.filename_stem}}</p></div><button class="primary" :disabled="!!importPreview.errors.length||!importPreview.tasks.length" @click="commitImport">确认导入</button><button @click="table=null">取消</button></section></div>
  <div v-if="showExport" class="m16-modal-backdrop"><section role="dialog" aria-modal="true" aria-label="保存和批量导出" class="m16-dialog"><h3>保存 / 批量导出</h3><label>导出范围<select v-model="exportMode"><option value="current">当前 take</option><option value="selection">当前选区</option><option value="selected">未跳过任务的选用 take</option><option value="all">全部 take 的当前版本</option><option value="versions">全部 take 的全部历史版本</option></select></label><label>版本<select v-model="rawExport"><option :value="false">当前编辑 / 处理版本</option><option :value="true">原始采样版本</option></select></label><label>WAV 格式<select v-model="subtype"><option value="FLOAT">32-bit float（保留超满幅值）</option><option value="PCM_24">24-bit PCM</option><option value="PCM_16">16-bit PCM</option></select></label><p>任务 {{tasksDraft.length}} 条，已有选用录音 {{finishedTasks}} 条，跳过 {{tasksDraft.filter(t=>t.skipped).length}} 条。缺录和跳过不生成空 WAV。</p><p class="muted">将在选定目录内建立新导出文件夹，附 JSON / CSV 清单。长录音按连续帧索引分段；导出不覆盖原始工程。</p><button class="primary" :disabled="busy||(exportMode==='selection'&&selection[0]===selection[1])" @click="exportRecording">选择目录并导出</button><button @click="showExport=false">取消</button></section></div>
 </ModuleFrame>
</template>
<style scoped>

.recording-page{height:100%;min-height:680px;display:flex;flex-direction:column;gap:8px}
.local-badge{font-size:12px;color:var(--teal);background:var(--teal-bg);padding:4px 8px;border-radius:20px}
.recording-layout{display:grid;grid-template-columns:var(--recording-sidebar) 7px minmax(0,1fr);flex:1 0 auto;min-height:530px}
.recording-sidebar{display:flex;flex-direction:column;gap:10px;padding:10px;background:var(--app);border:1px solid var(--border);border-radius:8px;min-height:0;overflow:auto}
.task-heading,.device-heading{display:flex;justify-content:space-between;gap:8px;align-items:center}
.task-heading strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.task-heading span,.muted{color:var(--muted);font-size:12px}
.free-recording{display:flex;align-items:flex-start;flex-direction:column}.free-recording span{font-size:11px;color:var(--muted)}
.selected{border-color:var(--accent)!important;background:var(--selected)!important}
.task-list{flex:1;min-height:100px;overflow:auto;display:flex;flex-direction:column;gap:5px}
.task-row{display:flex;align-items:flex-start;flex-direction:column;flex:none;text-align:left;gap:4px;width:100%;padding:9px}
.task-row span{width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.task-row small{font-size:11px;color:var(--muted)}
.task-buttons{display:flex;gap:5px;flex-wrap:wrap}.task-buttons button{padding-inline:7px;font-size:12px;min-height:30px}.delete-task{color:var(--danger)}
.task-order{border-top:1px solid var(--border);padding-top:9px}.task-order button:last-child{margin-left:auto}
.take-select{display:flex;flex-direction:column;gap:6px;font-size:12px}.take-select select{width:100%}
.sidebar-resizer{cursor:col-resize}.sidebar-resizer:hover{background:var(--selected)}
.recording-main{min-width:0;display:flex;flex-direction:column;gap:8px;padding-left:7px}
.prompt-card{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:12px;background:var(--app);border:1px solid var(--border);padding:12px;border-radius:8px}
.prompt-text{flex:1 1 200px;min-width:0}.prompt-text p{margin:5px 0 0;padding-bottom:2px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:20px;line-height:1.45;max-height:84px;overflow:auto}.prompt-text small{display:block;margin-top:5px;overflow-wrap:anywhere}
.recording-indicator{color:var(--danger);margin-left:12px}
.recording-controls{display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-left:auto}.recording-controls button{font-size:13px;min-height:38px;padding:6px 12px;white-space:nowrap}
.record-button{background:var(--danger)!important;border-color:var(--danger)!important;color:var(--on-accent,#fff)!important}.record-button:disabled{opacity:.5}.play-button{color:var(--accent);border-color:var(--accent);background:var(--selected)}.skip-button{color:var(--muted)}
.plot-toolbar,.selection-toolbar,.edit-toolbar,.preview-controls{display:flex;gap:7px;align-items:center;flex-wrap:wrap}
.plot-toolbar,.selection-toolbar,.preview-controls{font-size:12px}.plot-toolbar{min-height:32px}
.plot-toolbar label,.selection-toolbar label,.processing-toolbar label,.preview-controls label{display:flex;gap:5px;align-items:center;white-space:nowrap}
.plot-toolbar button,.selection-toolbar button,.edit-toolbar button{min-height:28px;padding:4px 7px;font-size:12px}
.version-control{margin-left:auto;display:flex;align-items:center;gap:6px}.version-control select{max-width:250px}
.recording-chart{height:clamp(280px,36vh,540px);min-height:280px;flex:1}
.selection-toolbar{padding-block:3px;row-gap:6px}.selection-toolbar input{width:86px;min-height:28px;padding:4px 6px}
.edit-toolbar{border-left:1px solid var(--border);padding-left:7px;gap:4px}
.processing-toolbar{display:flex;align-items:center;flex-wrap:wrap;gap:10px;background:var(--app);border:1px solid var(--border);padding:9px 10px;border-radius:7px;font-size:12px}
.processing-channels,.processing-group{display:flex;align-items:center;flex-wrap:wrap;gap:7px}.processing-channels{gap:10px}.group-label{color:var(--muted)}
.processing-group{border-left:1px solid var(--border);padding-left:10px}.processing-toolbar input[type=number]{width:58px;min-height:28px;padding:4px 6px}
.recording-page input[type=checkbox]{width:14px;height:14px;min-width:14px;min-height:14px;flex:none;margin:0;vertical-align:middle}
.processing-toolbar button{font-size:12px;min-height:28px;padding:4px 8px}.processing-help{flex-basis:100%;margin:0;color:var(--muted);font-size:11px;line-height:1.5}
.preview-controls{font-size:12px;row-gap:6px}.preview-controls select{min-height:28px;max-width:170px}.duration{margin-left:auto;font-variant-numeric:tabular-nums;font-weight:600;white-space:nowrap}
.noise-note{font-size:11px;color:var(--muted);margin:0;overflow-wrap:anywhere}.recording-status{display:flex;gap:15px;flex-wrap:wrap;color:var(--muted);font-size:11px}
.warning{color:var(--warning)}.devices-panel{border:1px solid var(--border);background:var(--app);border-radius:8px;padding:12px;display:flex;flex-direction:column;gap:8px}.device-heading strong{margin-right:auto}
.device-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.device-grid label,.m16-dialog>label,.mapping-grid label{display:flex;flex-direction:column;gap:5px;font-size:12px;min-width:0}.device-grid select{width:100%;min-width:0}.device-grid input{max-width:100%}
.meter-row{display:flex;gap:12px;align-items:center;flex-wrap:wrap;font-size:12px}.meter-row meter{width:130px}
.job-progress{display:flex;align-items:center;gap:7px;min-height:18px}.job-progress progress{display:block;flex:1;height:4px;border:0;border-radius:2px;overflow:hidden;appearance:none;background:var(--border)}.job-progress progress::-webkit-progress-bar{background:var(--border)}.job-progress progress::-webkit-progress-value{background:var(--accent)}.job-progress progress::-moz-progress-bar{background:var(--accent)}.job-progress button{font-size:17px;line-height:18px;min-height:18px;height:18px;min-width:18px;padding:0 3px;border:0;background:transparent;color:var(--muted)}
.export-results,.recovery-list{padding:10px;border:1px solid var(--border);border-radius:6px;font-size:12px;max-height:180px;overflow:auto}.recovery-list{display:flex;flex-direction:column;gap:8px}
.m16-modal-backdrop{position:fixed;inset:0;z-index:80;background:var(--overlay);display:flex;align-items:center;justify-content:center;padding:20px}.m16-dialog{width:min(520px,95vw);max-height:90vh;overflow:auto;background:var(--panel);border:1px solid var(--border);border-radius:10px;padding:22px;display:flex;flex-direction:column;gap:12px;box-shadow:var(--shadow)}.m16-dialog h3{margin:0}.m16-dialog textarea{font:inherit;color:var(--text);background:var(--panel);border:1px solid var(--border);border-radius:5px;padding:8px;resize:vertical}
.import-dialog{width:min(800px,95vw)}.mapping-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.import-rows{max-height:180px;overflow:auto;font-size:12px}.import-rows p{margin:3px 0}.m16-dialog p{margin:0;line-height:1.7;font-size:13px}.import-example{overflow:auto;border:1px solid var(--border);border-radius:6px}.import-example table{width:100%;border-collapse:collapse;font-size:13px;text-align:left;white-space:nowrap}.import-example th,.import-example td{padding:9px 12px;border-bottom:1px solid var(--border)}.import-example th{background:var(--app);font-weight:500}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap;margin-top:4px}
@container module (max-width:1050px){.recording-controls{margin-left:0}.prompt-text{flex-basis:100%}.version-control{margin-left:0}}
@container module (max-width:850px){.recording-layout{grid-template-columns:minmax(180px,210px) 5px minmax(0,1fr)}.recording-page{min-height:820px}.edit-toolbar{border-left:0;padding-left:0}.processing-group{border-left:0;padding-left:0}}
@container module (max-width:620px){.recording-layout{display:flex;flex-direction:column}.recording-sidebar{max-height:290px;flex:none}.sidebar-resizer{display:none}.recording-main{padding-left:0;margin-top:8px}.task-list{min-height:70px}.recording-chart{height:320px;flex:none}.recording-page{min-height:1180px}.mapping-grid{grid-template-columns:1fr}}
</style>
