<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted,markRaw,watch} from 'vue';
import type {ResearchContext,ResearchFile,DirectoryGrant,ParameterTable,SpectrogramView} from '../../platform/research.ts';
import {audioPreview} from '../../platform/research.ts';
import {workspace,host} from '../../state/workspace.ts';
import {stop} from '../../state/audio.ts';
import WaveformViewport from '../../components/WaveformViewport.vue';
import ParameterFigure from './ParameterFigure.vue';
import {matchingTable,visibleParameters,assignParameters,removeGroup,annotationRuns,type PlotGroup} from './state.ts';
const props=defineProps<{context:ResearchContext;stateKey:string;active:boolean}>();
const emit=defineEmits<{references:[];close:[]}>();
const waveformArea=ref<HTMLElement>();
const wave=workspace(props.stateKey),files=ref<ResearchFile[]>([]),audioDir=ref<DirectoryGrant>(),tableDir=ref<DirectoryGrant>();
const selected=ref(''),tableId=ref(''),table=ref<ParameterTable>(),busy=ref(false),error=ref(''),filter=ref(''),search=ref('');
const reaper=ref(true),correction=ref(false),marked=ref<string[]>([]),target=ref(1),maximized=ref<number|null>(null),leftWidth=ref(210),rightWidth=ref(250);
const saved=host.projects.read<{groups?:PlotGroup[]}>('m02.'+props.stateKey,{});
const groups=ref<PlotGroup[]>(Array.isArray(saved.groups)&&saved.groups.length&&saved.groups.every(g=>Number.isInteger(g.id)&&typeof g.title==='string'&&Array.isArray(g.parameters)&&g.parameters.every(p=>typeof p==='string'))?saved.groups:[{id:1,title:'图窗 1',parameters:[]}]);
let generation=0,disposed=false;const picker=ref<HTMLInputElement>();
const audios=computed(()=>files.value.filter(f=>f.kind==='audio'));
const current=computed(()=>audios.value.find(f=>f.id===selected.value));
const names=computed(()=>table.value?.columns.filter(name=>!['Time_s','Source_Time_s'].includes(name))??[]);
const visible=computed(()=>visibleParameters(names.value,search.value,reaper.value,correction.value));
const selectedTiers=computed(()=>[...new Set(groups.value.flatMap(g=>g.parameters))].filter(name=>table.value?.kinds[table.value.columns.indexOf(name)]==='text'));
const specLoader=computed(()=>{const file=current.value;return file&&props.context.files.spectrogram?(view:SpectrogramView)=>props.context.files.spectrogram!(file,view):undefined;});
watch(groups,()=>wave.dirty=true,{deep:true});
function save(){const ok=host.projects.write('m02.'+props.stateKey,{groups:groups.value});if(ok)wave.dirty=false;else error.value='绘图配置保存失败。';return ok;}
defineExpose({save});
async function refresh(){busy.value=true;error.value='';try{const first=await props.context.files.list(audioDir.value?.id);const second=tableDir.value?await props.context.files.list(tableDir.value.id):[];if(disposed)return;files.value=[...new Map([...first,...second].map(f=>[f.id,f])).values()];if(selected.value)await loadAudio(selected.value);}catch(e){error.value=e instanceof Error?e.message:'目录读取失败。';}finally{busy.value=false;}}
async function choose(kind:'input'|'association'){try{const grant=await props.context.files.choose?.(kind);if(!grant)return;if(kind==='input'){audioDir.value=grant;tableDir.value=undefined;}else tableDir.value=grant;await refresh();}catch(e){error.value=String(e);}}
async function loadTable(id:string){const ticket=++generation;tableId.value=id;table.value=undefined;marked.value=[];if(!id)return;busy.value=true;error.value='';try{const file=files.value.find(f=>f.id===id);if(!file||!props.context.files.parameters)throw Error('参数读取需要本地桌面版或已登录的网页项目。');const result=await props.context.files.parameters(file);if(disposed||ticket!==generation)return;table.value=markRaw(result);const allowed=result.columns.filter(n=>!['Time_s','Source_Time_s'].includes(n));groups.value=groups.value.map(g=>({...g,parameters:g.parameters.filter(p=>allowed.includes(p))}));if(!groups.value.some(g=>g.parameters.length))groups.value[0].parameters=visibleParameters(allowed,'',true,false);target.value=groups.value[0].id;}catch(e){if(ticket===generation)error.value=e instanceof Error?e.message:'参数读取失败。';}finally{if(ticket===generation)busy.value=false;}}
async function loadAudio(id:string){stop();const ticket=++generation;selected.value=id;wave.asset=null;table.value=undefined;tableId.value='';error.value='';const file=files.value.find(f=>f.id===id);if(!file)return;busy.value=true;try{const {asset}=await audioPreview(props.context.files,file);if(disposed||ticket!==generation)return;wave.asset=markRaw(asset);wave.start=0;wave.end=asset.duration;wave.offset=0;wave.zoom=1;wave.channel=0;const match=matchingTable(file,files.value);await loadTable(match?.id??'');}catch(e){if(ticket===generation)error.value=String(e);}finally{if(!disposed)busy.value=false;}}
function addGroup(){const id=Math.max(...groups.value.map(g=>g.id))+1;groups.value.push({id,title:'图窗 '+id,parameters:[]});target.value=id;}
function assign(){groups.value=assignParameters(groups.value,marked.value,target.value);}
function remove(id:number){groups.value=removeGroup(groups.value,id);if(!groups.value.some(g=>g.id===target.value))target.value=groups.value[0].id;maximized.value=null;}
function markVisible(){marked.value=[...new Set([...marked.value,...visible.value])];}
function addFiles(event:Event){props.context.files.add?.([...((event.target as HTMLInputElement).files??[])]);void refresh();}
onMounted(()=>{if(props.context.files.kind!=='desktop')void refresh();});onUnmounted(()=>{disposed=true;generation++;stop();});
</script>
<template><section class="workspace-page m02-page" :style="{'--m02-left':leftWidth+'px','--m02-right':rightWidth+'px'}">
<header class="page-heading"><div><h1>参数显示</h1><p class="muted">原帧数据 · 同步时间轴 · 自定义图窗</p></div><div><button @click="save">保存绘图配置</button><button @click="emit('references')">参数说明与来源</button><button @click="emit('close')">关闭模块</button></div></header>
<div class="m02-toolbar"><template v-if="context.files.choose"><button @click="choose('input')" :disabled="busy">选择音频目录</button><small>{{audioDir?.label}}</small><button @click="choose('association')" :disabled="busy">选择参数目录</button><small>{{tableDir?.label??'同音频目录'}}</small></template><template v-else-if="context.files.add"><input ref="picker" type="file" accept=".wav,.xlsx,.ptb.sqlite,.ptb.sqlite3" multiple hidden @change="addFiles"/><button @click="picker?.click()">添加文件</button></template><span v-else>使用当前项目已上传的 WAV 和参数表</span><button @click="refresh" :disabled="busy">刷新文件</button></div>
<p v-if="error" class="error-banner" role="alert">{{error}}</p><p v-if="busy" role="status">正在读取文件…</p>
<div class="m02-columns"><aside class="file-panel"><label>音频搜索<input v-model="filter" placeholder="搜索音频"/></label><label class="muted">列表宽度<input v-model.number="leftWidth" type="range" min="170" max="340" aria-label="音频列宽"/></label><div class="m02-files"><button v-for="file in audios.filter(f=>f.name.toLowerCase().includes(filter.toLowerCase()))" :key="file.id" :class="{selected:file.id===selected}" :disabled="busy" @click="loadAudio(file.id)">{{file.name}}</button></div><p v-if="!audios.length" class="muted">请选择音频目录，或在项目文件页上传文件。</p></aside>
<div class="signal-panel"><template v-if="wave.asset"><label>参数表关联<select :value="tableId" @change="loadTable(($event.target as HTMLSelectElement).value)" :disabled="busy"><option value="">未关联参数表</option><option v-for="file in files.filter(f=>f.kind==='parameter')" :key="file.id" :value="file.id">{{file.name}}</option></select></label><p v-if="!tableId" class="notice">未找到同名参数结果，仍可查看和试听音频。可手动关联已有 XLSX / SQLite。</p>
<div ref="waveformArea"><WaveformViewport :state="wave" :spectrogram-loader="specLoader"><template #annotations="{x,start,end}"><g v-if="table" class="m02-wave-annotations" pointer-events="none"><g v-for="(tier,index) in selectedTiers" :key="tier"><g v-for="run in annotationRuns(table,tier,start,end)" :key="run.start"><path :d="'M'+x(run.start)+' 0V90'" stroke="var(--warning)" stroke-dasharray="3 4" vector-effect="non-scaling-stroke"/><text class="ipa-text" v-if="run.text&&!['sil','<sil>','eps','nan'].includes(run.text.toLowerCase())" :x="x((run.start+run.end)/2)" :y="14+index*14" text-anchor="middle" fill="var(--text)" font-size="12"><title>{{tier}}</title>{{run.text}}</text></g></g></g></template></WaveformViewport></div>
<div class="m02-toolbar"><label>时间窗起点（秒）<input type="number" min="0" :max="wave.asset.duration-wave.asset.duration/wave.zoom" step=".001" :value="wave.offset" @change="wave.offset=Math.max(0,Math.min(wave.asset!.duration-wave.asset!.duration/wave.zoom,Number(($event.target as HTMLInputElement).value)||0))"/></label><label>时间窗长度（秒）<input type="number" min=".01" :max="wave.asset.duration" step=".001" :value="wave.asset.duration/wave.zoom" @change="wave.zoom=wave.asset!.duration/Math.max(.01,Math.min(wave.asset!.duration,Number(($event.target as HTMLInputElement).value)||wave.asset!.duration));wave.offset=Math.min(wave.offset,wave.asset!.duration-wave.asset!.duration/wave.zoom)"/></label><small>全长 {{wave.asset.duration.toFixed(3)}} s · 选区 {{Math.abs(wave.end-wave.start).toFixed(3)}} s</small></div>
<template v-if="table"><div v-for="group in groups" v-show="maximized===null||maximized===group.id" :key="group.id" :class="{'m02-maximized':maximized===group.id}"><ParameterFigure :table="table" :group="group" :wave="wave" :waveform="()=>waveformArea"><button @click="maximized=maximized===group.id?null:group.id">{{maximized===group.id?'还原图窗':'放大图窗'}}</button><button v-if="groups.length>1" @click="remove(group.id)">合并回首图</button></ParameterFigure></div></template>
</template><p v-else class="empty-small">选择音频后，在此显示波形及参数图。</p></div>
<aside class="parameter-summary"><h2>参数与图窗</h2><label>参数栏宽度<input v-model.number="rightWidth" type="range" min="200" max="360" aria-label="参数列宽"/></label><input v-model="search" placeholder="搜索参数" aria-label="参数搜索"/><div class="m02-toolbar"><label><input v-model="reaper" type="checkbox"/>reaper</label><label><input v-model="correction" type="checkbox"/>correction</label></div><p class="muted">筛选只改变候选列表，保留已有图窗和勾选。</p><div class="m02-toolbar"><button @click="markVisible" :disabled="!visible.length">全选可见参数</button><button @click="marked=[]">清空勾选</button></div><div class="m02-parameters"><label v-for="name in visible" :key="name"><input v-model="marked" :value="name" type="checkbox"/>{{name}}</label></div><p v-if="table&&!visible.length" class="muted">无匹配参数 <button @click="search='';reaper=true;correction=true">清除筛选</button></p>
<label>目标图窗<select v-model.number="target" aria-label="目标图窗"><option v-for="group in groups" :key="group.id" :value="group.id">{{group.title}}</option></select></label><button @click="addGroup">新建图窗</button><button class="primary" @click="assign" :disabled="!marked.length">将 {{marked.length}} 项分配到图窗</button><button @click="groups=groups.map(g=>({...g,parameters:g.parameters.filter(p=>!marked.includes(p))}))" :disabled="!marked.length">从图中移除勾选项</button><p class="muted">默认将多条参数曲线叠加在同一绘图区，用颜色和图例区分。分配到不同图窗后才分开绘制，时间范围和选区同步。</p></aside></div></section></template>
<style scoped>
.m02-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:8px 0}.m02-columns{display:grid;grid-template-columns:var(--m02-left) minmax(0,1fr) var(--m02-right);gap:12px;min-height:0;overflow:auto}.m02-columns>aside,.m02-columns>.signal-panel{min-width:0;padding:12px;overflow:auto}.m02-columns label{display:block}.m02-columns input:not([type=checkbox]),.m02-columns select{max-width:100%;width:100%}.m02-files{display:grid;gap:4px}.m02-files button{text-align:left;overflow-wrap:anywhere}.m02-parameters{max-height:48vh;overflow:auto}.m02-parameters label{padding:5px 0;overflow-wrap:anywhere}.parameter-summary>button{margin-top:8px;width:100%}.m02-maximized{position:fixed;inset:24px;z-index:40;background:var(--panel);border:1px solid var(--border);border-radius:var(--radius);padding:16px;overflow:auto}.signal-panel{background:var(--panel)}@media(max-width:1100px){.m02-columns{grid-template-columns:minmax(0,1fr)}.m02-files{max-height:170px;overflow:auto}.m02-parameters{max-height:260px}}
</style>
