const fragment=location.hash.slice(1);
export const session = /^[a-f0-9]{64}$/.test(fragment)?fragment:sessionStorage.getItem('ptb-manual-session') ?? '';
if(fragment){sessionStorage.setItem('ptb-manual-session',session);history.replaceState(null,'',location.pathname);}
export async function api(route:string,body?:unknown):Promise<any>{const response=await fetch('/api/'+route,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+session,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!response.ok){const result=await response.json();throw Object.assign(new Error(result.error||'作者接口失败'),{status:response.status,...result});}return response.json();}
export const assetUrl=(asset:{path:string})=>'/media/'+asset.path.split('/').map(encodeURIComponent).join('/')+'?session='+session;
export const readingAssetUrl=(asset:{path:string},distribution:string)=>'/'+(distribution==='public'?'reading-public':'reading')+'/'+asset.path.split('/').map(encodeURIComponent).join('/')+'?session='+session;
export async function bundleExport(distribution:string){const response=await fetch('/api/export?distribution='+distribution,{headers:{Authorization:'Bearer '+session}});if(!response.ok)throw new Error((await response.json()).error);const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=distribution==='public'?'说明书-公开内容.ptbmanual.gz':'说明书-完整工程.ptbmanual.gz';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return Number(response.headers.get('X-Skipped-Assets')??0);}
export function fileBase64(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}
export async function mediaMetadata(file:File,kind:string):Promise<Record<string,number>>{
  const url=URL.createObjectURL(file),metadata:Record<string,number>={};
  try{await new Promise<void>(resolve=>{const timeout=setTimeout(resolve,4000);if(kind==='image'){const image=new Image();image.onload=()=>{metadata.width=image.naturalWidth;metadata.height=image.naturalHeight;clearTimeout(timeout);resolve();};image.onerror=()=>{clearTimeout(timeout);resolve();};image.src=url;}else{const element=document.createElement(kind==='video'?'video':'audio');element.preload='metadata';element.onloadedmetadata=()=>{if(Number.isFinite(element.duration))metadata.duration=element.duration;if(element instanceof HTMLVideoElement){metadata.width=element.videoWidth;metadata.height=element.videoHeight;}element.removeAttribute('src');element.load();clearTimeout(timeout);resolve();};element.onerror=()=>{clearTimeout(timeout);resolve();};element.src=url;}});
    if(/\.wav$/i.test(file.name)){const view=new DataView(await file.arrayBuffer());if(view.byteLength>=36&&view.getUint32(0,false)===0x52494646){let offset=12;while(offset+8<=view.byteLength){const size=view.getUint32(offset+4,true);if(view.getUint32(offset,false)===0x666d7420&&size>=16&&offset+24<=view.byteLength){metadata.channels=view.getUint16(offset+10,true);metadata.sampleRate=view.getUint32(offset+12,true);break;}offset+=8+size+(size%2);}}}
  }finally{URL.revokeObjectURL(url);}return metadata;
}
