<script setup lang="ts">
import { computed, shallowRef, ref, onMounted, onBeforeUnmount, watch, nextTick } from 'vue';
import { Editor, EditorContent } from '@tiptap/vue-3';
import type { JSONContent } from '@tiptap/core';
import { NodeSelection, TextSelection } from '@tiptap/pm/state';
import { closeHistory } from '@tiptap/pm/history';
import ManualDocument from '../../../frontend/src/manual/ManualDocument.vue';
import type { ManualProject, ManualChapter, ManualNode, ManualAsset, ManualTarget } from '../../../frontend/src/manual/types';
import { extensions, unknownTypes } from './extensions';
import { toEditorDocument, fromEditorDocument, sourceNodeType } from './document-codec';
import { api, assetUrl, readingAssetUrl, bundleExport, fileBase64, mediaMetadata } from './api';
import { bindPageLifetime } from './page-lifetime';

interface Snapshot {path:string;project:ManualProject;chapters:ManualChapter[];revision:string;unsupported?:{chapterId:string;type:string}[]}
const snapshot=ref<Snapshot>(),project=computed(()=>snapshot.value?.project),chapterId=ref(''),editor=shallowRef<Editor>();
const current=computed(()=>snapshot.value?.chapters.find(c=>c.id===chapterId.value)),chapterDescriptor=computed(()=>project.value?.chapters.find(c=>c.id===chapterId.value));
const pathInput=ref(''),titleInput=ref('PhoneticToolbox 使用说明书'),status=ref('请选择说明书工程'),error=ref(''),dirty=ref(false),saving=ref(false),lastSaved=ref(''),unsupported=ref<string[]>([]);
const generated=ref<any>(),previewSource=ref('live'),generatedChapter=computed(()=>generated.value?.chapters.find((c:ManualChapter)=>c.id===chapterId.value)),previewChapter=computed(()=>previewSource.value==='generated'?generatedChapter.value:current.value),previewAssets=computed(()=>previewSource.value==='generated'?generated.value?.project.assets??[]:project.value?.assets??[]),previewReferences=computed(()=>previewSource.value==='generated'?generated.value?.project.references??[]:project.value?.references??[]),previewAssetUrl=(asset:ManualAsset)=>previewSource.value==='generated'?readingAssetUrl(asset,generated.value?.distribution??'software'):assetUrl(asset);
const preview=ref(true),dark=ref(false),previewWidth=ref('auto'),sourceVisible=ref(false),sourceDraft=ref(''),inspector=ref('block'),inspectorOpen=ref(false),selected=ref<{type:string;attrs:Record<string,any>;pos:number}>(),recoveryItems=ref<any[]>([]),recoveryVisible=ref(false),mediaInput=ref<HTMLInputElement>(),importInput=ref<HTMLInputElement>(),formatRevision=ref(0),searchText=ref(''),replaceText=ref(''),autoSave=ref(true),selectedAssetId=ref('');
const askText=window.prompt.bind(window);
let autoTimer:ReturnType<typeof setTimeout>|undefined,draftTimer:ReturnType<typeof setTimeout>|undefined,projectGeneration=0,unmounted=false;
let stopPageLifetime:(()=>void)|undefined;
const clone=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const newId=(prefix:string)=>prefix+'-'+crypto.randomUUID();
const emptyDoc=():ManualNode=>({type:'doc',content:[{type:'paragraph'}]});
const arrangeUndo:Snapshot[]=[];
function arrangeHistory(){if(snapshot.value){arrangeUndo.push(clone(snapshot.value));if(arrangeUndo.length>60)arrangeUndo.shift();}}
function editorStorage(){if(editor.value)(editor.value.storage as any).manualAssets={assets:project.value?.assets??[],resolve:assetUrl};}
function selectedState(){if(!editor.value)return;formatRevision.value++;const sel=editor.value.state.selection,node=sel instanceof NodeSelection?sel.node:sel.$from.parent,pos=sel instanceof NodeSelection?sel.from:(sel.$from.depth>0?sel.$from.before(sel.$from.depth):0);selected.value={type:sourceNodeType(node.type.name),attrs:clone(node.attrs),pos};}
function collectSections(chapter:ManualChapter){const sections:any[]=[];const walk=(node:ManualNode)=>{if(node.type==='heading'&&node.attrs?.id)sections.push({id:node.attrs.id,title:(node.content??[]).map(c=>c.text??'').join(''),level:node.attrs.level??2});for(const child of node.content??[])walk(child);};walk(chapter.body);return sections;}
function syncEditor(){if(current.value&&editor.value&&!unsupported.value.length){current.value.body=fromEditorDocument(editor.value.getJSON()) as ManualNode;const descriptor=chapterDescriptor.value;if(descriptor)descriptor.sections=collectSections(current.value);}}
function markDirty(){dirty.value=true;status.value='尚未保存 · 自动保存等待中';error.value='';clearTimeout(autoTimer);clearTimeout(draftTimer);const generation=projectGeneration;
  draftTimer=setTimeout(()=>{if(generation===projectGeneration&&snapshot.value)void api('draft',payload()).catch(e=>{error.value='磁盘恢复稿保存失败：'+e.message;});},400);
  if(autoSave.value)autoTimer=setTimeout(()=>{if(generation===projectGeneration)void save();},1200);
}
function payload(){syncEditor();return {project:clone(project.value),chapters:clone(snapshot.value?.chapters??[]),baseRevision:snapshot.value?.revision};}
function createEditor(){editor.value?.destroy();unsupported.value=current.value?unknownTypes(current.value.body as JSONContent):[];
  const serverUnknown=snapshot.value?.unsupported?.filter(x=>x.chapterId===chapterId.value).map(x=>x.type)??[];unsupported.value=[...new Set([...unsupported.value,...serverUnknown])];
  if(!current.value||unsupported.value.length){editor.value=undefined;return;}
  const instance=new Editor({extensions:extensions(project.value?.assets??[],assetUrl),content:toEditorDocument(clone(current.value.body) as JSONContent),editorProps:{attributes:{'aria-label':'章节正文','lang':'zh-CN'},handlePaste(_view,event){const file=[...(event.clipboardData?.files??[])].find(f=>f.type.startsWith('image/'));if(file){event.preventDefault();void importMedia(file,'image');return true;}return false;},handleDrop(_view,event){const file=event.dataTransfer?.files[0];if(file&&/^(image|audio|video)\//.test(file.type)){event.preventDefault();void importMedia(file,file.type.split('/')[0]);return true;}return false;}},onUpdate(){syncEditor();markDirty();selectedState();},onSelectionUpdate(){selectedState();},onTransaction(){formatRevision.value++;}});
  editor.value=instance;editorStorage();selectedState();
}
function applySnapshot(value:Snapshot){clearTimeout(autoTimer);clearTimeout(draftTimer);projectGeneration++;generated.value=undefined;previewSource.value='live';snapshot.value=value;pathInput.value=value.path;chapterId.value=value.project.chapters.some(c=>c.id===chapterId.value)?chapterId.value:value.project.chapters[0]?.id??'';dirty.value=false;error.value='';status.value='磁盘内容已读取';lastSaved.value=new Date().toLocaleTimeString('zh-CN');arrangeUndo.splice(0);createEditor();}
async function run(action:()=>Promise<any>){error.value='';try{return await action();}catch(e:any){error.value=e.message;status.value='操作未完成';return null;}}
async function openProject(create=false){if(dirty.value&&!await save())return;const value=await run(()=>api(create?'create':'open',{path:pathInput.value,title:titleInput.value}));if(value)applySnapshot(value);}
let savePromise:Promise<boolean>|undefined;
async function save():Promise<boolean>{if(savePromise){const okay=await savePromise;if(!okay)return false;return dirty.value?save():true;}savePromise=performSave().finally(()=>{savePromise=undefined;});return savePromise;}
async function performSave(){if(!snapshot.value)return false;clearTimeout(autoTimer);clearTimeout(draftTimer);saving.value=true;status.value='正在保存到磁盘…';
  const generation=projectGeneration,document=payload(),fingerprint=JSON.stringify(document);try{const result=await api('save',document);if(generation!==projectGeneration)return false;snapshot.value.revision=result.revision;if(editor.value)editor.value.view.dispatch(closeHistory(editor.value.state.tr));lastSaved.value=new Date().toLocaleTimeString('zh-CN');const latest=payload();latest.baseRevision=document.baseRevision;dirty.value=JSON.stringify(latest)!==fingerprint;status.value=dirty.value?'磁盘已保存，仍有新的编辑':'已保存到磁盘 · '+lastSaved.value;if(dirty.value&&autoSave.value)autoTimer=setTimeout(()=>void save(),1200);return true;}catch(e:any){error.value=e.message;status.value=e.status===409?'存在外部修改 · 当前稿已存为恢复稿':'保存失败 · 当前编辑仍保留';return false;}finally{saving.value=false;}}
async function selectChapter(id:string){if(id===chapterId.value)return;if(dirty.value&&!await save())return;syncEditor();chapterId.value=id;createEditor();}
function ensureChapter(){if(!project.value||!snapshot.value)return;arrangeHistory();const id=newId('chapter'),chapter:ManualChapter={schemaVersion:'ptb-manual-chapter/1',id,title:'新章节',body:emptyDoc()};project.value.chapters.push({id,title:chapter.title,path:`chapters/${id}.json`,status:'draft'});snapshot.value.chapters.push(chapter);chapterId.value=id;createEditor();markDirty();}
function renameChapter(){if(current.value&&chapterDescriptor.value){chapterDescriptor.value.title=current.value.title;markDirty();}}
function reorder(direction:number){if(!project.value)return;const index=project.value.chapters.findIndex(c=>c.id===chapterId.value),target=index+direction;if(target<0||target>=project.value.chapters.length)return;arrangeHistory();const [item]=project.value.chapters.splice(index,1);project.value.chapters.splice(target,0,item);markDirty();}
function duplicateChapter(){if(!current.value||!snapshot.value||!project.value)return;syncEditor();arrangeHistory();const id=newId('chapter'),chapter=clone(current.value);chapter.id=id;chapter.title+='（副本）';const renew=(node:ManualNode)=>{if(node.attrs?.id)node.attrs.id=newId(node.type);for(const child of node.content??[])renew(child);};renew(chapter.body);snapshot.value.chapters.push(chapter);const index=project.value.chapters.findIndex(c=>c.id===chapterId.value);project.value.chapters.splice(index+1,0,{id,title:chapter.title,path:`chapters/${id}.json`,moduleId:chapter.moduleId,status:'draft'});chapterId.value=id;createEditor();markDirty();}
function removeChapter(){if(!current.value||!project.value||!snapshot.value)return;if(!confirm('从目录撤下此章节？正文文件和素材会保留在工程中，可以通过撤销编排恢复。'))return;arrangeHistory();const index=project.value.chapters.findIndex(c=>c.id===chapterId.value);project.value.chapters.splice(index,1);snapshot.value.chapters=snapshot.value.chapters.filter(c=>c.id!==chapterId.value);chapterId.value=project.value.chapters[Math.min(index,project.value.chapters.length-1)]?.id??'';createEditor();markDirty();}
function undoArrangement(){const value=arrangeUndo.pop();if(!value||!snapshot.value)return;const revision=snapshot.value.revision;snapshot.value=value;snapshot.value.revision=revision;chapterId.value=value.project.chapters.some(c=>c.id===chapterId.value)?chapterId.value:value.project.chapters[0]?.id??'';createEditor();markDirty();}
function splitChapter(){if(!current.value||!project.value||!snapshot.value||!editor.value)return;syncEditor();const pos=editor.value.state.selection.$from,index=pos.index(0);const blocks=current.value.body.content??[];if(index<1||index>=blocks.length){error.value='请把光标放到需要成为新章开头的段落中，第一段不可拆分。';return;}arrangeHistory();const id=newId('chapter'),chapter={...clone(current.value),id,title:current.value.title+'（续）',body:{type:'doc',content:blocks.splice(index)}};snapshot.value.chapters.push(chapter);const position=project.value.chapters.findIndex(c=>c.id===chapterId.value);project.value.chapters.splice(position+1,0,{id,title:chapter.title,path:`chapters/${id}.json`,moduleId:chapter.moduleId,status:'draft'});createEditor();markDirty();}
function mergeNext(){if(!current.value||!project.value||!snapshot.value)return;const index=project.value.chapters.findIndex(c=>c.id===chapterId.value),next=project.value.chapters[index+1],chapter=next&&snapshot.value.chapters.find(c=>c.id===next.id);if(!chapter)return;syncEditor();arrangeHistory();current.value.body.content=[...(current.value.body.content??[]),...(chapter.body.content??[])];project.value.chapters.splice(index+1,1);snapshot.value.chapters=snapshot.value.chapters.filter(c=>c.id!==next.id);(project.value as any).redirects={...(project.value as any).redirects,[next.id]:chapterId.value};createEditor();markDirty();}
function command(name:string,argument?:any){const e=editor.value;if(!e)return;const chain:any=e.chain().focus();if(typeof chain[name]!=='function'){error.value='当前编辑位置不支持该操作';return;}(name==='updateAttributes' && Array.isArray(argument)?chain[name](...argument):chain[name](argument)).run();}
function insertNode(type:string,attrs:Record<string,unknown>={},content?:any[]){const node={type,attrs:{id:newId(type),...attrs},...(content?{content}:{})},e=editor.value;if(!e)return;const selection=e.state.selection;if(selection instanceof NodeSelection)e.chain().focus().insertContentAt(selection.to,node).run();else command('insertContent',node);}
function patchSelected(key:string,value:any){if(!editor.value||!selected.value)return;const node=editor.value.state.doc.nodeAt(selected.value.pos);if(!node)return;editor.value.view.dispatch(editor.value.state.tr.setNodeMarkup(selected.value.pos,undefined,{...node.attrs,[key]:value}));selectedState();}
function addColumns(){insertNode('columns',{},[{type:'column',content:[{type:'paragraph',content:[{type:'text',text:'左栏内容'}]}]},{type:'column',content:[{type:'paragraph',content:[{type:'text',text:'右栏内容'}]}]}]);}
function addNote(type:string){insertNode(type,{kind:'tip',title:'操作提示'},[{type:'paragraph',content:[{type:'text',text:type==='footnote'?'脚注内容':'提示内容'}]}]);}
function insertLink(){const href=prompt('链接地址（HTTP(S)、mailto）',editor.value?.getAttributes('link').href??'https://');if(href==null)return;if(!/^(https?:\/\/|mailto:)/i.test(href)){error.value='请输入有效的 HTTP(S) 或 mailto 链接';return;}command('setLink',{href});}
function openInspector(tab='block'){inspector.value=tab;inspectorOpen.value=true;}
function addReference(){const id=newId('ref');project.value?.references?.push({id,label:'作者（年份）',url:''});openInspector('references');markDirty();}
function insertReference(){const reference=project.value?.references?.[0];if(!reference){addReference();return;}insertNode('citation',{referenceId:reference.id,label:reference.label});}
function addCrossReference(){insertNode('crossReference',{chapterId:chapterId.value,targetId:collectSections(current.value!)[0]?.id??'',label:'参见小节'});}
function findReplace(replace=false){if(!editor.value||!searchText.value)return;const matches:{from:number;to:number}[]=[];editor.value.state.doc.descendants((node,pos)=>{if(!node.isText)return;let index=node.text!.indexOf(searchText.value);while(index>=0){matches.push({from:pos+index,to:pos+index+searchText.value.length});index=node.text!.indexOf(searchText.value,index+Math.max(1,searchText.value.length));}});if(!matches.length){status.value='未找到文字';return;}if(replace){const tr=editor.value.state.tr;for(const item of matches.reverse())tr.insertText(replaceText.value,item.from,item.to);editor.value.view.dispatch(tr);status.value=`已替换 ${matches.length} 处`;}else{const start=editor.value.state.selection.to,item=matches.find(m=>m.from>=start)??matches[0];editor.value.view.dispatch(editor.value.state.tr.setSelection(TextSelection.create(editor.value.state.doc,item.from,item.to)));editor.value.commands.focus();status.value=`找到 ${matches.length} 处`;}}
async function importMedia(file:File,kind:string){if(!snapshot.value)return;try{if(dirty.value&&!await save())return;const result=await api('asset',{baseRevision:snapshot.value.revision,name:file.name,data:await fileBase64(file),kind,distribution:'software-only',sourceType:kind==='audio'?'未分类':'作者导入',source:''});snapshot.value.revision=result.snapshot.revision;snapshot.value.project.assets=result.snapshot.project.assets;Object.assign(snapshot.value.project.assets.find(a=>a.id===result.asset.id)!,await mediaMetadata(file,kind));editorStorage();insertNode(kind,{assetId:result.asset.id,caption:'',alt:kind==='image'?file.name:'',width:kind==='image'?'100%':null});selectedAssetId.value=result.asset.id;openInspector('assets');}catch(e:any){error.value=e.message;}}
function mediaPicked(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file){let kind=/^image\//.test(file.type)?'image':/^audio\//.test(file.type)?'audio':/^video\//.test(file.type)?'video':'';if(!kind)kind=/\.(wav|mp3|flac|ogg|m4a)$/i.test(file.name)?'audio':/\.(mp4|webm|mov)$/i.test(file.name)?'video':'image';void importMedia(file,kind);}(event.target as HTMLInputElement).value='';}
async function exportProject(mode='software'){if(dirty.value&&!await save())return;await run(async()=>{const skipped=await bundleExport(mode);status.value=mode==='public'?`公开内容包已导出，跳过 ${skipped} 份受限素材`:'完整工程包已导出，含正文与全部工程素材';});}
async function importProject(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const target=prompt('把工程包导入到新的空目录（绝对路径）');if(target){const value=await run(()=>fileBase64(file).then(data=>api('import',{path:target,data})));if(value)applySnapshot(value);}(event.target as HTMLInputElement).value='';}
async function buildReading(){if(dirty.value&&!await save())return;await run(async()=>{const result=await api('build',{});generated.value=result;previewSource.value='generated';status.value='阅读资源已生成：'+result.path;});}
async function showRecovery(){const items=await run(()=>api('recovery'));if(items){recoveryItems.value=items;recoveryVisible.value=true;}}
async function loadRecovery(id:string){if(dirty.value&&!confirm('加载恢复稿会替换当前页面内容。当前稿可先保存或导出。继续？'))return;const value=await run(()=>api('recovery/'+id));if(value&&snapshot.value){arrangeHistory();snapshot.value.project=value.project;snapshot.value.chapters=value.chapters;chapterId.value=value.project.chapters[0]?.id??'';createEditor();markDirty();recoveryVisible.value=false;status.value='恢复稿已载入，请检查后保存';}}
function showSource(){syncEditor();sourceDraft.value=JSON.stringify(current.value,null,2);sourceVisible.value=true;}
async function applySource(){try{const chapter=JSON.parse(sourceDraft.value);if(chapter.id!==chapterId.value||chapter.schemaVersion!=='ptb-manual-chapter/1'||chapter.body?.type!=='doc')throw new Error('章节版本、ID 或正文结构无效');const unknown=unknownTypes(chapter.body);if(unknown.length)throw new Error('尚不支持的节点：'+unknown.join('、'));const candidate=clone(payload());candidate.chapters=candidate.chapters.map((c:ManualChapter)=>c.id===chapter.id?chapter:c);candidate.project!.chapters=candidate.project!.chapters.map((d:any)=>d.id===chapter.id?{...d,title:chapter.title}:d);await api('draft',candidate);const index=snapshot.value!.chapters.findIndex(c=>c.id===chapter.id);snapshot.value!.chapters[index]=chapter;chapterDescriptor.value!.title=chapter.title;createEditor();markDirty();sourceVisible.value=false;}catch(e:any){error.value='结构没有应用：'+e.message;}}
function sourceDownload(){const blob=new Blob([JSON.stringify(current.value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=chapterId.value+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function navigate(target:ManualTarget){if(target.chapterId!==chapterId.value)await selectChapter(target.chapterId);await nextTick();if(target.targetId)document.querySelector('.reading-preview [id="'+CSS.escape(target.targetId)+'"]')?.scrollIntoView({block:'center'});}
function blockMove(direction:number){if(!editor.value)return;const selection=editor.value.state.selection,index=selection.$from.index(0),body=editor.value.getJSON(),nodes=body.content??[],target=index+direction;if(target<0||target>=nodes.length)return;const item=nodes.splice(index,1)[0];nodes.splice(target,0,item);editor.value.commands.setContent(body,{emitUpdate:true});}
function keyboard(event:KeyboardEvent){if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();void save();}}
function beforeUnload(event:BeforeUnloadEvent){if(dirty.value){event.preventDefault();event.returnValue='';}}
async function closeTool(){if(dirty.value&&!await save())return;await run(async()=>{await api('close',{});stopPageLifetime?.();clearTimeout(autoTimer);clearTimeout(draftTimer);status.value='作者工具已退出，可以关闭此页面。';editor.value?.setEditable(false,false);});}
watch(dark,value=>{document.documentElement.classList.toggle('dark',value);document.documentElement.dataset.theme=value?'dark':'light';});
onMounted(async()=>{window.addEventListener('keydown',keyboard);window.addEventListener('beforeunload',beforeUnload);stopPageLifetime=bindPageLifetime(message=>{error.value=message;});const result=await run(()=>api('session'));if(result?.snapshot)applySnapshot(result.snapshot);});
onBeforeUnmount(()=>{unmounted=true;stopPageLifetime?.();clearTimeout(autoTimer);clearTimeout(draftTimer);editor.value?.destroy();window.removeEventListener('keydown',keyboard);window.removeEventListener('beforeunload',beforeUnload);});
const activeAsset=computed(()=>project.value?.assets.find(a=>a.id===selectedAssetId.value));
const buttons=[['toggleBold','粗体','B'],['toggleItalic','斜体','I'],['toggleUnderline','下划线','U'],['toggleStrike','删除线','S'],['toggleSubscript','下标','x₂'],['toggleSuperscript','上标','x²'],['toggleCode','行内代码','<>'],['toggleMark','IPA 样式','IPA']] as const;
const isActive=(name:string)=>{formatRevision.value;const mapped:{[key:string]:string}={toggleBold:'bold',toggleItalic:'italic',toggleUnderline:'underline',toggleStrike:'strike',toggleSubscript:'subscript',toggleSuperscript:'superscript',toggleCode:'code',toggleMark:'ipa'};return !!editor.value?.isActive(mapped[name]??name);};
const inputValue=(event:Event)=>(event.target as HTMLInputElement).value;
</script>

<template>
  <main class="studio">
    <header class="studio-header"><div class="brand"><span class="brand-mark">文</span><div><strong>说明书作者工作室</strong><small>PHONETICTOOLBOX · MANUAL STUDIO</small></div></div><span class="save-state" :class="{dirty}">{{ status }}</span><div class="header-actions"><button @click="dark=!dark">{{ dark?'浅色':'深色' }}</button><button @click="preview=!preview">{{ preview?'收起预览':'正式预览' }}</button><button :disabled="!snapshot" :class="{active:inspectorOpen}" :aria-expanded="inspectorOpen" aria-controls="editor-inspector" aria-label="排版、素材与文献" title="排版、素材与文献" @mousedown.prevent @click="inspectorOpen=!inspectorOpen">编辑工具</button><button :disabled="!snapshot||saving" class="primary" @click="save">保存 Ctrl+S</button><button @click="closeTool">退出工具</button></div></header>
    <div v-if="error" class="error-banner" role="alert">{{ error }}<button @click="error=''">收起</button></div>
    <section v-if="!snapshot" class="project-welcome"><span class="eyebrow">一份工程，持续写作</span><h1>打开你的说明书</h1><p>正文、图片和声音保存在工程目录中，阅读预览与软件内的正式说明书共用同一组件。</p><label>工程目录<input v-model="pathInput" placeholder="D:\PhoneticToolbox\PhoneticToolbox_v3\manual" aria-label="工程目录"></label><label>新工程标题<input v-model="titleInput" aria-label="新工程标题"></label><div><button class="primary" @click="openProject()">打开工程</button><button @click="openProject(true)">建立空工程</button><button @click="importInput?.click()">导入工程包</button></div><p class="muted">新建和导入须使用空目录，已有文件不会被覆盖。</p></section>
    <section v-else class="workspace" :class="{'preview-hidden':!preview,'inspector-open':inspectorOpen}">
      <aside class="chapter-sidebar"><div class="sidebar-title"><strong>章节目录</strong><button title="新建章节" aria-label="新建章节" @click="ensureChapter">＋</button></div><div class="project-caption">{{ project?.title }}</div><nav class="chapter-list"><button v-for="(item,index) in project?.chapters" :key="item.id" :class="{selected:item.id===chapterId}" @click="selectChapter(item.id)"><span>{{ String(index+1).padStart(2,'0') }}</span><div>{{ item.title }}<small>{{ item.moduleId || '公共章节' }} · {{ item.status || 'draft' }}</small></div></button></nav><div class="chapter-actions"><button @click="reorder(-1)">上移</button><button @click="reorder(1)">下移</button><button @click="duplicateChapter">复制</button><button @click="removeChapter">撤下</button><button @click="splitChapter">拆分</button><button @click="mergeNext">合并下一章</button><button class="wide" @click="undoArrangement">撤销编排</button></div><details class="engineering" open><summary>工程管理</summary><button @click="showRecovery">磁盘恢复稿</button><button @click="exportProject()">导出完整工程</button><button @click="exportProject('public')">导出公开内容</button><button @click="importInput?.click()">导入工程包</button><button @click="buildReading">生成阅读资源</button><button @click="openProject()">重新读取磁盘</button><label><input v-model="autoSave" type="checkbox"> 自动保存到磁盘</label><input v-model="pathInput" aria-label="切换工程目录"><button @click="openProject()">切换工程</button><small class="project-path">{{ snapshot.path }}</small></details></aside>
      <section class="author-pane"><div v-if="current" class="chapter-heading"><input v-model="current.title" aria-label="章节标题" @input="renameChapter"><div><input v-model="current.moduleId" aria-label="模块ID" placeholder="M08 / 公共章" @input="chapterDescriptor!.moduleId=current.moduleId;markDirty()"><select v-model="chapterDescriptor!.status" aria-label="章节状态" @change="markDirty"><option value="draft">草稿</option><option value="verified">已核验</option><option value="in_progress">修订中</option><option value="planned">预留</option></select><button @click="showSource">结构源码</button><button @click="sourceDownload">导出本章</button></div></div>
        <template v-if="current"><div v-if="unsupported.length" class="unknown-content"><h2>此章节含尚不支持的内容</h2><p>{{ unsupported.join('、') }}</p><p>原始 JSON 保持完整。请通过结构源码修订，或导出本章交给维护者处理。</p><button @click="showSource">打开结构源码</button><button @click="sourceDownload">导出原始章节</button></div>
        <template v-else><div class="toolbar" role="toolbar" aria-label="富文本工具栏"><div class="toolbar-row"><button title="撤销" aria-label="撤销" @mousedown.prevent @click="command('undo')">↶</button><button title="重做" aria-label="重做" @mousedown.prevent @click="command('redo')">↷</button><span class="separator"></span><select aria-label="段落类型" @change="inputValue($event)==='paragraph'?command('setParagraph'):command('toggleHeading',{level:Number(inputValue($event))})"><option value="paragraph">正文段落</option><option value="1">一级标题</option><option value="2">二级标题</option><option value="3">三级标题</option><option value="4">四级标题</option></select><button v-for="[name,label,symbol] in buttons" :key="name" :title="label" :aria-label="label" :class="{active:isActive(name)}" @mousedown.prevent @click="command(name,name==='toggleMark'?'ipa':undefined)">{{ symbol }}</button><button title="清除文字格式" @mousedown.prevent @click="command('unsetAllMarks')">清格式</button></div>
        <div class="toolbar-row"><select aria-label="字体" @change="command('setFontFamily',inputValue($event))"><option value="SimSun">宋体</option><option value="Microsoft YaHei">微软雅黑</option><option value="Times New Roman">Times</option><option value="JetBrains Mono">等宽</option><option value="Doulos SIL">Doulos SIL</option></select><select aria-label="字号" @change="command('setFontSize',inputValue($event))"><option value="16px">字号 16</option><option v-for="size in [10,12,14,18,20,24,28,32,40,48]" :key="size" :value="size+'px'">{{ size }} px</option></select><label class="color-tool" title="文字颜色">字色<input type="color" aria-label="文字颜色" @input="command('setColor',inputValue($event))"></label><label class="color-tool" title="背景强调">强调<input type="color" value="#fff1b0" aria-label="背景强调" @input="command('setHighlight',{color:inputValue($event)})"></label><span class="separator"></span><button v-for="[align,label] in [['left','左'],['center','中'],['right','右'],['justify','两端']]" :key="align" :aria-label="label+'对齐'" @mousedown.prevent @click="command('setTextAlign',align)">{{ label }}</button><button @mousedown.prevent @click="command('toggleBulletList')">• 列表</button><button @mousedown.prevent @click="command('toggleOrderedList')">1. 列表</button><button @mousedown.prevent @click="command('toggleBlockquote')">引用段</button></div>
        <div class="toolbar-row"><button @click="mediaInput?.click()">图 / 音频 / 视频</button><button @mousedown.prevent @click="command('insertTable',{rows:3,cols:3,withHeaderRow:true})">表格</button><button @mousedown.prevent @click="insertNode('formula',{latex:'f_0 = 1 / T',display:true})">公式</button><button @mousedown.prevent @click="command('toggleCodeBlock')">代码块</button><button @mousedown.prevent @click="insertLink">链接</button><button @mousedown.prevent @click="addCrossReference">交叉引用</button><button @mousedown.prevent @click="insertReference">文献</button><button @mousedown.prevent @click="addNote('footnote')">脚注</button><button @mousedown.prevent @click="addColumns">双栏</button><button @mousedown.prevent @click="addNote('admonition')">提示框</button><button @mousedown.prevent @click="command('setHorizontalRule')">分隔线</button></div></div>
        <div class="editing-area"><EditorContent :editor="editor" /></div></template></template><div v-else class="empty-editor"><h2>从第一章开始</h2><button class="primary" @click="ensureChapter">新建章节</button></div>
      </section>
      <aside v-if="inspectorOpen" id="editor-inspector" class="inspector-pane" aria-label="编辑工具栏"><div class="inspector-tabs"><button v-for="[key,label] in [['block','排版'],['assets','素材'],['references','文献']]" :key="key" :class="{active:inspector===key}" @click="inspector=key">{{ label }}</button><button class="inspector-close" aria-label="收起编辑工具" @click="inspectorOpen=false">收起</button></div>
        <section v-if="inspector==='block'" class="properties"><strong>{{ selected?.type || '段落' }} 属性</strong><template v-if="selected"><label>稳定锚点<input :value="selected.attrs.id || ''" @change="patchSelected('id',inputValue($event)||null)"></label><template v-if="['image','audio','video'].includes(selected.type)"><label>素材<select :value="selected.attrs.assetId" @change="patchSelected('assetId',inputValue($event))"><option v-for="asset in project?.assets.filter(a=>a.kind===selected!.type)" :key="asset.id" :value="asset.id">{{ asset.title||asset.id }}</option></select></label><label>标题 / 图注<textarea :value="selected.attrs.caption" @input="patchSelected('caption',inputValue($event))"></textarea></label><label>替代文字<input :value="selected.attrs.alt" @input="patchSelected('alt',inputValue($event))"></label><label>显示宽度<input :value="selected.attrs.width" placeholder="100% / 480px" @change="patchSelected('width',inputValue($event))"></label><label>对齐<select :value="selected.attrs.align" @change="patchSelected('align',inputValue($event))"><option value="left">左</option><option value="center">中</option><option value="right">右</option></select></label></template>
        <template v-if="selected.type==='formula'"><label>LaTeX 公式<textarea :value="selected.attrs.latex" @input="patchSelected('latex',inputValue($event))"></textarea></label></template>
        <template v-if="selected.type==='crossReference'"><label>章节<select :value="selected.attrs.chapterId" @change="patchSelected('chapterId',inputValue($event))"><option v-for="item in project?.chapters" :key="item.id" :value="item.id">{{ item.title }}</option></select></label><label>目标锚点<input :value="selected.attrs.targetId" @input="patchSelected('targetId',inputValue($event))"></label><label>显示文字<input :value="selected.attrs.label" @input="patchSelected('label',inputValue($event))"></label></template>
        <template v-if="selected.type==='citation'"><label>文献<select :value="selected.attrs.referenceId" @change="patchSelected('referenceId',inputValue($event))"><option v-for="item in project?.references" :key="item.id" :value="item.id">{{ item.label }}</option></select></label><label>引用文字<input :value="selected.attrs.label" @input="patchSelected('label',inputValue($event))"></label></template>
        <template v-if="['paragraph','heading','tableCell','tableHeader'].includes(selected.type)"><label>行距<input :value="selected.attrs.lineHeight || ''" placeholder="1.75" @change="patchSelected('lineHeight',inputValue($event)||null)"></label><label>段前<input :value="selected.attrs.marginTop || ''" placeholder="0.5em" @change="patchSelected('marginTop',inputValue($event)||null)"></label><label>段后<input :value="selected.attrs.marginBottom || ''" placeholder="0.75em" @change="patchSelected('marginBottom',inputValue($event)||null)"></label><label>缩进级数<input type="number" min="0" max="12" :value="selected.attrs.indent || 0" @change="patchSelected('indent',Number(inputValue($event)))"></label><label>底色<input type="color" :value="selected.attrs.backgroundColor || '#ffffff'" @input="patchSelected('backgroundColor',inputValue($event))"></label></template>
        <template v-if="selected.type==='codeBlock'"><label>代码语言<input :value="selected.attrs.language || ''" @input="patchSelected('language',inputValue($event))"></label></template>
        <template v-if="selected.type==='admonition'"><label>提示类别<select :value="selected.attrs.kind" @change="patchSelected('kind',inputValue($event))"><option value="tip">操作提示</option><option value="condition">条件说明</option><option value="result">结果解释</option><option value="limitation">限制</option></select></label></template>
        </template><details open><summary>表格操作</summary><div class="table-tools"><button v-for="[name,label] in [['addRowBefore','前加行'],['addRowAfter','后加行'],['deleteRow','删行'],['addColumnBefore','前加列'],['addColumnAfter','后加列'],['deleteColumn','删列'],['mergeCells','合并格'],['splitCell','拆分格'],['toggleHeaderRow','表头行'],['toggleHeaderColumn','表头列']]" :key="name" @mousedown.prevent @click="command(name)">{{ label }}</button></div><label>表题<input :value="editor?.getAttributes('table').caption || ''" @input="command('updateAttributes',['table',{caption:inputValue($event)}])"></label><button @mousedown.prevent @click="editor?.chain().focus().updateAttributes('table',{caption:askText('表题',editor.getAttributes('table').caption??'')??''}).run()">修改表题</button><button @mousedown.prevent @click="editor?.chain().focus().updateAttributes('table',{note:askText('表注',editor.getAttributes('table').note??'')??''}).run()">修改表注</button></details><details open><summary>查找与替换</summary><input v-model="searchText" aria-label="查找文字" placeholder="查找文字"><input v-model="replaceText" aria-label="替换文字" placeholder="替换为"><div class="table-tools"><button @click="findReplace()">查找下一处</button><button @click="findReplace(true)">全部替换</button></div></details><div class="table-tools"><button @mousedown.prevent @click="blockMove(-1)">块上移</button><button @mousedown.prevent @click="blockMove(1)">块下移</button></div></section>
        <section v-if="inspector==='assets'" class="properties"><strong>工程素材</strong><button @click="mediaInput?.click()">导入图音视频</button><select v-model="selectedAssetId" aria-label="素材列表"><option value="">选择素材</option><option v-for="asset in project?.assets" :key="asset.id" :value="asset.id">{{ asset.title||asset.id }}</option></select><template v-if="activeAsset"><label>名称<input v-model="activeAsset.title" @input="markDirty"></label><label>说明<textarea v-model="activeAsset.caption" @input="markDirty"></textarea></label><label>来源类型<input v-model="activeAsset.sourceType" placeholder="自然录音 / 处理结果 / 合成声音" @input="markDirty"></label><label>来源说明<textarea :value="typeof activeAsset.source==='string'?activeAsset.source:JSON.stringify(activeAsset.source??'')" @input="activeAsset.source=inputValue($event);markDirty()"></textarea></label><label>分发范围<select v-model="activeAsset.distribution" @change="activeAsset.git=activeAsset.distribution==='public';markDirty()"><option value="software-only">仅软件分发，排除公开 Git</option><option value="public">可公开内容</option></select></label><small>相对路径：{{ activeAsset.path }}<br>SHA-256：{{ activeAsset.sha256 }}</small><img v-if="activeAsset.kind==='image'" :src="assetUrl(activeAsset)" :alt="activeAsset.alt||''"><audio v-if="activeAsset.kind==='audio'" :src="assetUrl(activeAsset)" controls preload="metadata"></audio><video v-if="activeAsset.kind==='video'" :src="assetUrl(activeAsset)" controls preload="metadata"></video><button @mousedown.prevent @click="insertNode(activeAsset.kind,{assetId:activeAsset.id,caption:activeAsset.caption||''})">插入所选素材</button><details><summary>正文引用位置</summary><p v-for="chapter in snapshot.chapters.filter(c=>JSON.stringify(c.body).includes(activeAsset!.id))" :key="chapter.id"><button @click="selectChapter(chapter.id)">{{ chapter.title }}</button></p></details></template></section>
        <section v-if="inspector==='references'" class="properties"><strong>参考文献</strong><button @click="addReference">新增文献</button><article v-for="reference in project?.references" :key="reference.id" class="reference-card"><label>书目信息<input v-model="reference.label" @input="markDirty"></label><label>来源链接<input v-model="reference.url" @input="markDirty"></label><small>{{ reference.id }}</small><button @mousedown.prevent @click="insertNode('citation',{referenceId:reference.id,label:reference.label})">插入引用</button></article></section>
      </aside>
      <section v-if="preview" class="reading-preview"><header><strong>正式阅读预览</strong><select v-model="previewSource" aria-label="预览内容版本"><option value="live">源稿实时</option><option v-if="generated" value="generated">已生成阅读版</option></select><select v-model="previewWidth" aria-label="预览宽度"><option value="auto">自适应</option><option value="480px">窄栏 480</option><option value="760px">正文 760</option><option value="1024px">宽屏 1024</option></select></header><div class="reader-surface" :style="{width:previewWidth==='auto'?'100%':previewWidth}"><ManualDocument v-if="previewChapter" :chapter="previewChapter" :assets="previewAssets" :references="previewReferences" :asset-resolver="previewAssetUrl" @navigate="navigate" /><p v-else class="muted">新建章节后会显示正式阅读效果。</p></div></section>
    </section>
    <input ref="mediaInput" hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif,audio/*,video/*,.wav,.flac,.mp3,.ogg,.m4a,.mp4,.webm,.mov" @change="mediaPicked"><input ref="importInput" hidden type="file" accept=".gz,.ptbmanual" @change="importProject">
    <div v-if="sourceVisible" class="modal-backdrop"><section class="modal source-modal" role="dialog" aria-modal="true" aria-label="章节结构源码"><header><strong>章节结构源码</strong><button @click="sourceVisible=false">关闭</button></header><p>高级编辑保留稳定 ID。应用前验证节点与链接，未支持内容会明确提示。</p><textarea v-model="sourceDraft" aria-label="章节JSON源码" spellcheck="false"></textarea><footer><button @click="sourceDownload">导出原始章节</button><button class="primary" @click="applySource">验证并应用</button></footer></section></div>
    <div v-if="recoveryVisible" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="磁盘恢复稿"><header><strong>磁盘恢复稿</strong><button @click="recoveryVisible=false">关闭</button></header><p>恢复稿先加载到编辑界面，正式保存仍进行外部修改检查。</p><div class="recovery-list"><button v-for="item in recoveryItems" :key="item.id" @click="loadRecovery(item.id)">{{ new Date(item.time).toLocaleString('zh-CN') }} · {{ item.chapterCount }} 章<small>{{ item.id }}</small></button><p v-if="!recoveryItems.length">此工程尚无恢复稿。</p></div></section></div>
  </main>
</template>
