import test from 'node:test';import assert from 'node:assert/strict';
import {createEditor} from '../src/modules/annotation/editor.mjs';
import {serializeGrid,parseGrid,preferredGrid} from '../src/modules/annotation/format.ts';
import {spectrum,spectrumWindow} from '../src/modules/annotation/spectrum.ts';
const setup=()=>{const e=createEditor();e.state.textgrid={xmin:0,xmax:2,tiers:[{name:'words',intervals:[{xmin:0,xmax:1,text:'a'},{xmin:1,xmax:2,text:'b'}]},{name:'phones',intervals:[{xmin:0,xmax:.8,text:'a1'},{xmin:.8,xmax:1,text:'a2'},{xmin:1,xmax:1.2,text:'b1'},{xmin:1.2,xmax:2,text:'b2'}]}]};return e;};
const hit={tier:'words',index:0,edge:'end' as const,time:1};
test('R5 original TextGrid takes precedence over recovery copies with directory/case and ambiguity checks',()=>{const audio={name:'中文/a.wav'},original={name:'中文/A.TextGrid'},recovery={name:'中文/a_自动保存.TextGrid'},old={name:'中文/a_webedit.TextGrid'},unrelated={name:'其它/a.TextGrid'};assert.equal(preferredGrid(audio,[recovery,old,original,unrelated]),original);assert.equal(preferredGrid(audio,[recovery,old,unrelated]),recovery);assert.equal(preferredGrid(audio,[old]),old);assert.throws(()=>preferredGrid(audio,[original,{...original},recovery]));});
test('R5 window length is actual Hann sample count, padded FFT only, legacy remains available',()=>{for(const sr of [8000,16000,44100,48000,96000])for(const ms of [5,10,20,50,100]){const w=spectrumWindow(sr,ms);assert.equal(w.samples,Math.round(sr*ms/1000));assert(w.size>=w.samples&&w.size<2*w.samples);assert.equal(w.size&(w.size-1),0);}assert.deepEqual(spectrumWindow(44100),{samples:1024,size:1024});assert.throws(()=>spectrumWindow(16000,0));});
test('R5 longer spectral window resolves two tones while the relative RMS curve stays identical',()=>{const sr=16000,data=Float32Array.from({length:sr},(_,i)=>Math.sin(2*Math.PI*1000*i/sr)+Math.sin(2*Math.PI*1200*i/sr));const short=spectrum(data,sr,.5,.1,2,500,false,5,5),long=spectrum(data,sr,.5,.1,2,500,false,5,50);assert.deepEqual(short.intensity,long.intensity);const pixel=(hz:number)=>Math.floor((1-hz/5000)*500)*2*4;assert(long.rgba[pixel(1100)]>long.rgba[pixel(1000)]+50);assert.notDeepEqual(short.rgba,long.rgba);});
test('R5 backwards range selection ending exactly at zero retains the selected words',()=>{const e=setup();(e as any).finalizeRangeSelect({startTime:1.5,endTime:0});assert.deepEqual(e.state.selectedIndices,[0,1]);});
test('R5 shared word and phone boundary clamp together before an internal phone',()=>{const e=setup();e.moveBoundary(hit,1.5);assert.equal(e.wordTier()!.intervals[0].xmax,1.199999);assert.equal(e.phoneTier()!.intervals[1].xmax,1.199999);});
for(const target of [.9,1.1])test(`R5 Ctrl boundary drag separates only the moving side at ${target}, roundtrips and undoes`,()=>{
 const e=setup(),before=serializeGrid(e.state.textgrid!);e.beginBoundaryDrag(hit,{clientX:500,clientY:20,ctrlKey:true} as MouseEvent);e.dragBoundaryTo(target,550);
 // Repeated movement must reconstruct from the gesture snapshot, without accumulating gaps.
 e.dragBoundaryTo(target,560);e.onGridMouseUp();
 const words=e.wordTier()!.intervals,phones=e.phoneTier()!.intervals;
 assert.equal(words.length,3);assert.deepEqual(words.map(i=>[i.xmin,i.xmax]),target<1?[[0,.9],[.9,1],[1,2]]:[[0,1],[1,1.1],[1.1,2]]);
 assert.equal(words[1].text,'');assert(phones.some(i=>i.text===''&&i.xmin===Math.min(1,target)&&i.xmax===Math.max(1,target)));
 assert.equal(e.state.undoStack.length,1);assert.equal(serializeGrid(parseGrid(serializeGrid(e.state.textgrid!))),serializeGrid(e.state.textgrid!));e.undo();assert.equal(serializeGrid(e.state.textgrid!),before);
});
test('R5 direction reversal restores the stationary side and clamps at inner phone',()=>{const e=setup();e.beginBoundaryDrag(hit,{clientX:500,ctrlKey:true} as MouseEvent);e.dragBoundaryTo(.5,400);assert.equal(e.wordTier()!.intervals[0].xmax,.800001);e.dragBoundaryTo(1.5,700);e.onGridMouseUp();assert.equal(e.wordTier()!.intervals[0].xmax,1);assert.equal(e.wordTier()!.intervals[2].xmin,1.199999);});
test('R5 Ctrl phone separation is independent of words; outer boundaries cannot split',()=>{const e=setup(),words=structuredClone(e.wordTier()!.intervals);e.beginBoundaryDrag({...hit,tier:'phones',index:1},{clientX:500,ctrlKey:true} as MouseEvent);e.dragBoundaryTo(1.1,550);e.onGridMouseUp();assert.deepEqual(e.wordTier()!.intervals,words);assert.equal(e.phoneTier()!.intervals.length,5);const before=serializeGrid(e.state.textgrid!);e.beginBoundaryDrag({...hit,index:0,edge:'start',time:0},{clientX:0,ctrlKey:true} as MouseEvent);e.dragBoundaryTo(.5,50);e.onGridMouseUp();assert.equal(serializeGrid(e.state.textgrid!),before);});
test('R5 hit testing uses displayed canvas dimensions under CSS zoom',()=>{const e=setup();e.state.visibleDuration=2;e.setCanvas({width:1000,height:150,getBoundingClientRect:()=>({left:10,top:20,width:1500,height:225})} as HTMLCanvasElement);const h=e.hitTest({clientX:760,clientY:50} as MouseEvent)!;assert.equal(h.time,1);assert.equal(h.edge,'end');});
