import {test} from 'node:test';import assert from 'node:assert/strict';
import {createState,applyParameters,applySettings,dirty,defaults,validateSettings,matchAssociation,reconcile,snapshot,effectiveOutput,association,parameterKeys} from '../src/modules/parameter-estimation/state.ts';
import type {ResearchFile} from '../src/platform/research.ts';
const audio:ResearchFile={id:'a',name:'声调.wav',kind:'audio',size:10};
test('M01 all 80 keys and 14 defaults; empty selection is draft only',()=>{const s=createState();assert.equal(parameterKeys.length,80);assert.equal(Object.keys(defaults()).length,14);s.drawer='parameters';s.parameterDraft=[];assert(dirty(s));assert.throws(()=>applyParameters(s,[]));assert.equal(s.wave.parameters.length,80);s.drawer='';assert(!dirty(s));applyParameters(s,['pF0']);assert(dirty(s));});
test('settings apply/cancel cannot modify a previously captured job snapshot',()=>{const s=createState();s.files=[audio];const captured=snapshot(s);s.drawer='settings';s.settingsDraft.min_f0=70;assert(dirty(s));assert.equal(s.settings.min_f0,60);s.drawer='';assert(!dirty(s));applySettings(s,{...s.settings,min_f0:75});assert.equal(captured.settings.min_f0,60);assert.equal(s.settings.min_f0,75);});
test('public settings bounds and min/max are enforced before apply',()=>{for(const patch of [{max_formant:0},{min_f0:900,max_f0:100},{windowsize_ms:NaN},{only_voiced:1},{num_formants:3.5}])assert(validateSettings({...defaults(),...patch} as never));});
test('whole list, audition selection, and layer remain separate',()=>{const s=createState();s.files=[audio,{...audio,id:'b',name:'b.wav'}];s.selected='a';association(s).layer=2;assert.equal(snapshot(s).inputs.length,2);assert.equal(s.selected,'a');assert.equal(association(s).layer,2);});
test('association selection is case insensitive but rejects duplicate candidates',()=>{const grid:ResearchFile={id:'g',name:'声调.TextGrid',kind:'textgrid',size:12};assert.equal(matchAssociation(audio,[grid],'textgrid')?.id,'g');assert.throws(()=>matchAssociation(audio,[grid,{...grid,id:'g2'}],'textgrid'));assert.equal(matchAssociation(audio,[],'lip'),null);});
test('refresh removes vanished audio/association and invalidates pending preview',()=>{const s=createState();s.selected='a';s.files=[audio];association(s).textgrid={id:'g',name:'a.TextGrid',kind:'textgrid',size:12};association(s).gridHash='old';reconcile(s,[audio]);assert.equal(association(s).textgrid,null);assert.equal(association(s).gridHash,'');reconcile(s,[]);assert.equal(s.selected,'');assert.equal(s.loadVersion,1);});
test('independent projects retain draft and same-directory tracks input',()=>{const a=createState(),b=createState();applyParameters(a,['rF0']);assert.equal(b.wave.parameters.length,80);a.input={id:'input',purpose:'input',label:'语料'};a.output={id:'output',purpose:'output',label:'结果'};assert.equal(effectiveOutput(a)?.id,'input');a.sameDirectory=false;assert.equal(effectiveOutput(a)?.id,'output');});
test('native refresh retains a read association; changed server hash or missing legacy input clears it',()=>{
 const s=createState();s.selected=audio.id;const g:ResearchFile={id:'g',name:'声调.TextGrid',kind:'textgrid',size:12};
 association(s).textgrid={...g,sha256:'a'.repeat(64)};association(s).manual.textgrid=true;
 const legacy:ResearchFile={id:'old',name:'声调.xlsx',kind:'parameter',size:300};association(s).legacy=legacy;
 reconcile(s,[audio,g,legacy]);assert.equal(association(s).textgrid?.sha256,'a'.repeat(64));assert.equal(association(s).legacy?.id,'old');
 reconcile(s,[audio,{...g,sha256:'b'.repeat(64)}]);assert.equal(association(s).textgrid,null);assert.equal(association(s).legacy,null);
});
