import test from 'node:test';import assert from 'node:assert/strict';
import {defaults,valid,override,resize,f0Range,preset,draw,exportParams,importParams,ipa,isCurrent} from '../src/modules/speech-synthesis/state.ts';
test('M06 F01 range, duration, IPA and stale generation',()=>{const c=defaults();resize(c,3);assert.equal(c.curves.F0.points[1][0],3);f0Range(c,130,400);assert.equal(c.curves.F0.points[0][1],130);ipa('a-i/- ///u+/e++o/-');assert.throws(()=>ipa('a?i'),/第 2/);assert.throws(()=>f0Range(c,400,130));assert(!isCurrent(1,2,1,1));assert(!isCurrent(1,1,1,2));assert(isCurrent(1,1,2,2));});
test('M06 F02 override scalar, segmented interpolation and full underlying curve',()=>{const c=defaults();override(c,'Shimmer','3');assert.equal(c.curves.Shimmer.override,.03);assert.throws(()=>draw(c,'Shimmer',0,1,.02));override(c,'Shimmer','');draw(c,'Shimmer',0,1,.02);assert.equal(c.curves.Shimmer.override,null);override(c,'F0','100,200;150');assert.deepEqual(c.curves.F0.points,[[0,100],[1,200],[1,150],[2,150]]);assert.throws(()=>override(c,'F0','bad'));assert.throws(()=>override(c,'F0','5000'));});
test('M06 R3 calibrated presets and defaults',()=>{const c=defaults();preset(c,'耳语');assert.equal(c.curves.AV.override,0);assert.equal(c.curves.AH.override,40);preset(c,'气声');assert.equal(c.curves.AV.override,65);assert.equal(c.curves.AH.override,35);assert.throws(()=>preset(c,'missing'));assert.equal(c.sample_rate,16000);assert.equal(c.fade_in,50);});
test('M06 R2 complete CSV/JSON and explicit old-scale rejection',()=>{const c=defaults();c.sequence='a " i';override(c,'F0','130');c.curves.F0.points=[[0,100],[2,250]];assert.deepEqual(importParams(exportParams(c)),c);assert.deepEqual(importParams(JSON.stringify(c)),c);assert.deepEqual(importParams(JSON.stringify({schema_version:"m06/1",config:c,seed:123,action:"synthesize"})),c);assert.throws(()=>importParams('Parameter,Time,Value,Global\n__DURATION__,1,0,False\nShimmer,0,0.03,True'),/旧版/);assert.throws(()=>importParams(JSON.stringify({...c,schema_version:'m06/1'})),/旧版 AV/);assert.throws(()=>importParams('bad'));assert.throws(()=>valid({...c,duration:NaN}));});

test('M06 drawing outside graph clamps time without invalid endpoints',()=>{const c=defaults();draw(c,'F0',-5,-2,130);draw(c,'F0',3,4,150);valid(c);assert(c.curves.F0.points.every(([t])=>t>=0&&t<=2));});

test('M06 R1 reset respects applied F0 range and only changes selected formant',()=>{const c=defaults();f0Range(c,200,400);draw(c,'F0',0,1,999,true);assert(c.curves.F0.points.every(([,v])=>v>=200&&v<=400));const other=JSON.stringify(c.curves.F1);draw(c,'F2',.2,.8,1800);assert.equal(JSON.stringify(c.curves.F1),other);});
