import test from 'node:test';import assert from 'node:assert/strict';
import {Runner} from '../src/modules/perception/runner.ts';import {defaults,newSession,generate,type Asset,type Session} from '../src/modules/perception/model.ts';
import type {MediaBank} from '../src/modules/perception/media.ts';import type {LocalStore} from '../src/modules/perception/storage.ts';
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function fixture(){const p=defaults();p.config.useBeep=false;p.config.isi=0;p.config.interTrialInterval=0;p.config.advanceMode='manual';p.questionnaire=[];p.assets=[{id:'a',hash:'a'.repeat(64),name:'a.wav',path:'a.wav',group:'X',kind:'audio',size:44,mime:'audio/wav',originalSampleRate:48000} as Asset];p.trials=generate(p);const s=newSession(p,{}),stored:Session[]=[];let fail=false;
 const context={state:'running',get currentTime(){return performance.now()/1000;},createBufferSource(){return {buffer:null,connect(){},start(){},stop(){},disconnect(){},onended:null};},getOutputTimestamp(){return {contextTime:0,performanceTime:0};}};
 const bank={context,async trial(){return [{role:'X',media:{asset:p.assets[0],buffer:{duration:.001}}}];}} as unknown as MediaBank;
 const store={async commit(session:Session){if(fail)throw Error('quota');stored.push(structuredClone(session));session.revision++;}} as unknown as LocalStore;
 const r=new Runner(s,bank,store,()=>{});return {r,stored,setFail:(v:boolean)=>fail=v};}
async function responding(r:Runner){await r.start();r.continue();for(let i=0;i<100&&r.phase!=='responding';i++)await pause(2);assert.equal(r.phase,'responding');}
const event=(key:string,extra={})=>({key,code:'Key'+key.toUpperCase(),repeat:false,isComposing:false,ctrlKey:false,altKey:false,metaKey:false,shiftKey:false,timeStamp:performance.now(),...extra}) as KeyboardEvent;
test('M15 runner records at most one answer and durable completion precedes next trial',async()=>{const {r,stored}=fixture();await responding(r);r.keydown(event('f'));r.keydown(event('j'));await pause(5);assert.equal(r.phase,'completed');assert.equal(r.session.attempts.length,1);assert.equal(r.session.attempts[0].key,'f');assert.equal(stored[0].attempts[0].status,'running');assert.equal(stored.at(-1)?.attempts[0].status,'completed');});
test('M15 runner rejects queued pre-window response and long-held stage key',async()=>{const {r}=fixture();await r.start();const start=event('f');r.keydown(start);await pause(80);assert.equal(r.phase,'responding');r.keydown(event('f'));assert.equal(r.phase,'responding');r.keyup(start);r.keydown(event('f',{timeStamp:0}));assert.equal(r.phase,'responding');r.keyup(start);r.keydown(event('F'));await pause(2);assert.equal(r.phase,'completed');});
test('M15 runner ignores modifier/repeat/IME and cannot answer while playing',async()=>{const {r}=fixture();await r.start();r.continue();r.keydown(event('j'));r.keyup(event('j'));await pause(80);for(const extra of [{repeat:true},{isComposing:true},{ctrlKey:true},{shiftKey:true}]){r.keydown(event('j',extra));r.keyup(event('j'));assert.equal(r.phase,'responding');}r.keydown(event('j'));await pause(2);assert.equal(r.phase,'completed');});
test('M15 storage write failure stops automatic progression and preserves exportable response',async()=>{const {r,setFail}=fixture();await responding(r);setFail(true);r.keydown(event('f'));await pause(2);assert.equal(r.phase,'saving-error');assert.equal(r.session.attempts[0].status,'completed');assert.equal(r.session.nextIndex,1);setFail(false);await r.retrySave();assert.equal(r.phase,'completed');});
test('M15 interrupted response is never normal and explicit retry retains prior attempt',async()=>{const {r}=fixture();await responding(r);await r.interrupt('blur');assert.equal(r.session.attempts[0].status,'interrupted');assert.equal(r.session.attempts[0].rtMs,null);assert.equal(r.session.nextIndex,0);await responding(r);r.keydown(event('f'));await pause(2);assert.deepEqual(r.session.attempts.map(a=>a.status),['interrupted','completed']);assert.equal(r.session.attempts[1].attempt,2);});
test('M15 failed scheduling marks invalid instead of entering response phase',async()=>{const {r}=fixture();r.bank.context.createBufferSource=()=>{throw Error('device error');};await r.start();r.continue();await pause(5);assert.equal(r.phase,'paused');assert.equal(r.session.attempts[0].status,'invalid');assert.equal(r.session.attempts[0].rtMs,null);});
test('M15-R1 a late answer commit cannot start another trial after end',async()=>{
 const {r}=fixture();r.session.project.trials.push({...r.session.project.trials[0],id:'second'});await responding(r);
 let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>entered=resolve);const commit=r.store.commit.bind(r.store);let first=true;
 r.store.commit=async s=>{if(first){first=false;entered();await gate;}await commit(s);};
 r.keydown(event('j'));await started;const ending=r.end();release();assert.equal(await ending,true);await pause(80);
 assert.equal(r.phase,'completed');assert.equal(r.session.status,'ended');assert.equal(r.session.nextIndex,1);assert.equal(r.session.attempts.length,1);assert.equal(r.session.attempts[0].status,'completed');
});
