// Test-only fault injection. This file is never imported by the product.
import {defaults,newSession,generate,recover,LIMITS,type Asset} from '../src/modules/perception/model.ts';
import {LocalStore,lockSession} from '../src/modules/perception/storage.ts';
import {MediaBank,hashBlob} from '../src/modules/perception/media.ts';
import {Runner} from '../src/modules/perception/runner.ts';
const checks:string[]=[];const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s);};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function wav(f:number){const b=new ArrayBuffer(44+4800*2),v=new DataView(b);for(const [o,s] of [[0,'RIFF'],[8,'WAVE'],[12,'fmt '],[36,'data']] as const)[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));v.setUint32(4,b.byteLength-8,true);v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,48000,true);v.setUint32(28,96000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);v.setUint32(40,b.byteLength-44,true);for(let i=0;i<4800;i++)v.setInt16(44+i*2,Math.round(500*Math.sin(2*Math.PI*f*i/48000)),true);return new Blob([b],{type:'audio/wav'});}
document.querySelector('button')!.onclick=()=>{void run().then(value=>{(window as any).__m15Result=value;document.querySelector('pre')!.textContent=JSON.stringify(value);}).catch(e=>{(window as any).__m15Result={error:String(e),stack:e.stack,checks};});};
async function run(){const store=new LocalStore();await store.open();const p=defaults();p.questionnaire=[];p.config.useBeep=false;p.config.advanceMode='manual';p.config.interTrialInterval=0;p.config.isi=0;const blob=wav(440),hash=await hashBlob(blob),a:Asset={id:crypto.randomUUID(),hash,name:'same.wav',path:'same.wav',group:'X',kind:'audio',size:blob.size,mime:blob.type,originalSampleRate:48000};p.assets=[a];p.trials=generate(p);await store.putAssets([{meta:a,blob}]);await store.saveProject(p);check((await store.blob(hash)).size===blob.size,'real IndexedDB Blob persists');
 const s=newSession(p,{});await store.commit(s);const stale=await store.session(s.id);s.events.push({kind:'test',at:'now',perfMs:0,timeOrigin:performance.timeOrigin,detail:''});await store.commit(s);let conflict=false;try{await store.commit(stale);}catch{conflict=true;}check(conflict,'real IndexedDB CAS rejects stale revision');
 const release=await lockSession(s.id);let locked=false;try{await lockSession(s.id);}catch{locked=true;}check(locked,'Web Locks rejects concurrent same-session owner');release();
 const bank=new MediaBank(store);await bank.unlock();await bank.preflight(p,()=>{});check(bank.mode==='all','small project fully predecoded');const shared={...a,id:crypto.randomUUID(),group:'A' as const};delete shared.decodedSampleRate;delete shared.channels;delete shared.duration;delete shared.decodedBytes;const reused=await bank.prepare(shared);check(reused.asset.id===shared.id&&shared.decodedSampleRate===bank.context.sampleRate&&shared.channels===1,'same content in another role retains role identity and decoded provenance');
 const second=wav(550),secondHash=await hashBlob(second),a2={...a,id:crypto.randomUUID(),hash:secondHash};await store.putAssets([{meta:a2,blob:second}]);p.assets.push(a2);p.trials=generate(p);const budget=LIMITS.decodedBytes;LIMITS.decodedBytes=25000;await bank.preflight(p,()=>{});check(bank.mode==='chunked'&&bank.used===0,'decoded budget selects explicit trial chunks');await bank.trial(p,0);check(bank.used<=LIMITS.decodedBytes,'chunk preparation stays inside budget');LIMITS.decodedBytes=budget;
 const restoredBank=new MediaBank(store);await restoredBank.unlock();LIMITS.decodedBytes=25000;try{await restoredBank.trial(p,0);await restoredBank.trial(p,1);check(restoredBank.mode==='chunked'&&restoredBank.cache.size===1&&restoredBank.used<=25000,'unpreflighted recovery bank releases the previous decoded trial');}finally{LIMITS.decodedBytes=budget;restoredBank.dispose();}
 const missing={...a,hash:'f'.repeat(64)};let noBlob=false;try{await bank.prepare(missing);}catch{noBlob=true;}check(noBlob,'missing persisted stimulus blocks preparation');
 const bad=new Blob(['bad audio']),badHash=await hashBlob(bad),badMeta={...a,id:crypto.randomUUID(),hash:badHash};await store.putAssets([{meta:badMeta,blob:bad}]);let broken=false;try{await bank.prepare(badMeta);}catch{broken=true;}check(broken,'corrupt real audio refuses decoding');
 p.assets=[a];p.trials=generate(p);await bank.preflight(p,()=>{});const r=new Runner(newSession(p,{}),bank,store,()=>{});await r.acquire();await store.commit(r.session);await r.start();r.continue();for(let n=0;n<200&&r.phase!=='responding';n++)await wait(5);check(r.phase==='responding','real Web Audio runner reaches response');
 const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:any[]){if(this.name==='sessions')throw new DOMException('test write failure','QuotaExceededError');return original.apply(this,args as any);};
 r.keydown(new KeyboardEvent('keydown',{key:'j',code:'KeyJ'}));await wait(50);check(r.phase==='saving-error'&&r.session.attempts[0].status==='completed','quota injection stops and retains answered attempt');check(await r.dispose()===false,'failed dispose preserves the in-memory answer');let retained=false;try{await lockSession(r.session.id);}catch{retained=true;}check(retained,'failed dispose retains its actual Web Lock');IDBObjectStore.prototype.put=original;await r.retrySave();check(r.phase==='completed'&&(await store.session(r.session.id)).attempts[0].key==='j','retry commits real local answer');await r.dispose();const reacquired=await lockSession(r.session.id);reacquired();check(true,'successful dispose releases the actual Web Lock');
 const interrupted=new Runner(newSession(p,{}),bank,store,()=>{});await interrupted.acquire();await store.commit(interrupted.session);await interrupted.start();interrupted.continue();for(let n=0;n<200&&interrupted.phase!=='responding';n++)await wait(5);const persisted=await store.session(interrupted.session.id);check(persisted.attempts[0].status==='running','running safe boundary exists before response');const restored=recover(persisted);check(restored.attempts[0].status==='interrupted'&&restored.attempts[0].rtMs===null,'crash recovery cannot extend old RT');await bank.context.suspend();await interrupted.interrupt('audio-context-suspended');check(interrupted.session.attempts[0].status==='interrupted','context interruption retains invalid attempt');await interrupted.dispose();bank.dispose();return {checks,physicalTimingMeasured:false};}
