import {test} from 'node:test';
import assert from 'node:assert/strict';
import {csvRows,autoMapping,importRows,safeStem,taskCSV,readTable} from '../src/modules/recording/task-import.ts';
import * as XLSX from '../src/modules/perception/vendor/xlsx.mjs';
import {newTask,nextTask,normalizeSelection,setSelectionEndpoint} from '../src/modules/recording/state.ts';
import {recordingDefaults,bindInput} from '../src/modules/recording/defaults.ts';
import {shortcut} from '../src/modules/recording/shortcuts.ts';

test('M16 CSV quotes, Chinese and repeated rows expand deterministically',()=>{const rows=csvRows('task_id,prompt,repeat_count,filename_stem\r\nT1,"a, b\nɑ̃",2,test\r\n');const result=importRows(rows,autoMapping(rows[0]));assert.deepEqual(result.errors,[]);assert.equal(result.tasks.length,2);assert.equal(result.tasks[0].prompt,'a, b\nɑ̃');assert.equal(result.tasks[1].id,'T1_2');});
test('M16 duplicate identifiers and unsafe names reject preview',()=>{const rows=csvRows('task_id,prompt,filename_stem\na,x,good\na,y,good\nb,z,../bad');const r=importRows(rows,autoMapping(rows[0]));assert(r.errors.some(x=>x.includes('重复')));assert(r.errors.some(x=>x.includes('不安全')));for(const stem of ['CON','a/b','C:x','name.'])assert(!safeStem(stem));});
test('M16 expansion budget stops at 10000 rather than allocating a million tasks',()=>{const rows=[['prompt','repeat_count'],...Array.from({length:10000},(_,i)=>['item'+i,'100'])];const r=importRows(rows,autoMapping(rows[0]));assert.equal(r.tasks.length,10000);assert(r.errors.includes('展开后任务超过 10000 条'));});
test('M16 absent task list supports free recording and skipped rows are reversible',()=>{assert.equal(nextTask([],''),'');const tasks=[newTask(1),newTask(2),newTask(3)];tasks[1].skipped=true;assert.equal(nextTask(tasks,'T001'),'T003');tasks[1].skipped=false;assert.equal(nextTask(tasks,'T001'),'T002');});
test('M16 frame selection normalizes reverse and clamps without fractions',()=>{assert.deepEqual(normalizeSelection(10.4,-1,10),[0,10]);assert.deepEqual(normalizeSelection(1,1,10),[1,1]);});
test('M16 typed range retains the edited endpoint when entering start before end',()=>{
  let range:[number,number]=[0,0];range=setSelectionEndpoint(range,0,10,100);range=setSelectionEndpoint(range,1,20,100);assert.deepEqual(range,[10,20]);
  range=setSelectionEndpoint(range,1,5,100);assert.deepEqual(range,[5,5]);
  assert.deepEqual(setSelectionEndpoint(range,0,200,100),[100,100]);
  assert.deepEqual(setSelectionEndpoint([10,20],1,-1,100),[0,0]);
  assert.deepEqual(setSelectionEndpoint(range,0,NaN,100),range);
});
test('M16 CSV export guards spreadsheet formula text; JSON remains original',()=>{const t=newTask(1);t.prompt='=HYPERLINK("a")';assert(taskCSV([t]).includes("'=HYPERLINK"));assert.equal(t.prompt,'=HYPERLINK("a")');});
test('M16 malformed CSV and row limits fail before import',()=>{assert.throws(()=>csvRows('"unfinished'));assert.throws(()=>csvRows('prompt\n'+Array(10002).fill('x').join('\n')),/超过/);});
test('M16 defaults are two audio channels; mono fallback is explicit and EGG never inferred',()=>{const cfg=recordingDefaults();assert.equal(cfg.channels,2);assert.deepEqual(cfg.roles,['microphone','microphone']);const device={id:'one',index:0,name:'one',hostapi:'test',inputs:1,outputs:0,default_rate:48000};const mono=bindInput(cfg,device);assert.deepEqual(mono.config.roles,['microphone']);assert(mono.message.includes('仅有 1'));const stereo=bindInput({...cfg,roles:['microphone','egg']},{...device,inputs:2});assert.deepEqual(stereo.config.roles,['microphone','microphone']);});
test('M16 keyboard ignores inactive/capture/repeat/IME and preserves editor focus',()=>{const original=(globalThis as any).Element;class ElementStub{editing:boolean;constructor(editing=false){this.editing=editing;}closest(){return this.editing?{}:null;}};(globalThis as any).Element=ElementStub;try{const event={code:'Space',key:' ',target:null,repeat:false,isComposing:false,ctrlKey:false,metaKey:false,altKey:false,shiftKey:false} as unknown as KeyboardEvent;assert.equal(shortcut(event,true,false,false),'play');assert.equal(shortcut(event,false,false,false),null);assert.equal(shortcut(event,true,true,false),null);assert.equal(shortcut({...event,repeat:true} as KeyboardEvent,true,false,false),null);assert.equal(shortcut({...event,isComposing:true} as KeyboardEvent,true,false,false),null);assert.equal(shortcut({...event,target:new ElementStub(true)} as unknown as KeyboardEvent,true,false,false),null);assert.equal(shortcut({...event,key:'x',code:'KeyX',ctrlKey:true} as KeyboardEvent,true,false,false),null);assert.equal(shortcut({...event,key:'x',code:'KeyX',ctrlKey:true} as KeyboardEvent,true,false,true),'cut');}finally{(globalThis as any).Element=original;}});
test('M16 JSON task template preserves whitespace and formula-like text exactly',async()=>{const t=newTask(1);t.prompt='  =literal ɑ̃\n  ';const file=new File([JSON.stringify({schema_version:'ptb-recording-tasks/1',tasks:[t]})],'template.json');const table=await readTable(file);assert.deepEqual(table.template,[t]);});
test('M16 XLSX formatted identifiers keep leading zero and formulas are rejected',async()=>{const wb=XLSX.utils.book_new(),sheet=XLSX.utils.aoa_to_sheet([['task_id','prompt'],[1,'ɑ̃']]);sheet.A2.z='000';XLSX.utils.book_append_sheet(wb,sheet,'Sheet1');let file=new File([XLSX.write(wb,{type:'array',bookType:'xlsx'})],'id.xlsx');let table=await readTable(file);assert.equal(table.sheets[0].rows[1][0],'001');sheet.B2={t:'n',v:2,f:'1+1'};file=new File([XLSX.write(wb,{type:'array',bookType:'xlsx'})],'formula.xlsx');await assert.rejects(()=>readTable(file),/公式/);});
