import * as XLSX from './vendor/xlsx.mjs';
import {copy,defaults,roles,uid,refFor,relink,LIMITS,type Project,type Session,type Trial,type Paradigm} from './model.ts';
export function projectJSON(p:Project){return JSON.stringify(p,null,2);}
export function parseProject(text:string):Project{
 if(text.length>LIMITS.projectBytes)throw Error('配置超过 16 MiB');const v=JSON.parse(text);
 if(v.schema==='ptb-m15-project/1'){
  if(!Array.isArray(v.assets)||!Array.isArray(v.trials)||!Array.isArray(v.questionnaire)||!Array.isArray(v.randomizations)||!v.config||!Array.isArray(v.config.validKeys)||!Array.isArray(v.config.keyRanges)||!Array.isArray(v.config.shuffleRanges)||!roles(v.paradigm))throw Error('项目结构不完整');
  if(typeof v.id!=='string'||!v.id)throw Error('项目 ID 无效');
  const c=v.config;
  for(const name of ['title','introText','interTrialText'])if(typeof c[name]!=='string')throw Error('配置文本字段无效');
  for(const name of ['introLargeText','showInterTrialText','largeText','autoPlay','showFilename','useBeep'])if(typeof c[name]!=='boolean')throw Error('配置开关字段无效');
  const keyList=(ks:any)=>Array.isArray(ks)&&ks.every(k=>k&&typeof k.key==='string'&&typeof k.label==='string');
  if(!keyList(c.validKeys)||c.keyRanges.some((r:any)=>!r||typeof r.notice!=='string'||!keyList(r.keys)))throw Error('按键配置结构无效');
  for(const q of v.questionnaire)if(!q||typeof q.id!=='string'||typeof q.label!=='string'||typeof q.required!=='boolean'||!['text','radio','checkbox'].includes(q.type)||(q.type!=='text'&&(!Array.isArray(q.options)||q.options.some((x:any)=>typeof x!=='string'))))throw Error('问卷结构无效');
  if(v.assets.length>LIMITS.files||v.trials.length>LIMITS.trials)throw Error('项目超过数量预算');
  for(const a of v.assets)if(typeof a.id!=='string'||!/^[a-f0-9]{64}$/.test(a.hash)||typeof a.name!=='string'||typeof a.path!=='string'||!['audio','text','image'].includes(a.kind)||!['A','B','X'].includes(a.group)||!Number.isFinite(a.size)||a.size<0||a.size>LIMITS.fileBytes)throw Error('素材清单无效');
  for(const t of v.trials){if(typeof t.id!=='string'||!t.stimuli||typeof t.instruction!=='string')throw Error('试次结构无效');for(const r of roles(v.paradigm)){const x=t.stimuli[r];if(x&&(!(x.id===null||typeof x.id==='string')||typeof x.name!=='string'||!(x.hash===null||typeof x.hash==='string')))throw Error('刺激关联结构无效');}}
  return copy(v);
 }
 if(!v.playlistConfig&&!v.playlistNames)throw Error('未知项目版本');const p=defaults();p.config={...p.config,...v.config};if(v.questionnaire)p.questionnaire=v.questionnaire;
 const items=v.playlistConfig??v.playlistNames.map((fileName:string)=>({fileName}));p.trials=items.map((x:{fileName:string;instruction?:string})=>({id:uid(),instruction:x.instruction??'',stimuli:{X:{id:null,name:x.fileName,hash:null}}}));return p;
}
export function mergeLocalAssets(p:Project,local:Project){const out=copy(p);for(const a of local.assets)if(!out.assets.some(x=>x.id===a.id))out.assets.push(copy(a));return relink(out);}
export function zipBudget(bytes:ArrayBuffer){if(bytes.byteLength>LIMITS.projectBytes)throw Error('XLSX 超过 16 MiB');const v=new DataView(bytes);let entries=0,total=0;for(let i=Math.max(0,v.byteLength-65557);i+22<=v.byteLength;i++)if(v.getUint32(i,true)===0x06054b50){entries=v.getUint16(i+10,true);let offset=v.getUint32(i+16,true);if(entries>2000)throw Error('XLSX ZIP 条目过多');for(let n=0;n<entries;n++){if(offset+46>v.byteLength||v.getUint32(offset,true)!==0x02014b50)throw Error('XLSX ZIP 索引损坏');total+=v.getUint32(offset+24,true);if(total>64*1024*1024)throw Error('XLSX 解压预算超过 64 MiB');offset+=46+v.getUint16(offset+28,true)+v.getUint16(offset+30,true)+v.getUint16(offset+32,true);}return;}throw Error('需要有效的 XLSX ZIP 文件');}
export function workbook(rows:unknown[][],name='Sequence'){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),name);return XLSX.write(wb,{type:'array',bookType:'xlsx'});}
export function sequenceRows(p:Project,prefix=''){const rs=roles(p.paradigm);return [[...rs.map(r=>p.paradigm==='X'?'File_Path':'File_'+r),'Inter_Trial_Instruction',...rs.map(r=>'SHA256_'+r)],...p.trials.map(t=>[...rs.map(r=>{const ref=t.stimuli[r],a=p.assets.find(a=>a.id===ref?.id);return (prefix?prefix.replace(/[\\/]+$/,'')+'/':'')+(a?.path??ref?.name??'');}),t.instruction,...rs.map(r=>t.stimuli[r]?.hash??'')])];}
export function resourceRows(files:File[],paradigm:Paradigm,prefix=''){const rs=roles(paradigm);return [[...rs.map(r=>paradigm==='X'?'File_Path':'File_'+r),'Inter_Trial_Instruction'],...files.map(f=>[(prefix?prefix.replace(/[\\/]+$/,'')+'/':'')+(f.webkitRelativePath||f.name),...Array(rs.length).fill('')])];}
export function readSequence(bytes:ArrayBuffer,p:Project):Trial[]{zipBudget(bytes);const wb=XLSX.read(bytes,{type:'array',sheetRows:LIMITS.trials+2,cellFormula:false,cellHTML:false,bookVBA:false});const sheet=wb.Sheets[wb.SheetNames[0]];const range=XLSX.utils.decode_range(sheet['!fullref']??sheet['!ref']??'A1');if(range.e.r>LIMITS.trials||range.e.c>30)throw Error('XLSX 超过 10000 行或 31 列');const rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''}) as unknown[][];return rowsToTrials(rows,p);}
export function rowsToTrials(rows:unknown[][],p:Project):Trial[]{if(!rows.length)throw Error('空表');const header=rows[0].map(x=>String(x).trim().toLowerCase()),rs=roles(p.paradigm),hasHeader=header.some(h=>/file|path|instruction|展示语|^a$|^b$|^x$/.test(h));const col=(r:string)=>header.findIndex(h=>h==='file_'+r.toLowerCase()||h===r.toLowerCase()||(r==='X'&&(h==='file_path'||h==='path')));const instruction=header.findIndex(h=>h.includes('instruction')||h.includes('展示语'));
 return rows.slice(hasHeader?1:0).filter(row=>row.some(v=>String(v).trim())).map(row=>{const stimuli:Trial['stimuli']={};for(const [i,r] of rs.entries()){const name=String(row[hasHeader?col(r):i]??'').trim(),hashCol=header.indexOf('sha256_'+r.toLowerCase()),hash=hasHeader&&hashCol>=0?String(row[hashCol]??'').trim():null;const matches=p.assets.filter(a=>hash?a.hash===hash:a.path===name||a.name===name||a.name===name.split(/[\\/]/).pop());stimuli[r]=matches.length===1?refFor(matches[0]):{id:null,name,hash:hash||null};}return {id:uid(),stimuli,instruction:String(row[hasHeader?instruction:rs.length]??'')};});}
export function resultRows(s:Session){const q=s.project.questionnaire,first=q.find(q=>q.type==='text'&&/姓名|编号/.test(q.label))??q.find(q=>q.type==='text'),pid=first?s.answers[first.id]??'Anonymous':'Anonymous';return [['Participant_ID','Timestamp_Date','Timestamp_Time',...q.map(q=>'Q_'+q.label.replace(/[\s,，;:]+/g,'_')),'Trial_Index','Audio_Filename','Response_Key','Reaction_Time_ms','Is_Valid_Key','Session_ID','Participant_UUID','Attempt_ID','Attempt','Status','Reason','Paradigm','A_Name','A_SHA256','B_Name','B_SHA256','X_SHA256','RT_Definition','Response_Open_Perf_ms','Key_Event_Perf_ms','Key_Handled_Perf_ms','Time_Origin'],...s.attempts.map(a=>{const date=a.finishedAt??a.startedAt;return [pid,date.slice(0,10),date.slice(11,19),...q.map(q=>Array.isArray(s.answers[q.id])?(s.answers[q.id] as string[]).join(';'):s.answers[q.id]??''),a.trialIndex+1,a.roles.X?.name??'',a.key??'',a.rtMs??'',a.status==='completed'?'TRUE':'FALSE',s.id,s.participantId,a.id,a.attempt,a.status,a.reason??'',s.project.paradigm,a.roles.A?.name??'',a.roles.A?.hash??'',a.roles.B?.name??'',a.roles.B?.hash??'',a.roles.X?.hash??'',a.rtDefinition,a.timing?.responseOpenPerfMs??'',a.timing?.keyEventPerfMs??'',a.timing?.keyHandledPerfMs??'',a.timing?.timeOrigin??''];})];}
export function csv(rows:unknown[][]){return '\uFEFF'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');}
export function resultsBlob(s:Session,format:'json'|'csv'|'xlsx'){if(format==='json')return new Blob([JSON.stringify({...s,exportedAt:new Date().toISOString(),finalTrialOrder:s.project.trials.map(t=>t.id),formatVersion:'ptb-m15-results/1'},null,2)],{type:'application/json'});const rows=resultRows(s);return new Blob([format==='xlsx'?workbook(rows,'Results'):csv(rows)],{type:format==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/csv;charset=utf-8'});}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
// Old instructions permitted HTML. Keep inert formatting only; no remote resources, style, links or scripts.
export function safeMarkup(value:string){const doc=new DOMParser().parseFromString(value,'text/html');const allowed=new Set(['BR','B','STRONG','I','EM','U','P','SPAN','DIV']);function clean(node:Node):string{if(node.nodeType===3)return (node.textContent??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');if(node.nodeType!==1)return '';const el=node as Element;if(['SCRIPT','STYLE','IFRAME','OBJECT','IMG','SVG','LINK'].includes(el.tagName))return '';const contents=[...el.childNodes].map(clean).join('');return allowed.has(el.tagName)?`<${el.tagName.toLowerCase()}>${contents}</${el.tagName.toLowerCase()}>`:contents;}return [...doc.body.childNodes].map(clean).join('');}
