import {LIMITS,kindFor,roles,uid,type Asset,type Role,type Project,type Timing} from './model.ts';
import type {LocalStore} from './storage.ts';
export async function hashBlob(blob:Blob){const data=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return [...new Uint8Array(data)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function wavInfo(bytes:ArrayBuffer){const v=new DataView(bytes),str=(o:number,n:number)=>String.fromCharCode(...new Uint8Array(bytes,o,n));if(bytes.byteLength<12||str(0,4)!=='RIFF'||str(8,4)!=='WAVE')return null;let rate=0,channels=0,block=0,data=0;for(let i=12;i+8<=v.byteLength;){const tag=str(i,4),n=v.getUint32(i+4,true);if(tag==='fmt '&&n>=16&&i+24<=v.byteLength){channels=v.getUint16(i+10,true);rate=v.getUint32(i+12,true);block=v.getUint16(i+20,true);}if(tag==='data')data=n;i+=8+n+(n%2);}return rate&&channels&&block?{rate,channels,duration:data/block/rate}:null;}
export function rasterSize(bytes:ArrayBuffer):{width:number;height:number}|null{const v=new DataView(bytes),n=v.byteLength,s=(o:number,l:number)=>String.fromCharCode(...new Uint8Array(bytes,o,l));if(n>=24&&v.getUint32(0)===0x89504e47)return {width:v.getUint32(16),height:v.getUint32(20)};if(n>=10&&s(0,3)==='GIF')return {width:v.getUint16(6,true),height:v.getUint16(8,true)};if(n>=26&&s(0,2)==='BM')return {width:Math.abs(v.getInt32(18,true)),height:Math.abs(v.getInt32(22,true))};if(n>=30&&s(0,4)==='RIFF'&&s(8,4)==='WEBP'){const kind=s(12,4);if(kind==='VP8X')return {width:1+(v.getUint32(24,true)&0xffffff),height:1+(v.getUint32(26,true)>>>8)};if(kind==='VP8 ')return {width:v.getUint16(26,true)&0x3fff,height:v.getUint16(28,true)&0x3fff};if(kind==='VP8L'){const bits=v.getUint32(21,true);return {width:1+(bits&0x3fff),height:1+((bits>>>14)&0x3fff)};}}if(n>=4&&v.getUint16(0)===0xffd8){for(let i=2;i+9<n;){if(v.getUint8(i)!==255)break;const marker=v.getUint8(i+1);i+=2;if(marker===0xd8||marker===0x01)continue;const length=v.getUint16(i);if(length<2||i+length>n)break;if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return {width:v.getUint16(i+5),height:v.getUint16(i+3)};i+=length;}}return null;}
async function checkImage(blob:Blob,a:Asset){let size=rasterSize(await blob.slice(0,1024*1024).arrayBuffer());if(!size&&(a.name.toLowerCase().endsWith('.svg')||a.mime==='image/svg+xml')){if(blob.size>1024*1024)throw Error('SVG 超过 1 MiB');const text=await blob.text();if(/<!DOCTYPE|<script|<foreignObject|@import|url\(\s*['"]?(?!#)|(?:href|src)\s*=\s*['"](?!#)/i.test(text))throw Error('SVG 包含外部或活动资源，请使用独立静态图片');const doc=new DOMParser().parseFromString(text,'image/svg+xml'),root=doc.documentElement;if(root.tagName!=='svg'||doc.querySelector('parsererror'))throw Error('SVG 无效');const dimension=(name:string)=>{const raw=root.getAttribute(name)??'';return /^\d+(\.\d+)?(px)?$/.test(raw)?parseFloat(raw):NaN;};size={width:dimension('width'),height:dimension('height')};}
 if(!size||!Number.isFinite(size.width)||!Number.isFinite(size.height)||size.width<=0||size.height<=0||size.width*size.height>16000000)throw Error(`图片尺寸未知或超过 1600 万像素：${a.name}`);
}
export async function importFiles(files:File[],group:Role,existing:Asset[],store:LocalStore){if(files.length>LIMITS.files)throw Error('单次导入最多 2000 个');const known=[...existing],out:Asset[]=[];let bytes=existing.reduce((n,a)=>n+a.size,0);for(const file of files){if(file.size>LIMITS.fileBytes||!file.size)throw Error(`${file.name} 为空或超过 64 MiB`);const kind=kindFor(file);if(kind==='text'&&file.size>LIMITS.textBytes)throw Error('文本超过 1 MiB');const hash=await hashBlob(file),path=file.webkitRelativePath||file.name,prior=known.find(a=>a.hash===hash&&a.group===group&&a.path===path);if(!prior){if(known.length>=LIMITS.files)throw Error('素材最多 2000 个');if(bytes+file.size>LIMITS.totalBytes)throw Error('原始素材总量超过 512 MiB');}const info=kind==='audio'?wavInfo(await file.slice(0,1024*1024).arrayBuffer()):null;const meta:Asset=prior??{id:uid(),hash,name:file.name,path,group,kind,size:file.size,mime:file.type,originalSampleRate:info?.rate??null};await store.putAssets([{meta,blob:file}]);if(!prior){known.push(meta);bytes+=file.size;}out.push(meta);}return out;}
export interface Prepared {asset:Asset;buffer?:AudioBuffer;text?:string;image?:HTMLImageElement;url?:string;bytes:number}
export class MediaBank {
 context:AudioContext;
 cache=new Map<string,Prepared>();mode:'all'|'chunked'='all';used=0;
 private store:LocalStore;
 constructor(store:LocalStore){this.store=store;this.context=new AudioContext();}
 async unlock(){await this.context.resume();if(this.context.state!=='running')throw Error('音频未解锁，请点击预检与试音');}
 async tone(){await this.unlock();const osc=this.context.createOscillator(),g=this.context.createGain(),t=this.context.currentTime+.02;osc.frequency.value=600;g.gain.setValueAtTime(.08,t);g.gain.exponentialRampToValueAtTime(.00001,t+.15);osc.connect(g).connect(this.context.destination);osc.start(t);osc.stop(t+.15);osc.onended=()=>{osc.disconnect();g.disconnect();};}
 private clear(){for(const p of this.cache.values())if(p.url)URL.revokeObjectURL(p.url);this.cache.clear();this.used=0;}
 async preview(a:Asset){this.clear();return this.prepare(a);}
 async prepare(a:Asset):Promise<Prepared>{const cached=this.cache.get(a.hash);if(cached){if(cached.buffer)Object.assign(a,{decodedSampleRate:cached.buffer.sampleRate,channels:cached.buffer.numberOfChannels,duration:cached.buffer.duration,decodedBytes:cached.bytes});return {...cached,asset:a};}const blob=await this.store.blob(a.hash);if(await hashBlob(blob)!==a.hash)throw Error(`刺激 hash 不一致：${a.name}`);let result:Prepared={asset:a,bytes:0};
 if(a.kind==='audio'){
  const bytes=await blob.arrayBuffer(),wav=wavInfo(bytes);
  // Check decoded allocation before decodeAudioData. Other formats use metadata and a conservative channel estimate.
  let duration=wav?.duration,channels=wav?.channels??8;
  if(duration===undefined){const url=URL.createObjectURL(blob);try{duration=await new Promise<number>((resolve,reject)=>{const el=new Audio(),timer=setTimeout(()=>{el.src='';reject(Error(`音频元数据超时：${a.name}`));},10000);el.onloadedmetadata=()=>{clearTimeout(timer);resolve(el.duration);el.src='';};el.onerror=()=>{clearTimeout(timer);reject(Error(`格式不可解码：${a.name}`));el.src='';};el.preload='metadata';el.src=url;});}finally{URL.revokeObjectURL(url);}}
  if(!Number.isFinite(duration)||duration!<=0||duration!*channels*this.context.sampleRate*4>LIMITS.decodedBytes)throw Error(`单刺激解码预算超过 128 MiB 或时长未知：${a.name}`);
  const buffer=await this.context.decodeAudioData(bytes);result={asset:a,buffer,bytes:buffer.length*buffer.numberOfChannels*4};Object.assign(a,{originalSampleRate:wav?.rate??a.originalSampleRate,decodedSampleRate:buffer.sampleRate,channels:buffer.numberOfChannels,duration:buffer.duration,decodedBytes:result.bytes});
 }else if(a.kind==='text'){result.text=await blob.text();result.bytes=result.text.length*2;}else{
  await checkImage(blob,a);const url=URL.createObjectURL(blob),image=new Image();image.src=url;try{await image.decode();if(image.naturalWidth*image.naturalHeight>16000000)throw Error('图片超过 1600 万像素');result={asset:a,image,url,bytes:image.naturalWidth*image.naturalHeight*4};}catch(e){URL.revokeObjectURL(url);throw e;}
 }
 if(result.bytes>LIMITS.decodedBytes){if(result.url)URL.revokeObjectURL(result.url);throw Error(`刺激超过解码预算：${a.name}`);}this.cache.set(a.hash,result);this.used+=result.bytes;return result;
 }
 async preflight(p:Project,onProgress:(s:string)=>void){this.clear();this.mode='all';const required=new Set(p.trials.flatMap(t=>roles(p.paradigm).map(r=>t.stimuli[r]?.id))),assets=p.assets.filter(a=>required.has(a.id)),sizes=new Map<string,number>();
 // First decode sequentially to measure actual allocation without retaining unbounded buffers.
 for(const a of assets){this.clear();onProgress(`检查 ${a.name}`);const media=await this.prepare(a);sizes.set(a.hash,media.bytes);}this.clear();
 if([...sizes.values()].reduce((n,b)=>n+b,0)<=LIMITS.decodedBytes){for(const a of assets)await this.prepare(a);}else this.mode='chunked';
 }
 async trial(p:Project,index:number){const selected=roles(p.paradigm).map(role=>{const id=p.trials[index].stimuli[role]?.id,a=p.assets.find(a=>a.id===id);if(!a)throw Error(`缺少 ${role} 刺激`);return {role,asset:a};});if(this.mode==='chunked')this.clear();const prepared=[];for(const a of selected){const media=await this.prepare(a.asset);if(this.used>LIMITS.decodedBytes){this.clear();throw Error('单试次刺激解码总量超过 128 MiB');}prepared.push({role:a.role,media});}return prepared;}
 dispose(){this.clear();void this.context.close();}
}
export function clockMapping(ctx:AudioContext){const before=performance.now(),audioSeconds=ctx.currentTime,after=performance.now();return {audioSeconds,performanceMs:(before+after)/2,bracketMs:after-before};}
export function outputStamp(ctx:AudioContext){try{const t=ctx.getOutputTimestamp?.();return t&&typeof t.contextTime==='number'&&typeof t.performanceTime==='number'&&t.contextTime>0&&t.performanceTime>0?{contextTime:t.contextTime,performanceTime:t.performanceTime}:null;}catch{return null;}}
export function timing(ctx:AudioContext):Timing{return {timeOrigin:performance.timeOrigin,preparedPerfMs:performance.now(),responseOpenPerfMs:null,keyEventPerfMs:null,keyHandledPerfMs:null,visualFramePerfMs:null,audioMapping:clockMapping(ctx),planned:[],observedEnded:[],endDetectedPerfMs:null,responseDelayFromMappedEndMs:null,outputTimestamp:outputStamp(ctx)};}
