"""Synchronize application versions; root legacy pyproject remains untouched."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    version = json.loads((ROOT / 'release/version.json').read_text('utf-8'))
    outputs = {}
    for package in ['packages/phonetic_core', 'backend', 'desktop']:
        path = ROOT / package / 'pyproject.toml'
        content = path.read_text('utf-8')
        content = re.sub(r'(?m)^version = ".*"$', f'version = "{version["app_version"]}"', content)
        content = re.sub(r'phonetic-core==[^"\s]+', 'phonetic-core==' + version['app_version'], content)
        outputs[path] = content
    frontend = ROOT / 'frontend/package.json'
    value = json.loads(frontend.read_text('utf-8'))
    value['version'] = version['frontend_version']
    # Formatting is preserved if only semantic version data is already correct.
    if json.loads(frontend.read_text('utf-8')) != value:
        outputs[frontend] = json.dumps(value, indent=2) + '\n'
    outputs[ROOT / 'frontend/src/version.json'] = json.dumps(version, indent=2) + '\n'
    outputs[ROOT / 'backend/src/ptb_api/protocol_version.py'] = (
        '# Generated by scripts/sync_versions.py; do not edit.\n' + f'API_VERSION = {version["api_version"]!r}\n')
    drift = []
    for path, content in outputs.items():
        if not path.exists() or path.read_text('utf-8') != content:
            if args.check:
                drift.append(path.relative_to(ROOT).as_posix())
            else:
                path.write_text(content, encoding='utf-8', newline='\n')
    lock = ROOT / 'frontend/package-lock.json'
    if lock.exists():
        data = json.loads(lock.read_text('utf-8'))
        if data['version'] != version['frontend_version'] or data['packages']['']['version'] != version['frontend_version']:
            drift.append('frontend/package-lock.json (run npm install --package-lock-only --ignore-scripts)')
    print(json.dumps({'version_drift': drift}))
    raise SystemExit(bool(drift))


if __name__ == '__main__':
    main()
