<script setup lang="ts">
import {computed,ref} from 'vue';import ScientificPlot from '../../components/ScientificPlot.vue';import type {components} from '../../../../contracts/generated/api';
import {scientificPlotsPng,downloadPng} from '../../design/plot-export.ts';
const grid=ref<HTMLElement>(),saving=ref(false),error=ref('');
async function save(index?:number){if(!grid.value||saving.value)return;saving.value=true;error.value='';try{const panels=[...grid.value.querySelectorAll<HTMLElement>(':scope>section')];downloadPng(await scientificPlotsPng(index==null?panels:[panels[index]]),'EGG-逆滤波'+(index==null?'四图':'-'+(index+1))+'.png');}catch(e){error.value=String(e);}finally{saving.value=false;}}
const props=defineProps<{data:components['schemas']['EggInverseData']}>();
const extent=(values:number[]):[number,number]=>{const lo=values.reduce((a,b)=>Math.min(a,b),Infinity),hi=values.reduce((a,b)=>Math.max(a,b),-Infinity),pad=Math.max(.001,(hi-lo)*.05);return [lo-pad,hi+pad];};
const range=computed<[number,number]>(()=>[props.data.relative_times_s[0]*1000,props.data.relative_times_s.at(-1)!*1000]);
const waves=computed(()=>[{label:'归一化分析音频',times:props.data.relative_times_s.map(t=>t*1000),values:props.data.audio_values,opacity:.62,color:'var(--wave)'},{label:'IF 估计',times:props.data.relative_times_s.map(t=>t*1000),values:props.data.inverse_values,opacity:.62,color:'var(--teal)',right:true}]);
</script>
<template><div class="inverse-actions"><button @click="save()" :disabled="saving">保存四图 PNG</button><span v-if="saving" role="status">正在生成图片…</span><span v-if="error" role="alert">{{error}}</span></div><div ref="grid" class="inverse-grid"><section><h3>音频与 IF 频谱</h3><ScientificPlot :height="300" title="逆滤波前后频谱对比" :x="[0,5000]" :y="extent([...data.audio_db,...data.inverse_db])" unit="dB" x-unit="Hz" :traces="[{label:'归一化分析音频',times:data.frequencies_hz,values:data.audio_db,opacity:.62,color:'var(--wave)'},{label:'IF 估计',times:data.frequencies_hz,values:data.inverse_db,opacity:.62,color:'var(--teal)'}]"/><button @click="save(0)" :disabled="saving">保存此图 PNG</button></section><section><h3>音频与 IF 波形 · 中心 50 ms</h3><ScientificPlot :height="300" title="逆滤波前后波形对比" :x="range" :y="extent(data.audio_values)" :right="extent(data.inverse_values)" unit="振幅" right-unit="IF" x-unit="ms" :traces="waves"/><button @click="save(1)" :disabled="saving">保存此图 PNG</button></section><section><h3>EGG 频谱</h3><ScientificPlot :height="300" title="EGG 频谱" :x="[0,5000]" :y="extent(data.egg_db)" unit="dB" x-unit="Hz" :traces="[{label:'滤波 EGG',times:data.frequencies_hz,values:data.egg_db,opacity:.62,color:'var(--violet)'}]"/><button @click="save(2)" :disabled="saving">保存此图 PNG</button></section><section><h3>EGG 波形 · 中心 50 ms</h3><ScientificPlot :height="300" title="逆滤波区间 EGG 波形" :x="range" :y="extent(data.egg_values)" unit="振幅" x-unit="ms" :traces="[{label:'滤波 EGG',times:data.relative_times_s.map(t=>t*1000),values:data.egg_values,opacity:.62,color:'var(--violet)'}]"/><button @click="save(3)" :disabled="saving">保存此图 PNG</button></section></div><p class="hint">频谱沿用补零至至少 44100 点、周期 Hamming 窗及各谱峰下 80 dB 截底。两条音频波形分别使用左右纵轴。</p></template>
<style scoped>.inverse-actions{display:flex;gap:12px;align-items:center}.inverse-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.inverse-grid section{min-width:0;border:1px solid var(--border);border-radius:var(--radius);padding:8px}@media(max-width:850px){.inverse-grid{grid-template-columns:1fr}}</style>
