<script setup lang="ts">
import {computed} from 'vue';import ScientificPlot from '../../components/ScientificPlot.vue';import type {components} from '../../../../contracts/generated/api';
const props=defineProps<{data:components['schemas']['EggInverseData']}>();
const extent=(values:number[]):[number,number]=>{const lo=Math.min(...values),hi=Math.max(...values),pad=Math.max(.001,(hi-lo)*.05);return [lo-pad,hi+pad];};
const range=computed<[number,number]>(()=>[props.data.relative_times_s[0]*1000,props.data.relative_times_s.at(-1)!*1000]);
const waves=computed(()=>[{label:'归一化分析音频',times:props.data.relative_times_s.map(t=>t*1000),values:props.data.audio_values,color:'var(--wave)'},{label:'IF 估计',times:props.data.relative_times_s.map(t=>t*1000),values:props.data.inverse_values,color:'var(--teal)',right:true}]);
</script>
<template><div class="inverse-grid"><section><h3>音频与 IF 频谱</h3><ScientificPlot title="逆滤波前后频谱对比" :x="[0,5000]" :y="extent([...data.audio_db,...data.inverse_db])" unit="dB" x-unit="Hz" :traces="[{label:'归一化分析音频',times:data.frequencies_hz,values:data.audio_db,color:'var(--wave)'},{label:'IF 估计',times:data.frequencies_hz,values:data.inverse_db,color:'var(--teal)'}]"/></section><section><h3>音频与 IF 波形 · 中心 50 ms</h3><ScientificPlot title="逆滤波前后波形对比" :x="range" :y="extent(data.audio_values)" :right="extent(data.inverse_values)" unit="振幅" right-unit="IF" x-unit="ms" :traces="waves"/></section><section><h3>EGG 频谱</h3><ScientificPlot title="EGG 频谱" :x="[0,5000]" :y="extent(data.egg_db)" unit="dB" x-unit="Hz" :traces="[{label:'滤波 EGG',times:data.frequencies_hz,values:data.egg_db,color:'var(--violet)'}]"/></section><section><h3>EGG 波形 · 中心 50 ms</h3><ScientificPlot title="逆滤波区间 EGG 波形" :x="range" :y="extent(data.egg_values)" unit="振幅" x-unit="ms" :traces="[{label:'滤波 EGG',times:data.relative_times_s.map(t=>t*1000),values:data.egg_values,color:'var(--violet)'}]"/></section></div><p class="hint">频谱沿用补零至至少 44100 点、周期 Hamming 窗及各谱峰下 80 dB 截底。两条音频波形分别使用左右纵轴。</p></template>
<style scoped>.inverse-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.inverse-grid section{min-width:0;border:1px solid var(--border);border-radius:var(--radius);padding:8px}@media(max-width:850px){.inverse-grid{grid-template-columns:1fr}}</style>
