<script setup lang="ts">
import {computed} from 'vue';
import ScientificPlot from '../../components/ScientificPlot.vue';
import {visibleAmplitude,visibleF0Range} from './display.ts';
import type {EggPreviewData,EggTaskConfig} from '../../platform/research.ts';
const props=defineProps<{data?:EggPreviewData;psd?:string;config:EggTaskConfig}>();const emit=defineEmits<{seek:[time:number];gesture:[area:'main'|'micro',kind:'zoom'|'pan',value:number]}>();
const range=computed<[number,number]>(()=>[props.config.roi_start??0,props.config.roi_end??.5]);
const microRange=computed<[number,number]>(()=>[-(props.config.micro_width_ms??50)/2,(props.config.micro_width_ms??50)/2]);
const cursor=computed(()=>props.data?[{time:props.config.micro_center??props.data.micro_center,label:'微观中心',color:'var(--danger)'}]:[]);
const markers=computed(()=>[...(props.data?.gci??[]).map(time=>({time:(time-(props.config.micro_center??props.data!.micro_center))*1000,label:'GCI'})),...(props.data?.goi??[]).map(time=>({time:(time-(props.config.micro_center??props.data!.micro_center))*1000,label:'GOI',dashed:true}))]);
const trace=(key:'cq'|'sq'|'praat'|'gci_f0'|'reaper',label:string,color:string,right=false)=>({...(props.data?.[key]??{times:[],values:[]}),label,color,right,points:true});
const micro=(key:'audio'|'egg',label:string,color:string)=>({times:(props.data?.[key].times??[]).map(t=>(t-(props.config.micro_center??props.data!.micro_center))*1000),values:props.data?.[key].values??[],label,color});
const f0Range=computed(()=>visibleF0Range([...(props.config.keep_praat_f0&&props.data?[props.data.praat]:[]),...(props.config.keep_gci_f0&&props.data?[props.data.gci_f0]:[]),...(props.config.keep_reaper_f0&&props.data?.reaper?[props.data.reaper]:[])],...range.value));
const amplitude=(key:'audio'|'egg')=>{const trace=micro(key,'','');return visibleAmplitude(trace.times,trace.values,...microRange.value);};
</script>
<template><div class="egg-four-plots" title="CQ：processed ±100 ms 重复滤波；微观显示：raw ±100 ms 滤波裁剪；微观事件：raw ±50 ms。GCI 实线，GOI 虚线。">
<section class="egg-plot cq-pane"><header><h2>CQ / SQ</h2><small>点击定位 · 滚轮缩放 · 拖动平移</small></header><ScientificPlot fill :height="240" interactive wheel-zoom live-pan :axis-label-width="6" :markers="cursor" @zoom="emit('gesture','main','zoom',$event)" @pan="emit('gesture','main','pan',$event)" title="CQ 与 SQ 双轴图" :x="range" :y="[0,1]" :right="[-1.1,1.1]" unit="CQ" right-unit="SQ" :empty="!data" :traces="[trace('cq','CQ','var(--wave)'),trace('sq','SQ','var(--teal)',true)]" @seek="emit('seek',$event)"/></section>
<section class="egg-plot audio-pane"><header><h2>音频 · 微观</h2><small>{{data?(config.micro_center??data.micro_center).toFixed(4)+' s':'尚未定位'}} · 相对时间<span v-if="(data?.micro_sample_stride??1)>1"> · 每 {{data?.micro_sample_stride}} 点显示一点</span></small></header><ScientificPlot fill :height="240" interactive wheel-zoom live-pan @zoom="emit('gesture','micro','zoom',$event)" @pan="emit('gesture','micro','pan',$event)" title="音频微观波形与事件" :x="microRange" :y="amplitude('audio')" unit="归一化振幅" x-unit="ms" :empty="!data" :markers="markers" :traces="[micro('audio','归一化音频','var(--waveform-color,var(--wave))')]"/></section>
<section class="egg-plot spec-pane"><header><h2>语谱图 / F0</h2><small>PSD · 频率左轴 / F0 右轴</small></header><div class="egg-colorbar"><span>{{config.spec_vmin}} dB</span><i/><span>{{config.spec_vmax}} dB</span></div><ScientificPlot fill :height="240" interactive wheel-zoom live-pan @zoom="emit('gesture','main','zoom',$event)" @pan="emit('gesture','main','pan',$event)" title="EGG 音频语谱图及 F0" :axis-label-width="6" :markers="[...cursor,...(data?.movement??[]).map(([time,label])=>({time,label}))]" :x="range" :y="[0,5000]" :right="f0Range" reserve-right-axis unit="Hz" :right-unit="f0Range?'F0 Hz':undefined" :empty="!data" :raster="data&&psd?{url:psd,extent:data.spectral_extent}:undefined" :traces="[...(config.keep_praat_f0?[trace('praat','Praat','var(--violet)',true)]:[]),...(config.keep_gci_f0?[trace('gci_f0','GCI F0','var(--danger)',true)]:[]),...(config.keep_reaper_f0?[trace('reaper','REAPER F0','var(--teal)',true)]:[])]" @seek="emit('seek',$event)"/></section>
<section class="egg-plot egg-pane"><header><h2>EGG · 微观</h2><slot name="filter"/></header><ScientificPlot fill :height="240" interactive wheel-zoom live-pan @zoom="emit('gesture','micro','zoom',$event)" @pan="emit('gesture','micro','pan',$event)" title="EGG 微观波形与事件" :x="microRange" :y="amplitude('egg')" unit="归一化振幅" x-unit="ms" :empty="!data" :markers="markers" :traces="[micro('egg',config.signal_mode==='raw'?'原始 EGG':'滤波 EGG','var(--teal)')]"/></section>
</div></template>
<style scoped>
.egg-four-plots{display:grid;grid-template-columns:1fr 1fr;gap:10px;min-width:0}.egg-plot{min-width:0;border:1px solid var(--border);border-radius:var(--radius);background:var(--panel);overflow:hidden}.egg-plot>header{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap;padding:8px 12px 0;min-height:35px}.egg-plot>.hint{padding:0 12px 7px}.egg-colorbar{display:flex;align-items:center;gap:8px;padding:0 12px;font-family:var(--font-figure);font-size:var(--figure-size)}.egg-colorbar i{height:6px;flex:1;background:linear-gradient(to right,#fff,#000);border:1px solid var(--border)}@media(max-width:980px){.egg-four-plots{grid-template-columns:1fr}.audio-pane{grid-row:3}}
.egg-four-plots{height:100%;grid-template-rows:repeat(2,minmax(0,1fr))}.egg-plot{display:flex;flex-direction:column;min-height:0}.egg-plot :deep(.scientific-plot){flex:1;min-height:0}.egg-plot>header,.egg-colorbar{flex:none}@media(max-width:980px){.egg-four-plots{grid-template-rows:repeat(4,minmax(240px,1fr))}}
</style>
