<script setup lang="ts">
import {computed,ref,reactive,markRaw,watch,onMounted,onUnmounted} from 'vue';
import {type ResearchContext,type ResearchFile,audioPreview} from '../../platform/research.ts';
import {workspace,host,type Workspace} from '../../state/workspace.ts';import {stop} from '../../state/audio.ts';import {decodeWav} from '../../platform/decode.ts';
import ModuleFrame from '../../components/ModuleFrame.vue';import ModuleToolbar from '../../components/ModuleToolbar.vue';import ModuleSection from '../../components/ModuleSection.vue';import ModuleStatus from '../../components/ModuleStatus.vue';import ModalDialog from '../../components/ModalDialog.vue';
import WaveformViewport from '../../components/WaveformViewport.vue';import AudioTransport from '../../components/AudioTransport.vue';import TaskPanel from '../../components/TaskPanel.vue';
import PitchCurve from './PitchCurve.vue';import HistoryPlot from './HistoryPlot.vue';
import type {Config,Point,Mode,M08Port,Job,Result} from './port.ts';import {defaults,modes,finite,frequencies,validate,importF0,renamePlan,visible,errorText} from './state.ts';
const props=defineProps<{context:ResearchContext;stateKey:string;active:boolean;port?:M08Port}>();const emit=defineEmits<{references:[]}>();
const port=computed(()=>props.port??(props.context.files as typeof props.context.files&{m08?:M08Port}).m08);
const wave=workspace(props.stateKey),resultWave=reactive<Workspace>({...wave,asset:null,dirty:false});
const files=ref<ResearchFile[]>([]),source=ref<ResearchFile>(),directory=ref(''),picker=ref<HTMLInputElement>(),folderPicker=ref<HTMLInputElement>();
const config=reactive(defaults()),times=ref<number[]>([]),original=ref<number[]>([]),modified=ref<number[]>([]),refs=ref<number[]>([]),refInput=ref('200');
const minInput=ref('50'),maxInput=ref('350'),ymin=ref(50),ymax=ref(350),error=ref(''),notice=ref(''),busy=ref(false),tab=ref('single'),help=ref(false),importing=ref(false),importText=ref('');
const jobs=ref<Job[]>([]),history=ref<Result[]>([]),result=ref<Result>(),historyPlot=ref<InstanceType<typeof HistoryPlot>>(),playResult=ref(false),batchIds=ref<string[]>([]),cancelSubmit=ref(false);
const editing=ref(false),rows=ref<{time:string;freqs:string;mode:Mode;selected:boolean}[]>([]),selectedResults=ref<string[]>([]),manage=ref<'delete'|'rename'|null>(null),prefix=ref(''),pendingFile=ref<string>();
let disposed=false,epoch=0,previewAbort:AbortController|undefined,timer:ReturnType<typeof setInterval>,polling=false,resultEpoch=0;
const audioFiles=computed(()=>files.value.filter(f=>f.kind==='audio'));
const range=computed(()=>visible(wave.asset?.duration??0,wave.zoom,wave.offset));
const originalPlayback=computed<Workspace>(()=>({...wave,start:range.value[0],end:range.value[1]}));
const tasks=computed(()=>jobs.value.map(j=>({id:j.id,title:`${files.value.find(f=>f.id===j.source_id)?.name??'音频'} · ${j.id.slice(0,8)}`,status:j.state,error:j.error?errorText(j.error):undefined,canCancel:true})));
const currentBatch=computed(()=>history.value.filter(r=>r.source_id===source.value?.id&&r.start.toFixed(2)===range.value[0].toFixed(2)&&r.end.toFixed(2)===range.value[1].toFixed(2)));
const chosen=computed(()=>currentBatch.value.filter(r=>selectedResults.value.includes(r.id)));
watch(range,([a,b])=>{stop();wave.start=a;wave.end=b;});watch(config,()=>wave.dirty=true,{deep:true});
watch(()=>props.active,active=>{if(!active)stop();});
function dirty(){wave.dirty=true;}
async function attempt(work:()=>Promise<void>|void){error.value='';try{await work();}catch(e){if(!disposed)error.value=errorText(e);}}
async function refresh(){const next=await props.context.files.list(directory.value||undefined);if(disposed)return;files.value=next;batchIds.value=batchIds.value.filter(id=>next.some(f=>f.id===id));}
async function choose(){await attempt(async()=>{const grant=await props.context.files.choose?.('input');if(grant){directory.value=grant.id;await refresh();}});}
async function add(event:Event){await attempt(async()=>{const input=event.target as HTMLInputElement;props.context.files.add?.([...input.files??[]]);input.value='';await refresh();});}
function requestLoad(id:string){if(wave.dirty&&source.value&&id!==source.value.id){pendingFile.value=id;return;}void load(id);}
function selectSource(event:Event){const element=event.target as HTMLSelectElement,id=element.value;element.value=source.value?.id??'';requestLoad(id);}
async function load(id:string){await attempt(async()=>{const file=files.value.find(f=>f.id===id);if(!file)return;const ticket=++epoch;previewAbort?.abort();previewAbort=new AbortController();busy.value=true;stop();source.value=file;times.value=[];original.value=[];modified.value=[];result.value=undefined;resultWave.asset=null;history.value=[];wave.asset=null;
 try{if(port.value){const data=await port.value.preview(file,previewAbort.signal);if(disposed||ticket!==epoch)return;wave.asset=markRaw(await decodeWav(data.wav,file.name));source.value={...file,sha256:data.sha256};times.value=data.times;original.value=data.original_f0;modified.value=[...data.original_f0];}else{const data=await audioPreview(props.context.files,file,previewAbort.signal);if(disposed||ticket!==epoch)return;wave.asset=markRaw(data.asset);source.value={...file,sha256:data.sha256};}
 if(disposed||ticket!==epoch)return;wave.zoom=1;wave.offset=0;wave.start=0;wave.end=wave.asset!.duration;wave.channel=0;
 const voiced=times.value.filter((_,i)=>original.value[i]>0);config.points=[{time:Number((voiced[0]??0).toFixed(2)),freqs:[],mode:'order'},{time:Number((voiced.at(-1)??wave.asset!.duration).toFixed(2)),freqs:[],mode:'order'}];
 const saved=host.projects.read<{sha256?:string;modified?:number[];config?:Config;refs?:number[];ymin?:number;ymax?:number}>('m08.draft.'+props.stateKey+'.'+file.id,{});
 if(saved.sha256===source.value.sha256&&saved.modified?.length===times.value.length&&saved.modified.every(Number.isFinite)){modified.value=saved.modified;if(saved.config)Object.assign(config,saved.config);refs.value=saved.refs??[];ymin.value=saved.ymin??50;ymax.value=saved.ymax??350;minInput.value=String(ymin.value);maxInput.value=String(ymax.value);}
 if(port.value)history.value=await port.value.history(source.value);await Promise.resolve();wave.dirty=false;
 }finally{if(ticket===epoch)busy.value=false;}});}
function save(){try{if(!source.value)throw Error('请先选择音频');if(!host.projects.write('m08.draft.'+props.stateKey+'.'+source.value.id,{sha256:source.value.sha256,modified:modified.value,config:{...config},refs:refs.value,ymin:ymin.value,ymax:ymax.value}))throw Error('草稿保存失败');wave.dirty=false;notice.value='F0 与参数草稿已保存';return true;}catch(e){error.value=errorText(e);return false;}}
defineExpose({save});
function pan(delta:number){wave.offset=Math.max(0,Math.min((wave.asset?.duration??0)-(range.value[1]-range.value[0]),wave.offset+delta));}
function zoom(factor:number,time:number){if(!wave.asset)return;const old=range.value,rel=(time-old[0])/(old[1]-old[0]);wave.zoom=Math.max(1,Math.min(wave.asset.duration/.05,wave.zoom*factor));wave.offset=Math.max(0,Math.min(wave.asset.duration-wave.asset.duration/wave.zoom,time-rel*wave.asset.duration/wave.zoom));}
function applyAxis(){void attempt(()=>{const a=finite(minInput.value,'F0 下限'),b=finite(maxInput.value,'F0 上限');if(a>=b)throw Error('F0 上限必须大于下限');ymin.value=a;ymax.value=b;dirty();});}
function applyImport(){void attempt(()=>{modified.value=importF0(times.value,modified.value,...range.value,importText.value);dirty();importing.value=false;});}
function editPoints(){rows.value=config.points.map(p=>({time:String(p.time),freqs:p.freqs.join(','),mode:p.mode,selected:false}));editing.value=true;}
function savePoints(){void attempt(()=>{const points=rows.value.map(r=>({time:finite(r.time,'时间'),freqs:frequencies(r.freqs),mode:r.mode}));const middle=points.slice(1,-1).sort((a,b)=>a.time-b.time);const sorted=[points[0],...middle,points.at(-1)!];validate(sorted,...range.value);config.points=sorted;editing.value=false;});}
function snapshot(action:Config['action'],whole=false):Config {const speed=finite(config.speed,'语速倍率'),ratio=finite(config.pitch_ratio,'音高倍率'),hz=finite(config.pitch_hz,'音高偏移');if(speed<=0||ratio<=0)throw Error('倍率必须大于 0');const [a,b]=range.value;if(action==='linear')validate(config.points,a,b);return {action,start:whole?0:a,end:whole?(action==='transform'?null:wave.asset!.duration):b,speed,pitch_ratio:ratio,pitch_hz:hz,modified_f0:action==='synthesize'?[...modified.value]:null,points:action==='linear'?config.points.map(p=>({...p,freqs:[...p.freqs]})):[],offset:config.offset};}
async function show(r:Result){const ticket=++resultEpoch;await attempt(async()=>{stop();const bytes=await port.value!.audio(r);const asset=await decodeWav(bytes,r.name);if(disposed||ticket!==resultEpoch)return;result.value=r;resultWave.asset=markRaw(asset);resultWave.start=0;resultWave.end=asset.duration;resultWave.zoom=1;resultWave.offset=0;playResult.value=true;});}
async function poll(){if(polling||disposed||!port.value)return;polling=true;try{const old=jobs.value;const next=await port.value.jobs();if(disposed)return;jobs.value=next;for(const job of next){if(job.state==='succeeded'&&job.source_id===source.value?.id&&old.find(j=>j.id===job.id)?.state!=='succeeded'){if(job.results.length)await show(job.results[0]);if(source.value)history.value=await port.value.history(source.value);}}}catch(e){if(!disposed)error.value=errorText(e);}finally{polling=false;}}
async function submit(action:Config['action'],whole=false){await attempt(async()=>{if(!source.value||!port.value)throw Error('M08 任务接口尚未接入');const file={...source.value},cfg=snapshot(action,whole);if(action==='synthesize'&&!cfg.modified_f0?.length)throw Error('未取得真实 F0，无法合成');busy.value=true;cancelSubmit.value=false;try{const job=await port.value.submit(file,cfg,crypto.randomUUID());if(disposed||cancelSubmit.value){await port.value.cancel(job.id);return;}jobs.value=[...jobs.value.filter(j=>j.id!==job.id),job];if(job.state==='succeeded'&&job.results.length)await show(job.results[0]);await poll();if(action==='linear')history.value=await port.value.history(file);}finally{busy.value=false;}});}
async function batch(){await attempt(async()=>{if(!port.value)throw Error('M08 任务接口尚未接入');const cfg=snapshot('transform',true),inputs=audioFiles.value.filter(f=>batchIds.value.includes(f.id));if(!inputs.length)throw Error('请选择至少一个批处理文件');busy.value=true;cancelSubmit.value=false;const failures:string[]=[];try{for(const file of inputs){if(cancelSubmit.value||disposed)break;try{const job=await port.value.submit(file,structuredClone(cfg),crypto.randomUUID());jobs.value.push(job);if(cancelSubmit.value||disposed)await port.value.cancel(job.id);}catch(e){failures.push(file.name+': '+errorText(e));}}notice.value=cancelSubmit.value?'已停止提交剩余文件':'批次已提交，各文件状态见任务列表';if(failures.length)error.value=failures.join('\n');await poll();}finally{busy.value=false;}});}
async function saveAudio(){await attempt(async()=>{const r=result.value;if(!r||!port.value)return;busy.value=true;try{const saved=await port.value.save(r);notice.value='已保存 '+saved.name;if(source.value)history.value=await port.value.history(source.value);}finally{busy.value=false;}});}
function openManage(kind:'delete'|'rename'){selectedResults.value=currentBatch.value.map(r=>r.id);manage.value=kind;let common=currentBatch.value[0]?.name??'';for(const r of currentBatch.value)while(!r.name.startsWith(common))common=common.slice(0,-1);prefix.value=common;}
async function manageFiles(){await attempt(async()=>{if(!port.value||!chosen.value.length)throw Error('请勾选需要处理的结果');const selected=[...chosen.value];busy.value=true;try{if(manage.value==='delete'){const out=await port.value.remove(selected.map(r=>r.id));if(out.failed.length)throw Error(out.failed.map(f=>f.id+': '+f.error).join('\n'));notice.value=`已删除 ${out.removed.length} 个本批次结果`;}else{await port.value.rename(renamePlan(selected,prefix.value,history.value.map(r=>r.name)));notice.value='重命名完成';}manage.value=null;}finally{if(source.value)history.value=await port.value.history(source.value);busy.value=false;}});}
async function exportPng(){await attempt(async()=>{const blob=await historyPlot.value!.png(),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='comparison_plot.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice.value='已导出实际历史 F0 对比图';});}
onMounted(()=>{void attempt(refresh);void poll();timer=setInterval(()=>void poll(),1000);});onUnmounted(()=>{disposed=true;++epoch;++resultEpoch;previewAbort?.abort();clearInterval(timer);stop();});
</script>
<template><ModuleFrame label="变速变调工作区" class="m08-page" :aria-busy="busy">
<template #toolbar><ModuleToolbar><button v-if="context.files.choose" :disabled="busy" @click="choose">打开音频目录</button><button v-if="context.files.add" :disabled="busy" @click="picker?.click()">导入音频</button><button v-if="context.files.add" :disabled="busy" @click="folderPicker?.click()">导入文件夹</button><input ref="picker" hidden type="file" multiple accept=".wav,.mp3,.flac" @change="add"/><input ref="folderPicker" hidden type="file" multiple webkitdirectory @change="add"/><button :disabled="busy" @click="attempt(refresh)">刷新文件</button><button :aria-pressed="tab==='single'" @click="tab='single'">单文件与基频</button><button :aria-pressed="tab==='batch'" @click="tab='batch'">批量变速变调</button><template #actions><button @click="help=true">使用说明</button><button @click="emit('references')">方法与引用</button></template></ModuleToolbar></template>
<template #status><ModuleStatus v-if="error" kind="error" :message="error"/><ModuleStatus v-if="notice" :message="notice"/><ModuleStatus v-if="!port" message="当前入口尚未接入 M08 任务与文件管理接口。WAV 波形及试听可用，计算、保存和批次管理待平台接线。"/><ModuleStatus v-if="busy" kind="loading" message="正在处理，请稍候…"/></template>
<ModuleSection label="音频与参数"><div class="row"><label>音频<select aria-label="M08 音频" :value="source?.id??''" :disabled="busy" @change="selectSource"><option value="">选择音频</option><option v-for="file in audioFiles" :key="file.id" :value="file.id">{{file.name}}</option></select></label><label>语速倍率<input v-model="config.speed" aria-label="语速倍率" type="number" step=".1"/></label><button :disabled="!source" @click="save">保存编辑草稿</button><span>{{wave.dirty?'有未保存编辑':'编辑已保存'}}</span></div></ModuleSection>
<div v-show="tab==='single'" class="single">
<div class="plots"><ModuleSection label="原始波形" title="原始波形"><WaveformViewport v-if="wave.asset" :state="wave" compact-overview auto-amplitude continuous-detail/><ModuleStatus v-else kind="empty" message="选择音频后显示真实波形。"/></ModuleSection>
<ModuleSection label="基频编辑" title="基频编辑 · 原始虚线 / 修改实线"><PitchCurve v-if="times.length" :times="times" :original="original" :modified="modified" :start="range[0]" :end="range[1]" :min="ymin" :max="ymax" :references="refs" editable @edit="v=>{modified=v;dirty()}" @pan="pan" @zoom="zoom"/><ModuleStatus v-else kind="empty" message="取得 Praat F0 后可编辑。"/><small>Shift＋拖动绘制，Ctrl＋拖动恢复，普通拖动平移，Ctrl＋滚轮缩放。</small></ModuleSection>
<ModuleSection label="合成波形" title="合成波形"><WaveformViewport v-if="resultWave.asset" :state="resultWave" compact-overview auto-amplitude continuous-detail/><ModuleStatus v-else kind="empty" message="合成后显示实际输出。"/><small v-if="result">源区间 {{result.start.toFixed(3)}}–{{result.end.toFixed(3)}} s；输出 {{resultWave.asset?.duration.toFixed(3)}} s。当前编辑不会覆盖此结果。</small></ModuleSection>
<ModuleSection label="历史 F0 对比" title="历史 F0 对比 · 零起点对齐"><HistoryPlot ref="historyPlot" :results="history" :min="ymin" :max="ymax"/><button :disabled="!history.length" @click="exportPng">保存对比图</button></ModuleSection></div>
<ModuleSection label="曲线与试听"><div class="row"><label>F0 下限 Hz<input v-model="minInput" aria-label="F0 下限" type="number"/></label><label>上限 Hz<input v-model="maxInput" aria-label="F0 上限" type="number"/></label><button @click="applyAxis">应用范围</button><label>参考线 Hz<input v-model="refInput" aria-label="参考线 Hz" type="number"/></label><button @click="attempt(()=>{refs.push(finite(refInput,'参考线'));dirty()})">添加参考线</button><button @click="refs=[];dirty()">清除参考线</button><button :disabled="!times.length" @click="importing=true">导入基频序列</button></div>
<div class="row"><strong>当前视野 {{range[0].toFixed(3)}}–{{range[1].toFixed(3)}} s</strong><button class="primary" :disabled="busy||!port||!times.length" @click="submit('synthesize')">合成当前视野</button><button :disabled="busy||!port||!times.length" @click="submit('synthesize',true)">合成整段</button><button :disabled="busy||!result||!port" @click="saveAudio">保存并编号</button><button :disabled="!result||!port" @click="attempt(()=>port!.download(result!))">下载合成音</button><button :disabled="!wave.asset" @click="playResult=false;stop()">当前视野原音</button><button :disabled="!resultWave.asset" @click="playResult=true;stop()">合成音</button><span>{{playResult?'试听合成音':'试听当前视野原音'}}</span><AudioTransport :state="playResult?resultWave:originalPlayback" :active="active" compact/></div></ModuleSection>
<ModuleSection label="批量改变基频" title="批量改变基频"><div class="row"><button :disabled="!times.length" @click="editPoints">编辑拐点表</button><button :disabled="!times.length" @click="editPoints();rows.splice(rows.length-1,0,{time:'',freqs:'',mode:'order',selected:false})">添加拐点</button><button @click="config.points=config.points.length>=2?[config.points[0],config.points.at(-1)!]:[]">清除拐点</button><span>直线插值 · {{Math.max(0,config.points.length-2)}} 个拐点</span><label><input v-model="config.offset" type="checkbox"/>升降偏移 (Hz)</label><button :disabled="busy||!port||!times.length" @click="submit('linear')">批量生成并保存</button></div><div class="point-summary"><span v-for="(p,i) in config.points" :key="i">{{p.time}} s：{{p.freqs.join(', ')||'未填写'}} Hz · {{modes.find(m=>m.value===p.mode)?.label}}</span></div></ModuleSection>
<ModuleSection label="本批次与历史文件" title="本批次与历史文件"><div class="row"><button :disabled="busy||!currentBatch.length||!port" @click="openManage('delete')">删除本批次音频</button><button :disabled="busy||!currentBatch.length||!port" @click="openManage('rename')">批量重命名</button><span>当前视野批次 {{currentBatch.length}} 个；同源历史 {{history.length}} 个</span></div><ul class="history"><li v-for="(r,i) in history" :key="r.id"><span>{{i+1}} · {{r.name}}</span><button @click="show(r)">试听此版本</button><details><summary>生成参数</summary><pre>{{JSON.stringify(r.config,null,2)}}</pre></details></li></ul></ModuleSection></div>
<ModuleSection v-show="tab==='batch'" label="文件夹批量处理" title="文件夹批量处理 · 整段音频"><div class="row"><label>音高倍率<input v-model="config.pitch_ratio" aria-label="音高倍率" type="number" step=".1"/></label><label>音高偏移 Hz<input v-model="config.pitch_hz" aria-label="音高偏移 Hz" type="number"/></label><button @click="batchIds=audioFiles.map(f=>f.id)">全选音频</button><button @click="batchIds=[]">清除选择</button><button class="primary" :disabled="busy||!port" @click="batch">开始批量处理</button><button v-if="busy" @click="cancelSubmit=true">停止提交剩余文件</button></div><div class="file-list"><label v-for="f in audioFiles" :key="f.id"><input v-model="batchIds" :value="f.id" type="checkbox"/>{{f.name}}</label></div><small>先变速，再乘音高倍率，最后加 Hz 偏移。逐文件报告失败；结果交由平台保存，不覆盖原音频。</small></ModuleSection>
<ModuleSection label="变速变调任务"><TaskPanel :tasks="tasks" empty-text="实际任务接入后显示提交、取消及逐文件结果。" @cancel="id=>attempt(()=>port!.cancel(id))"/><div class="row"><button v-for="j in jobs.filter(j=>j.state==='succeeded'&&j.results.length)" :key="j.id" @click="show(j.results[0])">查看任务 {{j.id.slice(0,8)}}</button></div></ModuleSection>
<ModalDialog v-if="importing" title="导入基频序列" @close="importing=false"><p>每行一个 F0；两列时取第二列，时间列忽略。沿当前视野内唯一连续有声段均匀重采样，不改变视野。</p><textarea v-model="importText" aria-label="基频序列" rows="8"/><ModuleStatus v-if="error" kind="error" :message="error"/><template #footer><button @click="importing=false">取消</button><button @click="applyImport">导入序列</button></template></ModalDialog>
<ModalDialog v-if="editing" title="编辑拐点表" wide @close="editing=false"><p>首行与末行是起终点，可编辑、不可删除。中间拐点保存时按时间排序，连接方式随行保留。</p><div class="table-wrap"><table><thead><tr><th>选择</th><th>时间 s</th><th>频率列表 Hz</th><th>连接方式</th></tr></thead><tbody><tr v-for="(r,i) in rows" :key="i"><td><input v-model="r.selected" type="checkbox" :disabled="i===0||i===rows.length-1" :aria-label="'选择拐点 '+i"/></td><td><input v-model="r.time" type="number" :aria-label="'时间 '+i"/></td><td><input v-model="r.freqs" :aria-label="'频率 '+i"/></td><td><select v-model="r.mode" :aria-label="'连接 '+i"><option v-for="m in modes" :key="m.value" :value="m.value">{{m.label}}</option></select></td></tr></tbody></table></div><ModuleStatus v-if="error" kind="error" :message="error"/><template #footer><button @click="rows.splice(rows.length-1,0,{time:'',freqs:'',mode:'order',selected:false})">添加行</button><button @click="rows=rows.filter((r,i)=>i===0||i===rows.length-1||!r.selected)">删除选中拐点</button><button @click="editing=false">取消</button><button @click="savePoints">保存更改</button></template></ModalDialog>
<ModalDialog v-if="manage" :title="manage==='delete'?'确认删除本批次音频':'批量重命名'" :close-disabled="busy" @close="manage=null"><p>仅处理下列勾选的已生成结果，原始音频不在此列表。</p><label v-if="manage==='rename'">新的共同前缀<input v-model="prefix" aria-label="新的共同前缀"/></label><div class="file-list"><label v-for="r in currentBatch" :key="r.id"><input v-model="selectedResults" :value="r.id" type="checkbox"/>{{r.name}}</label></div><ModuleStatus v-if="error" kind="error" :message="error"/><template #footer><button :disabled="busy" @click="manage=null">取消</button><button :disabled="busy" @click="manageFiles">{{manage==='delete'?'确认删除所选音频':'确认重命名'}}</button></template></ModalDialog>
<ModalDialog v-if="pendingFile" title="保留当前编辑" @close="pendingFile=undefined"><p>切换文件前保存当前 F0 与参数草稿？</p><template #footer><button @click="pendingFile=undefined">取消</button><button @click="wave.dirty=false;load(pendingFile!);pendingFile=undefined">放弃并切换</button><button @click="if(save()){load(pendingFile!);pendingFile=undefined}">保存并切换</button></template></ModalDialog>
<ModalDialog v-if="help" title="变速变调使用说明" wide @close="help=false"><p>当前视野决定原音试听和局部合成。合成整段明确处理整个音频，F0 使用完整编辑曲线。变速后合成波形按实际输出时长显示。</p><p>F0 默认范围 50–350 Hz，语速 1.0，批量音高倍率 1.0、偏移 0 Hz。Praat 提取保留自身默认参数；Manipulation 为 0.01 s、75–600 Hz。小于等于约 0.01 的倍率差使用 V2 原阈值。</p><p>顺序/逆序先将列表排序，全连接按输入组合顺序，常量取首值。拐点必须位于起终点之间。偏移模式的值是 Hz 增量。</p><p>历史图来自已保存音频重新提取的 F0，零起点对齐。保存沿用 原名_起点_终点_modified_编号.wav；重复名称必须由宿主原子处理，不能覆盖旧文件。</p><p>方法：SRC-PRAAT。批量非零 Hz 偏移修正了旧版向 Praat 传入无效单位 Hz 的错误，使用 Hertz；其他计算顺序保持。</p></ModalDialog>
</ModuleFrame></template>
<style scoped>.m08-page{min-width:0;overflow-wrap:anywhere}.m08-page :deep(.task-row){min-width:0;overflow-wrap:anywhere}.single{display:grid;gap:var(--module-gap)}.plots{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--module-gap)}.row{display:flex;align-items:center;flex-wrap:wrap;gap:8px}.row+.row{margin-top:12px}.row label{display:flex;align-items:center;gap:6px}.row input[type=number]{width:86px}.row select{max-width:400px}.m08-page small{display:block;color:var(--muted);font-size:var(--support-size);line-height:1.6}.m08-page :deep(.wave-track svg){height:150px}.m08-page :deep(.m08-curve){height:240px}.m08-page :deep(.history-plot){height:240px}.point-summary,.file-list{display:flex;flex-direction:column;gap:8px;margin-top:10px}.history{padding-left:20px;max-height:260px;overflow:auto}.history li{margin:8px 0;overflow-wrap:anywhere}.history button{margin-left:8px}.history pre{white-space:pre-wrap}.file-list label{display:flex;gap:8px;overflow-wrap:anywhere}.table-wrap{overflow:auto}table input{max-width:180px}textarea{width:100%;background:var(--panel);color:var(--text);border:1px solid var(--border);font:inherit}button[aria-pressed=true]{background:var(--selected);color:var(--accent)}@media(max-width:1000px){.plots{grid-template-columns:1fr}.row select{max-width:100%}}@media(max-width:600px){.row label{flex-wrap:wrap;max-width:100%}.row select{width:100%}.row input{max-width:100%}}</style>
