<script setup lang="ts">
import ModuleWorkbench from '../../components/ModuleWorkbench.vue';
import ModuleFrame from '../../components/ModuleFrame.vue';
import ModuleToolbar from '../../components/ModuleToolbar.vue';
import ModuleStatus from '../../components/ModuleStatus.vue';
import {ref,computed,onMounted,onUnmounted,markRaw} from 'vue';
import type {ResearchContext,ResearchFile,JobView,ReconstructionConfig} from '../../platform/research.ts';
import {workspace} from '../../state/workspace.ts';
import {decodeWav} from '../../platform/decode.ts';
import {stop} from '../../state/audio.ts';
import WaveformViewport from '../../components/WaveformViewport.vue';
import {imageDimensions} from './image-header.ts';
const props=defineProps<{context:ResearchContext;stateKey:string}>();
const emit=defineEmits<{references:[];close:[]}>();
const wave=workspace(props.stateKey),files=ref<ResearchFile[]>([]),source=ref<ResearchFile>(),jobs=ref<JobView[]>([]),current=ref<JobView>();
const error=ref(''),notice=ref(''),busy=ref(false),imageUrl=ref(''),calibrated=ref(''),rebuilt=ref(''),metadata=ref<Record<string,unknown>>(),directory=ref(''),picker=ref<HTMLInputElement>();
const corners=ref<{x:number;y:number}[]>([]),selecting=ref(false),dimensions=ref({width:0,height:0});
const config=ref<ReconstructionConfig>({time_start:0,time_end:1,freq_start:0,freq_end:11025,min_db:-30,max_db:0,win_length_ms:10,n_iter:32,target_sr:44100,seed:0,corners:null});
const tasks=computed(()=>props.context.files.tasks),running=computed(()=>jobs.value.some(j=>['queued','running','cancel_requested'].includes(j.state)));
const changed=computed(()=>{const frozen=metadata.value?.config as ReconstructionConfig|undefined;if(!frozen)return false;return Object.entries(config.value).some(([k,v])=>k!=='corners'&&v!==frozen[k as keyof ReconstructionConfig])||JSON.stringify(corners.value.length?corners.value:null)!==JSON.stringify(frozen.corners);});
const states:Record<string,string>={queued:'排队中',running:'重建中',cancel_requested:'正在取消',cancelled:'已取消',failed:'失败',interrupted:'已中断，可重试',succeeded:'已完成'};
const errors:Record<string,string>={invalid_spectrogram_image:'图片格式无效，请使用 PNG、JPEG 或 BMP。',invalid_image_corners:'四点须按左上、右上、右下、左下顺序围成有效区域。',spectrogram_budget:'超出重建预算。请缩小图片区域、时长或迭代次数。',analysis_resource_limit:'图片或重建计算超过资源上限，请缩小区域。',deadline_exceeded:'重建超时，可缩小图片或减少迭代后重试。',input_unavailable:'原图已失效，请重新选择或上传。',execution_failed:'重建未完成。请检查图片格式与运行环境。'};
let disposed=false,epoch=0,polling=false;const urls=new Set<string>();
function url(raw:ArrayBuffer,type:string){const value=URL.createObjectURL(new Blob([raw],{type}));urls.add(value);return value;}
function release(value:string){if(value){URL.revokeObjectURL(value);urls.delete(value);}}
function clearResult(){stop();wave.asset=null;metadata.value=undefined;release(calibrated.value);release(rebuilt.value);calibrated.value='';rebuilt.value='';}
async function refresh(){try{const list=await props.context.files.list(directory.value||undefined);if(!disposed)files.value=list.filter(f=>f.kind==='image');}catch(e){error.value=String(e);}}
async function choose(){try{const grant=await props.context.files.choose?.('input');if(grant){directory.value=grant.id;await refresh();}}catch(e){error.value=String(e);}}
async function load(file:ResearchFile){const ticket=++epoch;current.value=undefined;error.value='';busy.value=true;try{if(file.size>16_000_000)throw Error('图片限 16 MB。');const data=await props.context.files.read(file);const size=imageDimensions(data.buffer);if(disposed||ticket!==epoch)return;dimensions.value=size;release(imageUrl.value);imageUrl.value=url(data.buffer,/\.png$/i.test(file.name)?'image/png':/\.bmp$/i.test(file.name)?'image/bmp':'image/jpeg');source.value=file;current.value=undefined;corners.value=[];selecting.value=false;clearResult();}catch(e){if(!disposed&&ticket===epoch)error.value=String(e);}finally{if(ticket===epoch)busy.value=false;}}
async function capture(){try{const file=await props.context.files.capture?.();if(file){await load(file);if(source.value?.id===file.id&&file.corners?.length===4){corners.value=file.corners.map(p=>({...p}));notice.value='截图与四角已载入，可直接重建或微调角点。';}}}catch(e){error.value=String(e);}}
function pick(event:MouseEvent){if(!selecting.value||corners.value.length>=4)return;const rect=(event.currentTarget as Element).getBoundingClientRect();corners.value.push({x:Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height))});if(corners.value.length===4)selecting.value=false;}
async function poll(){if(polling||disposed||!tasks.value?.reconstructions)return;polling=true;try{const data=await tasks.value.reconstructions();if(disposed)return;jobs.value=data;if(current.value){const next=data.find(j=>j.id===current.value?.id);if(next){const completed=current.value.state!=='succeeded'&&next.state==='succeeded';current.value=next;if(completed)await show(next);}}}catch(e){if(!disposed)error.value=String(e);}finally{polling=false;}}
async function submit(){if(!source.value||!tasks.value?.reconstruct)return;busy.value=true;error.value='';notice.value='';try{if(corners.value.length!==0&&corners.value.length!==4)throw Error('请完成四点选择，或重置为整张图片。');const frozen={...config.value,corners:corners.value.length===4?corners.value.map(p=>({...p})):null};clearResult();current.value=await tasks.value.reconstruct(source.value,frozen,crypto.randomUUID());await poll();}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function show(job:JobView){const ticket=++epoch;current.value=job;clearResult();if(job.state!=='succeeded'||job.result_manifest?.kind!=='managed_spec2wav_files'||!tasks.value?.result)return;busy.value=true;error.value='';try{const entries=job.result_manifest.files;const blobs:ArrayBuffer[]=[];for(const file of entries){blobs.push(await tasks.value.result(job.id,file.id,file.sha256));if(disposed||ticket!==epoch)return;}if(disposed||ticket!==epoch)return;for(let i=0;i<entries.length;i++){const name=entries[i].name,raw=blobs[i];if(name==='calibrated.png')calibrated.value=url(raw,'image/png');else if(name==='reconstructed.png')rebuilt.value=url(raw,'image/png');else if(name.endsWith('.json'))metadata.value=JSON.parse(new TextDecoder().decode(raw));else {const asset=await decodeWav(raw,name);if(disposed||ticket!==epoch)return;wave.asset=markRaw(asset);wave.start=0;wave.end=asset.duration;wave.offset=0;wave.zoom=1;wave.channel=0;}}}catch(e){error.value=String(e);}finally{if(ticket===epoch)busy.value=false;}}
async function cancel(job:JobView){try{await tasks.value?.cancelJob?.(job.id);await poll();}catch(e){error.value=String(e);}}
async function retry(job:JobView){try{current.value=await tasks.value!.retry(job.id,crypto.randomUUID());await poll();}catch(e){error.value=String(e);}}
async function save(){const job=current.value;if(!job||job.state!=='succeeded')return;busy.value=true;error.value='';try{if(tasks.value?.saveJob){const grant=await props.context.files.choose?.('output');if(!grant)return;const result=await tasks.value.saveJob(job.id,grant.id);notice.value=`已保存 ${result.count} 个结果文件，已有不同内容的文件保留原样。`;}}catch(e){error.value=String(e);}finally{busy.value=false;}}
async function download(id:string,name:string){try{await tasks.value?.download?.(id,name);}catch(e){error.value=String(e);}}
function addFiles(event:Event){props.context.files.add?.([...((event.target as HTMLInputElement).files??[])]);void refresh();}
onMounted(()=>{if(props.context.files.kind!=='desktop')void refresh();void poll();});
const timer=setInterval(()=>void poll(),2000);
onUnmounted(()=>{disposed=true;epoch++;clearInterval(timer);stop();for(const value of urls)URL.revokeObjectURL(value);});
</script>
<template><ModuleFrame fit label="语谱图转音频 工作区" class="workspace-page m09-page">
<template #toolbar><ModuleToolbar><button v-if="context.files.choose" @click="choose" :disabled="busy">选择图片目录</button><button v-if="context.files.capture" @click="capture" :disabled="busy">截取屏幕</button><template v-if="context.files.add"><input ref="picker" type="file" accept="image/png,image/jpeg,image/bmp" hidden multiple @change="addFiles"/><button @click="picker?.click()">导入图片</button></template><button v-if="directory||context.files.kind==='server'" @click="refresh">刷新图片</button><template #actions><button @click="emit('references')">方法与来源</button></template></ModuleToolbar></template>
<ModuleWorkbench :state-key="stateKey" :left-width="270" :right-width="270" left-label="图片与标定" center-label="语谱图与重建音频" right-label="重建任务与导出"><template #left><aside class="m09-settings"><h2>图片与标定</h2><p v-if="context.files.kind==='server'" class="muted">从项目已上传图片中选择，截图可先用系统截图工具保存并上传。</p>
<select :value="source?.id??''" aria-label="语谱图图片" :disabled="busy" @change="load(files.find(f=>f.id===($event.target as HTMLSelectElement).value)!)"><option disabled value="">选择图片</option><option v-for="file in files" :key="file.id" :value="file.id">{{file.name}}</option></select><small>{{source?.name}}</small>
<div class="calibration"><label>时间起点（s）<input v-model.number="config.time_start" type="number" min="0" step=".001"/></label><label>时间终点（s）<input v-model.number="config.time_end" type="number" step=".001"/></label><label>频率起点（Hz）<input v-model.number="config.freq_start" type="number" min="0"/></label><label>频率终点（Hz）<input v-model.number="config.freq_end" type="number" min="1" max="48000"/></label><label>最小 dB（白）<input v-model.number="config.min_db" type="number" min="-160" max="20"/></label><label>最大 dB（黑）<input v-model.number="config.max_db" type="number" min="-160" max="20"/></label><label>窗长（ms）<input v-model.number="config.win_length_ms" type="number" min=".01" max="1000" step=".1"/></label><label>迭代次数<input v-model.number="config.n_iter" type="number" min="1" max="128"/></label><label>输出采样率<select v-model.number="config.target_sr"><option :value="0">原生（2 × 频率终点取整）</option><option v-for="sr in [8000,16000,22050,24000,32000,44100,48000,96000]" :key="sr" :value="sr">{{sr}} Hz</option></select></label><label>随机种子<input v-model.number="config.seed" type="number" min="0" max="4294967295"/></label></div>
<p class="muted">时长 ≤ 30 秒，重建区域 ≤ 100 万像素，像素 × 迭代 ≤ 3200 万。图片文件 ≤ 16 MB。</p><button class="primary" @click="submit" :disabled="busy||!source||!tasks?.reconstruct">开始重建</button><p v-if="!tasks?.reconstruct" class="muted">请使用已启动任务服务的桌面版或登录网页项目。</p></aside></template><details class="m09-card" :open="!calibrated"><summary>原图与四点校正</summary><div class="section-title"><h2>原图与四点校正</h2><div class="actions"><button @click="corners=[];selecting=true" :disabled="!imageUrl||busy">选择四个角点</button><button @click="corners=[];selecting=false">重置为整图</button></div></div><p class="muted">{{selecting?`依次点击左上、右上、右下、左下，已选 ${corners.length} / 4`:'四点区域将在任务内执行透视校正，未选点时使用整图。'}}</p>
<div v-if="imageUrl" class="image-frame"><img :src="imageUrl" alt="待校正语谱图" @load="dimensions={width:($event.target as HTMLImageElement).naturalWidth,height:($event.target as HTMLImageElement).naturalHeight}"/><svg viewBox="0 0 1000 1000" preserveAspectRatio="none" :class="{selecting}" @click="pick"><polygon v-if="corners.length===4" :points="corners.map(p=>`${p.x*1000},${p.y*1000}`).join(' ')" fill="var(--selection)" fill-opacity=".25" stroke="var(--accent)" stroke-width="3"/><g v-for="(p,i) in corners" :key="i"><circle :cx="p.x*1000" :cy="p.y*1000" r="9" fill="var(--accent)"/><text :x="Math.min(970,p.x*1000+15)" :y="Math.max(35,p.y*1000-15)" font-size="35" fill="var(--accent)">{{i+1}}</text></g></svg></div><ModuleStatus v-else kind="empty" message="导入灰度语谱图，或在桌面版截取屏幕。"/><small v-if="imageUrl">原图 {{dimensions.width}} × {{dimensions.height}}</small></details>
<section v-if="calibrated&&rebuilt" class="m09-card"><h2>重建对比</h2><p v-if="changed" class="notice">当前标定或角点已改变。这里仍显示所选持久任务的原结果，需重新开始重建才会使用新设置。</p><details><summary>查看此结果的原始参数快照</summary><pre>{{JSON.stringify(metadata?.config,null,2)}}</pre></details><div class="comparison"><figure><figcaption>校正后的输入</figcaption><img :src="calibrated" alt="校正后的输入语谱图"/></figure><figure><figcaption>重建音频的频谱（相对灰度）</figcaption><img :src="rebuilt" alt="重建音频频谱"/></figure></div><p class="muted">两图的灰度标度不同，仅作结构比较。{{metadata?.frequency_mapping==='band-interpolation-zero-fill-v1'?'非零频率起点采用频带插值，低频区补零。':''}}</p><p>实际时长 {{Number(metadata?.duration??0).toFixed(4)}} s · 输出 {{metadata?.sample_rate}} Hz · 种子 {{metadata?.seed}} · PCM16 削波样本 {{metadata?.pcm16_clipped_samples}}</p><WaveformViewport v-if="wave.asset" :state="wave" compact-overview auto-amplitude continuous-detail/><p class="muted">使用底部统一播放条试听全段或选区。结果包含 WAV、两张 PNG 和参数/来源 JSON。</p></section><template #right><p class="notice">图片不含原始相位，重建声音仅供方法探索，不能视为恢复原录音。请使用灰度语谱图，裁去坐标、文字和彩色标记。</p>
<ModuleStatus v-if="busy" kind="loading" message="正在处理当前图像或结果…"/><ModuleStatus v-if="error" kind="error" :message="error"/><ModuleStatus v-if="notice" :message="notice"/>
<details class="m09-card"><summary>重建任务（{{jobs.length}}）</summary><p v-if="!jobs.length" class="muted">尚无任务。关闭模块不会删除任务。</p><div class="job-list"><div v-for="job in jobs" :key="job.id" class="job-row"><button @click="show(job)" :disabled="busy" :class="{selected:current?.id===job.id}">{{new Date(job.created_at*1000).toLocaleTimeString()}} · {{states[job.state]}} · {{job.id.slice(0,8)}}</button><button v-if="['queued','running'].includes(job.state)" @click="cancel(job)">取消任务</button><button v-if="['failed','interrupted','cancelled'].includes(job.state)" @click="retry(job)">重试</button><small v-if="job.error_code">{{errors[job.error_code]??job.error_code}}</small></div></div><p v-if="running" role="status">任务在后台执行，可切换模块。原图和参数快照已固定。</p></details>
<section v-if="calibrated&&rebuilt" class="m09-card"><button v-if="tasks?.saveJob" @click="save" :disabled="busy">保存重建结果</button><template v-if="tasks?.download&&current?.result_manifest?.kind==='managed_spec2wav_files'"><button v-for="file in current.result_manifest.files" :key="file.id" @click="download(file.id,file.name)">下载 {{file.name}}</button></template></section></template></ModuleWorkbench></ModuleFrame></template>
<style scoped>
.m09-columns{display:grid;grid-template-columns:var(--panel-left,300px) minmax(280px,1fr);gap:var(--module-gap);overflow:auto;min-height:0}.m09-settings,.m09-card{background:var(--panel);border:1px solid var(--border);border-radius:var(--radius);padding:var(--module-padding);min-width:0}.m09-settings{align-self:start}.m09-settings>select,.m09-settings>.primary{width:100%;margin:10px 0}.calibration{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.calibration label{display:flex;flex-direction:column;gap:5px;font-size:12px}.calibration input,.calibration select{width:100%;min-width:0}.actions{display:flex;gap:6px;flex-wrap:wrap}.m09-results{min-width:0;display:grid;gap:12px;align-content:start}.image-frame{position:relative;display:block;max-width:100%;width:min(100%,65vh);margin:auto}.image-frame>img{display:block;width:100%;height:auto;max-height:none}.image-frame>svg{position:absolute;inset:0;width:100%;height:100%}.selecting{cursor:crosshair}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:12px}.comparison figure{margin:0;min-width:0}.comparison img{width:100%;height:28vh;max-height:none;object-fit:contain;background:#fff}.comparison figcaption{margin-bottom:8px}.job-list{max-height:240px;overflow:auto}.job-row{display:flex;gap:8px;flex-wrap:wrap;margin:6px 0;align-items:center}.job-row small{color:var(--muted)}@media(max-width:1050px){.m09-columns{grid-template-columns:1fr}.comparison{grid-template-columns:1fr}.calibration{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:700px){.calibration{grid-template-columns:1fr 1fr}}
.m09-page summary{cursor:pointer}.m09-page :deep(.wave-track svg){height:max(160px,22vh)}.m09-card p,.m09-settings p{margin:6px 0}.m09-card h2,.m09-settings h2{margin:0 0 6px}.m09-card pre{max-height:180px;overflow:auto}.m09-page>.notice{margin:0}
</style>
