<script setup lang="ts">
import {ref,watch,nextTick,onMounted,onUnmounted} from 'vue';
import type {ReconstructionConfig,ReconstructionPreview} from '../../platform/research.ts';
type Stroke=NonNullable<ReconstructionConfig['strokes']>[number];
const props=defineProps<{preview:ReconstructionPreview;strokes:Stroke[];disabled?:boolean}>();
const emit=defineEmits<{ 'update:strokes':[Stroke[]] }>();
const canvas=ref<HTMLCanvasElement>(),viewport=ref<HTMLDivElement>(),color=ref<0|255>(0),size=ref(12),opacity=ref(100),zoom=ref(1),tool=ref<'brush'|'pan'>('brush'),redo=ref<Stroke[]>([]),message=ref('');
const displayWidth=ref(640),displayHeight=ref(360);let base:HTMLImageElement|undefined,cache:HTMLCanvasElement|undefined,overlay:HTMLCanvasElement|undefined,current:Stroke|undefined,pointer:number|undefined,last:{x:number;y:number;sx:number;sy:number}|undefined,observer:ResizeObserver|undefined,disposed=false;
function drawStroke(ctx:CanvasRenderingContext2D,s:Stroke){ctx.strokeStyle=ctx.fillStyle=s.color===0?'#000':'#fff';ctx.lineWidth=Math.max(1,Math.round(s.size/2))*2;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();s.points.forEach((p,i)=>{const x=p.x*(props.preview.width-1),y=p.y*(props.preview.height-1);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();if(s.points.length===1){const p=s.points[0];ctx.beginPath();ctx.arc(p.x*(props.preview.width-1),p.y*(props.preview.height-1),ctx.lineWidth/2,0,Math.PI*2);ctx.fill();}}
function layer(ctx:CanvasRenderingContext2D,s:Stroke){if(!overlay)return;const g=overlay.getContext('2d')!;g.clearRect(0,0,overlay.width,overlay.height);drawStroke(g,s);ctx.globalAlpha=s.opacity;ctx.drawImage(overlay,0,0);ctx.globalAlpha=1;}
function render(){const c=canvas.value;if(!c||!cache)return;const g=c.getContext('2d')!;g.drawImage(cache,0,0);if(current)layer(g,current);}
function rebuild(){if(!base||!canvas.value)return;const c=canvas.value;c.width=props.preview.width;c.height=props.preview.height;cache=document.createElement('canvas');overlay=document.createElement('canvas');cache.width=overlay.width=c.width;cache.height=overlay.height=c.height;const g=cache.getContext('2d')!;g.drawImage(base,0,0,c.width,c.height);for(const s of props.strokes)layer(g,s);render();}
async function load(){current=undefined;redo.value=[];zoom.value=1;await nextTick();const img=new Image();img.onload=()=>{if(disposed||img!==base)return;rebuild();};base=img;img.src='data:image/png;base64,'+props.preview.image_base64;}
watch(()=>props.preview,load);watch(()=>props.strokes,rebuild);
function point(e:PointerEvent){const r=canvas.value!.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
function down(e:PointerEvent){if(props.disabled||e.button!==0||pointer!==undefined)return;pointer=e.pointerId;canvas.value!.setPointerCapture(e.pointerId);message.value='';if(tool.value==='pan'||e.shiftKey){const v=viewport.value!;last={x:e.clientX,y:e.clientY,sx:v.scrollLeft,sy:v.scrollTop};return;}if(props.strokes.length>=256||props.strokes.reduce((n,s)=>n+s.points.length,0)>=8192){message.value='笔迹已达上限，请撤销部分笔迹。';pointer=undefined;return;}current={color:color.value,size:size.value,opacity:opacity.value/100,points:[point(e)]};render();}
function move(e:PointerEvent){if(pointer!==e.pointerId)return;if(last){viewport.value!.scrollLeft=last.sx+last.x-e.clientX;viewport.value!.scrollTop=last.sy+last.y-e.clientY;return;}if(!current)return;const p=point(e),q=current.points.at(-1)!;if(Math.hypot((p.x-q.x)*props.preview.width,(p.y-q.y)*props.preview.height)<.8)return;if(current.points.length>=4096||props.strokes.reduce((n,s)=>n+s.points.length,0)+current.points.length>=8192){message.value='本次笔迹已达上限，请结束当前笔画。';return;}current.points.push(p);render();}
function finish(e:PointerEvent){if(pointer!==e.pointerId)return;if(current){const s=current;current=undefined;redo.value=[];emit('update:strokes',[...props.strokes,s]);}last=undefined;pointer=undefined;if(canvas.value?.hasPointerCapture(e.pointerId))canvas.value.releasePointerCapture(e.pointerId);}
function undo(){if(props.disabled||current||!props.strokes.length)return;redo.value.push(props.strokes.at(-1)!);emit('update:strokes',props.strokes.slice(0,-1));}
function forward(){if(props.disabled||current)return;const s=redo.value.pop();if(s)emit('update:strokes',[...props.strokes,s]);}
function scale(value:number){zoom.value=Math.max(1,Math.min(8,value));}
function wheel(e:WheelEvent){if(!e.ctrlKey)return;e.preventDefault();scale(zoom.value*(e.deltaY<0?1.25:.8));}
function key(e:KeyboardEvent){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?forward():undo();}}
onMounted(()=>{observer=new ResizeObserver(()=>{displayWidth.value=Math.max(240,(viewport.value?.clientWidth??640)-4);displayHeight.value=Math.max(220,(viewport.value?.clientHeight??360)-4);});observer.observe(viewport.value!);void load();});
onUnmounted(()=>{disposed=true;observer?.disconnect();});
</script>
<template><section class="spectral-editor" aria-label="频谱绘图编辑器" @keydown="key">
 <div class="paint-tools"><div class="spectral-tool-group"><button :aria-pressed="tool==='brush'&&color===0" @click="tool='brush';color=0">黑色画笔</button><button :aria-pressed="tool==='brush'&&color===255" @click="tool='brush';color=255">白色画笔</button><button :aria-pressed="tool==='pan'" @click="tool='pan'">拖动画面</button></div>
 <label>粗细 <input aria-label="画笔粗细" type="range" min="1" max="100" v-model.number="size"/><output>{{size}}</output></label><label>不透明度 <input aria-label="画笔不透明度" type="range" min="0" max="100" v-model.number="opacity"/><output>{{opacity}}%</output></label>
 <div class="spectral-tool-group"><button aria-label="撤销笔迹" @click="undo" :disabled="disabled||!strokes.length">撤销</button><button aria-label="重做笔迹" @click="forward" :disabled="disabled||!redo.length">重做</button><button @click="scale(zoom/1.25)" :disabled="zoom<=1">−</button><output>{{Math.round(zoom*100)}}%</output><button @click="scale(zoom*1.25)" :disabled="zoom>=8">＋</button><button @click="zoom=1">适合窗口</button></div></div>
 <div class="axis-note"><span>高频 ↑</span><span>时间 → · 黑色增强，白色减弱</span><span>{{strokes.length}} 笔</span></div>
 <div ref="viewport" class="paint-viewport" @wheel="wheel"><canvas ref="canvas" tabindex="0" aria-label="可缩放频谱画布" :class="{panning:tool==='pan'}" :style="{width:displayWidth*zoom+'px',height:Math.max(220,Math.min(displayHeight,displayWidth*preview.height/preview.width))*zoom+'px'}" @pointerdown.prevent="down" @pointermove="move" @pointerup="finish" @pointercancel="finish" @lostpointercapture="finish"/></div>
 <p class="muted">Ctrl + 滚轮缩放 · Shift + 拖动平移 · Ctrl + Z 撤销 · Ctrl + Shift + Z 重做</p><p v-if="message" role="status">{{message}}</p>
</section></template>
<style scoped>
.spectral-editor{min-width:0}.paint-tools,.spectral-tool-group{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.paint-tools{gap:8px;margin-bottom:8px}.paint-tools label{display:flex;align-items:center;gap:5px;white-space:nowrap}.paint-tools input{width:78px;min-height:18px}.paint-tools output{min-width:3ch;text-align:center}.paint-tools button[aria-pressed=true]{background:var(--selection);border-color:var(--accent);color:var(--accent)}.paint-viewport{overflow:auto;height:min(44vh,440px);min-height:260px;scrollbar-gutter:stable;background:#fff;border:1px solid var(--border);border-radius:var(--radius);overscroll-behavior:contain}.paint-viewport canvas{display:block;touch-action:none;cursor:crosshair;max-width:none}.paint-viewport canvas.panning{cursor:grab}.axis-note{display:flex;justify-content:space-between;gap:8px;color:var(--muted);font-size:.857143rem;margin-bottom:4px}.muted{font-size:.857143rem;margin:6px 0 0}
</style>
